### ISSUE TITLE
[Investigate] Create a cheatsheet for using Vanilla

### ISSUE THREAD

**Issue by yaili** [canonical-web-and-design/vanilla-framework#1174]
Examples:
- https://hackerthemes.com/bootstrap-cheatsheet/
- https://www.scribd.com/document/47604303/Blueprint-CSS-framework-version-1-0-1-cheat-sheet

**Comment by deadlight** [comment]
Lack of user education has become an important issue. I've upped the priority accordingly.

**Comment by yaili** [comment]
Remove Priority: Low? 😇

**Comment by deadlight** [comment]
> Remove Priority: Low? innocent

Whoops. Yes, I meant to do that. Thanks :)

**Comment by PravallikaKura** [comment]
I and my teammate @HarshiniKarumuri want to work on this project for RGSoC. We are new to this framework but have experience in HTML, CSS, JavaScript..We would like to work on this issue.Please guide us through this.

**Comment by bartaz** [comment]
@PravallikaKura Thanks for reaching out and sorry for late response, I must have missed your comment.

This task is a proposal to be worked on during RGSoC when it starts in July. Sorry, it's not really fully ready to be worked on right now.

**Comment by bartaz** [comment]
Development needed: Investigate a way to automate this.

**Comment by anthonydillon** [comment]
Less useful if we are targeting internal use, I would say.
