### ISSUE TITLE
Standards for table patterns

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/vanilla-framework#1355]
Bartek created a new pattern for snapcraft-flask, [`p-table-key-value`](https://github.com/canonical-websites/snapcraft-flask/pull/51), which follows precedent from existing table patterns in Vanilla pretty well. However, I'm not too happy about this precedent:

- there is one actual pattern, `p-table-expanding`, and two modifiers for "`p-table`" - `p-table--sortable` and `p-table--mobile-card`
- all three patterns actually target `td` and `tr` elements directly

I thought it was policy not to target elements directly. And so these should ideally be targeting e.g. `.p-table-expanding-row` and `.p-table-expanding-cell` instead of `tr` and `td`. I think these patterns may be out-of-date because they were imported from themes with less strict standards, but I just wanted to confirm if my understanding of the ideal implementation is correct or not.

I don't think modifiers based on a `p-table` pattern should exist if the `p-table` pattern does not itself exist. And so e.g. `p-table--sortable` should really be `p-table-sortable`.

This brings up the issue that `p-table-expanding` in fact looks incredibly similar to `p-table--sortable`, even though the former is a pattern rather than a modifier. One could be forgiven for confusing patterns named like this with modifiers.

So I'd also like to suggest that when we create *patterns* with adjectives in the name, we consider using the more natural form of `p-{adjective}-{noun}` rather than `p-{noun}-{adjective}`, to clearly distinguish them from modifiers. Then `p-expanding-table` would be clearly of a different type than `p-table--sortable`. Thoughts?

**Comment by anthonydillon** [comment]
Approved in the working group.

Areas of work:
- Audit the table pattern and come up with a naming convention
- Rename deprecate old pattern names
- Consider combining patterns if required
- Look into the impact of renaming patterns across Vanilla to `p-{adjective}-{noun}`

**Comment by bartaz** [comment]
This was waiting very long. Bringing it back to WG for re-evaluation.

**Comment by bartaz** [comment]
WG:
- start going through these items in next iterations
- turn it into epic

**Comment by nottrobin** [comment]
@SirSamTumless why is this closed? @bartaz did anything happen with this?

**Comment by bartaz** [comment]
@nottrobin yes, any identified outstanding issues in this epic were fixed.

`p-table-expanding` was renamed to `p-table--expanding`, `p-table--sortable` was removed (`aria-sort` can be used for sorting), and some additional internal clean-ups have been made.

**Comment by nottrobin** [comment]
Thanks @bartaz
