### ISSUE TITLE
Expanding navigation menu to >1 page height causes blank first page when printing

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/vanilla-framework#1371]
@matthewpaulthomas commented on [Wed Jul 19 2017](https://github.com/vanilla-framework/vanilla-docs-theme/issues/52)

1\. Go to any page on [docs.vanillaframework.io](https://docs.vanillaframework.io/en/).
2\. Look at the print preview.
3\. Expand enough of the navigation menu’s categories that the menu becomes taller than one page.
4\. Look at the print preview again.

What happens:

2\. The navigation menu and the page contents start on the first page.
![vanilla docs navigation menu collapsed-0](https://user-images.githubusercontent.com/19801137/28362887-1fc6e9a0-6c76-11e7-81ae-210e6194531a.png)

4\. The first page is empty except for the header. The navigation menu and the page contents start on the second page.
![vanilla docs navigation menu expanded-0](https://user-images.githubusercontent.com/19801137/28362895-2726c03a-6c76-11e7-8c02-f8b8d17bd4f3.png) ![vanilla docs navigation menu expanded-1](https://user-images.githubusercontent.com/19801137/28362897-2959b3e4-6c76-11e7-8956-0ec01c441031.png)

What should happen:
4\. The page contents should always begin on the first page, not the second page.

One simple way to fix this bug might be for printing to omit the navigation menu altogether.

**Comment by Caleb-Ellis** [comment]
This may get fixed once the sidebar nav is updated with Vanilla styling ([Issue](https://github.com/ubuntudesign/docs.vanillaframework.io/issues/118)), but I'll leave it open until it is a confirmed fix.

**Comment by kwm14** [comment]
@matthewpaulthomas this has been fixed with the removal of the sidebar nav 👍 

<img width="1440" alt="Screenshot 2019-05-21 at 12 25 17" src="https://user-images.githubusercontent.com/17748020/58092275-99c25600-7bc3-11e9-8791-3259d21f1679.png">
