### ISSUE TITLE
Inconsistent numbers in class names

### ISSUE THREAD

**Issue by deadlight** [canonical-web-and-design/vanilla-framework#1406]
Numbers in class names should either be numeric - such as `col-4` - or spelled out as words - such as `p-heading--four` - but we shouldn't mix them in the codebase.

I have no real preference which system is chosen but we should pick and stick to one.

**Comment by anthonydillon** [comment]
This could be a breaking change if we are not thoughtful. My suggestion would be to support both ints and strings in all cases but only document the patterns as ints (easier to spell and less characters). Then deprecate the strings in 2.0.

**Comment by kwm14** [comment]
Agreed in working group:

- Support both
- Deprecate words in 2.0 release
