### ISSUE TITLE
Layouts: Sticky footer

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#1452]
This is a proposal for a new pattern (sticky footer) or amendment to current footer pattern to optionally make it sticky to to bottom of the screen (when there is not enough content on the page).

## Visual

![screen shot 2017-11-21 at 13 16 40](https://user-images.githubusercontent.com/83575/33072063-46e04b9e-cebe-11e7-8504-fc63069ed084.png)
![screen shot 2017-11-21 at 13 16 32](https://user-images.githubusercontent.com/83575/33072064-46f63d96-cebe-11e7-8eb4-9b5f335acef3.png)

## Context

On pages that can have very little content it may be useful to have footer stick to the bottom.

It was implemented in snapcraft.io https://github.com/canonical-websites/snapcraft.io/pull/151
(demo at: https://staging.snapcraft.io/search)

## Progressive enhancement

Snapcraft.io implementation uses flexbox (based on https://css-tricks.com/couple-takes-sticky-footer/#article-header-id-3). For browsers not supporting flexbox it will simply show a footer right after the content without breaking the layout.

**Comment by kwm14** [comment]
Agreed in working group:
- +1 from team
- Update Vanilla default footer

**Comment by Caleb-Ellis** [comment]
## Findings
- Adding `display: flex` and `flex-direction: column` to the `<body>` tag seems to have far-reaching, unintended side-effects. Any block element directly within `<body>` without an explicit width (i.e. `width: auto`) is rendered as wide as the browser window.
- While as @bartaz said it's unlikely anything would be rendered as a direct child of the `<body>`, and would instead likely be in a strip or grid etc, it's still technically possible and it doesn't address how the examples pages and consequently Vanilla docs would be affected.

## Options
- Have an optional class for the `<body>` tag for having a sticky footer (e.g. `.p-has-sticky-footer`)
- Add explicit widths or `align-self: start` to every pattern we don't want to be affected by the flexbox format
- Investigate a method that doesn't target the `<body>` element

Adding a `Status: Blocked` label until a suitable method is decided.

**Comment by kwm14** [comment]
## Agreed in working group
- Two options to explore
- Have an optional class for the <body> tag for having a sticky footer (e.g. .p-has-sticky-footer)
- Investigate CSS grid

**Comment by anthonydillon** [comment]
I can't tell if this was implemented?

**Comment by bartaz** [comment]
I think it was at some point (when p-footer was till a thing). It was an additional class to put on body, or maybe a setting variable?

Having a quick look I can't see anything like that in code, so probably was removed with footer pattern. I'll have a look next week.
Probably something we can get back with layouts.

**Comment by anthonydillon** [comment]
Thanks, I thought so and needed it this weekend but don't remember it in the framework. As part of the layout work is a good idea.

**Comment by bartaz** [comment]
Confirmed. Sticky footer was removed in 2.0 https://github.com/canonical-web-and-design/vanilla-framework/pull/2226

**Comment by bartaz** [comment]
Reopening, so we can plan to include sticky footer option as part of layouts work.

**Comment by solazio** [comment]
![image](https://user-images.githubusercontent.com/40214246/78363590-e7fdff00-75b3-11ea-8041-8e5558db3031.png)

**Comment by anthonydillon** [comment]
If it helps @solazio I have implemented it here: https://github.com/canonical-web-and-design/360-corp/blob/master/static/sass/styles.scss#L78
