### ISSUE TITLE
Animations documentation is confusing

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/vanilla-framework#1530]
1\. Go to [the Animations documentation page](https://docs.vanillaframework.io/en/settings/animation-settings).

What’s wrong:

- “Vanilla has a cross matrix of duration and easing that can be used to apply animation to components” introduces [the obscure mathematical term “cross matrix”](https://books.google.co.uk/books?id=YFr2BwAAQBAJ&pg=PA23&lpg=PA23&dq=%22cross+matrix%22&source=bl&ots=FLsGVlpDYA&sig=yzyhZ9V4O7feqsY8rW31eoRb7j0&hl=en&sa=X&ved=0ahUKEwjly4zp1-3YAhWJCcAKHbgsDZI4ChDoAQhYMAk#v=onepage&q=%22cross%20matrix%22&f=false) without defining it. The term isn’t used in the example code, or mentioned later, so probably it can be dropped: “Vanilla provides a choice of durations and easings for animating components.”

- “Vanilla uses a range of animation durations to dictate the time in which an animation should complete” is a tautology: in the context of animation, that’s obviously what the word duration means. This paragraph could instead be “Recommended durations for animations are stored in the map `$animation-duration`.”

- Spinning is a kind of animation, but it’s on an extremely short separate page. It could be on the same page.

**Comment by anthonydillon** [comment]
@matthewpaulthomas Thanks, good points.
