### ISSUE TITLE
Vertically center for inline elements

### ISSUE THREAD

**Issue by deadlight** [canonical-web-and-design/vanilla-framework#1598]
## Process

The `u-vertically-center` class only works with elements displayed in a block. It would be better for it to support inline items.

Example:
[Vertical centring not working with inline lists](https://codepen.io/deadlight/pen/MQGGba)

**Comment by bartaz** [comment]
It seems it is not trivial to make the same utility work well in different contexts (block and inline).
The easier solution would be to provide separate utility for inline context.
