### ISSUE TITLE
Scale icons with text

### ISSUE THREAD

**Issue by deadlight** [canonical-web-and-design/vanilla-framework#1599]
If we change the sizing of the `p-icon` class to ems rather than rems then icons will scale nicely with their surrounding text.

[Live example](https://codepen.io/deadlight/pen/OQZaJm)

**Comment by kwm14** [comment]
## Agreed in working group
- implement proposal
- design review existing examples @spencerbygraves @lyubomir-popov @kwm14

**Comment by bartaz** [comment]
This was waiting very long. Bringing it back to WG for re-evaluation.

**Comment by lyubomir-popov** [comment]
I've actually done this, I just didn't know there was an issue for it. Example [here](https://docs.vanillaframework.io/examples/utilities/font-metrics)

**Comment by bartaz** [comment]
Ok thanks. Closing this.
