### ISSUE TITLE
Docs sidebar search only matches beginning of pattern name

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#1607]
## Process

1. Go to https://docs.vanillaframework.io/en/
2. Go to search field and search for "nav"
3. Observe behavior

Similar when searching for 'menu'.

## Expected result

Links that match "nav" (such as "global navigation") should show up.
There is also top level "Navigation" group. Not sure how that should show in filtering, but the fact that it hides when searching for 'nav' is quite confusing.

## Current result

No matches found.

## Screenshot

<img width="291" alt="screen shot 2018-03-01 at 12 27 47" src="https://user-images.githubusercontent.com/83575/36842450-02c1b204-1d4c-11e8-8a8b-37e7917ed64f.png">

**Comment by kwm14** [comment]
Agreed with @anthonydillon @Caleb-Ellis 
- enhancement to current search functionality 
- match beginning of each word not just the first one

**Comment by bartaz** [comment]
Not relevant anymore
