### ISSUE TITLE
Unhelpful feedback before, during, and after clicking Copy button

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/vanilla-framework#1632]
1\. Go to [any page that uses the “Code snippet” pattern](https://docs.vanillaframework.io/en/patterns/code-snippet).
2\. Hover over the Copy button.
3\. Press down on the Copy button.
4\. Release the Copy button.

What happens:
2\. The pointer turns into a pointing hand.
3\. A thin blue line appears outside the left edge (#2319) of the button.
4\. Nothing.

What should happen:
~~2\. The pointer does not turn to a pointing hand. It’s a button, not a link.~~ (removed for later discussion)
3\. The button goes dark, to show that something will happen if you release it.
4\. Some kind of feedback, to confirm that the text has been copied [originally reported as [build.snapcraft.io#777](https://github.com/canonical-websites/build.snapcraft.io/issues/777)].

## Is this a proposal or an amendment?

Amendment to [“Code snippet”](https://docs.vanillaframework.io/en/patterns/code-snippet)

**Comment by kwm14** [comment]
Thanks @matthewpaulthomas I've created a design that could solve this issue [here](https://github.com/canonical-webteam/example-js/issues/30). When we begin documentation updates this will be one of the first issues we resolve.

**Comment by kwm14** [comment]
This will be updated as part of this [issue](https://github.com/vanilla-framework/vanilla-framework/issues/1631).

**Comment by matthewpaulthomas** [comment]
The version of this pattern [used on ubuntu.com](https://ubuntu.com/download/server/thank-you?country=GB&version=18.04.2&architecture=amd64) is a bit more responsive than the one on docs.vanillaframework.io: after the click, the contents of the field becomes highlighted. But it’s still weird that the button itself doesn’t change appearance at all during or after the click.
