### ISSUE TITLE
Enabled search fields inconsistent with disabled and other fields

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/vanilla-framework#1651]
Vanilla text fields are visibly indented, the same as native text fields on Windows, macOS, and Ubuntu.
![vanilla-text-field](https://user-images.githubusercontent.com/19801137/38024390-cb24fbbc-327c-11e8-9f35-ff7f882071a3.png)
![vanilla-textarea](https://user-images.githubusercontent.com/19801137/38024396-ce5ba312-327c-11e8-8189-657686b0cf22.png)

Disabled search fields have the same visible indent (zoomed in):
![vanilla-search-fields-disabled](https://user-images.githubusercontent.com/19801137/38024693-a5f810a8-327d-11e8-9b91-a4dd4706c090.png)

However, _enabled_ search fields are the odd one out, with no indent:
![vanilla-search-fields-enabled](https://user-images.githubusercontent.com/19801137/38024734-bcc6d0d0-327d-11e8-9bb5-f1a2cce9d175.png)

Enabled search fields should have the same indent as all the others.

**Comment by bartaz** [comment]
Input borders have been updated some time ago and this doesn't seem to be an issue anymore.
