### ISSUE TITLE
Can’t search for anything that isn’t a component name

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/vanilla-framework#1655]
1\. Go to docs.vanillaframework.io.
2\. Try to search for “error”, or “previous next”, or “pull quote”, or “radio button”.

What you see: No search results.

What you should see: Relevant search results, for example, “[.p-notification--negative](https://docs.vanillaframework.io/en/patterns/notification#.p-notification--negative)” and “[Validation classes](https://docs.vanillaframework.io/en/base/forms#validation-classes)” as results when searching for “error”.

This is separate from #1607, but it’s possible that implementing this would be one way of fixing that.

**Comment by kwm14** [comment]
Agreed with @anthonydillon @Caleb-Ellis we need to investigate a solution for this. 

@matthewpaulthomas how do expect the behaviour of this to be surfaced?
  - do we keep the search in the sidebar navigation or add the search into the navigation?
  - do we display the results like other docs sites ie; https://docs.ubuntu.com/search?q=server&domain=docs.maas.io
- do we autocomplete the results in the panel as we do now

**Comment by matthewpaulthomas** [comment]
> do we keep the search in the sidebar navigation or add the search into the navigation?

That question not making sense is an example of #1591.

If you mean “…or move the search into the header”, I’d agree with that. It would lose the elegance of showing matching patterns in their existing horizontal position. But it would be more familiar to users of other sites.

> do we display the results like other docs sites ie; https://docs.ubuntu.com/search?q=server&domain=docs.maas.io

Any results would be much better than none. However, serving search results from docs.ubuntu.com would have several immediate drawbacks:
- The header would say “Ubuntu documentation” when it isn’t.
- The header would not contain the usual links to Vanilla, Accessibility, Browser support etc.
- The search fields would be visually scrambled, which would not be a good look for a CSS framework.
- The search field would say “Search all docs”, which would be unhelpful if it was true, but wouldn’t be true.
- The footer would be full of stuff about Ubuntu, not Vanilla, and the “Report a bug” link would go to the wrong place.

Probably the search field issues could be fixed easily. But the header and footer issues would be more important.

> do we autocomplete the results in the panel as we do now

You could use a drop-down autocomplete menu instead. To avoid implying that auto-completed patterns were _all_ the results, the menu could end with an item labelled “Search for {current field value}”, which would do the same thing as pressing Enter in the field.

**Comment by bartaz** [comment]
Fixed by #2822
