### ISSUE TITLE
Use HTTPS and HTTP compatible URLs  

### ISSUE THREAD

**Issue by gamunu** [canonical-web-and-design/vanilla-framework#1692]
https://github.com/vanilla-framework/vanilla-framework/blob/7a360459fcf77faccc56c488ebf7abee8723541b/scss/_settings_font.scss#L6

i.e:
 ```$font-import: '//fonts.gstatic.com/s/ubuntu/v9/' !default; ```

**Comment by kwm14** [comment]
@gamunu thanks for reporting 😄 we will fix this up 👍

**Comment by bartaz** [comment]
We host fonts ourselves now and use https by default.
