### ISSUE TITLE
Limit menu items with a max-width so user names etc don't cause overflow.

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#1740]
This is an issue on snapcradft, but true anywhere a user name is present in the menu.
For reference ; https://github.com/canonical-websites/snapcraft.io/issues/516

**Comment by lyubomir-popov** [comment]
Removing label v1.7.0-beta-1 as this will require adding the bespoke dropdown toggle to vanilla first.
It is currently being used in maas and snapcraft, but will require a separate proposal.

**Comment by kwm14** [comment]
@lyubomir-popov happy for this to be pushed up to Vanilla when design/build has been finalised across MAAS and snapcraft 👍

**Comment by lyubomir-popov** [comment]
@bartaz could you please propose the working version of this to vanilla?

**Comment by bartaz** [comment]
@lyubomir-popov This issue says about max-width of menu items (that was casing issues in dropdowns).

Vanilla doesn't have navigation dropdowns ATM.
Do we want a proposal with full dropdown implementation or just max-width for navigation items?

If it's about full navigation dropdown pattern we may want to wait until snapcraft.io is migrated to latest Vanilla 1.7, to make sure it works properly there.
