### ISSUE TITLE
Remove or revise 'max-width' from type elements

### ISSUE THREAD

**Issue by kwm14** [canonical-web-and-design/vanilla-framework#1794]
## Process

Proposal to remove or revise 'max-width' from type elements as it's been highlighted a few times as an issue, it would be great to discuss further with the rest of the team.
- Was there a issue with type before max-width?
- Do we need a rule when to use?
- Can be be applied when needed?

### Notifications
![screen shot 2018-05-02 at 15 07 00](https://user-images.githubusercontent.com/17748020/39527975-c66bbbb0-4e1a-11e8-8232-45454f145e2f.png)

### Docs content
![docs-screenshot](https://user-images.githubusercontent.com/17748020/39527982-cb087910-4e1a-11e8-94be-18f9cdd172e3.png)

**Comment by kwm14** [comment]
## Agreed in working group
- increase default `38em` to `40em`
- we also have `p-max-width--long` which you can include as a mixin
- going forward we will add `p-max-width--long` as a class which by default is `60em`
- add max-width documentation to **Global layout** on docs.vf.io so it's visible and people know when/how to use

**Comment by steverydz** [comment]
:+1:

**Comment by deadlight** [comment]
Max width needs to be removed entirely from elements using `.u-align-center`

Examle:
`h1,
h2,
h3,
h4,
h5,
h6,
p {
  &.u-align--center {
    max-width: none;
  }
}`

**Comment by Caleb-Ellis** [comment]
@deadlight There is `u-align-text--center` which keeps the typography max-width, but applies margin equally on both sides. Admittedly it's a bit of a mess around, but it works for edge cases when you want multiple lines of text centred.

`.u-align-text--center`
![screenshot](https://user-images.githubusercontent.com/25733845/44214093-36eceb80-a167-11e8-8451-82004e0c33ee.png)

`u-align-center` with max-width removed
![screenshot_1](https://user-images.githubusercontent.com/25733845/44214109-410eea00-a167-11e8-8eb7-3cc4457adb17.png)

**Comment by deadlight** [comment]
This fix improved matters but did not fix the cases where text requires no max width.

I'm going to suggest that we add the [ubuntu.com implementation](https://github.com/canonical-web-and-design/ubuntu.com/blob/master/static/sass/styles.scss#L171) as a utility for this case.

**Comment by Lukewh** [comment]
I also think the fix changed things, but didn't fix things completely.

While it would be nice for the `max-width` to be content aware, I think the utility linked to by @deadlight makes most sense.

**Comment by Lukewh** [comment]
This issue is back https://github.com/canonical-web-and-design/snapcraft.io/issues/2312 this time for docs pages.

**Comment by bartaz** [comment]
While the `.u-no-max-width` utility proposal is nice it won't solve all the problems.
We don't want to (and even can't easily) add this class to all paragraphs on docs just to remove max-width from them. There should be an utility that can be applied on higher "layout" level to remove limit from all the text inside it.

**Comment by lyubomir-popov** [comment]
There's [research](https://en.wikipedia.org/wiki/Line_length) that links line length to reading speed, comprehension, optimal line-height etc.

There's a common argument that this research is limited to traditional printed typesetting, and does not apply to screen based reading. As the link above shows, this is not true. While there's no consensus on the actual length (varying from 75 to 95 characters per line) the necessity for a limit is not contested by any of the studies.

**Comment by lyubomir-popov** [comment]
@deadlight does this need to stay open? 

We reently updated the documentation to include explain why max-width is required, and why in cases where overriding is needed, a local override is a better than a framework wide one:

(Section Line length [here](http://192.168.64.2:8101/base/typography/))

**Comment by bartaz** [comment]
We feel like the current solution is correct, text elements should have max width constrained, block elements should use full width of their parent.
