### ISSUE TITLE
Automate Vanilla docs deployment

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical-web-and-design/vanilla-framework#1844]
At the moment, the Vanilla docs release requires several manual updates to reflect the latest release. It would be nice if this was better integrated with the Vanilla release, and all relevant data was updated automatically.

This includes:
- Updating the `vanilla-framework` package for the docs app
- Updating the version numbers in the "Get started" pages download link, hotlink, and What's new section
- Updating the version number in the sidebar dropdown

**Comment by bartaz** [comment]
Fixed by completing https://github.com/canonical-web-and-design/vanilla-squad/issues/563
