### ISSUE TITLE
Headings spacing is different for heading elements and heading classes

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical-web-and-design/vanilla-framework#1855]
When creating PR https://github.com/vanilla-framework/vanilla-framework/pull/1854 I noticed that the spacing between headings is different depending on if you use a heading element (`<h1>`, `<h2>` etc) or a heading class (`.p-heading--one`, `.p-heading--two`, etc).

The heading classes should be 100% identical in appearance and functionality to the heading elements.

## Screenshots

![screenshot_10](https://user-images.githubusercontent.com/25733845/41093023-2c9e5486-6a42-11e8-8e87-3f7e69fbc82a.png)

**Comment by lyubomir-popov** [comment]
I've fixed this a while ago - example with random tags using the heading classes:

![image](https://user-images.githubusercontent.com/2741678/69439863-ae80d180-0d3f-11ea-9cd5-6a571bf4d774.png)
