### ISSUE TITLE
Media queries are inconsistent

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical-web-and-design/vanilla-framework#1862]
There doesn't seem to be any standard on media queries in Vanilla, so there are some visual inconsistencies at the breakpoints (i.e. some patterns have `min-width: 768px` and others have `min-width: 769px`). Running the `parker` report shows that there are 23 different media queries, when there should really only be 14 for 4 defined breakpoints (x-small, small, medium, large).

|          |           |                 |                 |                 |
|----------|-----------|-----------------|-----------------|-----------------|
|  459 > x |  x >= 460 |  619 > x >= 460 |  767 > x >= 460 | 1029 > x >= 460 |
|  619 > x |  x >= 620 |  767 > x >= 620 | 1029 > x >= 620 |        -        |
|  767 > x |  x >= 768 | 1029 > x >= 768 |        -        |        -        |
| 1029 > x | x >= 1030 |        -        |        -        |        -        |

**Comment by lyubomir-popov** [comment]
@Caleb-Ellis AFAIK the right way to do this is to overlap breakpoints, and order them correctly. 
e.g.:

```
@media (max-width: 1024px) {...}
@media (min-width: 1024px) {...}
```
This way you don't have to worry about subtracting or adding, which is a common source of inconsistency.

**Comment by bartaz** [comment]
We should make sure we use mobile first approach, and build next step queries on top of that.
