### ISSUE TITLE
Tabstrip has max-width, but it doesn't take grid margins into account

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#1894]
## Process
• Open [Maas layout example ](https://vanilla-framework.github.io/vanilla-framework/examples/templates/maas-layout/)
• Inspect tabstrip
• Remove the row between p-tabs and p-tabs__list;
• Observe how the tabstrip expands into the 24px grid margins

## Expected result
I believe it should either:
• have max-width and the regular row padding-left and right, so it aligns with rows
• or have neither max-width nor padding-left/right, if the idea was to let its parent container deal with the grid.

Both of the above would work with the current makrup, whereas at the moment, if you want it to align with other rows, you need to insert a div classed "row" in between  .p-tabs and .p-tabs__list.

**Comment by kwm14** [comment]
### Agreed in WG
- remove max-width from tabs component
- update documentation that a `row` can constrain tabs component
