### ISSUE TITLE
Margin of buttons missing when .p-button-* is applied to different tags

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#1897]
1. Bug template

## Process

1. go to https://codepen.io/lyubomir-popov/pen/RJYyPV
2. change the <a> tag of the last button to <button>
3. observe how the buttons get closer 

## Expected result

changing markup shouldn't affect the maegins

## Current result

due to the :not(only-of-type), the margin is not applied because the two buttons are no longer of the same type

## Screenshot
<img width="374" alt="screen shot 2018-06-26 at 14 50 41" src="https://user-images.githubusercontent.com/2741678/41916617-54ce6d7a-7950-11e8-994b-d537fa7a8eee.png">

**Comment by bartaz** [comment]
It still happens, when `<a>` buttons are mixed with `<button>` buttons margins are not applied correctly.

**Comment by sowasred2012** [comment]
Closing - as discussed in https://github.com/canonical-web-and-design/vanilla-framework/issues/3384, the solutions we've attempted each introduce new problems that would have a relatively large impact on sites using Vanilla.
