### ISSUE TITLE
Amend the Definition list pattern

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/vanilla-framework#1916]
## Pattern to amend
Definition list

## Context
There is a lot of hate for the definition list. It is currently overridden in MAAS UI and www.ubuntu.com. Curreclty it description if on a different line and indented. In both mentioned cases it styling was overridden to be an inline key value style:
![screenshot-2018-7-11 training openstack ubuntu](https://user-images.githubusercontent.com/1413534/42564114-ce3d0380-84f7-11e8-9647-19af5c34dd95.png)

**Comment by kwm14** [comment]
## Agreed in WG
- Currently looks like this in MAAS, Snappy and ubuntu.com
- Update component to look like above
- @kwm14 to update design spec and create issue for update in build

**Comment by bartaz** [comment]
This was waiting very long. Bringing it back to WG for re-evaluation.

**Comment by matthewpaulthomas** [comment]
The ubuntu.com example is very ragged:

![vanilla#1916-dl](https://user-images.githubusercontent.com/19801137/75143682-64680d00-56ed-11ea-88ad-d8484e685f6f.png)

I’d use a `<table>` instead:

![image](https://user-images.githubusercontent.com/19801137/75144919-eeb17080-56ef-11ea-9cd4-06f083b0faae.png)

What does the MAAS example look like?

**Comment by lyubomir-popov** [comment]
Are we currently using this in maas? 

Searching for `<dl` or `"dl` in the code base doesn't return any results.

**Comment by anthonydillon** [comment]
JAAS example: 
![image](https://user-images.githubusercontent.com/1413534/75158286-b15bdb80-570d-11ea-931f-d5eab6497e61.png)

**Comment by anthonydillon** [comment]
Image builder:
![image](https://user-images.githubusercontent.com/1413534/75158367-d94b3f00-570d-11ea-8191-542d26e5df23.png)

**Comment by bartaz** [comment]
WG:
- keep DL as it now
- review how we use DL
- consider if we need 'compact' definition list variant as table

**Comment by anthonydillon** [comment]
Advantage dashboard:
![image](https://user-images.githubusercontent.com/1413534/75158555-452da780-570e-11ea-90d3-f4eebe15089a.png)

**Comment by matthewpaulthomas** [comment]
I think the Advantage dashboard instructions are really a table too. For example, if we’d implemented it a year or two earlier, it would have had a header row and a third column:

•|Ubuntu 12.04 LTS|Ubuntu 14.04 LTS
-|-|-
To check status:|`ubuntu-advantage status`|`ua status`
To turn on ESM:|`ubuntu-advantage enable-esm` _token_|`ua enable esm`
etc

**Comment by bartaz** [comment]
First thing to do would be to audit our products to see how definition lists are used.

**Comment by bartaz** [comment]
This have been through WG before, but because it needs UX work we should pass it though our new process.

**Comment by clagom** [comment]
These cases should be taken into consideration during the QA phase of the design/implementation.
