### ISSUE TITLE
Forms stacked have hardcoded widths, which get in the way when used in a 6-column container

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#1921]
## Pattern to amend

.p-form__stacked
.p-form__label & .p-form__control have hardcoded widths (25% / 75%)
My proposal is to come up with a way to allow col- classes to override the hardcoded values.
This is a tricky thing to change, because simply taking the hardcoded values out, or reducing the specificity (currently 2 levels deep, e.g. .p-form__stacked .p-form__label, which overrides the 1 level specificity of col-* classes) will break pages that use it as it is. So not sure what the best course of action is.

## Visual

![image](https://user-images.githubusercontent.com/2741678/42645950-50cc9bc6-85f7-11e8-8ce7-16642e1d9e45.png)

## Context

In what context does your amendment solve a problem?

There are a number of issues with this:
1) It doesn't use the grid, as it deosn't take gutters into account

2) has required overriding before (e.g. in maas [here](https://github.com/maas/maas/blob/7f7bcb050cfa796dd70d41a6cf4a5d1a5be4f6fb/src/maasserver/static/scss/_patterns_forms.scss#L7) and [here ](https://github.com/maas/maas/blob/7f7bcb050cfa796dd70d41a6cf4a5d1a5be4f6fb/src/maasserver/static/partials/dashboard.html#L116)). 

3) Any classes you add in an attempt to control the width of the label and control don't work, because the hardcoded values are further down in the cascade. This has resulted in a bit of a mess in maas, where we now have both col- classes that do nothing, and hardcoded override for vanilla's hardcoded values.
Provide a screenshot or link to a prototype of your pattern amendment.

![image](https://user-images.githubusercontent.com/2741678/42645728-b26b7222-85f6-11e8-91b7-c0a397aea127.png)

**Comment by kwm14** [comment]
## Agreed in WG
- @lyubomir-popov seems to make sense but can you provide an example of it fixed

**Comment by kwm14** [comment]
@lyubomir-popov is this still valid with your implementation of CSS grid?

**Comment by lyubomir-popov** [comment]
@kwm14 yes, it still has a hardcoded ```max-width: 25%;```.

**Comment by kwm14** [comment]
@lyubomir-popov ok thanks, maybe we can take a look at this week as we have a couple of sessions for Fixes in Vanilla 👍

**Comment by kwm14** [comment]
### Todo:
- Remove hardcoded CSS width
- Add an example using column classes
