### ISSUE TITLE
p-form--inline elements do not wrap

### ISSUE THREAD

**Issue by squidsoup** [canonical-web-and-design/vanilla-framework#1930]
The following bug was reported against MAAS recently: https://bugs.launchpad.net/maas/+bug/1782230

It appears that divs styled with _p-form--inline_ on the repository settings page render incorrectly, such that they don't appear to be visible. The divs are present in the markup, but as you can see from the attached screenshots, there appears to be a bug whereby the elements rendering outside the viewport fail to wrap appropriately.

# divs with p-form--inline
![image](https://user-images.githubusercontent.com/130286/42890747-977ca66e-8a7b-11e8-8287-aade665fcc62.png)
The "disabled pockets" div is selected here in the inspector.

# divs without p-form--inline
![image](https://user-images.githubusercontent.com/130286/42890725-8a21e8d0-8a7b-11e8-8d14-de975acd8eb9.png)

# Markup
The markup in question is in the form:

```html
<div class="row">
  <div class="col-6">
      <div class="p-form--inline">
          ...
      </div>
      <div class="p-form--inline">
          ...
      </div>
  </div>
</div>
```

**Comment by squidsoup** [comment]
It may well be that the markup is simply invalid, and this is an inappropriate use of _p-form--inline_.

**Comment by bartaz** [comment]
I verified that this is still an issue.

`--inline` form uses flex row display without wrapping. So when there are many form groups in a narrow container they will shrink in width until they stop fitting and will start overlapping:

![Screenshot 2020-09-07 at 13.22.15.png](https://images.zenhubusercontent.com/593a660851aa2c30578102bb/d417f8b8-f765-46ab-ab77-82b15cb3bb95)
[CodePen](https://codepen.io/bartoszopka/pen/YzqYdgM)

The way we could fix it on Vanilla side would be to add `flex-wrap: wrap`, but in such case, form groups will no longer be shrinked down, when they don't fit, but will simply wrap.
This may be a (visually) breaking change in places that use it currently (depending on size of the container and form elements in it).

![Screenshot 2020-09-07 at 13.24.30.png](https://images.zenhubusercontent.com/593a660851aa2c30578102bb/2f02f77c-6991-456d-bac1-5ce5fcf19232)
(we will also need to make sure that the left margin is replaced by right margin, to avoid additional space on wrapped items).

We can't control/check the size of the container element with media query, so we can't really respond to that (in similar way like on small screen inline form becomes stacked).

@lyubomir-popov Any thought or other ideas how to tackle this?

**Comment by bartaz** [comment]
For example, if we turn on wrapping, this form will start wrapping:

![Screenshot 2020-09-07 at 13.33.06.png](https://images.zenhubusercontent.com/593a660851aa2c30578102bb/d1a75e5d-eb11-40c8-a2c3-fa1945ffc7fb)
https://canonical.com/careers/engineering#available-roles

Although this one clearly doesn't fit in it's container, so not sure how this got through.

**Comment by lyubomir-popov** [comment]
@bartaz how about flex-shrink: 1, min-width: min-content, + flex-wrap: wrap; I get this:

![image](https://user-images.githubusercontent.com/2741678/92387875-36d53500-f10e-11ea-87da-25a48247087b.png)

**Comment by lyubomir-popov** [comment]
As for the careers page, this pattern doesn't seem ideal as ther'es no way to fit the items even with the changes above. I would explore placing the labels above the inputs and using the grid.
