### ISSUE TITLE
Update form class names

### ISSUE THREAD

**Issue by spencerbygraves** [canonical-web-and-design/vanilla-framework#1935]
## Forms

`.p-form--stacked` seems wrong as it's the label position that is important.

Could we use:

- Vertical
- Horizontal
- Inline

## Vertical

![image](https://user-images.githubusercontent.com/9105999/43001051-c37a030a-8c1b-11e8-9a35-c6f950523835.png)

## Horizontal

![image](https://user-images.githubusercontent.com/9105999/43001075-d358ac0e-8c1b-11e8-95b8-22fd0f14e1d4.png)

## Inline

![image](https://user-images.githubusercontent.com/9105999/43001093-e3a766d6-8c1b-11e8-97f0-48c8950fc312.png)

**Comment by kwm14** [comment]
## Agreed in WG
- Agreed not to update class name
- New proposal to apply styling to a field as opposed to the whole form
   - p-form__field--variant

**Comment by deadlight** [comment]
Upon investigation, this is just default form behavior in vanilla if you use not specific form layout class. It can be closed with no code changes needed.
