### ISSUE TITLE
Dropdown button 

### ISSUE THREAD

**Issue by lilyvidenova** [canonical-web-and-design/vanilla-framework#1957]
The dropdown button is widely used across MAAS as well as on the snapcraft store, on each individual snap's page. This type of button allows for more complex choices to be hidden away until needed. They trigger a new panel or modal to appear on the same page.

## Visual

<img width="339" alt="screen shot 2018-08-10 at 15 24 28" src="https://user-images.githubusercontent.com/17980375/43963179-89ef626e-9cb1-11e8-94db-9b762a039446.png">
wireframe for proposed new actions menu in MAAS

<img width="651" alt="screen shot 2018-08-10 at 15 25 02" src="https://user-images.githubusercontent.com/17980375/43963200-93664d4e-9cb1-11e8-97ae-8789f3212920.png">
snap page button

<img width="257" alt="screen shot 2018-08-10 at 15 25 37" src="https://user-images.githubusercontent.com/17980375/43963235-a8281906-9cb1-11e8-9c50-ea2c4e777723.png">
current MAAS design

## Context

In places where a number of actions can be grouped together, when most of the users would benefit from not seeing all options constantly.

## State

As with all buttons, the only addition is that the pressed state reveals a dropdown. 

## Progressive enhancement

A pattern should be designed small screen first. How does this pattern scale up?
- Same as normal buttons
- Depending on the size of the dropdown it might take over the full screen. If that's the case, a "close" button must be present at the top right of the dropdown.
How will this pattern degrade on less competent browsers?
- not sure :(

**Comment by kwm14** [comment]
## Agreed in WG
- update `contextual-menu`
   - allow for disabled links (new link class)
   - allow to group items
- update `button-icon` so icon can be positioned on the right
- @kwm14 to decide shadow vs key line border on contextual-menu

**Comment by lilyvidenova** [comment]
**Additional requirements** 
- the chevron to change direction + mouse-down/pressed state
- this should be a nav device rather than a form element, thus potentially have a different visual style for it

**Comment by kwm14** [comment]
Part of our Roadmap and will be built this cycle, closing as the work is now being tracked here https://github.com/canonical-web-and-design/vanilla-framework/issues/2336.
