### ISSUE TITLE
Search box reset button has unnecessary margin-right + strange hover/focus states

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical-web-and-design/vanilla-framework#1960]
1. There should not be any margin on the reset button. It was introduced in the `_base_button.scss` file when trying to add margin to inline buttons (`button + button`).
2. The reset button appears over top of the focus outline
3. There should probably be extra padding-right on the input because at the moment the text can be hidden underneath the reset button

![screenshot_1](https://user-images.githubusercontent.com/25733845/62922214-2a679700-bdab-11e9-8188-868d4b223082.png)
![screenshot_2](https://user-images.githubusercontent.com/25733845/62922221-2c315a80-bdab-11e9-9513-944cadb0e336.png)

**Comment by lilyvidenova** [comment]
@lyubomir-popov has your recent work fixed this?
