### ISSUE TITLE
Remove circled background on stepped list

### ISSUE THREAD

**Issue by therealjuan** [canonical-web-and-design/vanilla-framework#1973]
## Pattern to amend

Stepped list

## Visual

![image](https://user-images.githubusercontent.com/8167677/44579585-c8bfae80-a78e-11e8-995b-971e779bb00b.png)

## Context

The circled background on the stepped list takes a lot of visual impact on pages with loads of instructions. We can dial down the visuals by removing the background.

**Comment by Caleb-Ellis** [comment]
WG +1

Design team to go over current `.p-stepped-list` pattern and tone down the visual impact.

**Comment by bartaz** [comment]
This was waiting very long. Bringing it back to WG for re-evaluation.

**Comment by bartaz** [comment]
WG:
- there was an update to the design, we can close this
