### ISSUE TITLE
p-fluid-grid

### ISSUE THREAD

**Issue by Lukewh** [canonical-web-and-design/vanilla-framework#1974]
See https://github.com/canonicalltd/snap-squad/issues/597#issuecomment-412020662

And https://github.com/canonical-websites/snapcraft.io/pull/1011

**Comment by Caleb-Ellis** [comment]
WG +1

All agree to include this pattern in Vanilla. Whoever works on this should come up with a few options for names to minimise conflation with "flexbox" and to some extent the grid. Also, this pattern should be specced to consider how it aligns with column margins / the grid in general.

**Comment by deadlight** [comment]
Let's hold off on working on this issue until after 2.0 - we are making extensive changes to the Vanilla grid.

**Comment by kwm14** [comment]
@lyubomir-popov is working towards implementing CSS grid as an upgrade to our current gird system.

https://github.com/vanilla-framework/vanilla-framework/issues/2134

**Comment by deadlight** [comment]
Now that we have a CSS grid-based grid system in Vanilla, I don't think that we require this to be upstreamed.

The latest grid - going live in v2.0.0 - supports all features that the "fluid grid" proposal would have solved and we shouldn't have duplicate grids unnecessarily.

**Comment by Lukewh** [comment]
The implementation of the grid does not accommodate the use case this pattern was implementing. At a certain breakpoint the new grid just falls to 1 column.


Old pattern:
![old-pattern](https://user-images.githubusercontent.com/479384/62222241-f2c01e80-b3aa-11e9-9b9c-9d2361fb6e6a.gif)


New grid:
![new-grid](https://user-images.githubusercontent.com/479384/62222256-f653a580-b3aa-11e9-8032-d54400f40609.gif)

**Comment by lyubomir-popov** [comment]
@Lukewh have you tried using the small/medium breakpoint [grid classes](https://docs.vanillaframework.io/patterns/grid/)?

**Comment by Lukewh** [comment]
@lyubomir-popov it's ok... but going down from large to medium, just before medium you get this situation:
![Screenshot_2019-07-31 Snapcraft - Snaps are universal Linux packages](https://user-images.githubusercontent.com/479384/62230616-18a0ef80-b3ba-11e9-9d0f-847f4d3fcfe6.png)
(Above old behaviour, below new behaviour)
Is there a magic `col-${magic}-` breakpoint.

The thing that's nice (IMO) about the fluid-grid proposal is that the images are never resized, the layout wraps to the content, not the content squashing/ stretching to the layout.

I'd worry squashing these logos could breach some design guidelines (we've been bitten by that recently on snapcraft). I guess we could change the logo based on the size of the container - but I'm pretty sure that'd be heavier than the current implementation of the fluid-grid we've got in snapcraft.

It's also fine if it's decided this shouldn't be part of vanilla - we can just keep it in snapcraft.

**Comment by lyubomir-popov** [comment]
How about adding a media query to change the number of columns a logo takes up for the edge case above? At the above res the underlying grid is still 12 columns, but so you can make each logo take up 3 instead of 2 columns.

To clarify, there is no squashing - as in change of proportions. It is just scaling them down, so no risk of breaching guidelines.
No need to change the image either, as we're scaling down not up.

As for the loss of fluidity - The fluid grid breaks away from the grid used on the page, so shouldn't really be called a grid. It is just free flowing center-aligned content. If it were the only thing on the page, there's nothing wrong with that. As soon as it is placed on a page with a complex layout, it becomes inconsistent with the overall structure of the page. The logos do not align to other elements on the page and to me that's the main drawback of this pattern.

**Comment by Lukewh** [comment]
Aside from the fact the jetbrains logo already breaches guidelines, scaling will breach guidelines: https://www.jetbrains.com/company/brand/
Min size of the square on a screen 50px.

**Comment by lyubomir-popov** [comment]
True, I would suggest moving the query at which a logo starts spanning 3 columns to a point where all the logos stay above the recommended min-size.

**Comment by kwm14** [comment]
## WG
- Try https://docs.vanillaframework.io/examples/patterns/inline-images/ component and see if this solves the problem
- @kwm14 to update logo size using logo template to see if this helps too

**Comment by lyubomir-popov** [comment]
@Lukewh proposal implementation that keeps logos above a certain minimum size, replicates the "fluid grid" centering of the second row, and is fully based on the grid, with a minimal custom snippet: https://codepen.io/lyubomir-popov/pen/ympBrJ

It does it by altering the number of columns per logo in the range where it is needed. (In the example, it supposes that's 772-1036px, of course this will vary depending on the logo guidelines number of logos in the strip, etc.).

**Comment by lyubomir-popov** [comment]
@Lukewh can this be closed? I can see snapcraft.io uses the css grid implementation I proposed.

**Comment by Lukewh** [comment]
Yes thanks @lyubomir-popov
