### ISSUE TITLE
Labels wrapping checkboxes should style correctly

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical-web-and-design/vanilla-framework#1983]
Currently, checkboxes with labels are styled with the following markup:
```html
<input type="checkbox" id="checkExample1">
<label for="checkExample1">Checkbox option 1</label>
```
where the `input` is actually invisible, and the checkbox itself is a styled `label::before`.

We should be able to get the same styling with a label wrapping an input, e.g.
```html
<label>
  <input type="checkbox" id="checkExample1">
</label>
```

This is causing issues with `jsx-a11y/label-has-associated-control`

**Comment by lyubomir-popov** [comment]
We've discussed this a few times, the only way to avoid this non-semantic markup is to rebuild the checkbox without using input type="checkbox", which is simply impossible to style consistently across browsers. However this requires replicating all functionality via js. This is what material design does. Since there's no appetite to do this, I suggest we close this issue.

**Comment by lyubomir-popov** [comment]
Link to material design example heavily relying on js:
![image](https://user-images.githubusercontent.com/2741678/64024807-253c7300-cb33-11e9-89bf-359ad01dec19.png)
https://material.io/develop/web/components/input-controls/checkboxes/

**Comment by lyubomir-popov** [comment]
Link to material design checkbox js example https://material.io/develop/web/components/input-controls/checkboxes/

**Comment by lyubomir-popov** [comment]
Adding the WG label so we can discuss whether we want to replace native checkboxes with bespoke built ones, or whether we should close the related issues.

**Comment by lyubomir-popov** [comment]
Example from bootstrap, they do more or less what we do - 
siblings instead of input inside label:

![image](https://user-images.githubusercontent.com/2741678/64120088-3d123200-cd93-11e9-8e1f-6cc0e3d5b6c1.png)

**Comment by kwm14** [comment]
## WG
- Revert checkbox and radio styles back to the browser default
- Special cases when input wrapped inside label
