### ISSUE TITLE
Long words overflow in mobile

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/vanilla-framework#1985]
In Webkit browsers (e.g. Chrome on Android), Long words (e.g. links) overflow and push the page to the right in narrow screens, leading to a horizontal scroll bar:

![link-bug](https://user-images.githubusercontent.com/519935/45611730-bae50c80-ba60-11e8-8c5b-1300cbcb01ce.png)

The fix is simply:

``` css
word-break: break-word;
```

Which I've hacked into discourse-docs e.g. here:

https://github.com/nottrobin/discourse-docs.snapcraft.io/commit/ef3f0db1dc894063795570977f73fd3a91e65f68#diff-9f40d64fd95564c5ba27a3ef536cb50fR209

**Comment by bartaz** [comment]
The bug doesn't seem to exist anymore, local hack also doesn't seem to be in snapcraft codebase anymore.

Currently links are cut (overflow off the screen), but there is no horizontal scroll bar, which also is not ideal:

<img width="413" alt="Screenshot 2020-01-10 at 09 56 46" src="https://user-images.githubusercontent.com/83575/72139796-9e748e00-338f-11ea-8dbd-149fee3c057b.png">

**Comment by bartaz** [comment]
As discusses on stand up - we want to stay close to browser defaults, so will leave it as it is now.
