### ISSUE TITLE
Pattern: Docs layout

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/vanilla-framework#1991]
https://docs.vanillaframework.io uses a layout which has a left sidebar and a right content area.

https://docs.staging.snapcraft.io/ uses something very similar, but squeezed to `max-width: 64.875rem`. Hopefully, down the line these two will be unified, and will become the standard for all docs.

The latter I've turned into [a new layout component called `l-docs`](https://github.com/nottrobin/discourse-docs.snapcraft.io/blob/word-break/static/sass/_layout_docs.scss). Maybe we might want to consider making this an official part of the Vanilla?

**Comment by kwm14** [comment]
## Agreed in WG
- we need to understand why you've done it this way
- will discuss in the next WG when your here

**Comment by nottrobin** [comment]
Actions (from WG):

- [ ] Port documentation layout styles from docs.vanillaframework.io into Vanilla core, such that docs.vanillaframework.io has no custom styles (@deadlight to create issues)
- [ ] Carry out an investigation into top navigation width, to decide whether snapcraft.io, www.ubuntu.com are allowed to be different from e.g. maas.io
- [ ] Conclude discussion about documentation landing pages - is it okay to have custom, "pretty" landing pages in front of documentation that is otherwise generated from Discourse (discussion [started on snapcraft forum](https://forum.snapcraft.io/t/proposed-new-documentation-outline/6718/16))
- [ ] Decide whether documentation sites should be full width, or constrained width, or both

**Comment by deadlight** [comment]
Issue created: #2049

**Comment by bartaz** [comment]
Documentation layout work is in progress and tracked elsewhere (#2681 )
