### ISSUE TITLE
Add goal conversions to GA for docs.vanillaframework.io

### ISSUE THREAD

**Issue by kwm14** [canonical-web-and-design/vanilla-framework#2043]
## Describe the brief
Currently no goal conversions are set on https://docs.vanillaframework.io/en/

Action to add these to track specific user interactions on our site based on findings [here](https://github.com/ubuntudesign/vanilla-design/issues/315):
- Button/link clicks
- Framework downloads
- Releases / Design specs

**Comment by anthonydillon** [comment]
I believe we have these goals set in the data studio. Does anyone have access to the data studio? https://datastudio.google.com/u/1/reporting/1yvFO7HQbilita9Av08FV2poXADxV0WPz/page/1xZU

**Comment by bartaz** [comment]
@anthonydillon Do you think it's still relevant?

If we treat Vanilla focus on internal use, it's hard to define what goals we would like to define for it.

**Comment by anthonydillon** [comment]
Not at all, this is from the days we were trying to take over the world :rocket:
