### ISSUE TITLE
Provide variables to override navigation pattern colours

### ISSUE THREAD

**Issue by deadlight** [canonical-web-and-design/vanilla-framework#2046]
## Pattern to amend

p-navigation

## Context

Some colours are automatically generated within the p-navigation pattern from the colour variables passed in. There should be an option to override these generated colours with specific variables.

e.g. The background colour of hovered nav items is `background-color: darken($color-navigation-background, 3%);` with no way of avoiding this behaviour with a variable

**Comment by anthonydillon** [comment]
I would prefer these to be out of the box good options. If the background is dark the hover should be lighten.

**Comment by deadlight** [comment]
I agree, there should be sensible defaults (in fact, I think that there are since this bug was filed) but I'll make sure that all defaults use variables that may be overridden if required.
