### ISSUE TITLE
Document that some patterns require js, and that users will need to provide the implementation

### ISSUE THREAD

**Issue by squidsoup** [canonical-web-and-design/vanilla-framework#2050]
We don't appear to ship the scripts that patterns such as the contextual menu depend on in the `vanilla-framework` package. 

On a similar note, it isn't particularly clear from the documentation that scripts are required for some patterns to function, nor do we provide a link to the scripts on a CDN as far as I can tell.

**Comment by anthonydillon** [comment]
The difficulty is the number of ways JS is used peer project. We could bundle JS files with Vanilla but that wouldn't work in an angular/react/polymer project.

I agree the documentation is lacking.

**Comment by squidsoup** [comment]
Okay, that's fair enough. Perhaps this issue should just be that we need to make that clear in the docs.

**Comment by deadlight** [comment]
Agreed. I'll include it in an upcoming sprint. Perhaps a "javascript" section in the docs for each pattern saying which, if any, functionality users are expected to implement (which can also include links to practical examples or recommended libraries).

**Comment by squidsoup** [comment]
@deadlight thanks, sorry for the confusion on my part!

**Comment by kwm14** [comment]
## JavaScript Doc
I've created a [document](https://docs.google.com/spreadsheets/d/1CHdcYi2j9T0vgNRWDj4s0nzz19t9ncV0W9tHGlHpsdU/edit?usp=sharing) highlighting which components require JS, the first pass is adding a notification within the docs page with a functionality section added by our intern Gruff 💯  

<img width="1440" alt="Screenshot 2019-08-19 at 12 00 48" src="https://user-images.githubusercontent.com/17748020/63275277-25b64d80-c299-11e9-9f69-812f4e9ba1d5.png">

This iteration I will be creating a design for JavaScript section to feature on that particular components documentation page 👍 

@anthonydillon @deadlight @squidsoup could you have a look at the document and comment if anything needs changing 😃 also when we add JS section do you think we should supply example scripts for users?

**Comment by kwm14** [comment]
Updated document and ready for JS phase II 💯
