### ISSUE TITLE
Combining u-hide--medium and the grid

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/vanilla-framework#2070]
When using `u-hide-medium` on a column it hides the column but does not remove the margin-left on the next column as it's not the first element but the first visible one. We need a way for the grid to ignore hidden columns.

For example:
```html
<div class="row">
  <div class="col-6 u-hide--medium">
     ....
  </div>
 <div class="col-6">
      ....
  </div>
</div>
```

On a medium breakpoint the second column will have margin-left.

**Comment by deadlight** [comment]
This would prove very difficult to achieve. We can't select based on a neighbour's property so there's no pure CSS solution.

A solution, which feels a bit dirty would be a class which marks the second col-6 as "first--medium" but that feels very brittle and a lot to add to markup.

We should readdress this after we land #2134, which will make significant changes to the grid.

**Comment by deadlight** [comment]
The new grid no longer has this problem
