### ISSUE TITLE
Contextual menu outline using default styling instead of the vanilla one

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#2081]
**Describe the bug**
The accessibility outline on the contextual menu is the browser default dotted one, instead of our blue outline.
**To Reproduce**
1. Go to 'https://vanilla-framework.github.io/vanilla-framework/examples/patterns/contextual-menu/#'
2. Click on any of the links
3. Tab through the menu items

**Expected behavior**
Blue outline

**Screenshots**
![image](https://user-images.githubusercontent.com/2741678/49881325-fc017880-fe25-11e8-93bf-bba6dc091ea7.png)

Note: AFAIK this is quite common for many components. Maybe we need to QA all and standardise them?

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by deadlight** [comment]
Thanks for reporting this.

I think that you're right about this not being a single case. I'll suggest doing an audit of all HTML elements with a selected state to capture all of the inconsistencies.
