### ISSUE TITLE
Checkbox looks disabled/invisible against grey backgrounds

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/vanilla-framework#2083]
1\. Put a checkbox on a grey background.
2\. View the page in a Blink browser (in my case, Chromium on Ubuntu).

What happens: 

- If the background is not close to #cccccc, for example [in an ubuntu.com contact form](https://www.ubuntu.com/openstack/contact-us?product=foundation-cloud), the checkbox appears disabled when it is not.

  ![vanilla-checkbox-background-light](https://user-images.githubusercontent.com/19801137/50052719-6cf3a980-0120-11e9-9ca2-b97ccd21c843.png)

- If the background is exactly/nearly #cccccc, the checkbox disappears altogether!

  ![vanilla-checkbox-background-ccc](https://user-images.githubusercontent.com/19801137/50052733-97456700-0120-11e9-934d-59be58eba9d7.png)

It might save time to fix #2009 at the same time as this bug.

**Comment by deadlight** [comment]
This is unrelated to #2009, it's fine to work on them separately

**Comment by lyubomir-popov** [comment]
After discussing with @spencerbygraves we agreed to add white background to the checkbox, to make it blend less with the grey background in @matthewpaulthomas's example. We decided against altering the border colour to a black with transparency, which was a previously discussed solution.

**Comment by lyubomir-popov** [comment]
![image](https://user-images.githubusercontent.com/2741678/64334816-54d6f980-cfd1-11e9-97fb-5ef6bdfd05fd.png)
