### ISSUE TITLE
Ensure Lyubo's fixes are included upstream - MAAS

### ISSUE THREAD

**Issue by kwm14** [canonical-web-and-design/vanilla-framework#2098]

**Comment by kwm14** [comment]
Has this been fixed @lyubomir-popov ?

**Comment by lyubomir-popov** [comment]
I think this was about porting work done for the ubuntu nav and maas into vanilla. It hasn't been done yet and should probably be an epic, as it is a rather large task. (Very low priority though)

**Comment by kwm14** [comment]
Ok great 👍 thanks for the update.

**Comment by kwm14** [comment]
@lyubomir-popov any further updates on this issue?

**Comment by lyubomir-popov** [comment]
I think we can close it. The main things that started in those other repos were denser / minimal spacing between text elements, which was implemented with the update to u-min-margin--bottom. A Lot of the other small improvements have also made it into the 2.0 alpha.
