### ISSUE TITLE
Fix Vanilla release pipeline

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical-web-and-design/vanilla-framework#2114]
The current release process has completely broken at some point between the alpha/beta release cycle of the major spacing changes in 1.7 and now. As it stands:
- The Jenkins bot no longer has write access to master and cannot push automatically, causing the Jenkins job to fail
- The Jenkins bot can no longer publish to npm because of an expired token (see https://github.com/ubuntudesign/base-squad/issues/69)
- The current script does not allow for point releases of previous versions, instead it always releases from the develop branch. This makes it impossible to release small hot-fixes for previous minor versions.

We should come up with a plan of how we want to do releases in the future, which will tie in with how we want to separate the different versions within this repo, and whether we need both a develop AND master branch.

This should ideally be addressed before the 2.0 release.

We should also document how to troubleshoot issues with releasing.

**Comment by deadlight** [comment]
We have moved to manually deploying the NPM releases to allow flexibility. The Jenkins build is no longer an issue.
