### ISSUE TITLE
patterns_table-expanding has an invalid property

### ISSUE THREAD

**Issue by Lukewh** [canonical-web-and-design/vanilla-framework#2133]
**Describe the bug**
`patterns_table-expanding` has an invalid property

**To Reproduce**
View https://github.com/vanilla-framework/vanilla-framework/blob/develop/scss/_patterns_table-expanding.scss#L36

**Expected behavior**
`word-break: break-all;` or `word-wrap: break-word;`

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Firefox
 - Version 64.0.2

**Additional context**
I'm not sure what the desired functionality is. `break-all` will break no matter what - which probably isn't desired, however long url's won't break.

**Comment by bartaz** [comment]
@Lukewh 'word-break: break-word` seems to be a valid property and value. It's fully supported by most browsers although not by IE and Edge which we probably should address.

**Comment by bartaz** [comment]
Table expanding pattern seems completely broken in IE currently, so providing a fallback is impossible.
Closing this, as this particular bug doesn't need to be addressed.

Table expanding issue in IE reported separately #2726.
