### ISSUE TITLE
Implement CSS grid

### ISSUE THREAD

**Issue by kwm14** [canonical-web-and-design/vanilla-framework#2134]
Finalize and implement findings from spike here: https://github.com/vanilla-framework/vanilla-framework/issues/2101

**Comment by kwm14** [comment]
Will pick up potentially next iteration, if not there after as @lyubomir-popov is needed on MAAS as a resource.

**Comment by lyubomir-popov** [comment]
I have 2 spare days so picking this up again.

**Comment by kwm14** [comment]
@lyubomir-popov perfect, thats great 👍 I've got this work down to do this next iteration as we have you as a resource for the first week, although it's a bank holiday so we're only in the office for 4 days 😉
