### ISSUE TITLE
Close and back should be on the left of the pattern

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/vanilla-framework#2137]
## Pattern to amend
I have been asked to move the close and back functionality to the left side of each pattern. For example the close icon on the Modal pattern should be on the left.

**Comment by kwm14** [comment]
@anthonydillon what component does this functionality need to be applied to?

**Comment by anthonydillon** [comment]
The problem arose from the close position on the modal pattern. I am not aware of any others.

**Comment by spencerbygraves** [comment]
@anthonydillon this sounds a bit odd, what was the problem?

I think most modal windows have close on the right, although I haven't researched that. If it went before the title, the title would not be aligned with the content below.

I have seen modals with the close button top right on the dark background, as on the [Maas tour pages](https://maas.io/tour), which could be a solution.

**Comment by anthonydillon** [comment]
Personally I agree but it is something Mark has asked for multiple times.

**Comment by deadlight** [comment]
This is particularly poor UX and goes against very well established interface conventions...
But if it's mandated then there's not much choice in the matter.

**Comment by bartaz** [comment]
@anthonydillon Do you think it's still relevant? It hasn't been mentioned for w while.

**Comment by anthonydillon** [comment]
I am happy to close it for that reason.
