### ISSUE TITLE
Should not have to include base to cherrypick a pattern

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/vanilla-framework#2146]
Currently we need to include the base styles (which include the mixins) when including a single pattern.

**Comment by clagom** [comment]
Create a core file to be included in each pattern @deadlight

**Comment by lyubomir-popov** [comment]
@anthonydillon Is this still valid? We updated the [docs](https://docs.vanillaframework.io/customising-vanilla/) to say base_placeholders is the bare minimum.

**Comment by bartaz** [comment]
I guess we can close this.
Patterns do rely on base and we cant avoid that. We currently build the standalone examples to make sure patterns rely on minimal dependencies (ideally just base).
