### ISSUE TITLE
p-inline-list--middot: wrong dot position and gap on word wrap 

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#2147]
**Describe the bug**
The dot is misplaced; there's a gap to the left of the wrapped item (see screenshot)

**To Reproduce**
1. Go to a page containing the pattern, like https://vanilla-framework.github.io/vanilla-framework/examples/patterns/lists/lists-mid-dot/
2. Add at least two words in the last item
3. Resize so said item wraps

**Expected behavior**
On wrapping, dot and gap should be omitted.

**Screenshots**

With error (the dot appears in the middle of the letter on the preceding line: 
![image](https://user-images.githubusercontent.com/2741678/52221993-62d96600-289a-11e9-9269-baf21acc72f0.png)

![image](https://user-images.githubusercontent.com/2741678/52221894-1db53400-289a-11e9-9202-6b97fd1d20a7.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome

**Comment by lyubomir-popov** [comment]
This has been fixed. Dot now stays on the top row:
![image](https://user-images.githubusercontent.com/2741678/69422920-d6ab0900-0d1c-11ea-9d3f-92ba1b29c36d.png)

**Comment by anthonydillon** [comment]
That screenshot does not look right. Is that what the pattern looks like now? The dot should be centered between the list items.

**Comment by lyubomir-popov** [comment]
Yes, there's an [issue ](https://github.com/canonical-web-and-design/vanilla-framework/issues/2557) for that as well, I'm about to submit a pr to fix it.
