### ISSUE TITLE
Buttons: Amend examples to not nest <buttons> inside <p>s

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#2158]
## Pattern to amend: button patterns

Currently, button pattern examples show ```<button>```s wrapped in a ```<p>```. This was done before to space out buttons in v.1.6.8 and earlier, but that's no longer necessary. Arguably, it isn't very semantic either. 

I would propose that we change most examples to show buttons on their own, and maybe keep an example only to demonstrate backward support for the countless places on our sites where the buttons are nested in paragraphs. 

## Visual
![image](https://user-images.githubusercontent.com/2741678/52953197-b52c8380-337e-11e9-8a1e-c952324af650.png)

## Context
 Provides clear guidance when someone is in doubt whether to nest or not.

**Comment by kwm14** [comment]
@lyubomir-popov isn't this a bug rather than a proposal? 😕 

We're updating all component document pages as of the v2.0 release, so we can update the page examples as we go 👍

**Comment by lyubomir-popov** [comment]
@kwm14 wasn't sure, maybe we can classify as bug. If @anthonydillon @deadlight agree that this doesn't need discussion and we can just do it.

**Comment by deadlight** [comment]
@lyubomir-popov Yep, looks like a bug to me - it's simply updating the demo to how it's meant to be used.

**Comment by lyubomir-popov** [comment]
thanks @deadlight
