### ISSUE TITLE
p-navigation relies on element selectors

### ISSUE THREAD

**Issue by deadlight** [canonical-web-and-design/vanilla-framework#2168]
**Describe the bug**
p-navigation uses the `p-navigation__link > a`, which is excessively greedy and makes overriding without also using a `> a` rule in other patterns impossible.

We should use classes for all of these selectors.

**Comment by lyubomir-popov** [comment]
@deadlight Bumped into this one while working on the themes, do you have a recommendation? Should we introduce classes on the anchors? Sounds like the cleanest thing to do but it will be a breaking change.

**Comment by anthonydillon** [comment]
We should as we may like to use an other elements in the navigation other then links. For example, button, image, etc. The use of the element in the classname is also an anti-pattern. We should name classes based on there function not what the are or how they are styled as these things should be variable.

We would need to continue to support the element version until 3.0.

**Comment by deadlight** [comment]
Yes, I agree. We should introduce a class but keep support for the element selectors while marking them as deprecated. If the classes have to be more specific in the short run to override the element selector then that's acceptable as a short-term fix.

We can then do a minor release straight away and hold off on the removal until we have more reasons to jump to 3.0

**Comment by lyubomir-popov** [comment]
Sounds good, thanks.

**Comment by lyubomir-popov** [comment]
To avoid conflicts, I'll wait for the theming spike pr to be merged before tackling this one.

**Comment by kwm14** [comment]
Theming spike [merged](https://github.com/canonical-web-and-design/vanilla-framework/pull/2507). Issue now unblocked 👍

**Comment by bartaz** [comment]
Our current navigation structure is:

```
.p-navigation > .p-navigation__row > .p-navigation__nav > .p-navigation__links > .p-navigation__link > a
```

To remove element selector for `> a` we need to add yet another class to it. `__link` is already taken by it's parent, so maybe `p-navigation__item`?

```
.p-navigation > ... > .p-navigation__links > .p-navigation__link > .p-navigation__item
```

But, to be honest I think it should be opposite. The link at the end should be `__link`, and the parent should be an `__item`. We already have different type of navigation item that is not a "link" - subnav menu.

So I think a better structure would be:

```
.p-navigation > ... > .p-navigation__items > .p-navigation__item > .p-navigation__link
```

So, `__links` would rename to `__items`, `__link` would rename to `__item` and `> a` would become `__link`.
Of course we would need to keep the support for old class names and `a` until 3.0.

This backwards compatibility may also have a small drawback that `p-navigation__item` class name would be used in both on different elements, so some nesting would be needed to make sure they work properly.

@anthonydillon @lyubomir-popov Any thoughts? Should we go with bigger renaming of things, or just add a new `__item` class to the `a` and leave rest as it is?

**Comment by lyubomir-popov** [comment]
I like the new structure, one question though. Since the nav is essentially a list, and parents to most `*__item` classes are usually in the format `*-list`, should `items` be `list`?

As for nesting, maybe append an index to subnavs and follow the same structure? The subnav is curently a classthat is added to `p-navigation__link`, whereas it should arguably be just a modifier. This would simplify themeing too.

**Comment by bartaz** [comment]
@lyubomir-popov 

> I like the new structure, one question though. Since the nav is essentially a list, and parents to most *__item classes are usually in the format *-list, should items be list?

That's a good catch, and possibly this kind of consistency would make sense.
But for this to be useful and not even more confusing, I guess the new `p-navigation-list` pattern would need to be pattern on it's own, that in theory could live outside of `p-navigation`.

I'm not sure if that's not going too far.

**Comment by anthonydillon** [comment]
I like the new structure proposed:
> .p-navigation > ... > .p-navigation__items > .p-navigation__item > .p-navigation__link

I have never seen a use-case to have navigation list outside of the navigation pattern. Therefore, I suggest it is much easier to understand, use and maintain when they are combined.
