### ISSUE TITLE
Update code pattern for real-world uses

### ISSUE THREAD

**Issue by deadlight** [canonical-web-and-design/vanilla-framework#2170]
## Pattern to amend
`p-code-numbered`

## Context

On our websites code blocks tend to fall into two examples:
- excerpts of code from a file, requiring line numbers
- example terminal commands and output, not requiring line numbers but requiring a "$" marker to denote input

## Suggestion

We should generalise the pattern to `p-code`.

We can then add modifiers to the core pattern for the two current use cases:
- `p-code--numbered`
- `p-code--terminal`

`p-code--numbered` will work like the current pattern and the `--terminal` variant will enable users to mark-up lines as input.

e.g.:
```
<pre class="p-code--terminal"><code>
<span class="p-code__input">echo "hello world"</span>
<span>hello world</span>
</code></pre>
```

Which would look something like this on the page:
```
$ echo "hello world"
hello world
```

## Other issues

This will address the issue raised by @matthewpaulthomas in #1549

**Comment by matthewpaulthomas** [comment]
Nice. Of the three classes in the example, two start with `p-`, one has `code-`, one has `code--`, and one has `code__`. Could they be more consistent? For brevity, maybe just `p-terminal`, `p-input`, and `p-output`.

**Comment by deadlight** [comment]
@matthewpaulthomas we use [BEM notation](https://canonical-webteam.github.io/practices/coding/stylesheets.html) for class names in Vanilla, it's a formal naming system for consitency.

(I left some mangled markup in my example, which was confusing and which I have fixed)

The name is broken down as follows:
- "p-": denotes a pattern (rather than a utility, for example)
- "code": This is the name of the component (the Block in BEM)
- "__input", etc: These are Elements within the Block, the double-underscore marking hierarchy
- Anything with a "--" prefix is a modifier on the Block - in this case "--numbered" and "--terminal"

I appreciate that it can be a little confusing without context but consistency of API within the codebase isn't something we can compromise. Creating two top-level components for slight variants isn't something we should do.

**Comment by kwm14** [comment]
## WG
- @deadlight create a proof of comcept

**Comment by bartaz** [comment]
Bringing it back to proposals as it was validated long time ago and we already updated code components a bit.

**Comment by bartaz** [comment]
WG:
- get a big picture (from epic), have UX person to help with that
- assign mpt to the epic

**Comment by wgx** [comment]
Addressed by "Command prompt" in spec: https://discourse.ubuntu.com/t/code-snippet-pattern/19195

**Comment by sowasred2012** [comment]
@bartaz I think we can close this too - this has been covered by the basic, numbered and icon block variants in the new code snippet, right?

**Comment by bartaz** [comment]
Yes, covered by code snippet
