### ISSUE TITLE
Images are collapsed before load

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/vanilla-framework#2175]
Normally, if you add a `height="{number}"` attribute to your `<img`, the browser will reserve that space in the web page while it waits for the image to load, avoiding a jumping effect when the image arrives.

Something in Vanilla (1.8.1) is overriding this behaviour (at least in Firefox), and "height" attributes no longer reserve the space, so jumping still happens.

E.g. play with this HTML doc in Firefox:

``` html
<head>
  <link href="https://assets.ubuntu.com/v1/vanilla-framework-version-1.8.1.min.css" rel="stylesheet" />
</head>

<p>
  <img src="http://httpbin.org/delay/2" alt="GO AWAY!!!" width="300" height="360">
  </p>
  <p>
  Hello world
  </p>
```

**Comment by deadlight** [comment]
I can't replicate this in FF or Chrome:
https://codepen.io/deadlight/pen/qvxjva

I'm closing this issue, please reopen if you can confirm that it's valid.

**Comment by nottrobin** [comment]
As demoed, this is valid.

**Comment by lyubomir-popov** [comment]
Interesting bug. Looking at the shadow root in chrome, it appears the presence of an alt attribute converts it to an inline element:

![image](https://user-images.githubusercontent.com/2741678/54372245-d8dba480-4672-11e9-957a-98358418c4dc.png)

**Comment by nottrobin** [comment]
This is not caused by default Chrome behaviour alone, because it works as I would expect without vanilla framework. E.g. look at this fiddle:

https://jsfiddle.net/L3su5x8n/1/

The 360 pixel height is reserved for the first 20 seconds before the image "loads" (then it collapses when it realises there is no image - you might need a hard refresh to see it again after the first load).

Compare this to:

https://jsfiddle.net/L3su5x8n/2/ (again, try hard-refreshing)

**Comment by nottrobin** [comment]
Better illustrations:

https://jsfiddle.net/z50gd7w6/2/ (without Vanilla)

vs

https://jsfiddle.net/z50gd7w6/3/ (with Vanilla)

**Comment by lyubomir-popov** [comment]
it's the height: auto I think

**Comment by lyubomir-popov** [comment]
@deadlight I pasted the whole vanillla css in a style tag in @nottrobin's example, and started deleting rules until the image appeared at the right size. The culprit is img {height:auto}; 

Not sure how to fix this though. Strangely, overriding it with height: inherit / initial / unset doesn't change anything. Seems like as long as it is set to anything, it will override the html attribute height

**Comment by bartaz** [comment]
We discussed it before (https://github.com/canonical-web-and-design/vanilla-framework/issues/2588), this is not Vanilla issue. Images should have height defined on HTML level.
