### ISSUE TITLE
display:inline on <code> throws line-height off the baseline grid

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#2179]
**Describe the bug**
The fix introduced in #1765 causes the line-height of text inside a```<code>``` element nod adhere to the baseline grid. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'http://0.0.0.0:8101/vanilla-framework/examples/base/code/'
2. Turn baseline grid on
3. Observe how lines do not adhere to grid

**Expected behaviour**
Lines should adhere to grid.

**Screenshots**
I believe the fix was meant to avoid duplicate padding top on code snippets inserted in regular paragraphs. Doesn't display:inline block work for this purpose as well? I made a sample with a paragraph containing:
• one-word code snippet
• a few lines of code
• the original code inside pre example

Using inline block seems to work fine under these conditions. 
![image](https://user-images.githubusercontent.com/2741678/53732249-a44f3800-3e7d-11e9-9cea-ab61c32436d1.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome

**Comment by lyubomir-popov** [comment]
@Caleb-Ellis do you remember any additional details about #1765? Would changing to inline-block break something else?

**Comment by bartaz** [comment]
Seems to be fixed by now.
