### ISSUE TITLE
Tooltips on disabled buttons

### ISSUE THREAD

**Issue by steverydz** [canonical-web-and-design/vanilla-framework#2180]
**Describe the bug**
If you add a tooltip to a disabled button, the tooltip is transparent which can make it hard to read

**To Reproduce**
Add a tooltip to a disabled button

**Expected behavior**
A tooltip should be displayed at full opacity even if the button is disabled

**Screenshots**
https://codepen.io/steverydz/pen/XGjWJL

**Comment by bartaz** [comment]
After canonical-web-and-design/vanilla-squad#1000 this should be fixed (or easy to fix)

**Comment by sowasred2012** [comment]
Bumping to 5 for investigation later - Chrome doesn't allow mouseevents on disabled buttons (rather, Firefox is the only browser that _does_), so detached variant of the tooltip, which uses JS to position the tooltip relative to the trigger element, won't work.

**Comment by sowasred2012** [comment]
Adding mattermost comments on this subject from @lyubomir-popov and @wgx:

> sowasred2012
>12:09
>@lyubo do you have any thoughts on disabled elements being able to use tooltips? do we want to support that?

>lyubo
>12:11
> no, I don't think we should. the disabled state explicitly tells you this element is not interactive currently
>Any explanation why it is disabled shouldn't require discovering a hidden easter egg tooltip. It should be displayed in a paragraph next to the disabled element IMO. @wgx what do you think?

>wgx
>12:19
>Yep, agree. If something is disabled the users first thought is often "why can't I use this!?"
