### ISSUE TITLE
<code> white space set to pre-wrap

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#2184]
**Describe the bug**
White space inside ```code``` is set to pre-wrap. In the screenshot below, observe how white space is causing the element to wrap. 

![image](https://user-images.githubusercontent.com/2741678/53804343-323f2780-3f3f-11e9-9eb1-4cccad8d89fd.png)

 Shouldn't that behaviour be reserved for the ```<pre>``` element only? Why are we overriding the default?

**To Reproduce**
1. Go to 'http://0.0.0.0:8101/vanilla-framework/examples/base/code/'
2. Inspect the white-space property of the ```<code>``` element

**Comment by sowasred2012** [comment]
@bartaz @lyubomir-popov this doesn't seem to be the case anymore, white space isn't set on code at all now: https://vanillaframework.io/docs/examples/base/code-inline

Loosely related: I have set `white-space: pre-wrap` on the new code snippet, but only when using numbered lines (https://github.com/canonical-web-and-design/vanilla-framework/blob/master/scss/_base_code.scss#L88). However, I still think it should be the default on `pre`, scrolling vertically down the page and then horizontally within a given component presents accessibility issues: https://www.w3.org/WAI/WCAG21/Understanding/reflow
