### ISSUE TITLE
"Code snippet" copy button lacks UI feedback

### ISSUE THREAD

**Issue by clagom** [canonical-web-and-design/vanilla-framework#2213]
**Describe the bug**
The code snippet CLI code element has a copy-code button that doesn't have active or pressed state.
The code snippet HTML code has the same button, but that has UI feedback when pressed.

**To Reproduce**
Go to https://docs.vanillaframework.io/en/patterns/code-snippet click on the first copy button

**Expected behavior**
Same as the second example in the page https://docs.vanillaframework.io/en/patterns/code-snippet

**Screenshots**
Not working:
<img width="874" alt="Screenshot 2019-03-12 at 17 25 57" src="https://user-images.githubusercontent.com/1953388/54221866-31346a00-44ec-11e9-94dc-36858ccb8a38.png">

Working:
<img width="870" alt="Screenshot 2019-03-12 at 17 26 00" src="https://user-images.githubusercontent.com/1953388/54221871-3396c400-44ec-11e9-9e71-648396df7bbb.png">

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome

**Smartphone (please complete the following information):**
 - Version: Version 72.0.3626.119 (Official Build) (64-bit)

**Comment by kwm14** [comment]
Thanks for reporting @clagom I've added it as a work item [here](https://github.com/ubuntudesign/design-vanilla-framework/issues/348), whilst updating docs content I'll look at the example to 👍

**Comment by deadlight** [comment]
@clagom the latest build not uses the same styling for both buttons. There is a small styling bug for the outline, which I have captured in this issue: #2319

I think we can consider this bug fixed.
