### ISSUE TITLE
Embedded docs repo should build using tip of current branch, rather than the latest released version of Vanilla

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#2237]
**Describe the bug**
The docs repo builds its css using a version of vanilla specified in its package.json file. 
Currently, this is around six months old, and doesn't reflect numerous changes we've introduced. 

**Expected behavior**
The ideal behaviour would be to use the scss as it is at that moment in time in the ../scss folder, so documentation, documentation styling and actual framework are in sync.

**Comment by lyubomir-popov** [comment]
@nottrobin this is the docs issue ^

**Comment by nottrobin** [comment]
:+1: thanks for bringing this up and filing the issue @lyubomir-popov

**Comment by kwm14** [comment]
## WG
- @anthonydillon vs @nottrobin

**Comment by deadlight** [comment]
This change has been made
