### ISSUE TITLE
Interactions with acronyms on websites issue

### ISSUE THREAD

**Issue by lilyvidenova** [canonical-web-and-design/vanilla-framework#2280]
## Pattern to amend

Acronyms on websites

## Visual

The problem is the interaction, not the visual per say - it takes a very long time for the text of the acronym to be displayed, many people see this as a bug and is frustrating.

## Context

I do not have a solution, but I believe this pattern should be improved. Here's [Martin's comment](https://github.com/CanonicalLtd/MAAS-design/issues/792#issuecomment-470553743) on this issue when raised for maas.io

**Comment by deadlight** [comment]
@lilyvidenova to confirm, are interactions you're seeing are on the abbreviation HTML element like in this [example](https://codepen.io/deadlight/pen/qwPQGz)?

If I'm following correctly then we're talking about the default browser behavior. We've not overridden this behavior or style so far so this request would constitute a new pattern. That's fine but we'd need to scope it out for inclusion.

My suggestion would be just to replicate the way that tooltips work but we then have the double-popup problem on desktop (the example that @cassiocassio linked to has this problem: https://codepen.io/ire/pen/bOwdRM?editors=1100).

The only other option to suppress the browser-default abbr behaviour is to use JavaScript, which would be a bit over-engineered for such a simple element.

Let's get others' thoughts on this in the working group.

**Comment by lilyvidenova** [comment]
@deadlight Yep, that's the one I mean. I wasn't sure if it was going to be new or not - sorry!!

**Comment by kwm14** [comment]
## WG
- @deadlight to create a demo we could propose to Vanilla
- @deadlight investigate current browsers

**Comment by bartaz** [comment]
Closing at the moment. Please reopen if there is a need to fix this.

@lyubomir-popov Link to the issue as discussed on triaging with Martin
