### ISSUE TITLE
Medium screen issue with divider pattern

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/vanilla-framework#2287]
When using the divider pattern at breakpoint `768px` there is a border left and on top.

**To Reproduce**
1. Go to https://canonical-web-and-design.github.io/vanilla-framework/examples/patterns/divider/
2. Shrink the browser to `768px`
3. See error

**Expected behavior**
Either hold off showing the top border for 1px or make the pattern stack earlier.

**Screenshots**
![Screenshot_2019-04-24 Divider Vanilla framework - Examples](https://user-images.githubusercontent.com/1413534/56645247-3cdf8880-6675-11e9-8c08-281b50c71dc9.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Firefox
 - Version: 66

**Additional context**
Used on muiltipass.run.

**Comment by lyubomir-popov** [comment]
This has been fixed in the cssgrid branch.

**Comment by lyubomir-popov** [comment]
Closing as this branch is now merged.
