### ISSUE TITLE
Responsive header, mobile view, search bar

### ISSUE THREAD

**Issue by clagom** [canonical-web-and-design/vanilla-framework#2291]
This proposal is especially for brochure websites, with centered header navigation, but can be applied generally across website and web applications for a more flexible responsive behavior. Currently, the length of the search bar combined with the number of items creates a very wide breaking point for the mobile responsive menu to appear.

**_E.g. in JAAS.ai:_**

## Normal view
<img width="1203" alt="Screenshot 2019-04-26 at 14 02 34" src="https://user-images.githubusercontent.com/1953388/56809550-04ce7600-682c-11e9-9691-584a0558b9fb.png">

The mobile menu appears already at 1030px, hiding both the menu and the search bar

<img width="1029" alt="Screenshot 2019-04-26 at 14 02 52" src="https://user-images.githubusercontent.com/1953388/56809613-2f203380-682c-11e9-91a4-ca666258ec4a.png">

This results in a lot of wasted space, disappearing both the main navigation and the search bar into a collapsed menu for a width that should still be optimized to allow the desktop navigation.

## Proposed solution
![IMG_6659](https://user-images.githubusercontent.com/1953388/56821607-b8dcfa80-6846-11e9-8d64-aac61d577b30.jpg)

I would propose a responsive search bar, implementing a collapsed version with just the search icon when the width hits the breaking point, instead of making the navigation disappear, recovering much space for it.

Clicking on the icon we could expand the search bar, allowing for a type entry. Clicking out of the search bard would collapse it again. On further breaking point of the width, the whole thing would get into the mobile "menu".

On a side note, I think the current default search bar is very wide.

**Comment by kwm14** [comment]
## WG
- Agreed to reduce the width of the search box 
- +1 @clagom proposed solution
- @spencerbygraves to explore the design style
- Agreed to add as a modifier to our current search component

**Comment by spencerbygraves** [comment]
@clagom here are some designs for review, let me know what you think.

### Dark version

![image](https://user-images.githubusercontent.com/9105999/58311601-41789780-7e01-11e9-97ce-cc1a4023bc56.png)

### Light version (for Vanilla, not JAAS)

![image](https://user-images.githubusercontent.com/9105999/58311632-50f7e080-7e01-11e9-9d73-17fcab7d4c57.png)

**Comment by clagom** [comment]
That's great @spencerbygraves thank you 👍

**Comment by bartaz** [comment]
We need to clarify with UX the exact behaviour (when the search turns into a collapsed state).

**Comment by clagom** [comment]
I think this proposal has then been somehow addressed by the work that @anasereijo and @cassiocassio did on the navigation, log-in, search pattern. Still, the specs you are mentioning might still be necessary.

**Comment by clagom** [comment]
@bartaz @sowasred2012 for this issue could you please have a look at the current implementation on ubuntu.com, would this be enough to bring it in Vanilla?

**Comment by clagom** [comment]
Continuing here: #3635
