### ISSUE TITLE
Docs examples rendered using wrong template

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#2297]
**Describe the bug**
After the changes to docs, I'm having trouble adding / making changes to existing examples. The ones I've touched get rendered with the top-level docs template, and include google tag manager, top nav, etc.:

<img width="1680" alt="Screenshot 2019-05-07 at 13 26 25" src="https://user-images.githubusercontent.com/2741678/57299178-d2dece80-70cb-11e9-85c3-67638f871784.png">

**To Reproduce**
1. Check out branch cssgrid
2. ./run
3. Visit http://0.0.0.0:8101/examples/patterns/grid/nested-medium/

**Expected behavior**
Examples looking like this: http://0.0.0.0:8101/examples/patterns/grid/default/
(No added chrome, working markup)

**Comment by nottrobin** [comment]
I don't see a "nexted-medium.html" in https://github.com/canonical-web-and-design/vanilla-framework/tree/develop/docs/examples/patterns/grid

**Comment by lyubomir-popov** [comment]
Changing the layout from "default" to examples" fixed it. Thanks.
