### ISSUE TITLE
Spacing between paragraphs is lost in accordion

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#2301]
Default spacing between paragraphs is lost in accordion.

### To reproduce

Have an accordion with multiple paragraphs of text one after another (example: https://jsfiddle.net/bartaz/9gv4s75r/2/)

### Current

There is no spacing between paragraphs:

<img width="637" alt="Screenshot 2019-05-09 at 15 35 15" src="https://user-images.githubusercontent.com/83575/57457587-183c0100-7270-11e9-9511-ddbe5dfad94a.png">

### Expected

Unless it is expected choice to remove spacing of paragraphs in accordion it would be nice to keep default vanilla spacing for text in accordion:

<img width="637" alt="Screenshot 2019-05-09 at 15 35 28" src="https://user-images.githubusercontent.com/83575/57457639-31dd4880-7270-11e9-9248-8744fd803e8b.png">

**Comment by kwm14** [comment]
@bartaz thanks for raising this issue 👍 with the new vertical rhythm and spacing this is now fixed and will be released with v2.0.0 😄 

### Updated v2.0.0 accordion
<img width="699" alt="Screenshot 2019-05-16 at 15 24 05" src="https://user-images.githubusercontent.com/17748020/57861528-aa9f5000-77ee-11e9-9298-c63a9a7e4485.png">
