### ISSUE TITLE
Prototype secondary navigation

### ISSUE THREAD

**Issue by kwm14** [canonical-web-and-design/vanilla-framework#2302]
## Todo
- Build a demo prototype 
- With `h5` selected link version too 🔗 
- Design discussion can be found [here](https://github.com/canonical-web-and-design/design-vanilla-framework/issues/402)
- Design review meeting notes can be found [here](https://github.com/canonical-web-and-design/meeting-notes/issues/392)

### Visual
![canonical com x vanilla secondary v4](https://user-images.githubusercontent.com/17748020/57451555-8b864880-7259-11e9-9ff1-e0c512c078c8.png)

**Comment by bartaz** [comment]
Seems related (or duplicate) of canonical-web-and-design/design-vanilla-framework#371

**Comment by deadlight** [comment]
@bartaz yeah, this is the development build task for canonical-web-and-design/design-vanilla-framework#371

**Comment by elioqoshi** [comment]
Related to #814
