### ISSUE TITLE
Create NPM package to draw d3 charts.

### ISSUE THREAD

**Issue by inuwa** [canonical-web-and-design/vanilla-framework#2305]
## Summary
Create an NPM package for d3 charts and graphs used by Canonical Web team. The idea is to create an npm package that can used like a plugin to draw generic charts on webpages. Once the data for the charts has been fed in, it spits out the relevant charts.

**Comment by kwm14** [comment]
## d3 charts
We're currently building different types of charts across sites and applications:

Snapcraft - Metrics
MAAS - Dashboard
Ubuntu - Statistics
Juju - Status

**Comment by kwm14** [comment]
## Chit chat
Catching up with @Lukewh he has started a Vanilla d3 graph document, collating information to create a spec around the development of them.

https://docs.google.com/document/d/15sofprfkPEUdMB3SuJWHRB-6p_sjv9RIIZH1TRu3onk/edit#
