### ISSUE TITLE
Code copyable button focus state

### ISSUE THREAD

**Issue by deadlight** [canonical-web-and-design/vanilla-framework#2319]
**Describe the bug**
The focus state of the code copyable component only applies an outline to the left-hand of the button.

**To Reproduce**
1. Pull the latest version of the master branch
2. `./run`
3. http://0.0.0.0:8101/base/code/
4. Click on the button in the "Copyable" example
5. See the blue outline is only on the left of the button

**Expected behavior**
A blue outline around the whole button

**Screenshots**
![image](https://user-images.githubusercontent.com/118614/58083206-77730d00-7bb0-11e9-98f7-65b633dbad5f.png)

**Desktop:**
 - OS: Ubuntu
 - Browser Firefox

**Comment by Caleb-Ellis** [comment]
This appears to be fixed:
![screenshot_7](https://user-images.githubusercontent.com/25733845/66999465-5c141b80-f0d6-11e9-978c-5d8b376a5d2c.png)
