### ISSUE TITLE
Tooltips should stay active on hover

### ISSUE THREAD

**Issue by deadlight** [canonical-web-and-design/vanilla-framework#2325]

**Comment by deadlight** [comment]
This is proving difficult but it turns out that it might not be the best solution anyway.
I will speak to @cassiocassio and try and come up with a set of requirements.

**Comment by Caleb-Ellis** [comment]
@deadlight @kwm14 one way this might work is if there's an invisible pseudo-element that overlaps both the thing being hovered over and the tooltip text, though it might be tricky with how tooltips currently build the little triangle.

**Comment by Caleb-Ellis** [comment]
## WG meeting:
- @Caleb-Ellis to create an issue based on this PR proposal (I'm just using this issue instead)
- Proposal agreed 👍 
- Make sure it works for all directions of tooltip
- Keep the markup the same
- Investigate ways of getting around focus issues
- @kwm14 to triage in WG validated pipeline and add priority once the issue has been created

**Comment by sowasred2012** [comment]
Just spotted this on [Twitter](https://twitter.com/brad_frost/status/1139116974234046465), might be useful? Feels like they're solving a similar problem: https://slides.com/wireframe?debug=2#menu
