### ISSUE TITLE
Prioritise list of components

### ISSUE THREAD

**Issue by kwm14** [canonical-web-and-design/vanilla-framework#2333]
Document a list of components we think should have a dark theme available.

**Comment by lyubomir-popov** [comment]
We agreed not to pick up the theming work in 20.04, maybe we should close this @spencerbygraves ?

**Comment by spencerbygraves** [comment]
@lyubomir-popov Sure. I can't see "Dark theme" in the Backlog, I'll add a line so we don't forget.
