### ISSUE TITLE
Prototype subset of components

### ISSUE THREAD

**Issue by kwm14** [canonical-web-and-design/vanilla-framework#2334]

**Comment by lyubomir-popov** [comment]
My original idea was to keep a config file that asigns each component a default theme, and build using that theme, per component. The core challenge with this is that unlike less, scss [lacks dynamic imports](https://github.com/sass/sass/issues/739). The scss maintainers are planning to address that with a new modules system, but that seems to be going [nowhere fast](https://github.com/sass/sass/blob/master/accepted/module-system.md). This means we need to either:
- wrap imports in conditionals, which is not ideal
- import all themes, then manually specify which gets applied to which component.
- there might be other options, I'm still exploring this.
