### ISSUE TITLE
Media object image should fill it's container

### ISSUE THREAD

**Issue by kwm14** [canonical-web-and-design/vanilla-framework#2341]
**Describe the bug**
When using an image that's height is bigger than the width it squashes the media object image to accommodate the biggest value. Notice that the image is squashed.

To fix I had to upload an image with the same height and width value.

**Expected behavior**
Any image no matter height or width should fill the container.

**Screenshots**
<img width="1440" alt="Screenshot 2019-05-23 at 14 01 40" src="https://user-images.githubusercontent.com/17748020/58256767-805a0f00-7d67-11e9-8902-745f6450da4d.png">

**Comment by deadlight** [comment]
@kwm14 

This only applies to the circular variant - and there is a requirement for the initial image to be square in that case (there's no way to apply a circle over a rectangle without weird cropping).

I'll update the docs to note the square image requirement
