### ISSUE TITLE
Examples for "heading icon" missing

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/vanilla-framework#2349]
This fails differently in local development:

![image](https://user-images.githubusercontent.com/519935/58541843-491ab080-81f4-11e9-96d8-2a45883d048f.png)

than it does in production:

![image](https://user-images.githubusercontent.com/519935/58541869-58016300-81f4-11e9-88c6-b882ec05940f.png)

but both are broken for the same reason - the examples files aren't where they should be.

**Comment by deadlight** [comment]
The docs need updating. I'll fix that.
