### ISSUE TITLE
Clipboard icon cuts off the end

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/vanilla-framework#2364]
## Pattern to amend
Code snippet

## Visual
![Screenshot_2019-05-31 Code snippet Vanilla framework](https://user-images.githubusercontent.com/1413534/58708266-33051f80-83af-11e9-8af3-00f38d9f2d10.png)

## Context
When the value is longer then the space available and you highlight the text you can not see the end of the highlighted text.

I fixed this by adding 2.5rem padding-right to the input.

**Comment by Caleb-Ellis** [comment]
Looks like this has been fixed:
![screenshot_8](https://user-images.githubusercontent.com/25733845/66999591-9aa9d600-f0d6-11e9-8054-6b9268225f25.png)
