### ISSUE TITLE
Font file optimisation

### ISSUE THREAD

**Issue by barrymcgee** [canonical-web-and-design/vanilla-framework#2368]
Including Vanilla base includes these four separate font files on all sites:

<img width="926" alt="Screenshot 2019-06-03 at 12 29 55" src="https://user-images.githubusercontent.com/505570/58805473-08fc6900-860c-11e9-80bf-1f4d1f6c13b0.png">

Can these files be combined into a single font file that may then benefit from Gzipping and Woff2 compression?

**Comment by kwm14** [comment]
## WG meeting
- @barrymcgee which site did you test this on?
- Investigate into font-display and see what affect it has
- @deadlight to catch up and sync on next steps

**Comment by bartaz** [comment]
Partially closed by the use of `$font-use-subset-latin` variable
