### ISSUE TITLE
p-notification: support for multiple elements inside notifications

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/vanilla-framework#2382]
This came up through https://github.com/canonical-websites/docs.snapcraft.io/issues/130.

Currently the [notification pattern](https://docs.vanillaframework.io/en/patterns/notification) only officially appears to support one paragraph of text.

``` html
<div class="p-notification" id="notification">
  <p class="p-notification__response">A paragraph!</p>
</div>
```

It can be hacked to do more, but to get this to work properly with the variants with icons (e.g. `--caution`) needs `u-no-padding--top` and `u-no-margin--bottom`, which is a shame:

``` html
<div class="p-notification--caution" id="notification">
  <div class="p-notification__response">
    <p class="u-no-padding--top">A paragraph!</p>
    <p class="u-no-margin--bottom">Another paragraph!</p>
  </div>
</div>
```

**Comment by lyubomir-popov** [comment]
I think the notifications pattern is due a desin update. Apart from the issues mentioned here, other problems have been mentioned repeatedly: 
• We use it as a notification block, as in maas:
![image](https://user-images.githubusercontent.com/2741678/59422940-0f879f00-8dc9-11e9-8712-6768f9d39092.png)
In that scenario, the spacing above any but the first item should not include the 3px width added for the coloured strip. You can see how DHCP has more space above than underneath it for example.
• @cassiocassio has mentioned dismissing could be handled better with an icon than a dismiss link whose position varies depending on the preceding content.

**Comment by bartaz** [comment]
This is going to be covered by new notifications. We are not going to look into that before it happens.

**Comment by nottrobin** [comment]
@bartaz should this be closed? Can it be simply assumed that the new notifications probably won't have this problem?

**Comment by clagom** [comment]
@nottrobin yes this can be closed as the new coming notification pattern covers this issue, thanks.
