### ISSUE TITLE
[Docs] Remove p-icon--chevron from the icon list

### ISSUE THREAD

**Issue by kwm14** [canonical-web-and-design/vanilla-framework#2385]
## Bug
- Remove `p-icon--chevron` from the icon list. Currently, it's an empty state as it's been updated to be used as `p-icon--contextual-menu`
- Remove both use-cases under [standard](https://docs.vanillaframework.io/patterns/icons/#standard) and [standard dark](https://docs.vanillaframework.io/patterns/icons/#standard-dark)

### Screenshot
<img width="674" alt="Screenshot 2019-06-14 at 10 25 10" src="https://user-images.githubusercontent.com/17748020/59499162-b4b87b00-8e8e-11e9-96d2-5f290f792761.png">

**Comment by lyubomir-popov** [comment]
@deadlight The chevron icon here is wrong - it should use the new chevron. Somehow we have reverted to the old icon.
Also, since many sites use the mixin, could we please add to the upgrade guide blog post?
https://docs.vanillaframework.io/patterns/icons/#standard

**Comment by deadlight** [comment]
@lyubomir-popov this bug was to remove the icon from the docs, it has been removed. This issue can be closed.

You are right, however, that the chevron icon appears to have been put back into the sass file.

It's correct that we're no longer using a graphic icon and we should just use the character, right?

**Comment by deadlight** [comment]
@lyubomir-popov oh, do you mean the contextual menu icon is the incorrect image?

I'm not clear what's meant to be the case here. Can you and @kwm14 please have a conversation and confirm which icons we should have and which icons or characters we should be using?

**Comment by lyubomir-popov** [comment]
@deadlight yes, I thought we fixed all of these. The chevron icon that should be used is in this [mixin](https://github.com/canonical-web-and-design/vanilla-framework/blame/64308b6620b00e1b506c2873d9b131261575c78c/scss/_patterns_icons.scss#L71). 

I can see the mixin is still in master, but the contextual icon is apparently not using it?

**Comment by deadlight** [comment]
@lyubomir-popov ah, right. I understand now. It regressed somehow, probably a botched rebase somewhere.

**Comment by lyubomir-popov** [comment]
@deadlight the crooked chevron icon just refuses to retire :)
