### ISSUE TITLE
.p-inline-list--middot: the last dot before a text wrap should not be displayed

### ISSUE THREAD

**Issue by solazio** [canonical-web-and-design/vanilla-framework#2388]
In this case the dot after Jun should not be vissible

![image](https://user-images.githubusercontent.com/40214246/59674486-47248b80-91bb-11e9-9664-4b453ef275a8.png)

**Comment by lyubomir-popov** [comment]
Are they always wrapped like that? 
- If so, you can use .last-item to remove the dot on the last item on the row.
- If not, there is no way to identify last-item-before-wrapping without js, which would be outside of the cope of the Vanilla framework.

**Comment by bartaz** [comment]
I don't think we can do this in CSS. There is no way for us to detect when the elements wrap.
Any way of trying to workaround this that I can think of is a hack that would cause more problems that it solves.

So, I'm afraid it's a won't fix.
