### ISSUE TITLE
Docs: retructure docs nav, add tables documentation and link to examples page

### ISSUE THREAD

**Issue by deadlight** [canonical-web-and-design/vanilla-framework#2390]
**Describe the bug**
The page https://docs.vanillaframework.io/base/data-tables/ isn't listed in the nav sidebar

Also, is "data tables" a good title over simply "tables"?

**Comment by kwm14** [comment]
@deadlight do you think we should revert back to the original contents menu in the side navigation?

- Welcome
- Base elements
- Components
- Utilities 
- Templates

**Comment by deadlight** [comment]
@kwm14 all the feedback for the current system that I've had from users has been that it's confusing. I think that parity between the file structure and nav structure is important.

**Comment by lyubomir-popov** [comment]
Can we add somewhere a direct link to the examples?

**Comment by deadlight** [comment]
@lyubomir-popov yeah, I don't see why not. The examples page inclusion on live was just an accidental side-effect of the restructure. We should expose it on the nav as "all pattern examples" or something similar.

**Comment by deadlight** [comment]
I've renamed this issue to cover everything raised in the discussion
