### ISSUE TITLE
Padding between checkboxes is too big

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/vanilla-framework#2392]
Can we reduce the padding between [checkboxes](https://docs.vanillaframework.io/base/forms/#checkbox)?

On the image below you can see how it looks like when we remove the extra code and it's just the vanilla pattern (Robotics and Tutorials): it makes the form much deeper.

![image (2)](https://user-images.githubusercontent.com/36884067/60005355-3c0fa680-9666-11e9-9462-14e1bd2834fe.png)

**Comment by deadlight** [comment]
I believe a solution was already being investigated for this bug. @lyubomir-popov? @anthonydillon?

**Comment by anthonydillon** [comment]
@deadlight I am not aware of any solution.

**Comment by kwm14** [comment]
## WG
- Agreed there is a problem with spacing between checkboxes
- @lyubomir-popov to create a demo example of the use cases:

**Ubuntu sign-up**
- As seen above in @anasereijo example

**Snapcraft**
![image](https://user-images.githubusercontent.com/17748020/62474745-7d35c300-b79b-11e9-92a8-9b47f1cd5caf.png)

**MAAS**
- Modal (pic to be provided)

**Comment by lyubomir-popov** [comment]
After some investigation, it seems the main issue here is incorrect markup:
before: 
```        <label>
          <input class="mktoLogicalField mktoCheckboxList mktoHasWidth" type="checkbox" id="insightscloudserver"
            name="insightscloudserver" value="Cloud and server">
          <label for="insightscloudserver">Cloud and Server</label>
        </label>
```
the outer wrapping label is unnecessary. with it, you get too much spacing:

![image](https://user-images.githubusercontent.com/2741678/62530788-1830aa80-b839-11e9-892d-85613e9c7c72.png)


Correcting the markup to what vanilla recommends, and removing all the hacks (unnecessary .u-no-margin--top and .u-clearfix) , the spacing looks ok to me:

after:
![image](https://user-images.githubusercontent.com/2741678/62530832-28488a00-b839-11e9-80e9-28cfdba84142.png)

**Comment by lyubomir-popov** [comment]
if for some reason the label wrapper is unavoidable due to marketo or something, then removing its margin and padding would also solve this.

**Comment by lyubomir-popov** [comment]
I've checked with @spencerbygraves and the second screenshot shows the correct spacing we want. 

So the recommendation would be to:
- remove the hacks currently in place (u-no-margin--top and u-clearfix)
- and then either update the markup, or if that's not possible, use utilities to remove the superfluous spacing that comes from wrapping in the outer labels. 

@deadlight If this sounds reasonable can we close the issue?

**Comment by kwm14** [comment]
@lyubomir-popov nice investigation 😉 

I agree with @spencerbygraves that the second screenshot spacing is ideal 💯 

I believe @sowasred2012 is planned to upgrade [ubuntu.com](https://ubuntu.com/) this iteration, so if we can make him aware of changes to make more than happy to close this issue 👍

**Comment by kwm14** [comment]
Linked fix to an [issue](https://github.com/canonical-web-and-design/ubuntu.com/issues/5650) under Vanilla 2.0 upgrade for ubuntu.com 👍

**Comment by lyubomir-popov** [comment]
@sowasred2012 there's a stale [branch](https://github.com/canonical-web-and-design/ubuntu.com/tree/vf2.0) where I did a lot of the upgrade work, might come in handy if it can be rebased.
