### ISSUE TITLE
Blog: Build new layout

### ISSUE THREAD

**Issue by kwm14** [canonical-web-and-design/vanilla-framework#2397]
## Design
Design discussion can be found [here](https://github.com/canonical-web-and-design/design-vanillaframework.io/issues/14).

### Blog layout
![002-blog-posts](https://user-images.githubusercontent.com/17748020/60113474-becd5a00-9769-11e9-8b98-3573752a9f9d.png)

**Comment by deadlight** [comment]
Made basic template but we need to wait here for the infrastructure changes.

[Branch](https://github.com/deadlight/vanillaframework.io-1/tree/blog-template)

![image.png](https://images.zenhubusercontent.com/5931737051aa2c3057804027/4b913237-568b-4b35-83dc-22c329ae23f2)
