### ISSUE TITLE
Code snippet copy button scrolls with content

### ISSUE THREAD

**Issue by hughesjordan** [canonical-web-and-design/vanilla-framework#2398]
**Describe the bug**
The copy button within a code block scrolls with the content.

**To Reproduce**
1. Go to https://docs.vanillaframework.io/base/code/
2. Scroll down to a code block with a lot of content or reduce width of browser
3. Scroll within the code block
4. See copy button scroll with content

**Expected behavior**
Would expect the copy button to remain fixed to the top right of the code block despite scrolling within and position of content.

**Screenshots**
![Jun-26-2019 12-38-11 pm](https://user-images.githubusercontent.com/17141586/60177434-ce53ae00-9810-11e9-877b-708314bda711.gif)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version: 75.0.3770.100 (Official Build) (64-bit)

**Comment by lyubomir-popov** [comment]
Doesn't happen on the docs page in the issue. Has anyone seen this elsewhere? The example seems to be from https://conjure-up.io/, but I can't find it there either.

**Comment by kwm14** [comment]
@lyubomir-popov I can't replicate or find a similar issue so must have been fixed somewhere...

**Comment by lyubomir-popov** [comment]
Since we don't officially have a text area copyable (although there is a [request](https://github.com/canonical-web-and-design/vanilla-framework/issues/2453)) I suggest closing this.

**Comment by kwm14** [comment]
@lyubomir-popov agreed.
