### ISSUE TITLE
Fix padding in component example.js 

### ISSUE THREAD

**Issue by kwm14** [canonical-web-and-design/vanilla-framework#2399]
**Describe the bug**
Fix padding in component example.js.

Do we need to update the [example.js](https://github.com/canonical-web-and-design/example-js) repo to 2.0 or now that Vanilla docs live under the [vanilla-framework](https://github.com/canonical-web-and-design/vanilla-framework) repo, can we just fix it there?

Thoughts? @deadlight @anthonydillon @nottrobin 

**To Reproduce**
1. Go to any component example
2. Click on https://docs.vanillaframework.io/base/code/
3. See how each example has extra padding at the bottom

**Expected behavior**
Less padding #winning

**Screenshots**
![Screenshot 2019-06-26 at 16 33 14](https://user-images.githubusercontent.com/17748020/60193868-48475f80-9830-11e9-8bbd-98a50c11d7e5.png)

**Comment by deadlight** [comment]
This is caused by new lines inside the <code> tag, not padding. We need to stop these lines being generated.

**Comment by nottrobin** [comment]
@deadlight well volunteered :heart:

**Comment by bartaz** [comment]
We use CodePen now, so this issue no longer applies.
