### ISSUE TITLE
Dark variant of the p-divider pattern

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/vanilla-framework#2401]
## Pattern to amend
p-divider

## Visual
Now:
![Screenshot_2019-07-01 Jujucharms Juju](https://user-images.githubusercontent.com/1413534/60467335-44f80d80-9c4e-11e9-90ed-856a57b404eb.png)

Desire:
![Screenshot_2019-07-01 Zeplin - Project](https://user-images.githubusercontent.com/1413534/60467296-2d208980-9c4e-11e9-8ccb-7a8b25d54f18.png)

## Context
It would be nice if the divider pattern could respond to being inside a `is-dark` strip by adjusting the colour of the border.

**Comment by deadlight** [comment]
@anthonydillon seems like a reasonable request. I assume that your images are the wrong way around, right?

**Comment by anthonydillon** [comment]
No then its dark the grey should be lighter.

**Comment by deadlight** [comment]
@anthonydillon the one under "desire" has darker lines and the one under "now" has lighter lines (which look better). Anyway, the lines should be light on darker backgrounds :+1:

**Comment by spencerbygraves** [comment]
@anthonydillon @deadlight I chose `$color-mid-dark` rather than `$color-mid-light` for a dark background.

**Comment by lyubomir-popov** [comment]
Solving this with themeing would allow it to be in sync with other colors like hr color.
