### ISSUE TITLE
Social icon foreground and background colours can't be overridden

### ISSUE THREAD

**Issue by deadlight** [canonical-web-and-design/vanilla-framework#2402]
It is not possible to easily override the colours of the social media icons.

The icons should be configurable by setting the variables $color-social-icon and $color-social-icon-background

@solazio has the requirement to update the social icon colours

**Comment by spencerbygraves** [comment]
@anthonydillon recently changed the social icons for the Jaas footer - https://github.com/canonical-web-and-design/jaas.ai/pull/337

**Comment by deadlight** [comment]
Thanks @spencerbygraves this is exactly what I'm doing. I'm going to go one step further and make the variables overridable generically so minimal custom sass is needed to change the colours.
