### ISSUE TITLE
Table pattern not in docs

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/vanilla-framework#2406]
**Describe the bug**
I can not find docs on tables in the docs. I searched for table and it didn't find anything.

**To Reproduce**
1. Go to https://docs.vanillaframework.io/
2. Search for "table" 
3. See there are no results

**Expected behavior**
Tables are a big enough pattern with variants that it should be a top level page.

**Comment by kwm14** [comment]
@anthonydillon this was [discovered](https://github.com/canonical-web-and-design/vanilla-framework/issues/2390) by @deadlight the last iteration here and fixed up in small tasks [here](https://github.com/canonical-web-and-design/vanilla-framework/pull/2396). It will be visible again once we push out 2.1.0 today 👍

**Comment by anthonydillon** [comment]
We are still missing the Table pattern navigation from the navigation update: https://github.com/canonical-web-and-design/vanilla-framework/pull/2396/files

**Comment by kwm14** [comment]
Seems to be fine now since I've deployed https://docs.vanillaframework.io/base/tables/ 👍 💯
