### ISSUE TITLE
Docs pages are unprintable

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/vanilla-framework#2409]
1\. Go to any non-trivial Docs article, for example, [Buttons](https://docs.vanillaframework.io/patterns/buttons/).
2\. Try to print the article, or view the print preview.

What happens:

- The first page prints.
- The second page is blank.
- Any subsequent pages do not print at all.

![vanilla-docs-print-1](https://user-images.githubusercontent.com/19801137/61215967-29880a80-a704-11e9-9963-fca349eb9777.png) ![vanilla-docs-print-2](https://user-images.githubusercontent.com/19801137/61216075-6f44d300-a704-11e9-954f-a58ec151994d.png)

What should happen:
- The whole article prints.

**Comment by bartaz** [comment]
With the new docs layout it doesn't seem to be an issue anymore.
