### ISSUE TITLE
Printed code block has Copy button and missing lines

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/vanilla-framework#2410]
1\. Go to any page that uses `<div class="p-code-copyable">` or `<pre class="code-example">`.
2\. Print the page.

What happens:
- The code has a Copy button, which doesn’t do anything when you tap it.
- If the code is longer than 14 lines, the last lines are missing.

![vanilla-code-print](https://user-images.githubusercontent.com/19801137/61218573-4293ba00-a70a-11e9-84ba-a63252e1b5b8.png)

What should happen: when printed,
- Copy buttons should be hidden
- code blocks should be just tall enough to show the complete code.

**Comment by sowasred2012** [comment]
Closing, the new [code snippet](https://vanillaframework.io/docs/examples/patterns/code-snippet/code-snippet) pattern has no such height limits, and the code copyable pattern has been both deprecated and updated to look like the code snippet, with the button being actively hidden.
