### ISSUE TITLE
Pagination buttons are misaligned when no second line of text

### ISSUE THREAD

**Issue by lilyvidenova** [canonical-web-and-design/vanilla-framework#2418]
**Describe the bug**
When the pagination buttons do not have the second line of text and just display Previous/Next, the text and caret icon are misaligned.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://docs.snapcraft.io/search?q=snap
2. Scroll down to the end of results
3. See misaligned Next button
4. Click on misaligned Next button
5. See misaligned Previous button

**Expected behavior**
The text and icon to be aligned.

**Screenshots**
<img width="1680" alt="Screenshot 2019-07-23 at 14 57 53" src="https://user-images.githubusercontent.com/17980375/61726662-e95f0280-ad69-11e9-8c60-9f2b395f7f26.png">

**Desktop (please complete the following information):**
 - OS: OSX Mojave (but also Ubuntu)
 - Browser Safari and Chrome

**Additional context**

**Comment by lyubomir-popov** [comment]
This is not how the article pagination is intended to be used, we have an [example](https://vanillaframework.io/docs/examples/patterns/pagination/pagination-verbose) for previ/next buttons only. We recommend using that instead:

![image](https://user-images.githubusercontent.com/2741678/96130388-c4ffc080-0eef-11eb-930a-4834364b9cf0.png)
