### ISSUE TITLE
Copy icon blocks text on scroll

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/vanilla-framework#2419]
https://docs.vanillaframework.io/patterns/buttons/

![Screen Shot 2019-07-23 at 12 00 05 PM](https://user-images.githubusercontent.com/532033/61735592-848fb200-ad41-11e9-80d5-114af42846cf.png)

Scroll right on one of the examples and the copy icon stays with the text it covered.

**Comment by bartaz** [comment]
We don't have these code blocks examples, and we soon will not have copy buttons for code. Not relevant anymore.
