### ISSUE TITLE
p-stepped-list number becomes an oval if the title wraps

### ISSUE THREAD

**Issue by Lukewh** [canonical-web-and-design/vanilla-framework#2424]
**Describe the bug**
If you have a `p-stepped-list` in, let's say, a `col-8` with text that wraps, the number to the left becomes an oval - see (2) below:

![Screenshot_2019-07-26 Snapcraft - Snaps are universal Linux packages](https://user-images.githubusercontent.com/479384/61950144-e8fe7b80-afa4-11e9-92bd-6b51b1212146.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Firefox
 - Version: 68

**Comment by kwm14** [comment]
Good catch @Lukewh sure we don't want to have rugby ball styling... 😆 

We have a [Validated WG proposal](https://github.com/canonical-web-and-design/vanilla-framework/issues/1973) from @therealjuan to remove the background. Which will solve this issue 👍
