### ISSUE TITLE
p-pull-quote & p-pull-quote--large shows quotes in the wrong position

### ISSUE THREAD

**Issue by solazio** [canonical-web-and-design/vanilla-framework#2426]
**Describe the bug**
- When using `p-pull-quote` & `p-pull-quote--large` the quotes are not displayed in the correct location. 
- Using `p-pull-quote--small` works as expected.

(see below)

**Screenshots**
![image](https://user-images.githubusercontent.com/40214246/62120777-2a9b6900-b2ba-11e9-9d38-bf59df6690ee.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.04
 - Browser Chromium & Firefox
 - Version 75.0.3770.142 & 68.0.1

**Comment by sowasred2012** [comment]
If it helps any, the workaround I've used on u.c is [here](https://github.com/canonical-web-and-design/ubuntu.com/blob/vanilla-2-update/static/sass/styles.scss#L272).

**Comment by bartaz** [comment]
I can confirm this is still happening.

The styles of pull quote assume the existence of single line `<cite>` inside the pull quote.
If the cite is not there or if it wraps to more than one line the end quote starts to be mispositioned:

![Screenshot 2020-09-07 at 13.39.58.png](https://images.zenhubusercontent.com/593a660851aa2c30578102bb/c7da4fd1-4fc5-4232-afdf-12c03169dca2)

The position of the quotes should be relative to the quote text, independent from existence or size of cite element.
