### ISSUE TITLE
Docs search doesn’t work at all

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/vanilla-framework#2437]
1\. Go to any [docs.vanillaframework.io](https://docs.vanillaframework.io/) page.
2\. Enter anything in the search field.
3\. Clear the search field.

What happens:
2\. There are no search results.
3\. The sidebar remains empty.

What should happen:
2\. There are search results.
3\. The list of patterns reappears.

(Firefox 68.0.1, Chromium 65.0)

**Comment by kwm14** [comment]
Thanks, @matthewpaulthomas we're aware of this issue and was fixed as of yesterday https://github.com/canonical-web-and-design/vanilla-framework/pull/2429

We're pushing out a new release today https://github.com/canonical-web-and-design/vanilla-framework/releases/tag/v2.2.0 so will be fixed 👍
