### ISSUE TITLE
Table of contents often jumps after you choose something

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/vanilla-framework#2438]
1\. Go to any page on [docs.vanillaframework.io](https://docs.vanillaframework.io/).
2\. Scroll the table of contents.
3\. Choose an item.

What happens:
- The page for the chosen item loads in the right pane.
- The left pane scrolls back to the top.

What should happen:
- The page for the chosen item loads in the right pane.
- The left pane does not move at all.

I understand why this is happening — the table of contents is reloading as part of each page. However:
- This behaviour means that the current page, despite being highlighted in the table of contents, is often off-screen by default. 
- If you are browsing through the patterns, this makes it needlessly difficult to find the next one.
- Least importantly, because the table of contents has its own scrollbar, it’s visually indistinguishable from a `<frame>` that would not jump around like this. Things that look the same should act the same.

One way to solve this might be for a script to capture the ToC scroll position when a ToC link is clicked, and set a cookie with that position. Then when the next page is loaded, a script can read the cookie and scroll to the same position.

**Comment by bartaz** [comment]
This is not relevant anymore - the docs are now using new side navigation which (at least partially) addresses this problem.
It still has some issues but those are reported separately.
