### ISSUE TITLE
Inline radio selector for choosing what appears below

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/vanilla-framework#2439]
In three cases now, I’ve wanted a control consisting of a group of text strings, where selecting one of the strings determines what appears below.

1. snapcraft.io’s “first snap flow”:

   ![2-Snapcraft-selectors](https://user-images.githubusercontent.com/19801137/62288334-0f646100-b454-11e9-9ccd-b40dfad38243.gif)

   (snapcraft.io currently doesn’t use this, because the Linux snapd setup instructions unfortunately aren’t integrated with the rest of the instructions.)

1. The download page for EKS images ([Ubuntu-design#129](https://github.com/CanonicalLtd/Ubuntu-design/issues/129)):

   ![download-cloud-eks-listing-selector](https://user-images.githubusercontent.com/19801137/62287405-ada2f780-b451-11e9-91d8-ffee05acea60.png)

3. The setup instructions for ESM:

   ![esm-datacenter-signed-in-selector](https://user-images.githubusercontent.com/19801137/62287513-ed69df00-b451-11e9-8238-7e4d90e97b6b.png)

Another future use case might be:

4. Filtering ubuntu.com search results

   > Show: **All results (108)** • ubuntu.com (37) • Ubuntu Help (10) • Ubuntu Forums (61)

One way of thinking of this pattern is that it’s just a series of links, but instead of going to a new page, each changes the remainder of the current page.

This is different from:
- Tabs (as suggested by @pmahnke) because:
  - Tabs always have a default selection, while this control in some cases would not (if that would distract you, as in the first-snap flow example, or if it would bias you in making a choice).
  - Tabs have nothing to their left or right, while this control might be inline with an introductory label (as in the EKS example).
  - It’s visually confusing for tabs to wrap to multiple lines (so Vanilla’s scroll horizontally instead), whereas for this control, wrapping would be fine because it’s just bits of text that aren’t visually connected to anything.
- Contextual menu (as suggested by @anasereijo) because:
  - A contextual menu is hidden until something is clicked, whereas this control would always be visible.
  - A contextual menu lists items vertically, whereas this control would list items inline.

These would be somewhat similar to [scope buttons in macOS](https://developer.apple.com/design/human-interface-guidelines/macos/buttons/scope-buttons/), but with a broader purpose, not just for specifying the scope of a search.

**Comment by kwm14** [comment]
## WG
- @cassiocassio to put in an RT for Discourse Forum for Vanilla
- The proposal needs further testing 
  - https://snapcraft.io/first-snap#
  - https://snapcraft.io/first-snap/python

**Comment by therealjuan** [comment]
⭐️ ⭐️ ⭐️ Here is a strawman proposal document to [start the conversation](https://docs.google.com/document/d/11K-65QyRPx0kOqn2lmpS70ewYH1AGbyp434ONVH1xlM/edit#) ⭐️ ⭐️ ⭐️ 

![popcorn time](https://media2.giphy.com/media/LvaswPm6IHn44/source.gif)

**Comment by bartaz** [comment]
This have been through WG before, but because it needs UX work we should pass it though our new process.
