### ISSUE TITLE
Custom CSS grid styles break inside Vanilla grid

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#2444]
When some custom site styles are using CSS grid to position some elements they break in Vanilla 2.0 grid.

**To Reproduce**
See this example: https://jsfiddle.net/bartaz/2a0fhqdk/

Simple CSS grid component (with element on right and left) works fine when placed in `u-fixed-width`, but breaks when put into `row`.
CSS grid allows in theory for nesting grids, but it seems that some styles from Vanilla 2.0 grid system 'leak' or in other way affect nested grid layouts.

**Expected behavior**
CSS grid layout shouldn't break inside Vanilla grid.

**Screenshots**

<img width="833" alt="Screenshot 2019-08-05 at 13 46 04" src="https://user-images.githubusercontent.com/83575/62462562-0216e180-b788-11e9-83f2-f30e23a13648.png">

**Context**

It was found during snapcraft.io migration to Vanilla 2.0. We have some elements styled with CSS grid and this issue makes it difficult to migrate them without rewriting them completely.

**Comment by lyubomir-popov** [comment]
It is this rule:
```.row *  {grid-column-end: span 12;}```

Originally added to prevent incorrect markup (.row > <something without a col class>) from being squeezed into 1 column. It was intended to make incorrect usage (of which we have many instances) more forgiving, but maybe that was a wrong call.

**Comment by bartaz** [comment]
@lyubomir-popov I tried to reset it to 'auto', but it didn't help. Maybe I did it in wrong place (or in not enough places).

**Comment by lyubomir-popov** [comment]
@bartaz maybe the media query increases specificity?
I've made a pr to address this by decreasing the scope to only direct children that don't have an explicit column class:
 
https://github.com/canonical-web-and-design/vanilla-framework/pull/2445
