### ISSUE TITLE
`u-align--center` and `u-align-text--center` aren't well documented

### ISSUE THREAD

**Issue by Lukewh** [canonical-web-and-design/vanilla-framework#2448]
https://codepen.io/Lukewh/pen/gVozVX

`u-align--center` keeps the container the same size, but aligns the text in the center.
`u-align-text--center` resizes the container and aligns it to the center.

Judging by the names I would expect `u-align--center` to have the behaviour of `u-align-text--center` and vice versa?

OS: Ubuntu
Browser: Firefox 68.0.1

**Comment by deadlight** [comment]
The usage is different:

`u-align` classes are used for a container that contains other elements whereas the `u-align-text` classes is for elements that contain no HTML elements but just text content.

I've [modified your example](https://codepen.io/deadlight/pen/VoQGJa) to illustrate

The [docs example](https://docs.vanillaframework.io/utilities/align/) gives more usage examples.

**Comment by deadlight** [comment]
I've updated the title of this bug. I'll expand the docs to explain their usage clearly.

**Comment by lyubomir-popov** [comment]
Naming is indeed confusing. 
We should also make clear that u-align--center is applied on the parent, whereas u-align-text--center is applied on the element itself. No resizing of the parent is happening.

A name change would be a breaking change, so maybe consider that for 3.0 @bartaz?
In the meantime maybe simply update the documentation page t oexplain better? Currently the text align utility is below the "fold" in the codepen, so it is practically invisible:
![Uploading image.png…]()
