### ISSUE TITLE
`u-fixed-width` should clearfix

### ISSUE THREAD

**Issue by Lukewh** [canonical-web-and-design/vanilla-framework#2451]
## Pattern to amend

u-fixed-width

## Visual

https://codepen.io/Lukewh/pen/dxJBJQ

## Context

When you only have floated content within a u-fixed-width element.

**Comment by deadlight** [comment]
This seems quite simple but I don't think that it's something we should do right now. I'm going to flag it for discussion in the working group; not for this specific bug only but for some larger topics it touches on.

Thanks for making a detailed example, it makes it much easier to understand your use-cases.

The final example where you're using the clearfix utility is the correct use here if your layout is relying on floats. I can see what problem you're trying to solve here and you probably don't have time to change you're whole layout but this is exactly what the clearing utility is for.

The grid doesn't use floats so it doesn't make sense to add clearfix to it by default any more than it would to add clearfix to other arbitrary components. 

To give some background on why I'm taking this stance: Vanilla is a system of components which purposefully has opinions on how layouts are put together and we strongly favour the most suitable tools within our browser support matrix. In this specific case, the base positioning model is the CSS-grid and the recommended way of positioning within that would be using flex, avoiding the pitfalls of floats and clearing.

I get that this is the result of a real-world problem with legacy code coming from less fully-featured versions of Vanilla where you've had to work around shortcomings. I would suggest that you Keep using the specific utilities to help with this or, if this is something that you're relying on in multiple use-cases, extend the utility to add the clearing for your local site.

I hope that you follow where I'm coming from on this.

**Comment by deadlight** [comment]
To clarify, when I say "the recommended way of positioning within that would be using flex", I mean for instances where you can't use CSS grid.

**Comment by Lukewh** [comment]
:+1: That's fine. I'm just trying to use `u-fixed-width` instead of `row > col-12` as described in the migration blog post - 1 element instead of 2.

What would break adding built-in clearfix to the `u-fixed-width` utility?
I guess `u-fixed-width` isn't always used as a "full-page-width" utility, but can be used inside rows?

**Comment by Lukewh** [comment]
Can I change my proposal to be `p-full-width`. A pattern that combines `u-fixed-width` and `u-clearfix` :upside_down_face:?

**Comment by deadlight** [comment]
I'm not sure if anything would break now but I'm just cautious about adding surprising behaviour to quite simple utils.

Go ahead and do a local implementation of it and we'll talk about where these float-type utils fit into the bigger picture.

**Comment by lyubomir-popov** [comment]
For the simple case of floating one thing left, another right, flex is easier/cleaner in my opinion. We don't have that in vanilla yet, but this is what we use in many places in maas. You apply a class to the parent, so one place instead of on the two children, and there's nothing with !important stuck to it. https://codepen.io/lyubomir-popov/pen/wVyBvz

**Comment by Lukewh** [comment]
The way I see it `u-float-*` is top of the stack, and this is something I understand. I know that if I add a `u-float-*` that thing is going to float no-matter what and if I've resorted to using a float, that's what I want.

While flex is objectively "nicer" I don't agree it's either easier or cleaner. An abstract class name + 3 lines of extra CSS vs. a specific class name + 0 extra lines is both easier and cleaner in my opinion. As floats aren't the regular way we do layout, I want it to be explicit and obvious in the markup.

[Not to mention the random behaviour you get if you need to do something [more complicated](https://codepen.io/Lukewh/pen/LwQVaz) (obviously this example would never be implemented like this).]

**Comment by lyubomir-popov** [comment]
Fair enough. Maybe we do need a single class floats row to support that usecase.

**Comment by kwm14** [comment]
## WG
- Investigate approaches for floating elements
- @lyubomir-popov to create 3 examples
  - flex floats
  - mixture of both

**Comment by bartaz** [comment]
We are not adding float clear to u-fixed-width.

Instead we added a `p-inline-list--stretch` pattern variant (that can be used to lay out elements using flexbox). If floats are needed `u-clearfix` utility is available or properly nested `.row .col-X` will clear as well.
