### ISSUE TITLE
p-code-copyable.not-cli

### ISSUE THREAD

**Issue by Lukewh** [canonical-web-and-design/vanilla-framework#2454]
## Pattern to amend

p-code-copyable

## Visual

https://codepen.io/Lukewh/pen/YmeyLB

## Context

Aside from the textarea implementation in the codepen ([see here](https://github.com/canonical-web-and-design/vanilla-framework/issues/2453)), not all copyable code is directly related to a CLI environment (config settings for a YAML file, multiline markup as in the codepen).
The `$ command` generally refers to code or a command you should input into a terminal, this amendment adds a `not-cli` to remove the prefixed `$`.

I also don't think "not-cli" is the best name, for the record.

**Comment by deadlight** [comment]
yeah, this seems like something that's needed. Although I think that we'll implement it with a --modifier.

The larger code block has line numbers by default and there's a modifier to make individual lines look like command-line inputs.

I'll make sure that these work in similar ways so that the behaviour of either of them isn't surprising.

**Comment by lyubomir-popov** [comment]
My only concern is it feels a bit awkward having the button top-left:
<div class="p-strip">
![image](https://user-images.githubusercontent.com/2741678/63846229-49f1e880-c983-11e9-9da2-d37dffd23af5.png)

@kwm14 are you ok to stretch the copy button like so:
![image](https://user-images.githubusercontent.com/2741678/63846109-08613d80-c983-11e9-926a-4da42cfdb327.png)

**Comment by kwm14** [comment]
> @kwm14 are you ok to stretch the copy button like so:
> ![image](https://user-images.githubusercontent.com/2741678/63846109-08613d80-c983-11e9-926a-4da42cfdb327.png)

Yaaaas 💯 that works for me 👍

**Comment by lyubomir-popov** [comment]
@kwm14 Thinking about this some more, the stretched version can prove problematic. What if it is 15 lines tall? The icon could end up outside the browser window:
![image](https://user-images.githubusercontent.com/2741678/63854031-153a5d00-c994-11e9-8001-12d3caf515cb.png)
Maybe a simpler indent would work better, as in  [this](url
![image](https://user-images.githubusercontent.com/2741678/63854084-3307c200-c994-11e9-8778-f29770833656.png)

This means the button isalways top right, and it doesn't take up horizontal space that can be used to see more of the code inside.
)

**Comment by kwm14** [comment]
> @kwm14 Thinking about this some more, the stretched version can prove problematic. What if it is 15 lines tall? The icon could end up outside the browser window:
> ![image](https://user-images.githubusercontent.com/2741678/63854031-153a5d00-c994-11e9-8001-12d3caf515cb.png)

Ah yes, it doesn't look too great does it...

> So with our icon that would be:
> 
> ![image](https://user-images.githubusercontent.com/2741678/63854128-53d01780-c994-11e9-9676-a0dc5bc5d4b6.png)

This works for me and solves the issue 👍

**Comment by lyubomir-popov** [comment]
Moving out of the upgrade issues epic as this is an enhancment.

**Comment by lyubomir-popov** [comment]
@clagom what do we do with this in light of the request to remove the border and copy button?

**Comment by clagom** [comment]
@lyubomir-popov
I think ideally for now we would need to consider flexible options, e.g.: one just plain text without icons and border; one with just border and no icon; one with icons and border. I think a subtle background could be better than the border, for the discussions we had around this element.
With these options I think we can iterate and propose solutions to discuss.

**Comment by lyubomir-popov** [comment]
@kwm14 this should probably go through a sketch design phase and approval before coding anything?

**Comment by kwm14** [comment]
> @kwm14 this should probably go through a sketch design phase and approval before coding anything?

Yes, we plan to relook at this component next cycle, as there is a lot of opinions from the team how this should look and work 👍

**Comment by wgx** [comment]
Supported by spec "Command Prompt" in https://discourse.ubuntu.com/t/code-snippet-pattern/19195

**Comment by sowasred2012** [comment]
@bartaz @lyubomir-popov I think we can close this since we're deprecating code-copyable, and the code snippet supports "not CLI" code - what do you think?

**Comment by bartaz** [comment]
Yes, that's covered by code snippet now.
