### ISSUE TITLE
Navigation: Update hover state on link items

### ISSUE THREAD

**Issue by therealjuan** [canonical-web-and-design/vanilla-framework#2456]
**What is happening now?**
On the top navigation,  selected and hover states are minimal (closer to 0) this creates a bit of confusion as you can't distinguish what is the current page you are looking at and what is on hover:

![2019-08-07 09 23 37](https://user-images.githubusercontent.com/8167677/62607130-79b64f00-b8f5-11e9-9bcb-c6ccf1438746.gif)

You can look at the URL to know where you are but it feels strange might be because of many years used to the old pattern of having difference between hover and selected states.

–––
**Proposal:**
As text links operate on hover by showing an underline, it will be more logical to persist this pattern on navigation links:

![2019-08-07 09 28 33](https://user-images.githubusercontent.com/8167677/62607310-c69a2580-b8f5-11e9-8ee2-3d012d9548d5.gif)

**Comment by kwm14** [comment]
## WG
- Agreed to keep navigation styles as they are
- Will generate a list of navigation concerns (if any) and relook and updates in the future

**Comment by therealjuan** [comment]
There is a concern up there ^^^^

And also another one is ...
![image](https://user-images.githubusercontent.com/8167677/64123163-7cdd1780-cd9b-11e9-97b1-f510ff006166.png)


Which one is hover which one is not?

**Comment by bartaz** [comment]
Navigation styles changed since this was reported, so this is not an issue anymore.
