### ISSUE TITLE
Allow wrapping code in code block

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#2457]
## Pattern to amend

Code block was changed in Vanilla 2.0 not to wrap lines by default (uses whitespace `pre` instead of `pre-wrap`).
This caused some issues in snapcraft.io docs that relied on wrapping:

<img width="1672" alt="Screenshot 2019-08-07 at 12 42 39" src="https://user-images.githubusercontent.com/83575/62617777-f0ae1080-b912-11e9-8d6e-20e7bf22d518.png">

It would be good to have at least an option to turn wrapping on.

**Comment by lyubomir-popov** [comment]
Linking the [discussion](https://github.com/canonical-web-and-design/vanilla-framework/issues/1986) that lead to this change.

**Comment by anthonydillon** [comment]
This is a layout issue not a component issue. The component should only consume the space it has available from is parent. This is the same issue I gave fixed in 3 sites now. We really need a central place to resolve layout issues which is the layouts work in Vanilla.

**Comment by bartaz** [comment]
@anthonydillon Yes, it's a layout issue and was fixed in docs, but still, there are cases where using wrapping in code blocks could be useful.

Snapcraft docs often have console outputs with long lines of text. Wrapping made them nicely readable, now you need to scroll horizontally to read text.

**Comment by anthonydillon** [comment]
Interesting, good point. Modifier on the code block pattern?

**Comment by bartaz** [comment]
Vanilla seems to have 2 approaches `--modifier` or `is-modifier`, not sure if there is any formal distinction between the two.
Simply having an option to change the style without need for custom CSS would be welcome.

Unless of course from design point of view we feel it's better not to wrap code blocks in CSS and any wrapping should be done in content for better control.

**Comment by kwm14** [comment]
## WG
- We need to recommend an alternative in our Documentation as a hardcoded markup solution

**Comment by sowasred2012** [comment]
Commented the same on #2184 before spotting this, which is probably the more appropriate place:

I have set white-space: pre-wrap on the new code snippet, but only when using numbered lines (https://github.com/canonical-web-and-design/vanilla-framework/blob/master/scss/_base_code.scss#L88). However, I still think it should be the default on pre, scrolling vertically down the page and then horizontally within a given component presents accessibility issues: https://www.w3.org/WAI/WCAG21/Understanding/reflow

**Comment by bartaz** [comment]
@sowasred2012 We have this still to do: https://github.com/canonical-web-and-design/vanilla-framework/issues/3478 to allow having wrapping/no-wrapping variants for code snippet.

As far as I understand for accessibility reasons you suggest that we wrap by default, but we still should have a modifier (`is-no-wrap` on `p-code-snippet__block`?) to disable wrapping if someone needs to keep the line structure (for ascii art or something).

When we address this we should be able to close the wrapping related issues.
