### ISSUE TITLE
Pagination links turn blue when visited

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#2458]
**Describe the bug**

Not sure if that is intended behaviour (but looks quite weird and confusing), but pagination links in pagination buttons (dark text colour by default) turn blue when link is visited (because they inherit styles from visited link).

**To Reproduce**
1. Go to pagination docs: https://docs.vanillaframework.io/patterns/pagination/
2. Click on links in example paginations
3. See how visited buttons become blue

**Expected behavior**
Pagination buttons should not change colour when visited

**Screenshots**
<img width="417" alt="Screenshot 2019-08-07 at 14 40 25" src="https://user-images.githubusercontent.com/83575/62623644-a5e7c500-b921-11e9-9bd8-eb9cbc47b903.png">

**Comment by kwm14** [comment]
@bartaz that is the intended behavior, `$color-link` is our default link color and are 10% darker when already visited.

But you raise a valid point if the links are using `.p-link--soft` it should inherit 10% darker of that color, rather than referring to our default `$color-link`

**Comment by kwm14** [comment]
## Design update
- If using `.p-link--soft` the visited color should be 10% darker of that color

**Comment by kwm14** [comment]
Looking back tat the link saga I don't really want to open up changing link color styles.

Going forward we will keep as is, but if any more frequent issues are raised about the visited link we can revisit this issue 👍
