### ISSUE TITLE
Make `vf-highlight-bar` a utility class

### ISSUE THREAD

**Issue by kwm14** [canonical-web-and-design/vanilla-framework#2460]
## Pattern to amend

Highlight bar - https://docs.vanillaframework.io/utilities/functions/#highlight-bar

## Context

Currently, it's a mixin so you'd need to make/write some SASS to give it a class you could use in CSS.

Proposal to make it a utility class so we don't have to write custom CSS for it, but of course, it's not as easy as adding a line to anything as discovered by @bartaz 

<img width="224" alt="Screenshot 2019-08-07 at 16 47 56" src="https://user-images.githubusercontent.com/17748020/62632889-265ef380-b92b-11e9-9ddf-332211a34356.png">

**Comment by bartaz** [comment]
For more context on when this request comes from.

With sidebar navigation component being removed from Vanilla it would be nice to have a consistent way to build such navigation from existing components classes.

Sure, we can use `p-list` with a list of links in a grid, but what is missing is ability to select one of the links as active/current.

If the solution is a utility class, or a modifier to a list component - I don't know, but it would be nice to have something built in, not to invent it in the projects.

**Comment by bartaz** [comment]
Seems like return of side navigation is proposed in #2466 so maybe `vf-highlight-bar` will not be needed if that is accepted.

**Comment by bartaz** [comment]
Not relevant anymore.
