### ISSUE TITLE
Misaligned checkboxes (because of padding on label)

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#2461]
**Describe the bug**

Vanilla 2.0 introduced some changes to spacing in form labels (adding top padding).
This is also reflected in checkbox pattern (which must be used with label), this additional padding gets in a way in places where checkboxes where used with expectation of no top spacing (such as some tables in snapcraft):

<img width="392" alt="Screenshot 2019-08-08 at 08 41 41" src="https://user-images.githubusercontent.com/83575/62681051-070ea780-b9b9-11e9-9f0c-68550e8039cd.png">

Usually issues like this can be easily solved with `no-margin` or `no-padding` utilities.
In this case however placement of custom checkbox relies on top padding, so removing it (while moves label text into place) leaves checkbox itself misaligned:

<img width="376" alt="Screenshot 2019-08-08 at 08 43 30" src="https://user-images.githubusercontent.com/83575/62681117-36251900-b9b9-11e9-8066-e6ba78a83197.png">

**Expected behavior**
If top padding/margin on labels is necessary for spacing reasons it should be optional and cancelable with Vanilla provided utilities to allow aligning in cases when top spacing is not expected:

<img width="350" alt="Screenshot 2019-08-08 at 08 42 48" src="https://user-images.githubusercontent.com/83575/62681195-68367b00-b9b9-11e9-9887-a72906cf9041.png">

**Comment by lyubomir-popov** [comment]
@bartaz just checked and I've added an inline version (label.is-inline-label) to vanilla, but neglected to document it. Would this work in your case? If not, then we'll need to provide new classes that calculate box tick and radio circle offsets without including the nudge value. 

Example [here](https://docs.vanillaframework.io/examples/templates/tick-element-comparison/) - the ones in the table:
![image](https://user-images.githubusercontent.com/2741678/62691587-e4838b00-b9c6-11e9-916f-74657dab51c8.png)

**Comment by bartaz** [comment]
@lyubomir-popov Yes, it does. Thanks.

Although I feel the checkbox is a bit higher relative to text than in block version (making it look like it's a bit above baseline):

<img width="352" alt="Screenshot 2019-08-08 at 12 37 55" src="https://user-images.githubusercontent.com/83575/62696806-798f7f80-b9d9-11e9-91cb-3f59194db6e0.png">

**Comment by lyubomir-popov** [comment]
@bartaz yes, seems like it needs some fine-tuning. I'll asign myself to tackle when I'm done with the theming spike.

**Comment by bartaz** [comment]
Great thanks, I'll use it already so it will be updated whenever it's fixed in Vanilla.
