### ISSUE TITLE
Buttons too small in expanding row

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/vanilla-framework#2462]
In expanding rows the buttons are narrow as if they where in a normal `<td>`. I think these should probably have the regular button height. See the Cancel and Delete buttons below:

<img width="255" alt="Screen Shot 2019-08-09 at 2 09 10 pm" src="https://user-images.githubusercontent.com/361637/62753681-04db4480-bab0-11e9-837d-7d6cfe2b0fec.png">

**Comment by spencerbygraves** [comment]
@kwm14 @deadlight I think we made a less tall button to fit in table rows, is that correct?

**Comment by kwm14** [comment]
@spencerbygraves @huwshimi yes that correct 😃buttons scale inside table rows so we don't increase the height of the default table row.

**Comment by huwshimi** [comment]
Do you think this should be the case in the expanded content? e.g in this sort of case: https://codepen.io/huwshimi/pen/ExYVmrK

There's a design here that shows the buttons as full height: https://app.zeplin.io/project/5ce5423a25863c1e0d7abb27/screen/5d36e2233615fbb2789ce87f

**Comment by lyubomir-popov** [comment]
The selector here can be improved. It shouldn't happen to all buttons inside a table indiscriminately, it should rather be invoked with a modifier.
