### ISSUE TITLE
Mismatched button icon alignment in expanding tables 

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/vanilla-framework#2464]
When using `<a>` and `<button>` with icons in a `p-table-expanding` then the alignment is different between the two elements. In the following the pencil icon is an `<a>` whereas the trash icon is a `<button>`.

<img width="133" alt="Screen Shot 2019-08-09 at 4 17 33 pm" src="https://user-images.githubusercontent.com/361637/62758258-390b3100-bac1-11e9-9dbf-c41df39eb4d6.png">

Here's a working example, note the two trash icons on the right: https://codepen.io/huwshimi/pen/bXjGZO

**Comment by lyubomir-popov** [comment]
This pen also demonstrates we need td in expanding rows to have align-items: flex-start;

**Comment by lyubomir-popov** [comment]
This has already been fixed in the latest master. Closing.

![image](https://user-images.githubusercontent.com/2741678/68691791-3f032900-056c-11ea-9bf6-2795900957c2.png)
