### ISSUE TITLE
Breadcrumbs pattern depends on _base_typography_definitions

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#2474]
Breadcrumbs pattern can't be built out on its own as it uses `%default_text` that is defined in `_base_typography_definitions`, but not imported in breadcrumbs.
To make things worse `_base_typography-definitions` depends even deeper on other styles (like `_base_typography-max-widths`).

Not sure if it is intended and patterns assume that base styles are always available, but it breaks the build in projects that include patterns selectively and required to have custom scss files that provide all necessary dependencies.

**Comment by bartaz** [comment]
Some other similar error examples:

```
"message": "\"%icon\" failed to @extend \"%vf-hide-text\".\nThe selector \"%vf-hide-text\" was not found.
```

```
"message": "\".p-stepped-list--detailed .p-stepped-list__item\" failed to @extend \"%row\".\nThe selector \"%row\" was not found.
```

**Comment by bartaz** [comment]
After clearing this out it seems that some of them are fixed by simply adding:

```
@import 'vanilla-framework/scss/_base_placeholders.scss';
```

Which is fair, but would be nice if patterns would do that themselves. As long as these are placehoders they shouldn't add to CSS sizes if included multiple times (right?).

A bit tricker ones are with typography. Not only `typography-definitions` rely on `typography-max-widths`, but they both also require being not only imported, but also included:

```
@import 'vanilla-framework/scss/_base_typography-definitions.scss';
@import 'vanilla-framework/scss/_base_typography-max-widths.scss';

@include vf-b-typography-max-widths;
@include vf-b-typography-definitions;
```

**Comment by lyubomir-popov** [comment]
@bartaz AFAIK duplicate import of placeholder results in duplication of the classes that extend it https://github.com/sass/sass/issues/2224

@deadlight I think the intention was for %placeholders to be included always, right? Probably something for the documentation to mention.

**Comment by deadlight** [comment]
Yes, we should have clear guidance on the minimal include set.

**Comment by lyubomir-popov** [comment]
The information on the minimum include set will be visible here once released: https://docs.vanillaframework.io/customising-vanilla/
