### ISSUE TITLE
Light border around dark navigation dropdown

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#2478]
Navigation dropdown has a light border even if background of the nav is changed to dark.
It seems that the border was defined to be in line with light navigation border. Not sure if it was intended to be the same when nav color is changed.

**Expected behavior**
When navigation color is changed dropdown border color should adapt. Or it should be possible to change color of the dropdown border alongside nav background color.

**Screenshots**
<img width="484" alt="Screenshot 2019-08-13 at 08 18 38" src="https://user-images.githubusercontent.com/83575/62919486-1b7ce680-bda3-11e9-9966-c302d4ad2d7e.png">
<img width="757" alt="Screenshot 2019-08-13 at 08 14 39" src="https://user-images.githubusercontent.com/83575/62919487-1b7ce680-bda3-11e9-8990-740720933194.png">
<img width="780" alt="Screenshot 2019-08-13 at 08 14 12" src="https://user-images.githubusercontent.com/83575/62919488-1b7ce680-bda3-11e9-906e-5ded86f138af.png">

**Comment by bartaz** [comment]
I just found that there is a variable `$color-navigation-border` that is used to define colour of bottom border of the navigation, but it is not used as a border of the dropdown.

It would be useful to have these variables listed at least in https://docs.vanillaframework.io/customising-vanilla/, but ideally also with the documentation of the component itself, so developers know what parts of pattern can be customised and what needs to be overridden.

**Comment by lyubomir-popov** [comment]
@deadlight do you know why p-subnav is a separate component, instead of a modifier on p-navigation__link? I'm asking because if it is a separate pattern, theming it will require adding --dark or is--dark on every single dropdown, which seams too much.

**Comment by lyubomir-popov** [comment]
To avoid conflicts, I'll wait for the theming spike pr to be merged before tackling this one.

**Comment by kwm14** [comment]
Theming spike [merged](https://github.com/canonical-web-and-design/vanilla-framework/pull/2507). Issue now unblocked 👍
