### ISSUE TITLE
Navigation item are misaligned when on the right side of the page

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#2480]
When navigation contains items aligned to the right side of the page they don't have the same padding as rest of the page layout leaving them outside of page borders.

**Expected behavior**
It should be possible to align items in nav to right without them overflowing out of the page.

**Screenshots**
<img width="1238" alt="Screenshot 2019-08-13 at 08 57 35" src="https://user-images.githubusercontent.com/83575/62926761-6c95d600-bdb5-11e9-90d0-dfcb8ddc4b6e.png">

**Test case**
https://jsfiddle.net/bartaz/a256px8d/4/

<img width="978" alt="Screenshot 2019-08-13 at 10 36 35" src="https://user-images.githubusercontent.com/83575/62927174-47ee2e00-bdb6-11e9-841b-89d69a96749f.png">

**Comment by bartaz** [comment]
Something like this solves the issue (not sure if it covers all cases):

```scss
.p-navigation__links:last-child {
  margin-right: $grid-margin-width;
}
```

**Comment by bartaz** [comment]
But even when aligned with same grid paddings dropdowns of global nav and page nav **look** missaligned because of their individual spacing (of arrow icons):

<img width="1154" alt="Screenshot 2019-08-13 at 11 35 08" src="https://user-images.githubusercontent.com/83575/62931392-930c3f00-bdbe-11e9-918e-8b26755d8781.png">

**Comment by lyubomir-popov** [comment]
I'm about to push a fix for this, it space the chevron the same way it is spaced in selects:

![image](https://user-images.githubusercontent.com/2741678/63777757-91bd3500-c8db-11e9-94c2-61690420a2a2.png)

We will need to adjust the global nav as a separate task.

**Comment by lyubomir-popov** [comment]
Fix: https://github.com/canonical-web-and-design/vanilla-framework/pull/2514
