### ISSUE TITLE
Unnecessary spacing in navigation in Firefox (when inside row)

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#2483]
**Describe the bug**
When navigation is put inside `.row` (as docs suggest to constrain the width) there is unnecessary additional spacing between banner and nav items in Firefox.

**To Reproduce**
Open https://jsfiddle.net/bartaz/hvwfbup3/ in Chrome and Firefox.
Compare space between logo and items:

Chrome:
<img width="1102" alt="Screenshot 2019-08-14 at 10 18 00" src="https://user-images.githubusercontent.com/83575/63005659-4471aa00-be7d-11e9-87e7-afc61ea555ff.png">

Firefox:
<img width="1100" alt="Screenshot 2019-08-14 at 10 17 04" src="https://user-images.githubusercontent.com/83575/63005660-4471aa00-be7d-11e9-8954-5f2387f42fbb.png">

**Expected behavior**
There should be no spacing between banner and navigation items.

**Comment by bartaz** [comment]
Workaround (or fix?):

```
.p-navigation .row {
   grid-gap: 0;
}
```

**Comment by lyubomir-popov** [comment]
This is tricky. A css grid row is not ideal for the nav, as columns in a nav are not useful. Navs  contains arbitrarily wide elements. u-fixed-width is closer but not perfect, and we wouldn't want to make people change names. 

There's a class called .p-navigation__row, I think we should recommend that over .row. THen just adding display:flex on p-navigation__row will probably fix things. I'll experiment and report back.

**Comment by lyubomir-popov** [comment]
Fixed in https://github.com/canonical-web-and-design/vanilla-framework/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Alyubomir-popov, closing.

While we still support .row, it is deprecated. The recommendation is to always insert p-navigation__row / p-navigation__row--full-width that wraps the children of p-navigation.
