### ISSUE TITLE
`u-hide` issue when hiding images on small screens

### ISSUE THREAD

**Issue by Lukewh** [canonical-web-and-design/vanilla-framework#2484]
Not specifically a bug, but something worth discussing.

On pages like https://jaas.ai/u/openstack-charmers-next `u-hide--small` is used to hide icons on smaller screens, however using the class doesn't prevent the images being downloaded (at least in Firefox) when loaded at a smaller screen-size. I imagine this is because the icons are prioritised above the CSS, that would prevent the icons from being loaded, by the browser.

Worth discussing how Vanilla can improve progressive enhancement out of the box?

**Comment by bartaz** [comment]
As far as I understand there is nothing we can do on CSS level in Vanilla to prevent images (defines as `img` tag in HTML) from loading.
Resources defined in HTML are prioritized over CSS and browser loads them regardless.

It seems it needs to be responsibility of given project to use techniques that would not load unnecessary resources.
Maybe it's something out image template module could do?
