### ISSUE TITLE
Form help text too close when $multi = 1

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical-web-and-design/vanilla-framework#2488]
**Describe the bug**
If `$multi = 1` (i.e. density is high) the help text underneath text and select inputs is too close. On checkboxes the spacing is fine, however.

**Screenshots**
![screenshot_1](https://user-images.githubusercontent.com/25733845/63098753-de1b8300-bf73-11e9-9a15-51eec3a2a090.png)

![screenshot_2](https://user-images.githubusercontent.com/25733845/63098812-060ae680-bf74-11e9-9955-2157036506c1.png)

**Comment by lyubomir-popov** [comment]
I noticed that, I think I fixed it in https://github.com/canonical-web-and-design/vanilla-framework/pull/2452

So a fix will be available shortly.

**Comment by lyubomir-popov** [comment]
That pr removes the margin-top -.5rem on many text elements, which in part solves Robin's issue and this one. Still needs some finalizing before I can merge it.
