### ISSUE TITLE
.p-stepped-list assumes list items contain a title

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/vanilla-framework#2489]
**Describe the bug**
The `.p-stepped-list` pattern doesn't appear to accommodate `.p-stepped-list__item` elements that don't contain `.p-stepped-list__title` elements.

**To Reproduce**
1. Go to https://codepen.io/sowasred2012/pen/ZEzWxrE
2. Look at the three differently implemented list items

**Expected behavior**
I expect to be able to use a stepped list pattern on lists where the list itself has a heading, rather than each individual item.

**Additional context**
I discovered this whilst upgrading to Vanilla 2.x.x on u.c, on this page specifically: https://ubuntu.com/download/iot/installation-media

It features a number of lists that use a stepped list pattern - each list is preceded by a header, and the list items only contain `p` elements.

**Comment by lyubomir-popov** [comment]
Intended use: 

![image](https://user-images.githubusercontent.com/2741678/95975564-3b2bf680-0e0e-11eb-8ba3-0d213fda486b.png)
