### ISSUE TITLE
Increase the height of the Modal iframe...

### ISSUE THREAD

**Issue by BaseMax** [canonical-web-and-design/vanilla-framework#2492]
Hello,
I'm Max.

There is a bug on Modal page. (https://docs.vanillaframework.io/patterns/modal/)
Currently, the height of the iframe is `82px`, it should increase to something bigger...

![Capture](https://user-images.githubusercontent.com/2658040/63158248-154e6a80-c02e-11e9-926d-d579ad7cc2dd.PNG)

- [docs/examples/patterns/modal.html](https://github.com/canonical-web-and-design/vanilla-framework/blob/master/docs/examples/patterns/modal.html)
- [docs/patterns/modal.md](https://github.com/canonical-web-and-design/vanilla-framework/edit/master/docs/patterns/modal.md)

Best Regards,
Max

**Comment by anthonydillon** [comment]
Max, thank you very much for taking the time to report this issue to us. We will try and get a fix out in the next release on the site.
