### ISSUE TITLE
Increase the height of the Floats iframe...

### ISSUE THREAD

**Issue by BaseMax** [canonical-web-and-design/vanilla-framework#2493]
Hello,
I'm Max.

There is a bug on Floats page. (https://docs.vanillaframework.io/utilities/floats/)
Currently, the height of the iframe is `18px`, it should increase to something bigger...

![Capture](https://user-images.githubusercontent.com/2658040/63158480-90b01c00-c02e-11e9-848e-b8c8bfef7f55.PNG)

- [docs/utilities/floats.md](https://github.com/canonical-web-and-design/vanilla-framework/blob/master/docs/utilities/floats.md)

Best Regards,
Max

**Comment by deadlight** [comment]
Thanks for reporting this issue, @BaseMax.

We'll fix this, I think that the content doesn't have a height being set, due to the float contents.

If you'd like an example in the meantime, you can [see the page directly](https://docs.vanillaframework.io/examples/utilities/floats/default/)

**Comment by bartaz** [comment]
This is not an issue anymore as we use CodePen for embedding examples.
