### ISSUE TITLE
Provide a sense of the current version of library

### ISSUE THREAD

**Issue by therealjuan** [canonical-web-and-design/vanilla-framework#2496]
Now we have some beautiful labels telling people what has change on the sidebar content but it would be good to refer when the change happened.

![image](https://user-images.githubusercontent.com/8167677/63258693-8a12e600-c274-11e9-95ec-c4fecd98b650.png)

Swift documentation on the apple developer site is quite neat and showcases on a version what are the main changes as a recap?

![image](https://user-images.githubusercontent.com/8167677/63260346-a0bb3c00-c278-11e9-8d4b-94e74ba520b2.png)

Perhaps something interesting to include at the very top of the vanilla sidebar?

**Comment by cassiocassio** [comment]
We're going to need something like this everywhere, for maas features, for juju cli versions, for screenshots in docs that vary over versions.

As I understand it, a docs discourse is meant to be for version 1.x, 2.x, 3.x, etc, and we may need URLS and navigation and guidance for <go to major version> but some kind of labelling and filtering as per the Apple example for the minor versions.

**Comment by therealjuan** [comment]
This was more like starting by adding the version number on the sidebar so you can refer back... if we want to extend functionality to keep other versions that is a different matter that would probably require more thought

**Comment by deadlight** [comment]
@kwm14 Initially, we can simply display the current version in the sidebar; this could do with some design input

**Comment by lyubomir-popov** [comment]
This was completed here, closing:

https://github.com/canonical-web-and-design/vanilla-framework/pull/2842


![image](https://user-images.githubusercontent.com/2741678/80687593-6fab3080-8ac2-11ea-806c-3e4482a111d6.png)
