### ISSUE TITLE
Form submit button too close to input when $multi = 1

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical-web-and-design/vanilla-framework#2497]
**Describe the bug**
If `$multi = 1` (i.e. density is high) the submit button below a form is too close. 

**Screenshots**
![screenshot_3](https://user-images.githubusercontent.com/25733845/63266668-b8062380-c290-11e9-9605-3f1575aa5f2e.png)

**Comment by lyubomir-popov** [comment]
@Caleb-Ellis Where does this appear in maas? Looking at the vanilla examples this doesn't seem too bad, but msyber I'm missing the context.

**Comment by Caleb-Ellis** [comment]
By default, Vanilla has forms that look like this:

### No help text
![screenshot_1](https://user-images.githubusercontent.com/25733845/63940522-f1494b00-ca69-11e9-9cfd-86c0489155e7.png)

### Help text
![screenshot](https://user-images.githubusercontent.com/25733845/63940528-f7d7c280-ca69-11e9-9e20-43557291a091.png)

In the current `maas-ui` I've added a bit of spacing with:
``` scss
.p-form__control:last-of-type {
  margin-bottom: $spv-outer--small;
}
.p-form__group:last-of-type {
  margin-bottom: $spv-outer--medium;
}
```

### No help text
![screenshot_3](https://user-images.githubusercontent.com/25733845/63940574-150c9100-ca6a-11e9-94ff-3e4743e39ad6.png)


### Help text
![screenshot_2](https://user-images.githubusercontent.com/25733845/63940581-19d14500-ca6a-11e9-865b-33e289142793.png)


Which I think is more evenly spaced. Maybe this could be an issue of wanting dense spacing in some places but not others, but imo the submit button is too close even for high density.
