### ISSUE TITLE
Very dense tables need smaller column headings

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#2501]
## Pattern to amend

In maas we've changed column headings to be smaller and  a bit heavier (font-weight 400 instead of 300). I would like to propose upstreaming this to vanilla, as any app could benefit from labels that take up less space. The changes are:

- reduce font-size of column headers one notch down the modular scale, in order to gain space that can be used where it is needed
- increase font-weight to 400, to avoid text becoming too thin at this font-size

## Visual

before:

![image](https://user-images.githubusercontent.com/2741678/63342738-22c46700-c344-11e9-8397-20eaa331daa2.png)

after:

![image](https://user-images.githubusercontent.com/2741678/63342719-1809d200-c344-11e9-836c-3599737e695b.png)

## Context

In very dense tables, we often have column labels that are 2x wider than the content in the column. This takes too much space that can otherwise be used in columns which often overflow and are truncated with an ellipsis, like a mac address, status text, etc. Reducing the width of the column headers, while maintaining visual balance by increasing the font-weight, works quite well in my opinion.

**Comment by kwm14** [comment]
## WG
- Agreed 'after' looks good 👍
