### ISSUE TITLE
Provide highlight-able version of tables

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#2502]
## Pattern to amend

In many places in maas, row interactions are shown using a change in row background.
To accomodate this, content in the first / last column needs to be padded. It would be nice if this could be a vanilla modifier, instead of a local override.

Visual
By default, tables look like this:
![image](https://user-images.githubusercontent.com/2741678/63344023-5bb20b00-c347-11e9-9450-f2c0007f6053.png)

With overrides, we achieve this:
![image](https://user-images.githubusercontent.com/2741678/63344068-708e9e80-c347-11e9-9e12-c4a5896c07aa.png)

## Context

When row interaction is shown using a change in background-colour.

**Comment by kwm14** [comment]
@lyubomir-popov can we estimate this, please? :smile

**Comment by lyubomir-popov** [comment]
Since this is just about padding table cells, not deciding on highlight class names, interaction, colours etc, we can close it. I it already done:
![image](https://user-images.githubusercontent.com/2741678/65784065-2d46fd00-e149-11e9-900d-ca48a2ee3fb1.png)
