### ISSUE TITLE
Buttons in dense tables aren't spaced properly

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical-web-and-design/vanilla-framework#2504]
**Describe the bug**
In `maas-ui` we need a few custom styles to improve spacing in dense tables.

**Default Vanilla**
![screenshot_6](https://user-images.githubusercontent.com/25733845/63345521-3a571c00-c353-11e9-9aa9-8f3c00ebb5e6.png)

**Expected**
![screenshot_7](https://user-images.githubusercontent.com/25733845/63345534-4347ed80-c353-11e9-8c1c-120f60e62f2c.png)

**Comment by lyubomir-popov** [comment]
Isn't this a case of buttons stretching the row height? If so I would make a modified version of buttons that fits properly, instead of modifying the table row padding.

**Comment by Caleb-Ellis** [comment]
@lyubomir-popov Yeah you're right, it's really the buttons that are messing with spacing. I'll amend the title, but regardless this should be fixed in Vanilla. Maybe just simply:
``` scss
@if $multi == 1 {
  td:not(.p-table-expanding__panel) [class*="p-button"] {
    // amended button spacing
  }
}
```

**Comment by lyubomir-popov** [comment]
Thanks for clarifying, I'll see what's best. One one hand the buttons need to go into the existing padding, on the other their baseline needs to stay aligned with the first line of text in adjacent cells.

**Comment by lyubomir-popov** [comment]
there's another related [bug](https://github.com/canonical-web-and-design/vanilla-framework/issues/2463), adding a reminder here to close both when we make a pr for this.
