### ISSUE TITLE
Notification close misaligned with $multi = 1

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/vanilla-framework#2512]
With high density (`$multi: 1;`) then the close button on notifications does not adjust accordingly. See:

<img width="313" alt="Screen Shot 2019-08-26 at 1 04 14 pm" src="https://user-images.githubusercontent.com/361637/63662566-471bba00-c802-11e9-9d5d-c6143106e6e5.png">

**Comment by lyubomir-popov** [comment]
This will need to increase in scope a bit, we need to deprecate the button.p-icon--close markup but still support it, and use the corecton <button><i class='p-icon--close'>Close</i></button> markup. This will involve some qualifying elements in a deprecate mixin.
