### ISSUE TITLE
Remove top border from Matrix on small screens

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/vanilla-framework#2517]
## Pattern to amend
Remove the top border on the first element on the Matrix pattern on small screens

## Visual
![Screenshot_2019-08-28 Vanilla documentation](https://user-images.githubusercontent.com/1413534/63853481-b7594580-c992-11e9-9566-a457bb9c3260.png)

Request:
![Screenshot_2019-08-28 Vanilla documentation](https://user-images.githubusercontent.com/36884067/63845520-faf78380-c981-11e9-8a78-c37b4b3a82b6.png)

**Comment by lyubomir-popov** [comment]
Why do you want to remove it?

**Comment by lyubomir-popov** [comment]
@anthonydillon can you attach an image of where this is used and a border is problematic? I guess one concern is that we don't know what comes above, so a border just makes sure preceding content isn't confused as part of the first item. But we could maybe provide an optional class to strip it?

**Comment by anthonydillon** [comment]
I do not want to provide a bunch of utility classes that the users needs to learn to use a basic pattern like matrix. The matrix pattern is used widely across all websites. There are images attached to the issue description. 

We do not provide an initial divider of content in the list divided pattern. This is due to the fact the content in the pattern is inherently connected to the content above as it is in the same strip.

If the pattern has no content above it, it acts as an unnecessary divider.

**Comment by lyubomir-popov** [comment]
Got it, ok. We'll remove it.
