### ISSUE TITLE
.p-stepped-list__title wraps incorrectly if it contains child elements

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/vanilla-framework#2518]
**Describe the bug**
If a `p-stepped-list__title` contains another HTML element, such as a `<strong>` tag, space either side of the element collapses, and the element will wrap incorrectly at different device widths.

**To Reproduce**
1. Go to https://codepen.io/sowasred2012/pen/wvwevwN?editors=1000
2. Resize the browser

**Expected behavior**
Child elements of the `p-stepped-list__title` should not deform their parent element.

**Screenshots**
![Screenshot 2019-08-28 at 15 38 27](https://user-images.githubusercontent.com/2376968/63866614-6275f900-c9ab-11e9-9bef-2f77ae1ec6df.png)

**Comment by bartaz** [comment]
`p-stepped-list__title` uses `display: flex` (to position the circle), but this also means it affects all child elements, making them blocks inside flex layout.

A workaround for that would be to wrap the whole contents in an element:

```html
<h3 class="p-stepped-list__title"><span>Something <strong>bolded</strong> to wrap</span></h3>
```

This solves the problem, but we will look for a better styling in Vanilla to avoid such workarounds.
