### ISSUE TITLE
Input field validation icon

### ISSUE THREAD

**Issue by hughesjordan** [canonical-web-and-design/vanilla-framework#2521]
**Describe the bug**
In extreme cases the input text appears to continue over the icon making the icon hard to see. It also looks as though the character limit is also overlaid.

**Expected behavior**
Text to cut off just before the icon, character limit to be visible somewhere.

**Screenshots**
<img width="823" alt="Screenshot 2019-08-30 at 10 18 50 am" src="https://user-images.githubusercontent.com/17141586/64013866-b2260300-cb18-11e9-91fd-a7a5d67bda8d.png">

**Comment by lyubomir-popov** [comment]
Thanks for reporting @hughesjordan
