### ISSUE TITLE
Code-copyable should provide help / warnings

### ISSUE THREAD

**Issue by popey** [canonical-web-and-design/vanilla-framework#2527]
## Pattern to amend

code-copyable (I think, from the sourcecode)?

![Screenshot from 2019-09-03 11-21-48](https://user-images.githubusercontent.com/1841272/64165532-317b4580-ce3d-11e9-9485-1ced0e5d1c02.png)

## Visual

Suggestion 1.

```
+-------------------------------+
|  $ sudo snap install gcompris |
+-------------------------------+
                    What is this?
```

Suggestion 2.

```
+-------------------------------+
|  $ sudo snap install gcompris |
+-------------------------------+
                              [?]
```

## Context

New users to Linux do not know what to do with a terminal command. It just looks like a pre-formatted chunk of technical garbage. 

In a recent study, a non-Linux user was completely thrown by seeing pre-formatted text on a page with no indication what to do with it. While many of our existing users are technical, if we want to bring new users over, we should explain what things are. The "Command Line" is not a thing normal Windows users transitioning to Linux will immediately know about.

I'd suggest some addition near the box which indicates what it's for. I don't know whether it should be a short popup, or a link to an external documentation page, but it should be generic. Something like this which is highly generic (CTRL+ALT+T isn't a standard):

```
This box contains command(s) which are executed in a terminal. Launch the terminal from your desktop menu and paste the command in to complete this task.
Note: Some commands are powerful may be dangerous to your system, we recommend speaking to a technical expert if you're unsure what this command does.
```

**Comment by fitojb** [comment]
This seems completely out of scope for a generic framework for designing websites. This should be filed to the snapcraft website.

**Comment by deadlight** [comment]
While I agree that it's good to provide additional information, this can be achieved with the existing patterns. If you come up with a good solution in snapcraft then I'm happy to include it as an example in the documentation's usage notes.
