### ISSUE TITLE
Show include snippet per component on documentation

### ISSUE THREAD

**Issue by kwm14** [canonical-web-and-design/vanilla-framework#2549]
_An issue raised by @barrymcgee_ 

When importing components separately into a project, it would be good to surface the `@include` snippet to the documentation of that component.

Saving time to look in the `.scss` file and hunting to find the exact include for that particular component.

- We could add a section in the context menu called 'Import'?
- We could add a snippet alongside the component heading?

**Comment by lyubomir-popov** [comment]
Also might help list any external placeholders that need to be imported for the pattern to work. E.g. every icon uses %vf-hide-text, which is in base_placeholders.scss
