### ISSUE TITLE
Any icon in positive button is turned into +

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#2552]
If you put any icon into `p-button--positive` it is changed into `p-icon--plus`.

**To Reproduce**
1. Go to https://docs.vanillaframework.io/examples/patterns/buttons/icon/
2. Change icon in positive icon to anything else
3. Icon doesn't change

**Expected behavior**
You should be able to use any icon in positive button

**Screenshots**
<img width="782" alt="Screenshot 2019-09-18 at 13 44 15" src="https://user-images.githubusercontent.com/83575/65145791-a6907280-da1a-11e9-9d47-dd30918929e6.png">

**Comment by bartaz** [comment]
This issue is blocking snapcraft.io update to vanilla 2.4.0

**Comment by kwm14** [comment]
Thanks for raising @bartaz have created an [epic](https://github.com/canonical-web-and-design/vanilla-squad/issues/694) to fix issues related to the same component.
