### ISSUE TITLE
Icons are misaligned in buttons without p-button class

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#2553]
If an icon is used in `<button>` without any class name, icons are misaligned.
Icons are only positioned correctly if `p-button` class (or any variant) is present on the button.

`p-button` class is not required if there is any text in the button.

**To Reproduce**
1. Go to https://docs.vanillaframework.io/examples/patterns/buttons/icon/
2. Remove classes from a button that only has an icon
3. See that it is misaligned

**Expected behavior**
Icons should behave normally in pure HTML `<button>` or it should be clear from the documentation that buttons require `p-button` class and base buttons behave differently.

**Screenshots**
<img width="876" alt="Screenshot 2019-09-18 at 13 51 12" src="https://user-images.githubusercontent.com/83575/65146332-d4c28200-da1b-11e9-812d-186569313444.png">

**Comment by kwm14** [comment]
Thanks for raising @bartaz have created an [epic](https://github.com/canonical-web-and-design/vanilla-squad/issues/694) to fix issues related to the same component.

**Comment by lyubomir-popov** [comment]
I lean towards updating the documentation to clarify you need to use classes if you want an icon inside a button.

The other option, expanding the selector to include any icons inside a button tag, would create unnecessary overhead if you do not plan to use icons inside buttons, or if you're happy doing those with classes. 
What do you think @deadlight?

**Comment by deadlight** [comment]
@lyubomir-popov yes, I agree that a documentation update/clarification is needed. A plain `<img>` inside a plain `<button>` would be fine but, as soon as Vanilla classes are used, I think we're ok to mandate that they're used on the container and contents.

**Comment by kwm14** [comment]
Issue fixed in https://github.com/canonical-web-and-design/vanilla-framework/pull/2619 and documented how to use classes https://github.com/canonical-web-and-design/vanilla-framework/pull/2578. Button with icon updates will be in the next minor release v2.5.0.
