### ISSUE TITLE
[Documentation] Impossible to change a part of the theme

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#2554]
It is impossible to change one part of a theme (for example just background color).
Whole theme definition needs to be copied and overriden to change anything inside it.

For example, if we want to change background color in dark theme, instead of just changing one variable, we need to redefine whole dark theme.

```scss
$colors--dark-theme: (
  background: #333, // we just want to change this colour of the navigation
  background-dark: hsl(0, 0%, 12%),
  background-highlighted: hsl(0, 0%, 17%),
  border-default: hsl(0, 0%, 27%),
  border-high-contrast: hsl(0, 0%, 42%),
  text-hover: hsl(0, 0%, 56%),
  text-default: hsl(0, 0%, 100%)
);
```

**Expected behavior**
It should be possible to change individual parts of themes definitions.

**Comment by deadlight** [comment]
@bartaz: The theming wasn't intended to have noticeable effects but we neglected to test a use case like yours.

We will look into a more elegant solution but, in the meantime, you can merge a map onto the default one like this:
```
$colors--dark-theme: map-merge($colors--dark-theme, (background: #333));
```

I'll investigate the use of maps vs variables and set some standards for naming, etc. Apologies for this bug.

**Comment by lyubomir-popov** [comment]
One thing to keep in mind here is we want any component using the dark theme to look exactly the same across all products. So I think customising these maps should be discouraged.

The exact colours of the dark theme are still experimental, so there will be changes there once we complete the design research. We've tentatively agreed with @spencerbygraves to treat the global nav (and its corresponding mega-menu) as the base background colour:

![image](https://user-images.githubusercontent.com/2741678/65151702-eb220b00-da26-11e9-8772-695b5d733c14.png).

I think it is logical to then express the lighter p-navigaiton (#333) which we currently use everywhere as the value for the background-highlighted key in the dark colours maps.

**Comment by bartaz** [comment]
I assume we don't want to lock Vanilla to internal use, so any way to customize colors should be available. Currently it's possible by redefining values of some color variables. Introduction of themes shouldn't take away ability to customise things. Actually (as 'theming' suggests) it should make customisation easier.

**Comment by lyubomir-popov** [comment]
Not sure I understand - overwriting the map key's value as @deadlight's suggested is just as easy, if slightly more verbose:
```$colors--dark-theme: map-merge($colors--dark-theme, (background: #333));```

We could replace the maps with just variables, but then the variable names would need to contain all the information so would be longer:
```$colors--light-theme__background--highlighted```

**Comment by bartaz** [comment]
@lyubomir-popov I was referring to:

> So I think customising these maps should be discouraged.

It suggests that we don't want any customisation of built in color themes. This seems quite limiting in a CSS framework that we aim to be used outside of internal company sites.

I don't mind overriding map over the variable. But I think there should be a built in way to customise colors that would be supported in Vanilla, documented and consistent across versions.

**Comment by lyubomir-popov** [comment]
@bartaz Oh I see - yes of course, as a community user you're free to do as you please, and we will do our best to make it as easy as possible.

My comment was just about trying to keep our products as consistent as possible, and addressing this bug by changing the default to what we currently use, rather than customising in snapcraft.

**Comment by lyubomir-popov** [comment]
Related pr [here ](https://github.com/canonical-web-and-design/vanilla-framework/pull/2556)

**Comment by bartaz** [comment]
It would be worth updating documentation. There is no mention of `is-dark` at all. Also the part about customising colour via `$color-navigation-background` is not correct anymore: https://docs.vanillaframework.io/patterns/navigation/
