### ISSUE TITLE
The dot inside mid dot list incorrectly aligned

### ISSUE THREAD

**Issue by kwm14** [canonical-web-and-design/vanilla-framework#2557]
**Describe the bug**
The dot inside mid dot list incorrectly aligned to the top.

**To Reproduce**
1. Go to https://vanillaframework.io/
2. Scroll down to the footer
4. Notice footer link mid dots are misaligned

**Expected behavior**
Middots to be aligned vertically center between links

**Screenshots**
<img width="662" alt="Screenshot 2019-09-18 at 16 29 02" src="https://user-images.githubusercontent.com/17748020/65157969-da2ac700-da31-11e9-9b12-eebd85faafe8.png">

**Additional context**
This is in latest release v2.4.0

**Comment by bartaz** [comment]
I can confirm it, happens on snapcraft as well when updated to 2.4:

<img width="506" alt="Screenshot 2019-09-18 at 16 36 10" src="https://user-images.githubusercontent.com/83575/65158391-8371bd00-da32-11e9-8bf4-861bdff36f3d.png">
