### ISSUE TITLE
labels misaligned 

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/vanilla-framework#2558]
<img width="303" alt="Screenshot 2019-09-19 at 12 24 11" src="https://user-images.githubusercontent.com/36884067/65248605-b54a5880-daf2-11e9-9d68-8de30540e6f5.png">

**Comment by kwm14** [comment]
Thanks for raising @anasereijo but this has been fixed in v2.4.0 👍 

<img width="288" alt="Screenshot 2019-09-19 at 16 12 41" src="https://user-images.githubusercontent.com/17748020/65251861-55ef4700-daf8-11e9-9323-a7aa4aaf8d9d.png">
