### ISSUE TITLE
Add RSS icon

### ISSUE THREAD

**Issue by kwm14** [canonical-web-and-design/vanilla-framework#2560]
Original discussion by @anasereijo: https://github.com/canonical-web-and-design/web-squad/issues/1713

_**In vanilla**_

![vanilla](https://user-images.githubusercontent.com/36884067/65611039-259d2200-dfaa-11e9-81b6-71afad7327fe.png) 

Add new icon to [Social](https://docs.vanillaframework.io/patterns/icons/#social) section under Icons

@anasereijo to supply SVG to this issue so we can add to Vanilla icon set 👍

**Comment by anasereijo** [comment]
icons here

https://assets.ubuntu.com/v1/21fa3170-icon-rss.svg

https://assets.ubuntu.com/v1/a3aa67b2-icon-rss-hover.svg

**Comment by kwm14** [comment]
@anasereijo as we're updating all social icons in Vanilla to use official brand assets, I've also updated the RSS icon you supplied to use their official one seen on their [site](https://rss.com/blog/free-rss-icon/).

![rss-icon](https://user-images.githubusercontent.com/17748020/68595932-4b1ab800-0492-11ea-9343-6be1a2e06287.png)

The only difference is the shape it sits in 😄

**Comment by anasereijo** [comment]
That's cool! thanks
