### ISSUE TITLE
Usabilla | "What example? I am looking for the JS still!! please do tell"

### ISSUE THREAD

**Issue by kwm14** [canonical-web-and-design/vanilla-framework#2565]
**Describe the bug**
Usabilla feedback | "What example? I am looking for the JS still!! please do tell"

**To Reproduce**
1. Go to https://docs.vanillaframework.io/base/code/#functionality
2. Scroll down to **Functionality**
3. Please copy the entire JS in the example, for copy to clipboard functionality. But there isn't a JS example to copy?

**Desktop (please complete the following information):**
 - OS: GNU/Linux
 - Browser: Chrome 
 - Version : 77.0.3865.90

**Comment by bartaz** [comment]
Should be better now as CodePen has JS tab for examples.
