### ISSUE TITLE
The themeing feature has broken the navigation pattern with no easy fix 

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/vanilla-framework#2566]
The latest release `2.4.0` has introduced a breaking change to the navigation rendering the `$color-navigation-background` setting useless and causing the navigation to be set to white. We should have kept the variables influence on the pattern until a version release.

The (documentation of the navigation pattern)[https://docs.vanillaframework.io/patterns/navigation/] are still stating that variable is how to modify the navigation background color.

**Comment by cristinadresch** [comment]
@deadlight can you estimate please?

**Comment by anthonydillon** [comment]
We have agreed to revert the themeing work for the next point release. Therefore, it will be complex to unpick from the other changes in the commit. For manual revert I would suggest 5-8 but will leave the final estimation to @deadlight

**Comment by deadlight** [comment]
@cristinadresch I'll have to shuffle tasks around since priorities have changed. I'll update everything once this workshop is complete.

**Comment by lyubomir-popov** [comment]
@deadlight I made a branch to fix this, including a documentaiton update https://github.com/canonical-web-and-design/vanilla-framework/pull/2571
