### ISSUE TITLE
Z-index conflict between tabs and contextual menu

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#2577]
**Describe the bug**
Border under current selected tab appears on top of contextual menu (both have z-index of 1).

**To Reproduce**
Have both contextual menu and tabs. Tabs should be after/below contextual menu in document order.

**Expected behavior**
Contextual menu should appear correctly on top of tabs

**Screenshots**
<img width="377" alt="Screenshot 2019-10-15 at 15 57 24" src="https://user-images.githubusercontent.com/83575/66840164-ea1dc400-ef67-11e9-9f60-4b7e146b5e95.png">

**Comment by lyubomir-popov** [comment]
No longer an issue:

![image](https://user-images.githubusercontent.com/2741678/96098120-aa1a5580-0ec9-11eb-9589-4812b38e2bd9.png)
