### ISSUE TITLE
Form fieldset - no border option

### ISSUE THREAD

**Issue by solazio** [canonical-web-and-design/vanilla-framework#2580]
## Pattern to amend

Form fieldset

## Visual

![image](https://user-images.githubusercontent.com/40214246/66927361-907cce80-f027-11e9-96ef-9658c13cc76a.png)

## Context

In the latest designs we are asked very often to remove the border of the form fieldset.

**Comment by spencerbygraves** [comment]
WG: agreed to add a no border variant. We should also look at how this can be improved in line with the work undertaken by @lyubomir-popov on the use of white and grey backgrounds.

**Comment by bartaz** [comment]
In long term, we should remove styling from fieldset.

We can add an option to remove the current styling;

**Comment by lyubomir-popov** [comment]
The look of fieldsets has been changed to match a card, without a border it would not be visible. Closing.
