### ISSUE TITLE
“Details” reference page makes no sense

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/vanilla-framework#2584]
1. Go to [the “Details” reference page](https://docs.vanillaframework.io/base/details/).

What you see:

- The page is one of six in a “Base elements” category. I don’t know what a “base element” is, but after reading it, it seems implausible that this element is so important to Vanilla that it’s one of only six of them.

- ~~The page is headed “Code”, but doesn’t seem to have anything to do with code. (The example includes a `<code>` element, but that seems to be a coincidence.) This looks to be a copy-paste error.~~ _Duplicate of #2579._

- There’s no explanation of what the element is used for.

- “We apply” — who’s we?

- “some basic styling of the details element to align the summary” — From the example, it seems that it’s referring to the `<details>` and `<summary>` HTML elements, but this is surprising given it’s in the same category as “Reset” and “Typography” which are not HTML elements (and not, for that matter, “elements” at all). I shouldn’t need to read the example below to understand the first sentence. This would be clearer if it said “…to HTML’s `<details>` element to align its `<summary>…`.

- “to the baseline grid”. What baseline grid? This is not defined, linked, or immediately visible in the table of contents (it’s way down in the “Utilities” section).

- “If you want the rest of the content to align as well, use headings paragraphs after the summary.” What are “headings paragraphs”? They are not defined, linked, or present at all in the table of contents, and as far as I know, there’s no such HTML element.

- The example does not illustrate the described effect. The baseline grid is not shown anywhere, so I can’t see what is aligned with the grid and what isn’t.

## Pattern to amend

Details

**Comment by matthewpaulthomas** [comment]
> it seems that it’s referring to the `<details>` and `<summary>` HTML elements

FWIW, I mentioned this to a Web developer last night, and their response was, “…HTML has a `<details>` element??” As HTML elements go, it’s pretty obscure, which makes it more important to give context like I suggested.

**Comment by lyubomir-popov** [comment]
I propose taking this page down.

- Usage of the details element is exactly as per the spec, we've just aded some basic styling
- The information on it is hardly essential. It only says it is aligned to the baseline grid, which is true of any other element.
- @matthewpaulthomas has identified some larger issues with the information architecture. Ours seems to have copied Bootstrap's at some point, so lots of things like lists are on the typography page. This means that we have a category (base) which contains very disparate members: 

- Reset (which touches every html element)
- Typography (which houses most native html elements we apply styling to)
- A few elements that haven't ben crammed in typography

I would propose categorising things as:

- Core (Typography, Reset)
- Elements where styling is applied without the need for a class (not sure what the best name for these are, but maybe something along the lines of "native")
- Components which require a class

**Comment by matthewpaulthomas** [comment]
Categorisation generally probably belongs in a separate issue, especially if this page is discarded. But on that last point, I don’t think categorising elements by whether they require a class would help people find things, because we couldn’t expect people to guess whether they do. For example, “Lists” would presumably be categorised as requiring a class, because `<ul>` is styled differently from all the documented list varieties. But “Buttons” currently doesn’t require a class, because `<button>` is styled identically to `<button class="p-button--neutral">`. Whether “Buttons” ended up in the same category as “Lists” would depend on whether that `<button>` styling happens to be an undocumented feature or a bug, and we couldn’t expect users to guess which.

**Comment by lyubomir-popov** [comment]
@matthewpaulthomas are you ok to resolve this issue by removing the page? We can discuss categorisation separately.

**Comment by matthewpaulthomas** [comment]
@lyubomir-popov Sure. I guess the page exists because of the “If you want the rest of the content to align as well…” sentence? If that behaviour can’t/shouldn’t be made automatic, and that info is important to retain, one option would be to expand “Baseline grid” to describe the grid itself plus any other elements that require special handling.

**Comment by lyubomir-popov** [comment]
Well, we added a "feature", so documenting it seemed like the right thing to do. However, since the feature is something that applies to everything else, this is completely superfluous. I'll put a pr to remove this and open an IA one to continue the categorisation discussion.
