### ISSUE TITLE
img (responsive) styling ignores height from HTML

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#2588]
Base `img` styling to make images responsive (`max-width: 100%; height: auto`) makes images ignore `height` set in HTML.

Setting `height` in HTML is a well known practice to prevent repainting the page when images are loaded (and overall better experience), because space for an image will be already reserved.
Setting `height: auto` in CSS for all the images overrides any height set in HTML making setting image size in HTML pointless.

It became even more visible recently when we started to lazy load images on our sites, so at times images will only start loading when user scrolls to their position and when loading they will make the layout of the page 'jump' when images load into place.

### Expected

There doesn't seem to be an easy solution to this issue.

`height: auto` is needed on most of the images, because we want them to scale well in our fluid width grid. So it is quite reasonable to have this as a default.

The only problematic scenario is when images are loading (which of course ideally is very short).

It would be nice if there was a possibility of having an utility that would switch `height: auto` off, but because it already overridden the height from HTML, there is no easy way of saying in CSS to use the height defined in HTML. It seems that the only way to override `height: auto` would be to redefine height in HTML inline style `<img height="123" style="height: 123px" />`.

Also, there may be situations (like with banner in screenshot below) where we would like to have a height "fixed" during image loading, but remove it and have it responsive after image is loaded, so there would need to be some scripting involved to turn it on and off.

We currently start using our [image template tag](https://github.com/canonical-web-and-design/canonicalwebteam.image-template) across the project, so maybe, if there is no Vanilla/CSS solution for that, we would be able to improve the template tag to workaround the issue.
 

## Visual

Loading effect on snapcraft store page on slow connection - whole page is moved when banner is loaded.

![lazyload](https://user-images.githubusercontent.com/83575/67183646-49555b80-f3e2-11e9-82e6-731ac7c847ab.gif)

## Context

Similar issue reported in bootstrap: https://github.com/twbs/bootstrap/issues/1899
They fixed it by removing `max-width: 100%; height: auto` from `img` and moving it to dedicated `.img-responsive` class.

**Comment by matthewpaulthomas** [comment]
The Snap Store banner adds to Vanilla’s `{max-width: 100%; height: auto}` with its own `{width: 100%}`. The jumpiness in this case is is [scheduled to be fixed in Firefox 71, and in Chrome soon afterward](https://www.youtube.com/watch?v=4-d_SoCHeWE): when `{height: auto}` is present, browsers will resume using `width=` and `height=`, in this case not as pixel dimensions but for calculating the image’s aspect ratio. Then placeholder height = CSS-determined width ÷ HTML-determined aspect ratio.

I don’t know whether anything similar will happen for images with `width=` and `height=` but no `width:` property (effectively ignoring `height: auto` except in the max-width case), but you could download a Firefox nightly and see.

**Comment by barrymcgee** [comment]
@matthewpaulthomas beat me to it - I spotted Jen Simmon's tweet over the weekend. 

A (hacky) fix in the meantime might be to add the image height as an inline style via the image module which would override the Vanilla CSS style?

**Comment by bartaz** [comment]
Awesome, thanks @matthewpaulthomas @barrymcgee 

If this is coming to browsers soon(ish) I'm not sure if it's worth putting more work to workaround it in image template. We can add height via style, but that would not keep the aspect ratio (like browsers are about to do) and we would need to take it off after image is loaded (so that height and aspect ratio can be taken from the image data, not hardcoded in style). So it seems a bit like quite a complicated piece of work, for something that browsers soon will handle themselves.

**Comment by bartaz** [comment]
I'm closing this, as this doesn't need fix on Vanilla side.

I'll bring this up on next dev catch up, so we can decide there if there is any action needed.
