### ISSUE TITLE
Setting navigation items to the right of the navbar? 

### ISSUE THREAD

**Issue by flamendless** [canonical-web-and-design/vanilla-framework#2590]
It is unclear how to put the ul and li items to the right side of the navbar. It always stay in the side of the logo. Ive tried float, clear, and so on. Some doesn't do anything, some works but make it really ugly (like using p-card + float) 

Im following the source code of the main website of the vanilla framework as reference. 

_Sent from my HUAWEI GR5 2017 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by deadlight** [comment]
Thanks for reporting the issue @flamendless 

I think you can achieve the result that you're looking for using the markup in this [codepen](https://codepen.io/deadlight/pen/abbpNar). Essentially, two instances of the class `p-navigation__links` will be arranged to the left and right of the container.

We will extend the documentation to clarify this usage. Please let us know if you encounter any problems working with the pattern in this way and we'll try to fix any issues.

**Comment by flamendless** [comment]
Thank you. It is my first project in frontend and backend. I focus my interest and time with php as backend as I don't want to be in deep with frontend frameworks like vue, angular, and react. I just need a simple, beautiful, yet easy to implement styles. I find vanilla perfect for my needs. Thanks for the support.

**Comment by flamendless** [comment]
It works. Thank you.
