### ISSUE TITLE
How to use needed fonts for offline development.

### ISSUE THREAD

**Issue by flamendless** [canonical-web-and-design/vanilla-framework#2591]
Hi, ive noticed that the framework "downloads" fonts from the Ubuntu assets storage. Problem is, I do not have access to internet most of the time I am developing my project.

How would one download the fonts to my local storage and have the stylesheet refer to that saved fonts instead of always downloading from Ubuntu.

P.S, I always do force refresh (CTRL + F5) on my page for JS scripts to be reloaded. I think that causes the already downloaded/stored fonts to be fetched again.

**Comment by deadlight** [comment]
You have a few options here:

You can override the [font settings](https://docs.vanillaframework.io/settings/font-settings/) in your local scss files and change the fonts to ones available on your system.

Or you could override the [@fontface declarations](https://github.com/canonical-web-and-design/vanilla-framework/blob/master/scss/_base_fontfaces.scss) set by Vanilla in your local scss to point to a local copy of the Ubuntu font files (which will need to be served by your app).

**Comment by flamendless** [comment]
Hmmm. I was thinking for a solution that requires changing the style in either js script.

**Comment by flamendless** [comment]
@deadlight ive done the latter instruction and rebuilt the style.ss, however, it still shows the "Slow internet connection... Using fallback fonts localhost/assets/fonts/Ubuntu--..." which is where the fonts are. Ive updated both the "src and url" field in the base_fonts.scss. 

_Sent from my HUAWEI GR5 2017 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by flamendless** [comment]
Hmm it seems that I also need to fetch the other fonts (no names) for greek and cyrillic and etc.

**Comment by deadlight** [comment]
If `$font-use-subset-latin` is set to true then you shouldn't need the non-latin fonts

**Comment by flamendless** [comment]
I found out that the request to google webfonts was the lingering problem.
