### ISSUE TITLE
Slider requires Vanilla class, other form elements don’t

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/vanilla-framework#2602]
## Pattern to amend

[Slider](https://docs.vanillaframework.io/patterns/slider/)

## Visual

No change

## Context

Vanilla styles [most HTML form controls](https://docs.vanillaframework.io/base/forms/) without any `class=` necessary.

HTML’s slider `<input type="range">` is an exception: it requires `class="p-slider"`.

Lyubo writes: “The slider styling should probably be applied to it, this looks like an instance of overlooking on the part of whoever wrote that.”

**Comment by lyubomir-popov** [comment]
@deadlight do you know the history of this? Should we apply the styling to the native element, and deprecate the class?
