### ISSUE TITLE
No explanation of why “vertical dividers” are horizontal

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/vanilla-framework#2603]
With a browser window narrower than about 1350px:

1\. Visit whichever page describes the “Vertical divider”. (Currently this is [the Lists page](https://docs.vanillaframework.io/patterns/lists/#vertical-divider), though it’s not a list.)

What you see:

- This is a [“Horizontal divider”](https://docs.vanillaframework.io/patterns/lists/#horizontal-divider):

  ![image](https://user-images.githubusercontent.com/19801137/67569706-7cbc2100-f727-11e9-929a-7b164f42fe24.png)

- This is a [“Vertical divider”](https://docs.vanillaframework.io/patterns/lists/#vertical-divider):

  ![image](https://user-images.githubusercontent.com/19801137/67569776-ad9c5600-f727-11e9-940f-27f876f49c6b.png)

What’s wrong with this: They’re both horizontal.

After thinking about this for a few minutes, I wondered if the “vertical divider” might actually be vertical in a much larger window. Sure enough, it was.

What you should see:
- the page should explain that the behaviour differs by viewport width, and/or
- the example viewport should be wide enough to show the eponymous behaviour, and/or
- the example viewport should be resizable to let you see both behaviours.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Firefox
 - Version: 70.0

**Comment by lyubomir-popov** [comment]
In addition to the points mentioned above, I would suggest renaming the patterns (not the classes).

The names of the pages suggest these are related, while they are not. The class names are completely unrelated. One is a list with horizontal dividers, the other is a 3-section responsive layout.

**Comment by lyubomir-popov** [comment]
Also the p-divider markup does not use lists, so not sure why it is on the lists page to begin with.

**Comment by deadlight** [comment]
This is a misnaming that I hadn't previously noticed. It was intended to be "vertically *divided*".

**Comment by lyubomir-popov** [comment]
@deadlight given the division direction changes responsively, I think the "vertical~" part needs redefining.

**Comment by matthewpaulthomas** [comment]
@lyubomir-popov beat me to the punch: I was just about to say, the class is `divider__block`, and “Divider block” would be a perfectly reasonable name.

**Comment by deadlight** [comment]
Yeah, I'm not a fan of the name, even when correct. I think that the pattern would be much better if it described its use more than its look. It's a good candidate for renaming.
