### ISSUE TITLE
How to properly display image button dropdown menu in navigation

### ISSUE THREAD

**Issue by flamendless** [canonical-web-and-design/vanilla-framework#2606]
Displaying inline button doesnt style it correctly. 

If it is possible to use accordion but change the icon?

PS whats the update on the [menu button](https://docs.vanillaframework.io/patterns/menu-button/)

**Comment by kwm14** [comment]
> PS whats the update on the [menu button](https://docs.vanillaframework.io/patterns/menu-button/)

Hi @flamendless we will be releasing v2.5.0 and the end of this week, a new feature in this release is our new `menu-button` component. So you'll be able to add into your project 👍
