### ISSUE TITLE
Add table cell content truncation

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/vanilla-framework#2625]
## Pattern to amend
Table

## Visual
![Screenshot from 2019-11-07 07-43-33](https://user-images.githubusercontent.com/1413534/68369557-8768b400-0132-11ea-8947-f4a0dedac7fa.png)

## Context
It's a common request to truncate content of a table cell and for bonus points, it would be nice to find a way to display a tooltip with the content when hovering.

Example: https://github.com/canonical-web-and-design/jaas-dashboard/pull/186

**Comment by lyubomir-popov** [comment]
About the tooltip part, hows should this differ from the current tooltip example? If it should use the actual tooltip, then maybe mentioning that in the .md file would suffice?
