### ISSUE TITLE
Use image/icon instead of text in contextual-menu in header navigation

### ISSUE THREAD

**Issue by flamendless** [canonical-web-and-design/vanilla-framework#2627]
The `menu` page in the docs is still not updated. Im looking for a way to properly put icon/image instead of text in header navigation button or menu. Just like in github, the Profile with dropdown.

**Comment by kwm14** [comment]
> The `menu` page in the docs is still not updated. 

Hi @flamendless as mentioned in your previous [issue](https://github.com/canonical-web-and-design/vanilla-framework/issues/2606#issuecomment-562056098) this will be landing in our forthcoming release v2.5.0

> I'm looking for a way to properly put icon/image instead of text in the header navigation button or menu. Just like in GitHub, the Profile with dropdown.

You will be able to do this also in our next release v2.5.0, we've added a new variant to our existing contextual menu. Which will enable you to change icons and button classes to suit your needs, please see a visual reference below of what's coming 💯 

![61457843-18880500-a961-11e9-9054-a94062c99d4c (2)](https://user-images.githubusercontent.com/17748020/70224961-0c50e880-1746-11ea-9fb7-63d6e339d1de.png)

**Comment by flamendless** [comment]
Awesome. Is there any way to get notifications from the framework releases? Like some rss feed?

**Comment by kwm14** [comment]
> Awesome. Is there any way to get notifications from the framework releases? Like some RSS feed?

Definitely. If you visit https://vanillaframework.io/ and scroll to the bottom of the page, you will see a 'Subscribe to Vanilla updates'

If you sign up you will receive newsletters every release which contains new features, documentation updates, and general bug fixes and code maintenance 👍
