### ISSUE TITLE
Should tables have a bottom border?

### ISSUE THREAD

**Issue by barrymcgee** [canonical-web-and-design/vanilla-framework#2628]
## Pattern to amend

Table

## Visual

<img width="988" alt="Screenshot 2019-11-07 at 14 33 50" src="https://user-images.githubusercontent.com/505570/68397800-a6376c80-016b-11ea-964f-4b939fb10493.png">

## Context

The last row of tables in Vanilla do not have a bottom border. However, in JAAS Dashboard, where multiple tables follow each other, @spencerbygraves has added a bottom border.

<img width="780" alt="Screenshot 2019-11-07 at 14 35 48" src="https://user-images.githubusercontent.com/505570/68397987-f282ac80-016b-11ea-8840-65a682d933c8.png">
<img width="706" alt="Screenshot 2019-11-07 at 14 35 42" src="https://user-images.githubusercontent.com/505570/68397988-f31b4300-016b-11ea-85e5-a667cc77b126.png">

Should all tables have a bottom border?

**Comment by kwm14** [comment]
@barrymcgee [tables](https://docs.vanillaframework.io/base/tables/) shouldn't have a bottom border on the last cell.

In this case, the design is incorrect, unless this is the desired design decision? @spencerbygraves 

MAAS has many tables and they don't have bottom-border on the last cell of tables...

![Unattended+server+discovery](https://user-images.githubusercontent.com/17748020/68398650-fbc04900-016c-11ea-9aa5-5a1d2db9319c.png)

**Comment by spencerbygraves** [comment]
@barrymcgee @kwm14 looks like a mistake on my part, sorry! No bottom border on tables.

**Comment by kwm14** [comment]
@spencerbygraves no worries. Question solved 👍
