### ISSUE TITLE
Table sortable docs don't sort

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/vanilla-framework#2635]
**Describe the bug**
The docs for sorting a table (https://docs.vanillaframework.io/base/tables/#sortable) no longer work as the `<th>` elements need `role="columnheader"` which was removed.

**To Reproduce**
1. Go to https://docs.vanillaframework.io/base/tables/#sortable (scroll to the "Sortable" example).
2. Click on one of the headers(status/cores etc.).
3. Notice that no sorting happens.

**Expected behavior**
The headers should have hover states and sort when clicked.

**Comment by lyubomir-popov** [comment]
Added the role attribute in https://github.com/canonical-web-and-design/vanilla-framework/pull/2640,

but the js still doesn't work.
