### ISSUE TITLE
No class to style a button as a link

### ISSUE THREAD

**Issue by steverydz** [canonical-web-and-design/vanilla-framework#2642]
Currently there is no pattern to style a button as a link. There is the [base button class](https://docs.vanillaframework.io/patterns/buttons/#base) which is good in many cases but sometimes the button needs to look and behave exactly like a link.

## Visual
![Screenshot from 2019-11-13 09-46-56](https://user-images.githubusercontent.com/501889/68752367-1b3af400-05fb-11ea-918c-574817709587.png)

## Context
In MAAS we are currently using a custom style to override the inherited button styles. This is also used in RBAC:

```
.p-button--link {
  @extend %p-button--base;

  border: 0;
  color: $color-link;
  line-height: 1.25rem;
  margin-bottom: 0;
  padding: 0;
  pointer-events: all;
  text-align: left;

  &:hover {
    background-color: inherit;
    text-decoration: underline;
  }

  &:visited {
    color: $color-link;
  }

  // Override inherited button style from Vanilla
  &:active {
    background-color: inherit !important;
  }
}
```

## State
![Screenshot from 2019-11-13 09-47-40](https://user-images.githubusercontent.com/501889/68752338-0eb69b80-05fb-11ea-8fde-08f3577019f4.png)

![Screenshot from 2019-11-13 09-47-22](https://user-images.githubusercontent.com/501889/68752357-170ed680-05fb-11ea-8409-c3fcb6234559.png)

**Comment by spencerbygraves** [comment]
WG: approved, group agreed we need this as we currently do it the other way around.
