### ISSUE TITLE
Horizontal+Vertical stepped lists: Indent contents

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/vanilla-framework#2649]
## Pattern to amend

- [Vertical stepped list](https://docs.vanillaframework.io/patterns/lists/#vertical-stepped)
- [Horizontal stepped list](https://docs.vanillaframework.io/patterns/lists/#horizontal-stepped)

## Visual

Before|After
-|-
![image](https://user-images.githubusercontent.com/19801137/68850397-e054c100-06cb-11ea-911a-58065f3ede6a.png)|![image](https://user-images.githubusercontent.com/19801137/68850285-a4b9f700-06cb-11ea-9245-5d3f6fc6a516.png)

## Context

This change would:
- make it easier to see when a list has finished
- make the list visually calmer (one left edge for all text, rather than two)
- improve consistency, since [ordered](https://docs.vanillaframework.io/base/typography/#ordered-list), [unordered](https://docs.vanillaframework.io/base/typography/#unordered-list), [ticked](https://docs.vanillaframework.io/patterns/lists/#ticked), [ticked with horizontal divider](https://docs.vanillaframework.io/patterns/lists/#ticked-with-horizontal-divider), and [split](https://docs.vanillaframework.io/patterns/lists/#split) lists all indent subsequent lines as proposed here.

**Comment by lyubomir-popov** [comment]
Couldn't agree more. @kwm14 does this require discussion? Or can we just update it?

**Comment by kwm14** [comment]
@lyubomir-popov no discussion required, we can go ahead and make this update next iteration 👍
