### ISSUE TITLE
Can’t find explanation of <hr class="p-separator">

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/vanilla-framework#2655]
1\. Encounter `<hr class="p-separator">` on a Vanilla site.
2\. Go to [docs.vanillaframework.io](https://docs.vanillaframework.io/).
3\. Try to find any reference to this component.

What happens:
- The search field doesn’t return any results for “hr”, or “rule”, or “p-separator”, or “separator”. (If any of these are mentioned _inside_ some page, this is an example of #1655.)
- There’s no mention of `p-separator` in [“Spacing”](https://docs.vanillaframework.io/settings/spacing-settings/).
- The navigation sidebar doesn’t list any other page that would obviously cover it.

What should happen:
- there’s a page for “Horizontal rules” or “Separators”, or
- horizontal rules are described as a spacing technique in “Spacing”.

[Encountered while trying to debug [charmed-osm.com#11](https://github.com/canonical-web-and-design/charmed-osm.com/issues/11).]

**Comment by lyubomir-popov** [comment]
`.p-separator` is a local style on the site you pointed to. I've added comments on the pr suggesting alternatives that would achieve the same.

Vanilla provides 3 ways to achieve the same effect:
1) p-strip + bordered row:
https://docs.vanillaframework.io/examples/patterns/grid/bordered/

2) bordered strip:
https://docs.vanillaframework.io/examples/patterns/strips/is-bordered/

3) .p-strip>hr.u-no-margin--bottom (this will be off by 1px, if that matters)

I suggest either closing this, or converting it to a WG proposal, in case the above 3 alternatives are not satisfactory.

**Comment by matthewpaulthomas** [comment]
Ahhhh sorry. From the `p-` I assumed it was Vanilla.
