### ISSUE TITLE
Investigate file size and see if reductions can be made.

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#2657]
The file size has surpassed the parker.js limit of 200kb. Currently, small prs are hitting that limit. 
The question is, did something that land recently create an unreasonable amount of output? Or did the framework organically grow with the addition of new features etc.

**Comment by lyubomir-popov** [comment]
@kwm14  @Caleb-Ellis The following two commits have increased the file size limit from 182 to 200:

## 11kb 
commit 137a118095120821900751f49121a49fd96c3770
--
Merge: b55fb855 6e699262
Author: Karl Waghorn-Moyce <karl.waghorn-moyce@canonical.com>
Date:  Thu Nov 14 15:15:24 2019 +0000
 
Merge pull request #2641 from canonical-web-and-design/update-social-icons-to-official
Update social icon library


---------------
## 4kb
commit b55fb855900a17fb0aa5bda7c8d60e8acc876f2b
--
Merge: 5b0e7540 bf922b35
Author: Karl Waghorn-Moyce <karl.waghorn-moyce@canonical.com>
Date:  Tue Nov 12 16:58:30 2019 +0000
 
Merge pull request #2639 from canonical-web-and-design/add-new-rss-share-icon
Add new social RSS icon


Is the rss icon optimised? If yes, is the icon worth the file size increase?

**Comment by lyubomir-popov** [comment]
@Caleb-Ellis is there a test we can embed - e.g. husky or something similar  in the CI - which watches the difference between a file's size before / after a commit? It would make it much easier to resolve this before it gets merged.

**Comment by kwm14** [comment]
@lyubomir-popov I will look at the RSS and LinkedIn icon to see if I can reduce the icon size and put up a new PR, and hopefully, this will fix breaking the threshold (for now) 👍

**Comment by lyubomir-popov** [comment]
👍 Once the size is down, we can also reset the parker limit to 200kb. let me know if you need help.

**Comment by lyubomir-popov** [comment]
Made an [issue](https://github.com/canonical-web-and-design/vanilla-framework/issues/2658) to investigate a better way to detect when something large is being added.
