### ISSUE TITLE
Border bottom does not appear on <tr> when table is empty

### ISSUE THREAD

**Issue by barrymcgee** [canonical-web-and-design/vanilla-framework#2662]
**Describe the bug**

Border bottom does not appear on `<thead ><tr>` when the table is empty.

**To Reproduce**

When a table with data is displayed, a bottom border appears on the table head row: https://codepen.io/barrymcgee/pen/wvvNPPQ

However, when no table content is loaded, the border doesn't display: https://codepen.io/barrymcgee/pen/Vwwgrjb

**Expected behavior**

The bottom border would appear irrespective of `<tbody>` content.

**Comment by lyubomir-popov** [comment]
Can't find any information about this strange behaviour, but there is a simple fix:

```
thead::after {
  content: '';
}
```
https://codepen.io/lyubomir-popov/pen/OJJqaYo

Would that be too hacky @anthonydillon ?
