### ISSUE TITLE
Tooltips cannot be used with React Portals

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical-web-and-design/vanilla-framework#2672]
**Describe the bug**
With [React Portals](https://reactjs.org/docs/portals.html), DOM elements are injected inside `<body>` in the DOM, which is helpful for side-stepping z-index and overflow issues. So in practice, you hover over an element that is deep in the DOM, and then JS places the tooltip message it at the top. However the current Vanilla implementation relies on the hovered element being the direct parent of the tooltip message.

**Expected behavior**
Tooltips that can work without needing the message to be a direct child of the wrapper.

**Additional context**
This has been solved in MAAS with the following additional class:
``` scss
.p-tooltip__message--portal {
  display: inline;
}
```

All this does is override the default `display: none` since its display is determined with JS (React).
PR: https://github.com/canonical-web-and-design/maas-ui/pull/505

**Comment by lyubomir-popov** [comment]
It would require a variant or new component that doesn't hide using css, so it can be handled separately with js.

**Comment by bartaz** [comment]
After canonical-web-and-design/vanilla-squad#1000 verify how much work in needed
