### ISSUE TITLE
Build application sidebar navigation

### ISSUE THREAD

**Issue by kwm14** [canonical-web-and-design/vanilla-framework#2676]

**Comment by anthonydillon** [comment]
@bartek has this been done? Strange to have an empty epic with an estimate.

**Comment by bartaz** [comment]
@anthonydillon  I think this is an old epic prepared by Karlos when preplanning this cycle.

And (if we treat as side navigation for application layout - like JAAS dashboard) we haven't done it, because we don't have application layout.

**Comment by bartaz** [comment]
I guess we should remove it from the master epic for this cycle.

**Comment by lyubomir-popov** [comment]
This is completed - example here - https://vanillaframework.io/docs/examples/patterns/side-navigation/dark

**Comment by lyubomir-popov** [comment]
Some design decisions still need to be made - expand/collapse handled by layout vs component, whart happens to a collapsed one without icons, etc.

**Comment by bartaz** [comment]
To be worked on as part of Side navigation enhancements in 21.04: https://docs.google.com/document/d/1fRUVOi_9Pk-YQBgw5sWewbgV5PidjyUUNIyzLeZo950/edit#
