### ISSUE TITLE
Document sidebar navigation + spec

### ISSUE THREAD

**Issue by kwm14** [canonical-web-and-design/vanilla-framework#2677]

**Comment by bartaz** [comment]
@spencerbygraves  @lyubomir-popov 
Couple of questions after having a look at the designs on Zeplin:

1. Is the right side border part of the side navigation component, or should it be provided by page layout or other means?

I suppose if we always want the border, it will be best to provide it with sidebar nav styles.

2. Does sidebar nav define it's own width or should it adapt to the width of where it's placed in the layout?

We don't have layout classes in Vanilla yet. So we would need to propose how to use this. My initial guess it that it should be put inside the existing grid? So for example in existing 12 column grid 3 or 4 columns would be for sidebar, rest for the content?

3. How should it behave when labels of navigation items would be too long to fit in one line. Wrap? Truncate? How right side icons should behave in such case?

4. How should it look on small screens?

Following my assumption from 2) that we put it into grid, what would be the grid layout to use on small and medium screens?

5. Are we currently only providing light/white version? We plan to have dark (JAAS) theme later?

6. The group "headings" (like: **Fruit**, **Animals** in the examples) - are they links as well? Can they be links, or are they always just a text. Do we allow having a group of links without a heading?

**Comment by lyubomir-popov** [comment]
Sorry to be replying before @spencerbygraves , but since the questions are mostly technical, thought I might answer the technical aspects:

> 1. Is the right side border part of the side navigation component, or should it be provided by page layout or other means?

I'd say it depends. If you look at the juju side nav, that border isn't there.

> 2. Does sidebar nav define it's own width or should it adapt to the width of where it's placed in the layout?

I think that depends too. In my mind, the most flexible way to do this would be have width as a mixin arg with a default value (say auto) so by default this spans the full width of a parent container (e.g. a .col-* class), but you should be able to set the arg to say 12rem for a left-nav example as juju, where it sits outside the grid.

> 3. How should it behave when labels of navigation items would be too long to fit in one line. Wrap? Truncate? How right side icons should behave in such case?

Wrap by default, option to truncate the text element (which is a child of the __item element, and a sibling to any icons)

> 4. How should it look on small screens? 
Shouldn't this be left to the layout to handle? Unless an explicit width has been provided, fill the parent's width at all breakpoints.

> 5. Are we currently only providing light/white version? We plan to have dark (JAAS) theme later?

Depends on what we agree to in the Frankfurt session on themes. Either way, the default white theme should follow the theming architecture, so no refactor is necessary when (if) additional themes are added later.

> 6. The group "headings" (like: Fruit, Animals in the examples) - are they links as well? Can they be links, or are they always just a text. Do we allow having a group of links without a heading?

Both options should be supported, when not links it would only be possible to tell when you hover. Not sure if that's a UX concern.

**Comment by spencerbygraves** [comment]
@bartaz thanks for the questions. I agree with @lyubomir-popov's points, but just to confirm...

>Is the right side border part of the side navigation component, or should it be provided by page layout or other means?

The border is optional. We may need it on docs but we don't use it on the Jaas dashboard. Perhaps I should remove it from the design.

>How should it behave when labels of navigation items would be too long to fit in one line. Wrap? Truncate? How right side icons should behave in such case?

I think it should wrap, and get some UX guidance on where to truncate if the text is very long. I'll add some wrapping text to the design to show its relation to an icon.

>The group "headings" (like: Fruit, Animals in the examples) - are they links as well? Can they be links, or are they always just a text. Do we allow having a group of links without a heading?

Yes, they can be links as on some of the current docs sites. And yes, we should allow groups of links without headings, as on the Jaas dashboard example.

**Comment by anthonydillon** [comment]
On Tue, Feb 25, 2020 at 9:47 AM Bartek Szopka <notifications@github.com>
wrote:

> @spencerbygraves <https://github.com/spencerbygraves> @lyubomir-popov
> <https://github.com/lyubomir-popov>
> Couple of questions after having a look at the designs on Zeplin:
>
>    1. Is the right side border part of the side navigation component, or
>    should it be provided by page layout or other means?
>
> Yes, all styling should come from the component as the layout should only
contain css grid styles.

>
>
> I suppose if we always want the border, it will be best to provide it with
> sidebar nav styles.
>
>    1. Does sidebar nav define it's own width or should it adapt to the
>    width of where it's placed in the layout?
>
> The width should be completely inherited from the top-level layout layer.
Therefore, the sidebar pattern should fill the width of its parent without
limitations.

>
>
> We don't have layout classes in Vanilla yet. So we would need to propose
> how to use this. My initial guess it that it should be put inside the
> existing grid? So for example in existing 12 column grid 3 or 4 columns
> would be for sidebar, rest for the content?
>
I would like the layout to be above the grid. Which, allows areas of the
layout to initiate its own internal grid via ".row"

>
>    1.
>
>    How should it behave when labels of navigation items would be too long
>    to fit in one line. Wrap? Truncate? How right side icons should behave in
>    such case?
>
> It should either wrap or truncate (UX decision) but should only provide
one for the best experience across the sites and apps.

>
>    1.
>
>    How should it look on small screens?
>
> I would like to suggest to acts as an off-screen menu but there should be
a design spec for this before development begins.

> Following my assumption from 2) that we put it into grid, what would be
> the grid layout to use on small and medium screens?
>
>    1.
>
>    Are we currently only providing light/white version? We plan to have
>    dark (JAAS) theme later?
>
> Let's start with the light version as its easy to override locally.

>
>    1.
>
>    The group "headings" (like: *Fruit*, *Animals* in the examples) - are
>    they links as well? Can they be links, or are they always just a text. Do
>    we allow having a group of links without a heading?
>
> We need one method that we want to use across everything and settle on a
method of navigation.

**Comment by spencerbygraves** [comment]
@bartaz I've added some details [here](https://github.com/canonical-web-and-design/design-vanilla-framework/tree/master/Sidebar%20navigation).Let me know if I've missed anything.

Thanks.

**Comment by spencerbygraves** [comment]
@bartaz I've added some details [here](https://github.com/canonical-web-and-design/design-vanilla-framework/tree/master/Sidebar%20navigation).Let me know if I've missed anything.

Thanks.

**Comment by bartaz** [comment]
@spencerbygraves Looks good, thanks.

I don't think I need anything more at the moment. I guess there still may be some things to clarify when we start building and interacting with the thing.
