### ISSUE TITLE
Baseline grid background on examples

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#2699]
Examples seem to have the red baseline grid in the background.
It looks strange and confusing in docs.
It shows up when elements are closed/collapsed.
<img width="1603" alt="Screenshot 2019-12-09 at 12 15 10" src="https://user-images.githubusercontent.com/83575/70431868-3ffd7c80-1a7e-11ea-8669-4f5e33501e8f.png">

It flashes when examples are first rendered.

![example-lines](https://user-images.githubusercontent.com/83575/70431875-468bf400-1a7e-11ea-9568-60f8f4b46c09.gif)

**Expected behavior**
There should be no baseline grid in the background (unless it's turned on when needed with baseline utility).

Or it should be always visible consistently, so it's understood that it's there and what is the purpose of it.

**Comment by kwm14** [comment]
@anthonydillon raised a similar issue for the baseline [toggle](https://github.com/canonical-web-and-design/vanilla-framework/issues/2668) to removed too.

**Comment by lyubomir-popov** [comment]
@bartaz the baseline grid was meant for the raw example pages. There should be a way to make it not appear in the documentation, as we did with the baseline toggle.

**Comment by lyubomir-popov** [comment]
No longer an issue with codepen, closing
