### ISSUE TITLE
Add docs search backend endpoint

### ISSUE THREAD

**Issue by kwm14** [canonical-web-and-design/vanilla-framework#2720]

**Comment by matthewpaulthomas** [comment]
It’s hard to tell without a description, but depending on the scope, this looks like a duplicate of either #1607 or #1655.

**Comment by bartaz** [comment]
@matthewpaulthomas Yes, we are using #1607 #1655 https://github.com/canonical-web-and-design/vanillaframework.io/issues/181 as a base to explore possible improvement for search and implement them here.
