### ISSUE TITLE
External link icon displays incorrectly in safari

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#2728]
**Describe the bug**

**To Reproduce**
1. Go to a page containing an external link
2. See issue:
![image](https://user-images.githubusercontent.com/2741678/72141008-e2fd2b00-3389-11ea-945b-313dfdd43fb9.png)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Safari
 - Latest

**Comment by Saviq** [comment]
A version of this also affects Edge on Windows 10 1909:
![image](https://user-images.githubusercontent.com/231077/74945511-2c647f80-53f8-11ea-86dd-1430d3004a6a.png)

**Comment by bartaz** [comment]
@Saviq Which version of Edge is it?

**Comment by solazio** [comment]
This still happens in iOS 13.3.1 & 13.4.1 - Safari & Catalina - Safari 13.

![image](https://user-images.githubusercontent.com/40214246/80370959-02f92180-8889-11ea-975d-1ff4909a731f.png)

![image](https://user-images.githubusercontent.com/40214246/80371082-38057400-8889-11ea-8252-9acbbb395156.png)

**Comment by bartaz** [comment]
@solazio Does it happen for you on latest Vanilla?
https://vanillaframework.io/docs/examples/patterns/links/links-external

Snapcraft seems to be using 2.5.0 Vanilla. We are on 2.10 already. 
https://github.com/canonical-web-and-design/snapcraft.io/blob/master/package.json#L96

**Comment by solazio** [comment]
@bartaz you are right. It doesn't happen on vanilla 2.10 and snapcraft.io needs an update...closing
