### ISSUE TITLE
Add centered modifier for the pagination pattern

### ISSUE THREAD

**Issue by steverydz** [canonical-web-and-design/vanilla-framework#2729]
## Pattern to amend

[Pagination](https://docs.vanillaframework.io/patterns/pagination/)

## Visual

![blog_pagination_screenshot](https://user-images.githubusercontent.com/501889/72148025-bc45f100-3397-11ea-82ee-81d1c7fb6b12.png)

## Context

ubuntu.com will be using the pagination pattern for /blog and /tutorials. These templates will be using a centered variant of this pattern.

[Pull request that introduces this](https://github.com/canonical-web-and-design/ubuntu.com/pull/6343)

This can be achieved by adding `justify-content: center;` to a `--centered` modifier.

**Comment by bartaz** [comment]
Doesn't `u-align--center` work in your case? We used it on pagination in snapcraft.io/blog

**Comment by steverydz** [comment]
@bartaz you're right it does. I swear I tried that - nevermind - I'll close this
