### ISSUE TITLE
Subnav background colour is darker than the nav bg colour

### ISSUE THREAD

**Issue by solazio** [canonical-web-and-design/vanilla-framework#2752]
## Pattern to amend

p-subnav

## Visual

Provide a screenshot or link to a prototype of your pattern amendment.
![image](https://user-images.githubusercontent.com/40214246/72623226-a490de80-393c-11ea-8dc3-12bdf4e65360.png)

## Context

When the navigation theme is set to dark, the subnav background colour is slightly darker.

**Comment by bartaz** [comment]
Confirmed it happens with navigation dark theme in plain vanilla as well:
<img width="263" alt="Screenshot 2020-01-20 at 08 35 59" src="https://user-images.githubusercontent.com/83575/72707163-1d23b500-3b60-11ea-821f-b5f0e899de3e.png">


@lyubomir-popov It this expected and design choice to have subnav darker than main nav background?

**Comment by lyubomir-popov** [comment]
No, it is not. It should match the rest of the nav.
