### ISSUE TITLE
Subnav items are indented to the right - we should have the option to remove the indentation

### ISSUE THREAD

**Issue by solazio** [canonical-web-and-design/vanilla-framework#2753]
## Pattern to amend
p-subnav

## Visual

Provide a screenshot or link to a prototype of your pattern amendment.
![image](https://user-images.githubusercontent.com/40214246/72623683-837cbd80-393d-11ea-84a7-adfb113b175e.png)

## Context

Open the subnav on small screens and notice the items are indented. We should have the option of removing that indentation.

**Comment by bartaz** [comment]
This is somehow related to #2752 (at least in terms of darker background).

@lyubomir-popov Is this how subnav was expected to look on small screens or should we improve it?
(note that blue visited color link is a separate bug that is already fixed)

**Comment by lyubomir-popov** [comment]
@bartaz The design spec only includes a desktop version:
![image](https://user-images.githubusercontent.com/2741678/72714240-4e06e880-3b66-11ea-8428-6f0650b94800.png)

My proposal for the mobile version:
![Subnav](https://user-images.githubusercontent.com/2741678/72718070-1f404080-3b6d-11ea-9fe7-5e5701d426db.png)

When something is tapped:
![Subnav pressed subitem](https://user-images.githubusercontent.com/2741678/72718069-1f404080-3b6d-11ea-957f-2c998a7c97f2.png)

The proposal eliminates the indent of subitems. I think it is clear enough without it:
- the top item has a chevron
- the lack of borders between subitems implies they are more related to each other than they are to the siblings of its parent

@spencerbygraves does this sound ok?

**Comment by spencerbygraves** [comment]
@lyubomir-popov yes, that looks fine. Thanks.

**Comment by lyubomir-popov** [comment]
Thanks, I've added the mockup to the spec: 

https://github.com/canonical-web-and-design/design-vanilla-framework/blob/master/Navigation/sub-navigation--mobile-dark.png
