### ISSUE TITLE
Consider removing borders from subnav dropdown

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#2765]
## Pattern to amend

Sub navigation

## Context

@lyubomir-popov commented on a PR with subnav fixes suggesting that we don't need these borders:
https://github.com/canonical-web-and-design/vanilla-framework/pull/2761#issuecomment-576596009

This will simplify the look and allow to remove some code that adds these borders, hides them on mobile, etc.

## Visual

Current:

<img width="238" alt="Screenshot 2020-01-21 at 10 39 38" src="https://user-images.githubusercontent.com/83575/72817679-7972fb80-3c6a-11ea-89ba-be7d46dd1441.png">

Without border:

<img width="329" alt="Screenshot 2020-01-21 at 10 41 03" src="https://user-images.githubusercontent.com/83575/72817696-80017300-3c6a-11ea-8050-b38e7ec1eea8.png">

Provide a screenshot or link to a prototype of your pattern amendment.

**Comment by lyubomir-popov** [comment]
I've made some preliminary exploration, but we should put this on hold until we finish the sidebar design work, as the two need to be aligned. The contextual menu too, potentially.

Here's where I got to, key issues to think about:
- styling should be similar between mobile and desktop versions, e.g. if we introduce a background for the subnav,s that should happen in bot hplaces
- we have places where, depending on the solution, a background might extend beyond the width of the dividers - which is a bit awkward, so something to consider
- drop shadow is a necessity in all desktop cases, as we don't know what is going to be underneath
[
![Border alternative Copy 2](https://user-images.githubusercontent.com/2741678/72891145-7b40cb80-3d0b-11ea-8197-e98eb408606f.png)
![Border alternative Copy](https://user-images.githubusercontent.com/2741678/72891146-7b40cb80-3d0b-11ea-9cb3-45506cd06b80.png)

](url)

**Comment by spencerbygraves** [comment]
WG: agreed to work on this as part of the side nav project.

**Comment by bartaz** [comment]
@spencerbygraves @lyubomir-popov 

Seems we decided this should be a part of sidebar nav project. Not sure how does it fit into designs you are creating now? Can the navigation dropdowns be considered there as well (to have consistent styling with side nav)?

**Comment by bartaz** [comment]
Sidebar nav started, let's wait until we implement it.

**Comment by spencerbygraves** [comment]
@bartaz this was waiting for the sidebar designs to see if it can share styling. I think we can remove it from the sidebar epic and @lyubomir-popov can work on the designs again.
