### ISSUE TITLE
Navigation items animate on page load

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#2770]
**Describe the bug**
There seems to be a weird behaving animation in docs navigation (probably affects Vanilla p-navigation) when page loads.

As reported by @squidsoup in https://github.com/canonical-web-and-design/vanilla-framework/pull/2769#issuecomment-577580248

**To Reproduce**
1. Go to docs.vanillaframework.io
2. Click on links in the sidebar to navigate to different pages
3. See navigation items 'slide in'

It doesn't happen always, it's hard to determine what triggers the animation

![](https://s5.gifyu.com/images/2020-01-23-10.30.50.gif)

**Comment by bartaz** [comment]
@lyubomir-popov Does the animation look intentional? 

There seems to be:
```scss
      & > a {
        @include vf-animation;
        // ....
     }
```

Which adds transition to ALL properties on navigation links. What was supposed to be animated? Shouldn't it be color of the link only?

**Comment by lyubomir-popov** [comment]
only the change of background colour
