### ISSUE TITLE
Social icons background/foreground colours not changing

### ISSUE THREAD

**Issue by solazio** [canonical-web-and-design/vanilla-framework#2771]
**Describe the bug**
Social icons background/foreground colours not changing when using `$color-social-icon-foreground` or `$color-social-icon-background`.

**Expected behavior**
Should change colours when the variables are changed.

**Screenshots**
![image](https://user-images.githubusercontent.com/40214246/72981228-3765c900-3dd4-11ea-9be5-ee3d9f10b97f.png)

They [were removed](https://github.com/canonical-web-and-design/vanilla-framework/commit/ae6c3243598948cdb1f06015b1463721657fc012#diff-bf412830d8ed6226e7af95d4fb65d56a) when the icons were changed.

**Comment by bartaz** [comment]
Seems like new social icons come with colours specific to given brand and cannot be changed.

The variables used previously for changing social icons were removed:
https://github.com/canonical-web-and-design/vanilla-framework/pull/2641

@solazio Is there something wrong with icons themselves that you want to change the colors?

**Comment by solazio** [comment]
@bartaz nothing wrong with the icons. Was just thinking to change them to use the old colours. If these colours are "design approved", i'm more than happy to keep them as they are.

**Comment by lyubomir-popov** [comment]
I am not aware of any decisions to move from tinted grey icons to coloured ones. @spencerbygraves or @deadlight do you remember any conversations around that when Karlos replaced the old icons with the new svg files a few months ago? 

Or is it just a regression that hasn't been noticed before?

In any case a lot of sites still used tinted icons, like ubuntu.com:
![image](https://user-images.githubusercontent.com/2741678/72984501-bf9b9c80-3ddb-11ea-912d-c3a6d8afd5f5.png)

If we change them to coloured then that should probably be done everywhere.

**Comment by spencerbygraves** [comment]
@solazio @lyubomir-popov yes, this was agreed in a design review.

https://github.com/canonical-web-and-design/vanilla-framework/issues/2575

https://github.com/canonical-web-and-design/vanilla-squad/issues/712

**Comment by bartaz** [comment]
ubuntu.com (even being on 2.5.0) seems to be using inline SVG icons instead of built-in Vanilla ones.
