### ISSUE TITLE
<dl> tag behaves like an <li> rather than an <ul> and has no margin at the bottom

### ISSUE THREAD

**Issue by solazio** [canonical-web-and-design/vanilla-framework#2791]
**Describe the bug**
[`<dl>` tag behaves like an `<li>`](https://github.com/canonical-web-and-design/vanilla-framework/blob/2f2b83c1c7bfab2f79211c1ffd73fed4adfa123e/scss/_base_lists.scss#L29) rather than an `<ul>` and has no margin at the bottom

**To Reproduce**
1. Go to 'https://snapcraft.io/vlc'
2. See there is no gap between "Last updated" date and "Companion apps"

**Expected behavior**
perhaps there should be some margin added to the end of the <dl>

**Screenshots**
![image](https://user-images.githubusercontent.com/40214246/73355032-10edd500-428f-11ea-893a-d3785591dd10.png)

**Comment by bartaz** [comment]
@lyubomir-popov Is this intended for `<dl>` to have no bottom margin?

**Comment by lyubomir-popov** [comment]
@bartaz No, this is a bug. The dl selector should apply the samew rules as ol and ul, apart from the bits inside the nav - which should probably be removed and applied on a class instead of tags anyway.
