### ISSUE TITLE
Modal title doesn't look great on large modals

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/vanilla-framework#2801]
## Pattern to amend

Modal

## Visual

<img width="1680" alt="Screen Shot 2020-01-30 at 3 05 33 PM" src="https://user-images.githubusercontent.com/532033/73491719-da8a8580-4374-11ea-808c-3a38348e0c35.png">

## Context

I don't have any suggestions for an improvement here but maybe providing a couple header style options would help.

**Comment by bartaz** [comment]
@spencerbygraves to review the design

**Comment by spencerbygraves** [comment]
We could add a hr under the title:

![image](https://user-images.githubusercontent.com/9105999/76237033-81402c80-6225-11ea-978a-50e67272e36d.png)

**Comment by spencerbygraves** [comment]
@bartaz @lyubomir-popov design for this is done.
