### ISSUE TITLE
List pattern placeholders cannot be included without all list patterns

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#2808]
**Describe the bug**
The placeholders here are inside the @mixin vf-p-lists:
https://github.com/canonical-web-and-design/vanilla-framework/blob/64fe763f601f2f3702b84749d84804a15024e629/scss/_patterns_lists.scss#L267

In order to extend say  %vf-list from maas for example, you need to include the entire mixin, which includes all [list patterns](https://github.com/canonical-web-and-design/vanilla-framework/blob/64fe763f601f2f3702b84749d84804a15024e629/scss/_patterns_lists.scss#L314)

**Expected behavior**
The placeholders should be in a separate mixin that doesn't output anything, so they can be included cleanly.

**Comment by anthonydillon** [comment]
This issue is still valid. This will cause an issue when importing a particular list. For example, `import "vf-p-list-divided"`.
