### ISSUE TITLE
Allow option to only change input opacity when disabled.

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical-web-and-design/vanilla-framework#2813]
In MAAS there are cases where we want to disable a checkbox, but keep the label opacity at 1. In the screenshot below, the label is actually a link which is functional even if the checkbox is disabled:

![screenshot_15](https://user-images.githubusercontent.com/25733845/73734386-da580480-473d-11ea-8d41-c81694df8b6d.png)

Question is, should this functionality be a case handled by Vanilla or should this be a local class in MAAS?

**Comment by matthewpaulthomas** [comment]
I think neither. It’s standard behaviour for a checkbox’s label to be clickable to toggle the checkbox. If this piece of text does not do that — if it’s a link instead — then it’s not really a label for the checkbox. I don’t know what your markup is, but if it involves a `<label>` tag, you could fix this issue simply by removing that tag.

Occasionally checkboxes don’t have labels, when they have a table column to themselves. This looks like one of those cases.
