### ISSUE TITLE
Tidy up spacing on p-table--mobile-card

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/vanilla-framework#2817]
## Pattern to amend

`p-table--mobile-card
`
## Visual

How it currently looks like:
 
<img width="684" alt="Screenshot 2020-02-06 at 15 21 33" src="https://user-images.githubusercontent.com/36884067/73951163-0ec1f100-48f5-11ea-8dca-c10923ee125e.png">

My proposal:
<img width="1153" alt="Screenshot 2020-02-06 at 15 23 29" src="https://user-images.githubusercontent.com/36884067/73951187-16819580-48f5-11ea-99d7-811e1f58b0da.png">

## Context

Visually I don't think it looks right having all that white space on the left side, in my opinion, it looks like a mistake. It's also taking much space compared to my proposal, making the user scroll much more.

**Comment by lyubomir-popov** [comment]
~40 uses across sites
- Review cases and see if there's a clear optimum
If an optimum exists, use that
Otherwise, look into alternatives - 
1) per-case solution (local code)
2) look for an alternative easy way to make it adjust to content

**Comment by solazio** [comment]
![image](https://user-images.githubusercontent.com/40214246/79753034-2d892e80-830d-11ea-84de-35a2e2b2c56b.png)

**Comment by bartaz** [comment]
The width of the first 'column' needs to be fixed in CSS (it can't be flexible from content itself) so we can only predefine move values (25% / 50% / 57%) and make them available as `--narrow` `--wide` variants.

**Comment by bartaz** [comment]
From accesibility point of view the component is a bad example of `aria-label` usage. Screen reader would only read label OR cell text. Which makes this pattern useless for screen readers.

**Comment by bartaz** [comment]
Seems like the design of that could be aligned with updates to key-value definition list: canonical-web-and-design/vanilla-framework#1916

**Comment by bartaz** [comment]
@lyubomir-popov wants to propose a redesign of that component

**Comment by lyubomir-popov** [comment]
I'd like to propose a slightly different design, which is more flexible. The label and text get thesame width, at the expense of height.

If you know the values will be short enough to use half the screen, you use a modifier on the table to get that version:

![Default](https://user-images.githubusercontent.com/2741678/111155088-e42c7800-858b-11eb-9c3e-6a3324a4c93c.png)
![Split, achieved with a modifier class](https://user-images.githubusercontent.com/2741678/111155099-e7276880-858b-11eb-9ab4-646abb7ba745.png)


What do you think @spencerbygraves ?

**Comment by spencerbygraves** [comment]
Thanks @lyubomir-popov, looks like a good improvement

**Comment by lyubomir-popov** [comment]
This is ready to be built @bartaz. Should we keep it in the current iteration, or move it back to triaged?
I know you wanted to fix the misuse of aria-labels so won't rush with the implementation.

**Comment by bartaz** [comment]
@lyubomir-popov let's move it back to triaged.

Fixing both: changing the design and addressing aria-label issue, can make it quite large. We may need to split that into two separate issues.
