### ISSUE TITLE
Display version in the docs

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/vanilla-framework#2823]
We are adding notices that patterns are being depreciated in v3 in the docs but there is no indication which version of the docs I am looking at. 

Can we render the version of Vanilla the docs are referring too at the top of the side navigation or something?

**Comment by lyubomir-popov** [comment]
Maybe next to the logo?

![vanilla-version](https://user-images.githubusercontent.com/2741678/74255067-41029280-4ce9-11ea-9ec7-44e2f87f2bbe.jpg)

**Comment by spencerbygraves** [comment]
@anthonydillon @lyubomir-popov At the top of the side navigation might be better for now, otherwise the [header diverges further](https://github.com/canonical-web-and-design/vanillaframework.io/issues/282).

**Comment by anthonydillon** [comment]
If in the header it would have to be across the site which I think it's trivial now it's flask. @bartek?

**Comment by lyubomir-popov** [comment]
@anthonydillon I think you meant to tag @bartaz  :)

**Comment by bartaz** [comment]
@anthonydillon The site is not flask yet, just docs. Which we probably should merge into one project sooner than later. Site is like 5 static pages, so there is no good reason to keep it separate.

**Comment by lilyvidenova** [comment]
Maybe we can add an item where the release notes for all versions live? 

MAAS does it like this:
![image](https://user-images.githubusercontent.com/17980375/74529951-d5a30580-4f20-11ea-9aca-44f82c8c6f48.png)
[Example](https://maas.io/docs/whats-new-in-2-6)

**Comment by bartaz** [comment]
Also, Jaas seems to have version in sidebar:

<img width="1253" alt="Screenshot 2020-02-14 at 11 32 06" src="https://user-images.githubusercontent.com/83575/74530208-d1c7b100-4f29-11ea-9b50-2a0cba8d021c.png">
