### ISSUE TITLE
p-heading-{number} classes have wrong margin-bottom

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#2835]
**Describe the bug**
changing e.g. an h3 to p.p-heading--3 leads to in the amount of space between the heading and the paragraph:
![image](https://user-images.githubusercontent.com/2741678/74824433-06f44a80-5300-11ea-9d60-533976e2a9c5.png)

Correct spacing on the left, wrong one on the right. The problem comes from the fact that p+p {margin-top -.5rem} is not overriden when the second p has a class 'p-heading--*'. I believe this is a recent regression.

**To Reproduce**
1. Go to 'https://docs.vanillaframework.io/examples/templates/typographic-spacing', find a heading preceding a paragraph
2. Replace the heading tag (e.g. `h3`) with `p.p-heading--3`
3. Observe spacing change

**Expected behavior**
p-heading--* classes should disable the p+p margin-top  -.5rem, or the p+p rule should exclude p's with [class*='p-heading--']

**Comment by bartaz** [comment]
It got broken a while ago. 

It was working in 2.3.0:

![Screenshot 2020-02-21 at 11.13.15.png](https://images.zenhubusercontent.com/593a660851aa2c30578102bb/9edfb9ae-f6b5-4e36-a02a-2ff90c5eef8b)

Broken in 2.4.0:

![Screenshot 2020-02-21 at 11.12.58.png](https://images.zenhubusercontent.com/593a660851aa2c30578102bb/7d5d2af9-24d3-4a5b-80f4-6260c52ccb5c)

https://codepen.io/bartoszopka/pen/abOBOOq?=true

**Comment by lyubomir-popov** [comment]
Nice investigation, don't know why I got confused and thought it was the latest version. Feel free to leave it to me if you don't want to sort through the overly complicated selector that got deleted in 2.4

**Comment by bartaz** [comment]
@lyubomir-popov This seems to be the PR and change that caused the issue:

https://github.com/canonical-web-and-design/vanilla-framework/pull/2452/files#diff-835de81767074b6c90941c47335f0fd9L86-L112
