### ISSUE TITLE
Code patterns: Provide user-controllable wrapping, row output view

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#2841]
## Pattern to amend
Code numbered, code

We've gone [back](https://github.com/canonical-web-and-design/vanilla-framework/issues/1986) and [forth](https://github.com/canonical-web-and-design/vanilla-framework/issues/2457) on the issue of wrapping code snippets. Lack of user control has led to problematic requests e.g. making the whole [pastebin](https://pastebin.canonical.com/p/gxB4SycF3s/) page scroll horizontally (which would cause a slew of other issues).

Most sites displaying embedded code snippets allow some degree of control - github for example has this toolbar as part of the code component:

![image](https://user-images.githubusercontent.com/2741678/74924221-f7413880-53c9-11ea-8da9-eb1ee9047030.png)

Notably, they have opted for a horizontal scroll with no wrapping by default, but have a "raw" button which displays the code unstyled and wrapping within the browser window.

We've tried raw buttons but not as part of the code pattern, which I personally didn't even notice because of its position:
![image](https://user-images.githubusercontent.com/2741678/74924448-69198200-53ca-11ea-8785-6671e4946167.png)

So my proposal is:
- provide modifiers so a developer could choose between wrapping / not-wrapping code snippet when including the component
- create an optional control toolbar in code snippets (design TBD), and in it:
  - provide a user override in the form of a "wrap" switch / toggle
  - provide a "raw" button

**Comment by lyubomir-popov** [comment]
Design proposal:
![Code snippet redesign](https://user-images.githubusercontent.com/2741678/75355313-3548cb80-58a6-11ea-9b70-1703a01542db.png)

- Remove unnecessary borders / background change to avoid L / T shapes caused from vertical line numbers and horizontal toolbar
- Reduce space of line numbers column (number width + 1rem either side, might be easier said than done though)
- Comparing with github, their numbers column is a lot less wide:
![image](https://user-images.githubusercontent.com/2741678/75355632-b2744080-58a6-11ea-8dd3-7f11ff705635.png)
- Text instead of icons to avoid mixing copy icon with "view raw" text. (we've had other requests to remove the copy icon, so partially because of that as well)

**Comment by lyubomir-popov** [comment]
@matthewpaulthomas is already looking at improving code snippets, removing WG label.

**Comment by wgx** [comment]
Covered by new code pattern, also in #2457
