### ISSUE TITLE
Right aligned key / left aligned value pair pattern

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#2848]
We've designed and in some cases implemented a key-value pair pattern that keeps keys and values close to each other in a few different places, and it seems to crop up in mockups for other sites (image builder?).

It has been well received in MAAS, and if developers are being asked to build it in other products, maybe it deserves a place in the framework?

## Visual
![image](https://user-images.githubusercontent.com/2741678/75266485-4f24d880-57ea-11ea-979a-b26873bc51d4.png)

TBD, the above currently serves maas' needs, and has no states. It does have support for up to 4 levels of hierarchy, which is to some extent dependant on the viewer being familiar with the format. 
In a more general case, the first 3 levels should work regardless of familiarity.

## Context

- Whenever the parent layout is likely to introduce a big gap between a left aligned column of keys and a left aligned column of values

- Whenever easy scanning of the keys is not essential. This means a limited number of keys. 

- ... Possibly more reasons UX-wise ? @matthewpaulthomas?

## State

Beyond the simple collapse / expand functionality, states haven't been explored currently, as there hasn't been a need for them. If someone thinks of using this in an interactive context, please supply interaction requirements.

## Progressive enhancement

It is inherently mobile friendly, and it can be squeezed into a small columns without breaking. Both keys and values can wrap without creating ambiguity.
It could require js for expanding / collapsing, in case it is disabled, it would default to expanded.

**Comment by anthonydillon** [comment]
There was [a similar proposal](https://github.com/canonical-web-and-design/vanilla-framework/issues/1349) some time ago which was rejected as this pattern can be created with existing patterns. Vanilla does not support grey text this should be a separate issue.

**Comment by lyubomir-popov** [comment]
Fair point, I tried to build it but I couldn't come close enough - [codepen here](https://codepen.io/lyubomir-popov/pen/YzXZxaV):

![image](https://user-images.githubusercontent.com/2741678/75335135-df156180-5880-11ea-8048-34f62821bb30.png)

Issues:
- If you use the grid, the column gutter is way too large
- Resizing will lead to truncation or excessive wrapping
- I have to override margins/padding on pretty much everything
- Nearly every single element requires a utility
- No way to adjust the width of left vs right column, which you'd want to do once you know what kind of text goes into each column
- Adding the accordion to this would lead to additional padding / sizing issues
- Takes 10x more time, and will require multiple design reviews to request all the utilities

**Comment by lyubomir-popov** [comment]
It raises another good point though, which I think is relevant to the logo strip discussion.
What do we consider a pattern? Does the fact you can build it from stock components mean it doesn't qualify?
AFAIK, that's not necessarily the case . From [wikipedia](https://en.wikipedia.org/wiki/Software_design_pattern):

>"Rather, it is a description or template for how to solve a problem that can be used in many different situations."

So even if you can truly build it without any design compromises (and in this case I don't think it's possible, however in the case of the [logo strip](https://github.com/canonical-web-and-design/vanilla-framework/issues/2847) it is), shouldn't it still be readily available in vanilla in some form?

**Comment by anthonydillon** [comment]
This would be my proposed example:
![Screenshot from 2020-02-26 10-54-41](https://user-images.githubusercontent.com/1413534/75338423-98c30100-5886-11ea-9cb1-5d115f1b9c4d.png)

[Demo example](https://codepen.io/anthonydillon/pen/abOJLJW)

**Comment by lyubomir-popov** [comment]
Fair, didn't think of that. But still, once both the accordion version and the non-accordion version are placed next to each other, this is what I get (mockup vs markup version):


![image](https://user-images.githubusercontent.com/2741678/75340974-623bb500-588b-11ea-9b21-06af3e3e8fed.png)

(I've also taken the liberty of adding a utility to take out the lines on the rows)
```
.u-transparent-border--top {
  border-top-color: transparent !important;
}
```

**Comment by matthewpaulthomas** [comment]
> ... Possibly more reasons UX-wise ? @matthewpaulthomas?

I think you have them exactly right. :+1:

> What do we consider a pattern?

Not an engineer, but for me it’s anything shared for efficiency, consistency, or quality. If you do something a second time, and you could have saved time, or avoided accidental inconsistency, or avoided bugs, by sharing code with the first one, that’s a pattern candidate. Even if the thing you’re doing a second time is applying a particular combination of overrides and utilities to an existing pattern.

**Comment by anthonydillon** [comment]
@matthewpaulthomas You absolutely right. As we are using this pattern multiple times across multiple projects the only way to drive consistency is to make it a simple to use - documented pattern.

Therefore, IMO the next steps are to either update an existing pattern to match this one (definition list) or create a brand new pattern.

**Comment by lyubomir-popov** [comment]
Validated; next steps:

Identify which parts of the design constitute a pattern, and which can be achieved separately.

**Comment by lyubomir-popov** [comment]
Another use of this with inputs from https://github.com/canonical-web-and-design/web-squad/issues/2638#issuecomment-616148958:

![image](https://user-images.githubusercontent.com/2741678/79742041-2278d300-82fa-11ea-800d-f5f4461ed95e.png)

**Comment by matthewpaulthomas** [comment]
> Another use of this with inputs

Previously those text fields had labels above, and now they have labels to the left (thanks!) — but that’s just for better fit with the rest of the dialog. Semantically, they’re no more “key-value-ish” than they were before.

Giving fields grey labels would also suggest that the fields are disabled. (And being empty text fields, with `#999999` borders, there’d be no visible sign that they _aren’t_ disabled.)

So maybe grey text shouldn’t just mean “this is the key of a key-value pair”, it should mean “this is a label for data that you can’t change right now”. For example, if a key-value table happened to contain one item you could edit, with an Edit button converting it to a text field, that item’s label would simultaneously switch from grey to black.

**Comment by lyubomir-popov** [comment]
Thanks @matthewpaulthomas that's an important thing to keep in mind. I wonder if there's any research showing grey labels on fields makes them perceived as disabled. 

This is an argument that has been made numerous times, and if we agree that it does, then we should reconsider its use in many places.

On the other hand, I've seen it in many places e.g. material design, so I wonder what research says about that:
![image](https://user-images.githubusercontent.com/2741678/80206761-dc3ab100-8624-11ea-90c5-fb8c7aaed265.png)

**Comment by matthewpaulthomas** [comment]
Many factors can contribute to making a control look disabled: lighter (e.g. greyer) label, less shadow, lighter border, less bevel, greyer/lighter fill, and (where applicable) greyer/lighter contents. Few toolkits use all at once (especially since flat design lacks some of them to start with), but the more they use, the easier it is to tell. Not being an Android user, I genuinely can’t tell which of those Material mockups is enabled and which is disabled.

My point was that we could use grey generally to mean “this is a label for something that isn’t editable right now” — including the keys in almost all key-value pairs, and the labels for disabled controls — rather than “this is a label for something positioned to the right”. That would let us emphasise the values in key-value tables (as in the MAAS example), while avoiding inconsistency in forms where some controls happen to be labelled horizontally and others vertically.

**Comment by lyubomir-popov** [comment]
Cataloguing another recent use, just to provide enough real world examples for when we get around to turning this into a pattern:
![image](https://user-images.githubusercontent.com/2741678/87446124-ccfa4c80-c5f0-11ea-9d33-406af02ac55f.png)

**Comment by danielmutis** [comment]
Adding here an example of this on charm publisher pages. When the list items have quite short names it is hard to see where things are aligned, or why there is so much gap on the left. I have addressed it for now with a list.
![Screenshot 2020-11-23 at 11.47.17.png](https://images.zenhubusercontent.com/5e1c5367f4dbe2bfe4c77ad8/7f0031cf-7c24-440d-b5aa-b78de77537e0)

**Comment by matthewpaulthomas** [comment]
@danielmutis In the examples above, any heading (A) aligns with a horizontal line below, (B) aligns with the left edge of some text below, or (C) is boxed off so that it’s not expected to align with anything. Your second layout does both (A) and (B). Your first layout does none of the three. You could do (A) or (C) while still having right-aligned labels. And maybe there’s a good reason for the card to be so much wider than the text, but if there isn’t, you could narrow the card and do (B) as well.

**Comment by bartaz** [comment]
Related to canonical-web-and-design/vanilla-framework#1916

**Comment by bartaz** [comment]
This have been through WG before, but because it needs UX work we should pass it though our new process.

**Comment by clagom** [comment]
Needs UX specification

**Comment by clagom** [comment]
@SirSamTumless this is a big task would require some dedicated time during planning

**Comment by elioqoshi** [comment]
@SirSamTumless Likely 2 iterations needed since I am on holidays next week

**Comment by ziheliu214** [comment]
@elioqoshi @AnnSoMuller Hi guys, vanilla police here! 🍦👮‍♀️
As discussed in WG meeting, please turn this issue into an epic, then break down issues into research, UX design, Visual (if needed in your case) and so on with descriptions.
We hope to see the UX issue gets closed by this Friday, so Long can dedicate some time for visuals next iteration.
Thank you!

CC @SirSamTumless @cristinadresch
