### ISSUE TITLE
"Muted" small text

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#2851]
We use small grey text in multiple places, but there's no class in vanilla for it. 

## Visual

Maas as built:
![image](https://user-images.githubusercontent.com/2741678/75337398-d9217f80-5884-11ea-9c20-e34909e077c2.png)

(RBAC from an old mockup)
![image](https://user-images.githubusercontent.com/2741678/75337465-f7877b00-5884-11ea-98b6-6cdfd14eaef6.png)

## Context

Cases where smaller font size is not enough to create sufficiant contrast between a paragraph and accompanying small text.

## State

No, but it should be readily theme-able. Maybe arrive at #666 using opacity instead of a hex color?

**Comment by spencerbygraves** [comment]
@bartaz @lyubomir-popov could we extend this to having #666666 as an option for text more generally? The new sidebar designs used this colour on p and h5 text.

I'm about to write the spec for this, but we don't have grey text yet.

**Comment by lyubomir-popov** [comment]
Good point, it shouldn't be tied to text-size. Maybe call it 'p-muted-text' and only set the colour.
In the interest of making theming consistent, I would define it as a contrast ratio rather than a hex value, so that:
- for the white theme, starting from the darkest grey it could appear on, offset by the contrast ratio. So maybe daken(#f7f7f7).
- in the dark theme, same with the lightest background it can appear on, say #262626 from the nav

**Comment by lyubomir-popov** [comment]
@spencerbygraves so for the spec, maybe refer to it as the "muted grey" colour and once this is implemented, we could link to the documentation that explains what muted grey colour is?

**Comment by spencerbygraves** [comment]
@lyubomir-popov ok, thanks.

**Comment by lyubomir-popov** [comment]
Closing, this is a duplicate.
