### ISSUE TITLE
Mock up template examples for side navigation

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#2859]
Create some basic HTML mock-ups (CodePen?) to understand better contexts/layouts in which we want sidebar nav to work (JAAS dashboard, docs) and what HTML structure would be.

**Comment by bartaz** [comment]
"docs layout": https://codepen.io/bartoszopka/pen/rNVpZmM

**Comment by bartaz** [comment]
https://codepen.io/bartoszopka/pen/vYOpVgq

**Comment by lyubomir-popov** [comment]
For the hover state, I wonder if we can keep the font-weight light to avoid the change of width of the words. @spencerbygraves what do you think?

**Comment by spencerbygraves** [comment]
Thanks @bartaz let's try a colour change only, from mid-dark to dark.
