### ISSUE TITLE
Build optional sidenav icons

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#2862]

**Comment by bartaz** [comment]
@spencerbygraves @lyubomir-popov 

I think our current designs don't specify that.
Do we allow nested levels to have icons as well?

Should they be all aligned with 1st level?

![Screenshot 2020-03-12 at 16.13.50.png](https://images.zenhubusercontent.com/593a660851aa2c30578102bb/a0e0cd62-c35e-46fe-91ec-e69036721769)

Or should they be nested as well?

![Screenshot 2020-03-12 at 16.15.10.png](https://images.zenhubusercontent.com/593a660851aa2c30578102bb/c5a92242-6c37-443a-8215-281b8936f9a2)

**Comment by spencerbygraves** [comment]
@bartaz we think it's unlikely that icons are needed for second and third level links, perhaps we can leave that for now.

**Comment by lyubomir-popov** [comment]
if it's not too much hassle would be nice to align icons  with the previous level's text:
```
[•]  Level n <li> 
     [•]  Level n+1 <li>
```
Just  so it doesn't look broken if someone does add icons.

**Comment by bartaz** [comment]
@lyubomir-popov 

To do that we would need to add quite big paddings to nested elements (even those without icons) to make them all align:

![Screenshot 2020-03-13 at 08.00.41.png](https://images.zenhubusercontent.com/593a660851aa2c30578102bb/edfcfb62-1690-4872-8cae-9106fc747111)

To avoid that (have default smaller padding if icons are not used in nested levels) we would need to add "has icons" modifier on each nested level, not just on root of component - which adds complexity to code and usage of the pattern, that is probably unnecessary - assuming that we don't really expect icons on nested levels.

I would suggest going with a simplest solution that covers our case (icons on first level) and document that icons are not supported on nested levels.

Both proposals from my previous comment are fairly easy to implement. Currently the first one (all icons aligned on the left, not nested) requires the least code (as it doesn't add rules to nest the icons).
