### ISSUE TITLE
Clearing a search field annoyingly defocuses it

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/vanilla-framework#2866]
1\. Go to [the search box page](https://docs.vanillaframework.io/patterns/search-box).
2\. Focus the example search field.
3\. Type some text.
4\. Click the clear button.
5\. Start typing some different text.

What should happen: The text you type appears in the search field.

What actually happens: The text is lost, because the search field is no longer focused.

When someone clears a search field, most of the time it will be because they want to start a new search. So defocusing the field is annoying.

Intriguingly, while this bug occurs on [ubuntu.com](https://ubuntu.com/), it does not occur with the search field in the header of docs.vanillaframework.io.

**Comment by lyubomir-popov** [comment]
Interestingly, the vanilla docs site wide search in the top right corner returns focus to the search field for me. @bartaz is the js handling that different?

**Comment by bartaz** [comment]
Yes, as far as I understand the examples don't use JS at all - just default browser `reset` button behaviour.

Search box in the navigation has some JS handling.

I guess we could add some simple JS to the examples to provide better experience.

**Comment by matthewpaulthomas** [comment]
If the resolution is to add JS to the examples, does that mean it will need fixing individually for each search field where the problem occurs? Besides ubuntu.com, I’ve seen it in the WIP image builder (what prompted me to report this) and [the MAAS documentation](https://maas.io/docs).

**Comment by bartaz** [comment]
Yes, the default browser (no-JS) solution would clear the field and remove focus.
Sites that don't have JS implementation of clearing search field would need to implement this (or use our example when we update it).
