### ISSUE TITLE
Dynamic blog feed

### ISSUE THREAD

**Issue by kwm14** [canonical-web-and-design/vanilla-framework#2903]
## Summary

We've implemented a [blog section](https://github.com/canonical-web-and-design/vanillaframework.io/pull/261) which pulls in the articles manually, as we currently have 4 posts written it seems a lot of work to invest in creating a bespoke feed.

## Process

Going forward as we plan to write posts over the next cycle (6months) we can revisit the blog section and create a dynamic feed if needed.

Things to consider:
- **Category** - Design
- **Tags** - Currently '_Vanilla_' and '_vanilla framework_' 
  - This tag is used for _Web and Design Team summary_ weekly posts, ideally, we don't want every post to feature on our site
- **Topic** - ...

**Comment by bartaz** [comment]
Now that the site is flask we could use blog module server side, or have a client side JS to fetch latest blogposts.
