### ISSUE TITLE
“Docs” header inconsistent with the rest of vanillaframework.io

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/vanilla-framework#2904]
1\. Go to [the “Docs” section of the site](https://docs.vanillaframework.io/).
2\. Go anywhere else on the site.

What you see:

1. ![image](https://user-images.githubusercontent.com/19801137/73607758-2fffa600-45b2-11ea-816d-5313385e13eb.png)

2. ![image](https://user-images.githubusercontent.com/19801137/73607765-3ee65880-45b2-11ea-8c1a-76bcc2de08cc.png)

What you should see:
- The header links are the same across the site
- The header links are in exactly the same position across the site.

This is a regression of canonical-web-and-design/vanillaframework.io#104. I guess that means the header is being maintained in two separate codebases, so that it repeatedly accidentally diverges. Perhaps one could import from the other?

**Comment by bartaz** [comment]
Now that Vanilla site is part of Vanilla docs it will be easier to address.

@lyubomir-popov is working on revisiting the site layout to make it work for both docs and brochure pages.

**Comment by bartaz** [comment]
Vanilla is using the fixed width docs layout, same as other sites.
