### ISSUE TITLE
Slack if for @canonical only

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#2914]
We promote the Slack as means to contact us on vanilla site, but only @canonical email accounts can join.

We should either open up Slack for people to be able to join or remove Slack from documented ways of contacting Vanilla team.

**Comment by anthonydillon** [comment]
Personally, I don't use Slack so is not a natural place for me to provide help. 

That said, if Slack is where the community is we shouldn't shut it out. Maybe open and promote the channel for a set period and see if we get traction.

Can you set some KPIs such as duration and measure of success and see if we reach it?

**Comment by bartaz** [comment]
@anthonydillon I mention it because I thought we could use Slack for communication during Rails Girls Summer of Code.

We barely have any outside community, so there is no high need for open communication tool. On the other hand maybe we would have some community communication if we did have an open channel.

**Comment by bartaz** [comment]
We can invite new users directly into Vanilla slack or generate invite link for them to use and join.

So we should be able to use Slack for communication with students during RGSoC.
