### ISSUE TITLE
Sidebar responsive behaviour

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#2920]
Specify what happens as the screen width decreases.
- when the sidenav is the main site nav
- when the side nav is part of the page body

**Comment by clagom** [comment]
@lyubomir-popov please ping me when you start working on this, I have some examples and ideas

**Comment by lyubomir-popov** [comment]
Audit, benchmarking and maas settings version https://app.zeplin.io/project/5e53b1de467c3764be6f133a/dashboard?seid=5e84c903a298bb48fd2531b9

**Comment by lyubomir-popov** [comment]
I've updated the mockups with a new docs section:

https://app.zeplin.io/project/5e53b1de467c3764be6f133a/dashboard?seid=5e8c8e4018867db9a6518186

**Comment by lyubomir-popov** [comment]
bartaz section link added to the issue zpl://project?seid=5e8ca15f44dc2120385aa0ee&pid=5e53b1de467c3764be6f133a

**Comment by bartaz** [comment]
@lyubomir-popov could you link to online project? I don't have zepplin app to open zpl:// links

**Comment by lyubomir-popov** [comment]
https://zpl.io/bAyz6zq (section currently at the top)
