### ISSUE TITLE
Sidenav: dark theme

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#2921]
Specify what colours should be used for each coloured element in the sidenav.

**Comment by bartaz** [comment]
@lyubomir-popov What are your thoughts on background color of the whole nav?

Currently (as I implement it) side navigation has no background of it's own - assuming it will just have the background of its container.

How will it work with dark theme? Should the side nav background become dark? It may look weird if it's not in a dark container (for example not whole column will be dark, but just side nav list).
We can assume that if you use dark side nav it is in dark container, but it's contrary to how other dark theme components work (they don't rely on external dark background).

**Comment by lyubomir-popov** [comment]
I think we should treat the currently designed white version as this component's default theme. 
To be safe, it needs to set all colours, including background, to ensure things are always readable.

JAAS already needs a dark version of this, and while they will want to customise the background color to the jaas blue, everything else can probably come from the vanilla dark theme as implemented in the vanilla horizontal navigation. I've added a task to design this next iteration, and I think we should implement with the release of this component.

**Comment by lyubomir-popov** [comment]
This component should follow the theming architecture, and I expect jaas will need to implement their own theme as the base colour there is the jaas blue.

**Comment by lyubomir-popov** [comment]
![image](https://user-images.githubusercontent.com/2741678/77349622-33521b00-6d33-11ea-989c-5661fabd7263.png)


text active li: $colors--dark-theme--text-default (#fff)
text inactive li's: $colors--dark-theme--text-default at 55% opacity

separators, highlight of active item: 
$colors--dark-theme--text-default, 5% opacity

bar: $colors--dark-theme--text-default

**Comment by lyubomir-popov** [comment]
let's try specifying things with opacity as discussed in the WG meeting; 
the inactive text is at the exact threshold of AA accessibility .

**Comment by bartaz** [comment]
Closing, as I assume it's done (we follow the discussion in build PR).
