### ISSUE TITLE
Subtle text

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/vanilla-framework#2922]
More and more designs lately contain text which is smaller and light grey. This was always avoided in the past to provide a good contract as the framework cannot know what background the element is on but can enforce clear dark and light styling. For example, we shouldn't have to treat the subtle text differently when on a `p-strip--light` but we might have to couple the patterns to provide accessibility.

My proposal would be to consider a text utility class, such as `.u-text--subtle` to provide the new styling.

Things to consider:
- Will it always be 14px or should it just slightly reduce to font-size on the host element?
- Are we concerned people will use this grey text on grey?
- Can this design be achieved with current patterns?

## Visual
![image](https://user-images.githubusercontent.com/1413534/76462701-04a27f00-63da-11ea-80df-33ec6760ec6e.png)

## Context
It's normally used to sub/meta data.

## State
No

## Progressive enhancement
It's a text utility so should be fine.

**Comment by spencerbygraves** [comment]
@anthonydillon [we already have an issue for this](https://github.com/canonical-web-and-design/vanilla-framework/issues/2851), where we discussed having #666666 as an option for text more generally and not tied to size.

**Comment by lyubomir-popov** [comment]
yes, small text and #666 do not always go hand in hand, and we need #666 on 1rem text as in the sidenav.

we have .p-text--small (14) and .p-text-x-small (12.8), so a color utility would allow us to cover all cases.

**Comment by lyubomir-popov** [comment]
accessibility-wise we're safe as long as we don't aim for AAA:
![image](https://user-images.githubusercontent.com/2741678/76508645-a65fb580-6446-11ea-8357-60bbc19f5eb1.png)

**Comment by lyubomir-popov** [comment]
the threshold for accessibility for text on #f7f7f7 is #717171:

![image](https://user-images.githubusercontent.com/2741678/76508920-1110f100-6447-11ea-82f3-d64c486a6dab.png)

**Comment by anthonydillon** [comment]
@lyubomir-popov great news! Thanks for checking. AA is are target :+1:

**Comment by lyubomir-popov** [comment]
Validated: Agreed to get to the subtler shade using opacity.

**Comment by lyubomir-popov** [comment]
This is completed, example here http://192.168.64.2:8101/docs/examples/utilities/muted-text. Closing.
