### ISSUE TITLE
Flex split

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/vanilla-framework#2923]
Since we removed the float utilities I cannot think of a way without using the grid of splitting items left and right on the same row. All I want is to be able to use `u-align--left` and `u-align--right` to two sets of images and have them displayed nicely.

The proposed solution was to create a new flex utility which initiated flex and allowed me to split to utility children evenly. For example:
```html 
<div class="u-flex">
  <div class="u-flex__split u-align--left">
    <img src="..." alt="">
  </div>
  <div class="u-flex__split u-align--right">
    <img src="..." alt="">
    <img src="..." alt="">
  </div>
</div>
```

## Visual
![image](https://user-images.githubusercontent.com/1413534/76464567-821bbe80-63dd-11ea-8238-2208a7e1bf38.png)

## Context
We have a design which reasonably asks for a set of items on the same row to align left and the others to align right. This is possible with the grid but seems overkill to just simply use flex and justify.

## State
No

## Progressive enhancement
Flex should stack once the items don't fit next to each other to should be fine.

**Comment by lyubomir-popov** [comment]
I've wanted flex utilities for a while. In this particular case, is the wrapper necessary? You could achieve the same effect (and more complex ones) by simply controlling the margin on the children as in this [demo](https://codepen.io/lyubomir-popov/pen/oNXEVoX?editors=1100).

**Comment by anthonydillon** [comment]
@lyubomir-popov You demo seems very similar to the proposed solution. Before I would have used the `u-float--right` `u-float--left` classes to achieve this but I can't think of a way to apply this layout without a container setting flex.

**Comment by lyubomir-popov** [comment]
yes, the flex container is needed, but these you can do without: 
`<div class="u-flex__split u-align--left">`

**Comment by anthonydillon** [comment]
The nice thing about `flex__split` is that it does what it does exactly that. So you could have four items in the u-flex and they would be evenly distributed and then we can extend then using existing alignment utilities. So the u-flex is more to apply flex then about alignment.

**Comment by lyubomir-popov** [comment]
I agree it makes it simpler to reason about it, and I'm fine to do it that way. My concerns there (minor ones really):

### 1 
u-flex__split has flex:1, which makes left and right containers same width; so things might wrap before they need to:

![image](https://user-images.githubusercontent.com/2741678/76613402-f6597d80-6515-11ea-9e25-d5a6185b9b77.png)

as a minimum, I would suggest flex 1 0 auto, so things can grow, but no shrink, and the width is determined by the combined width of the children; this results in:

![image](https://user-images.githubusercontent.com/2741678/76613534-41739080-6516-11ea-9f1c-bfa4a6b93e5c.png)

### 2
If all we want is stick elements to the left and right edge, justify-content: space between is cleaner, requires less classes, and ensures the wrappers' widths are exactly fitted to the content inside:
![image](https://user-images.githubusercontent.com/2741678/76614407-eb9fe800-6517-11ea-98c5-3fbafc505979.png)
