### ISSUE TITLE
Audit the table pattern and come up with a naming convention

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#2927]

**Comment by bartaz** [comment]
### `p-table--sortable`

Seems unnecessary for it to be a modifier on table level.

The only style applied to the table is `table-layout: fixed` which is also applied to regular table, so can be removed.
Any other styles are applied to column headings `<th>`.

Proposal:
- deprecate and remove `p-table--sortable`
- create a new pattern (for example `p-sortable-column` to be applied on columns in the table to make them sortable)

**Comment by bartaz** [comment]
### Open questions about standards

- targeting elements in selectors
  - as a rule we don't want to target elements, we should target class names
  - but for things with very strict HTML structure (tables) it makes us add classnames just for the sake of it
- having modifiers on 'patterns' that don't exist
   - headings `p-heading--1`
   - tables - because we style table as default, we don't have `p-table`

**Comment by bartaz** [comment]
@anthonydillon Can you have a look at the audit notes and proposals?

**Comment by anthonydillon** [comment]
## `p-table--sortable`
The reason class is top level is to target with JS as the functionality is table-wide.

## `p-table-expanding`
Agree the name change is an improvement.

## `p-table--mobile-card`
`muted-heading` is extended here without being imported and so could cause errors. I wonder if we can simplify the contextual menu out of this pattern? By, displaying all the content as cards.

> targeting elements in selectors

I would say table is an expectation here as the classes would be mindless.

> having modifiers on 'patterns' that don't exist

Personally, I don't mind this.

**Comment by bartaz** [comment]
> `p-table--sortable` The reason class is top level is to target with JS as the functionality is table-wide.

@anthonydillon In JavaScript we could make it work without the class on parent table as well. Sure, it's easier when the class is there, but there is no problem in checking if given table has any sortable headings inside, so the class won't be needed on the table.

> `muted-heading` is extended here without being imported and so could cause errors. 

`%muted-heading` placeholder is part of base typography placeholders, so it's available for all components. Maybe the name is a bit misleading and suggests that it comes from pattern.

> I wonder if we can simplify the contextual menu out of this pattern? By, displaying all the content as cards.

Not sure what you mean here. How to simplify contextual menu?

To be honest I don't fully understand what the contextual menu overrides do in mobile card pattern, as we don't have example for that.
I think I'd try it first and maybe then check with different teams if they use it this way.

**Comment by bartaz** [comment]
### Next steps:

- Rename `p-table-expanding` to `p-table--expanding`
- Clean up `p-table--mobile-card` of external dependencies (contextual menu)
- Remove (deprecate) `p-table--sortable`, create new sortable column pattern in its place
- Once we switch to stylelint (#2945) try to add a rule that prevents using element selectors - make exceptions from this rule explicit and commented in the code

**Comment by anthonydillon** [comment]
> Rename p-table-expanding to p-table--expanding #2946

:+1: 

> Clean up p-table--mobile-card of external dependencies (contextual menu) #2947

:+1: 

> Remove (deprecate) p-table--sortable, create new sortable column pattern in its place #2948

I think that is good but will need though into backwards compatibility and the correct method this should be done. I would like to work with you on the spec for the new sortable table if that is ok.

> Once we switch to stylelint (#2945) try to add a rule that prevents using element selectors - make exceptions from this rule explicit and commented in the code #2949

:+1:
