### ISSUE TITLE
New `p-checkbox` and `p-radio` patterns

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#2931]
Based on the context of the discussion in #2913 @lyubomir-popov proposed adding new `p-checkbox` and `p-radio` patters to cover specific cases where we need to address these components, but can't do it in current markup (because they are inside class less label).

See #2913 for context.

**Comment by lyubomir-popov** [comment]
Validated. Consider reverting to the semantic way of doing checkboxes, label>input + any wrapper or list for a sequence.

**Comment by lyubomir-popov** [comment]
We need to make sure [this ](https://github.com/canonical-web-and-design/vanilla-framework/issues/3177) variation is possible with the new tick elements pattern.
