### ISSUE TITLE
Fix color function for icons to support rgba

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#2955]
Our current implementation of `vf-url-friendly-color` Sass function only works with `#RGB` colors.
It can't be used with `rgba` transparent values.

**Comment by bartaz** [comment]
I'm marking this as blocked for now. While I can fix the color function to support rgba colors, the icon SVGs are not produced to support transparent shapes, because parts of some icons overlap:

![Screenshot 2020-05-08 at 08.30.04.png](https://images.zenhubusercontent.com/593a660851aa2c30578102bb/af815bf4-7a78-4a26-880d-52518b9a8524)

I had a quick look at some of the icons in new set and they have exactly the same problem.
They have been produced with solid color in mind, not for transparent colors.

**Comment by lyubomir-popov** [comment]
@waynecrosby is there a version of the finalised icon set with expanded strokes and merged overlaps?

**Comment by waynecrosby** [comment]
@lyubomir-popov Not yet, I'm hoping to get it finished in the next day or so.

**Comment by lyubomir-popov** [comment]
@waynecrosby great, thanks!
