### ISSUE TITLE
Remove non-example pages from Percy

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#2957]
We should consider removing non essential pages from Percy.
Ideally we should just screenshot examples and remove any screenshots of marketing site and docs themselves.

There are several issues with that it can help with:
- Percy build takes quite long to process - we screenshot over 400 pages, around 70 of it are docs
- Every build and every screenshot counts agains our Percy quota - with ~ 100 builds a month we can save 7000 screenshots
- Very often the changes found by percy on these pages are useless - they are caused by content changes or Vanilla version bumps, etc, all significant changes to the styles should be covered by examples anyway - this leads to us needed to approve a lot of percy screenshots just because they are docs changes (see for example: https://percy.io/vanilla-framework/vanilla-framework/builds/4687413)

**Comment by bartaz** [comment]
@anthonydillon @barrymcgee @lyubomir-popov Thoughts?

**Comment by lyubomir-popov** [comment]
I agree, it is a chore. Still, for doc pages it is difficult to QA without knowing what changed. I wonder if we can distinguish between meaningful docs changes - like text being changed - vs meaningless changes - like a component design change that affects a doc page (and that is already qa-ed in the example of the component in question).

**Comment by bartaz** [comment]
@lyubomir-popov I don't think we can distinguish on Percy level - any pixel change is a change for Percy.

But, meaningful documentation changes can be easily noticed in code review - documentation files will be updated.
I guess we should make sure that it's part of our review process.
If PR includes documentation changes - it should be mentioned in description QA steps.

**Comment by lyubomir-popov** [comment]
Works for me.

**Comment by barrymcgee** [comment]
> Very often the changes found by percy on these pages are useless

Fair enough then 👍🏻

**Comment by anthonydillon** [comment]
Percy should run only on examples as that is the main purpose of them. To be visual tests. 

Regarding QA, every review should include three main things. Pattern change, example update and documentation when necessary.

**Comment by bartaz** [comment]
Percy is quite slow for us recently, so moving it to next iteration so we can remove unnecessary screenshots sooner than later.
