### ISSUE TITLE
Use versioning in static resources URLs to avoid caching problems

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#2959]
When serving static resources such as latest vanilla (`/static/build/css/build.css`) we should include some way of hashing version (`build.css?v=123456`) to make sure the file is requested when it changes.

Currently when we release new version of the site if CSS is cached in the browser it will not be refreshed unless user forces it.

We could use similar solution to [snapcraft static_url](https://github.com/canonical-web-and-design/snapcraft.io/blob/f25ecf96b670b884243f4427bfa850ea82f53989/webapp/template_utils.py#L61-L82)

**Comment by sowasred2012** [comment]
I _think_ we can just use `versioned_static('/static/build/css/build.css')`, which we already have available to us in [`canonicalwebteam.flask-base`](https://github.com/canonical-web-and-design/canonicalwebteam.flask-base/blob/6a0ee3301df330fa6fbc58ba712b2feeb5bdfe4d/canonicalwebteam/flask_base/context.py#L15)
