### ISSUE TITLE
Add toggle option for side nav icons

### ISSUE THREAD

**Issue by solazio** [canonical-web-and-design/vanilla-framework#2960]
## Pattern to amend

p-side-navigation

## Visual

Provide a screenshot or link to a prototype of your pattern amendment.

## Context

Make the icons on the right usable as a toggle, and display only when hover over.This is used on [charmhub.io currently](https://app.zeplin.io/project/5d3f1850b938ee0dc24c60c4/screen/5e39844b6d883bb55fd4e7ee).

## Proposed code

.p-side-navigation__link {
  .p-side-navigation__status.is-toggle {
    display: none;
  }

  &:hover {
    .p-side-navigation__status.is-toggle {
      display: block;
    }
  }
}

**Comment by lyubomir-popov** [comment]
@solazio we're discussing whether this component is the correct one to use for a multi-select interaction that updates a view rather than navigating to a different view. Once we have an outcome there, we can update this issue.

**Comment by solazio** [comment]
@lyubomir-popov thanks for letting me know.

**Comment by bartaz** [comment]
On the other hand I would argue that these icons don't need to be shown just on hover.
It will be much easier for user to know they can disable the selection if the X icon is visible always when given item is selected.

Also - if you can click on the whole item to select it - why not click on whole item to unselect it? Does it need the X icon at all?

**Comment by lyubomir-popov** [comment]
@bartaz @solazio the discussion I mentioned is happening here (and in a couple of catchups):
https://docs.google.com/document/d/1p1FRgzd1ZIY5X6wJJ-TH-R9JGPM1LK2YdgmWjkQDMB4/edit?ts=5e823891

**Comment by lyubomir-popov** [comment]
Is this still relevant now that this is done with checkboxes?

**Comment by solazio** [comment]
@lyubomir-popov no, you can close this.
