### ISSUE TITLE
Alternatives to checkboxes / radios outside of forms

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#2961]
We've had repeated comments that checkboxes / radios, while functionally accurate, are not entirely satisfactory visually. Recent example - a list of category toggles that filter content in the main column:

![image](https://user-images.githubusercontent.com/2741678/77937871-d6afac80-72ac-11ea-9b8b-5b5c4b8fd782.png)

Thought I'd create an issue for it, so we can track cases where the tick elements (radio, checkbox) are not ideal, and eventually provide an alternative and rules around when to use what.

**Comment by lyubomir-popov** [comment]
@danielmutis ^

**Comment by clagom** [comment]
Thanks @lyubomir-popov

**Comment by matthewpaulthomas** [comment]
In Zeplin I linked to [a Baymard collection of 110 examples of this pattern](https://baymard.com/ecommerce-product-lists/benchmark/page-types/product-list-search).

In that collection, for independent filters like these, most sites use a column of checkboxes with none checked by default.

**Comment by bartaz** [comment]
Is this related (or maybe even the same) as #2931 (adding `p-checkbox` and `p-radio` patterns)?

**Comment by clagom** [comment]
Yes, @bartaz.
We asked for an opinion to @matthewpaulthomas

**Comment by lyubomir-popov** [comment]
We've discussed creating a new "UX" documentation for Vanilla, this is where this would fit. Removing WG label.
