### ISSUE TITLE
Update another project's docs to use Vanilla docs template

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#2975]
Take snapcraft, maas or juju docs and update to new template.

Requires Vanilla responsive side nav to be released.

List of sites with documentation to potentially update:
https://docs.google.com/spreadsheets/d/1pWPtuX-nBVyzZb3Gi4P4uEdR9n55_kYCC4Dzfmagndo/edit#gid=0

**Comment by bartaz** [comment]
Blocked by https://github.com/canonical-web-and-design/canonicalwebteam.discourse-docs/issues/36

**Comment by bartaz** [comment]
Meeting notes from catch-up with @nottrobin @anthonydillon @bartaz 

We decided:
- documentation specific variant of side navigation will be added to Vanilla (as part of documentation layout) to style pure elements (lists of links) in similar way to side navigation
- this will be documented as part of documentation layout docs
- when integrating the docs the site in Flask template will need to use correct elements as a wrapper of side navigation, contents of the side navigation will come directly from Discourse
- any unusual markup coming from Discourse that is not styled by side navigation and breaks the visual look may need to be removed or updated in Discourse at the time of updating to new side navigation

**Comment by bartaz** [comment]
Snapcraft PR: https://github.com/canonical-web-and-design/snapcraft.io/pull/2765

**Comment by anthonydillon** [comment]
Looks really good @bartaz nice work!

**Comment by bartaz** [comment]
New docs layout is on Snapcraft now.
