### ISSUE TITLE
Checkbox filter list

### ISSUE THREAD

**Issue by solazio** [canonical-web-and-design/vanilla-framework#2980]
On charmhub.io we need to implement a checkbox filter list to list the items displayed. 

In order to implement this filter and get it to work without JS, it is necessary to use an `<a>` that wraps the `<input>` and `<label>`. Because clicking on the `<label>` does not register as a click on the link, the page is not refreshed and therefore nothing happens with the filters, other than the checkbox being checked (this can be fixed using JS). Another option to avoid adding custom styles, is to have:
``<a>
  <input>
  <label></label>
  Label text
</a>``
but this implies having an empty label in the html. That is why [I preferred to remove the label and add custom styling](https://github.com/canonical-web-and-design/charmhub.io/pull/57/files#diff-2aa856d7e9af0f834ef65d1a66f0ace0R1).

## Visual

![image](https://user-images.githubusercontent.com/40214246/79325029-650c6b00-7f08-11ea-9e1c-e4f8bb8018e9.png)

**Comment by lyubomir-popov** [comment]
@anthonydillon we moved the discussion here. 

@solazio don't think we've had that need before, so it seems a valid candidate for vanilla. Checkboxes in side an anchor is how amazon and ebay do it, so maybe we can make some small modifications of the vanilla css and provide an example, so that we can avoid having local styling in charmhub.

**Comment by bartaz** [comment]
There is lot of question on how this interaction works.

That exactly is a link? Only label? The whole box? Where does it link to?
If these are links - do they need to be checkboxes? Maybe the 'checkbox' is just an icon to make link look selected?

If it is a checkbox within a link - what happens when you click on checkbox and not a link?

**Comment by lyubomir-popov** [comment]
@bartaz yes, lots to consider. Amazon and ebay implement it a>label>input type="checkbox", so it seems like there's a valid case for that. the design @solazio was implementing is this: https://app.zeplin.io/project/5d3f1850b938ee0dc24c60c4/screen/5e849151aec09346e01c3c8c

**Comment by bartaz** [comment]
In terms of this particular issue - what are we expected to do?

Is this proposal for a pattern? Amendment to checkboxes to support such scenario?

**Comment by pmahnke** [comment]
@solazio, I don't understand the behaviour if you have a backend, you surely can use a normal form and just need classes to provide visual state changes?  Is there a requirement that this happens without a backend or javascript?  Can you provide more information about the interaction?

**Comment by nottrobin** [comment]
It seems to me that the only sensible way to provide this functionality without JavaScript is to add a "filter" button to the bottom, so people can tick as many boxes as they like and then click "filter". I think this is basically the point @pmahnke is making. Trying to make every tick box into a link seems crazy.

**Comment by lyubomir-popov** [comment]
@bartaz I thought we can make some small amendments to support the markup, and provide an example. Just so people can use it without writing extra css locally. 

Admittedly, checkboxes inside anchors seem like a strange structure, but amazon and ebay do the same, so I thought it might be a valid need.

![image](https://user-images.githubusercontent.com/2741678/79432411-a281fe80-7fc3-11ea-857a-b9dd6602c470.png)

![image](https://user-images.githubusercontent.com/2741678/79432478-ba598280-7fc3-11ea-9d8a-8f3c74bf67c3.png)

**Comment by nottrobin** [comment]
> Admittedly, checkboxes inside anchors seem like a strange structure, but amazon and ebay do the same, so I thought it might be a valid need.

i strongly disagree with this reasoning. A use-case is valid because it's the simplest, most maintainable and standards-compliant way to achieve an important goal, not because Amazon do it.

Amazon's website is famous for breaking usability principles all over the shop, and their code is definitely nothing special. They get away with it, but they're definitely the exception.

I think at the moment we're still trying to decide exactly what goal we're trying to achieve, and whether it's valid, so let's please hold off on whether the markup can be supported.

**Comment by solazio** [comment]
@nottrobin @pmahnke @lyubomir-popov @bartaz @anthonydillon @Lukewh I agree that we don't have to do it the way Amazon or Ebay does it. **But I think the first decision we need to make for all our websites is if we support no-JS or not.** If we decide not to support no-JS, definitely JS can handle everything and all this discussion is useless. However, if we decide we want to support no-JS then we need to find ways to make it work. My proposal was inspired by Amazon and was proposed to get this discussion moving. If we have better options, we should definitely consider all of them before we make a decision.

**Comment by nottrobin** [comment]
@solazio yes thank I appreciate that. Thanks for considering no-JS, and for starting the discussion.

I do think a no-JS solution is definitely important and worth considering how to support. But given that presumably the primary experience involves JS, I don't suppose we need to go out of our way to exactly match the design for the no-JS fallback. As in, a "Filter results" button at the bottom should be okay.

I would stick much closer to a traditional HTML structure for this, with something like (this is pseudocode, and so I've no idea if it works in either pure HTML or vanilla):

``` html
<div class="p-side-navigation">
  <form>
    <ul class="p-side-navigation__list">
      <li class="p-side-navigation__item--title">
        <input type="checkbox" name="analytics" id="analytics"><label for="analytics">Analytics</label>
      </li>
      <li class="p-side-navigation__item--title">
        <input type="checkbox" name="app-servers" id="app-servers"><label for="app-servers">App-servers<label>
      </li>
    </ul>
    <button type="submit">Filter results</button>
  <form>
</div>
```

**Comment by bartaz** [comment]
@solazio By principle of course we support no-JS version. Especially on public websites. I guess we are not that strict for 'applications'.
That said, we don't really QA no-JS, and are not very strict about it, so quite likely there are many places where things break or don't work without JS.

Should we assume that user have JS when building new thing like that - I don't think so.
Does it mean we have to put checkboxes in links? Probably not.
If these are checkboxes, for no-JS version they should be in a form with a Submit "Filter" button.
So user without JS clicks on any filters they are interested in and submits them.
Then with when JS is on the page we can enhance this: Clicking on checkboxes may automatically load given filter without submitting. Maybe even without reloading the whole page. Maybe "Filter" button is not needed anymore and can be hidden... We can go as far as we want from there.

For Vanilla CSS at this point the question is, are our patterns that we currently have enough to provide proper styling to what we want to build.

**Comment by lyubomir-popov** [comment]
Another use of something: [similar](https://app.zeplin.io/project/5d5566ee83622d9b72e8801d/screen/5d5a73958866d6522f648762):

![image](https://user-images.githubusercontent.com/2741678/79757685-5234d480-8314-11ea-9c00-b3fcd484125a.png)

- Part of the search and filter modular pattern
- Useful to have a component - block of checkboxes with a `<noscript>` submit button
- Consider nested categories

@solazio to implement locally and propose into Vanilla.

**Comment by bartaz** [comment]
Next steps:
- UX design

**Comment by anthonydillon** [comment]
To complete the loop we have rewritten the checkbox area to use `p-list` with `p-checkboxes` with JS attached to though elements to provide functionality. For non-JS users a `noscript` element containing a button will provide a filtered search.

The pattern now contains no bespoke markup or styling.

**Comment by bartaz** [comment]
This have been through WG before, but because it needs UX work we should pass it though our new process.

Is this still needed if it was implemented using existing Vanilla patterns?

**Comment by clagom** [comment]
@solazio are we fine with the current implementation on charmhub.io and close this issue?

**Comment by solazio** [comment]
I guess so. It served us well so far.
