### ISSUE TITLE
Pagination enhancements

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#2981]
## Pattern to amend

Pagination

## Visual

[TBD]

## Context

In what context does your amendment solve a problem?
Tables in apps

Just wanted to capture some interesting comments that form the modular table pattern discussion, worth making an exploration when we decide to revisit the pagination pattern:

@cassiocassio wrote:

"We should have page numbers as a basic, essential pattern, but I think there smarter paging that application designers can/should investigate in the future....

(one day) I would like to see us explore A. B. C. D. E. F for jump to first item beginning with that letter. It's odd to give users the task of guessing how many pages through the thing the want is...

There are probably other indexing schemes, depending on the application data, depending on sort order, e.g if sorted by storage, imagine single clicks to jump to the page of machines with (at least) 100GB, 200GB, 500GB 1TB, 2TB, 5TB, 10TB, 50Tb.... feels more useful that go to page 7 of 10 hoping to find a certain size disk."

**Comment by bartaz** [comment]
Relating pagination to data only makes sense when data is sorted. So only when data is sorted alphabetically pagination (in theory) may be related to A, B, C, D...
If user changes sorting this wont be the case.

So such pagination (that hints what value items on given page have) will need to be aware of current sorting.

The other implementation issue is that from application point of view we usually don't know what data is on given page. We know how many pages are there (how many items are in total), but we don't know what items are on every page (to know that we would need to fetch given page).
So, to implement such pagination, the API providing data would need to support it.

On the other hand - if user wants to get to items starting on specific letter or (even more so, specific disk size) - is this a task for a pagination, or filtering?

**Comment by lyubomir-popov** [comment]
The current pagination pattern supports the scenario described above. The buttons need not contain single digits - they can have any value needed. Closing.
