### ISSUE TITLE
Removing extra space inside padded interaction elements

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#2982]
We've had a few cases where aligning an icon inside a borderless button or drop down with the edge of the parent container is not possible or simple to override.

The most recent example is the newly built side navigation pattern. 

Mockup:
 
![image](https://user-images.githubusercontent.com/2741678/79448196-e7fcf680-7fd8-11ea-910e-e484f6e2fcd3.png)

Implemented version:

![image](https://user-images.githubusercontent.com/2741678/79448250-0236d480-7fd9-11ea-91d7-471e831e7201.png)

or 

![image](https://user-images.githubusercontent.com/2741678/79448296-17abfe80-7fd9-11ea-9e4d-a07bf11de730.png)

A similar case in jaas - button and label not aligned:
![image](https://user-images.githubusercontent.com/2741678/79448452-5b9f0380-7fd9-11ea-9447-e251eb24c5b0.png)

The issue is not limited to buttons. In snapcraft, the  "Products" menu and User name dropdown we have a similar misalignment. Both buttons include padding, which is proportional to the button size, and both are offset from the edge of the fixed width container by different amounts:

![image](https://user-images.githubusercontent.com/2741678/79348299-baf30a00-7f2c-11ea-9884-a31957b23621.png)

My proposal is to introduce interaction elements that do not rely on hover and thus do not require left/right padding. It should be available for the contexts above, as an alternative to buttons, menus, selects etc.

**Comment by lyubomir-popov** [comment]
Needs design exploration - an accessible hover state that doesn't require a padded area.
Similar patterns: breadcrumb, link with icon.

Setting to validated for now, once we attach a specific example, we can discuss in more detail.

**Comment by bartaz** [comment]
@lyubomir-popov mentioned it's not possible to achieve this without causing other problems, so closing for now
