### ISSUE TITLE
Notifications: “Actions” claims it “will add a margin”, but doesn’t

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/vanilla-framework#2986]
[The Notification “Actions” reference](https://vanillaframework.io/docs/patterns/notification#actions) says: “Notifications have the ability to add an action link to them. These should appear inline with the notification response and will add a margin between the link and content.”

The example shows that it does not add any noticeable margin between the link and the content. It’s just normal word spacing.

![image](https://user-images.githubusercontent.com/19801137/79546681-bcd2df80-808a-11ea-96fd-bf229f876fa8.png)

Either it should add a margin, or it shouldn’t claim that it does.

**Comment by bartaz** [comment]
Yes, looking at the code it seems that all we do is making sure there is at least a single space between action and text:

https://github.com/canonical-web-and-design/vanilla-framework/blob/1f1c055f0c254b3b8ead7745780b645b703ef6c1/scss/_patterns_notifications.scss#L55-L58

We probably shouldn't call it "margin" in the docs.

**Comment by anthonydillon** [comment]
I wonder if we should extend this pattern to have a more true stylised call to action styling? We might want two actions aswell?

**Comment by bartaz** [comment]
@anthonydillon I think I've heard notifications mentioned by Claudio and Cristina as one of patterns to work on future from design/UX point of view. So seems like it is already in the backlog of things to look at across our products.

**Comment by lyubomir-popov** [comment]
Part of the plan for the UX/UI work is to make it modular, e.g. with/without card. 
Once it is modular, any of the existing CTAs would be possible, with some recommendations around defaults, alignment, etc.
