### ISSUE TITLE
"Selected blue" exploration

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#2987]
The current selected blue used in jaas.ai doesn't provide enough contrast against the vanilla link blue to meet AA accessibility standards.
Due to its hue, it is also prone to becoming invisible on low quality displays, projectors, etc.

Would be helpful to compare against what others use and how they avoid this kind of issue, and propose alternatives.

**Comment by lyubomir-popov** [comment]
comparison of blues used in other design systems - dark blue is the main call to action/primary button blue, lighter color for text selections:

![image](https://user-images.githubusercontent.com/2741678/79558168-a719e600-809b-11ea-9a14-fd0e4be91951.png)

**Comment by lyubomir-popov** [comment]
Link to proposal: https://zpl.io/blY0Dmz

Placing in review to encourage people to look and provide feedback on the direction, as I continue to explore.

**Comment by lyubomir-popov** [comment]
I've updated the exploration with final colour values and more examples on u.c, snapcraft, jaas, vanilla forms example page.

**Comment by spencerbygraves** [comment]
@lyubomir-popov 👍
