### ISSUE TITLE
Modular table drag and drop - more prominent drop targets

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#2991]
@lilyvidenova commented that the drop targets in the modular table are not prominent enough:

Before:
![image.png](https://images.zenhubusercontent.com/59d2496bb0222d5de479ea17/e8e913db-98cb-4e35-995c-0c290c7ef5f8)

After:
![image.png](https://images.zenhubusercontent.com/59d2496bb0222d5de479ea17/ca968cd5-aa98-4862-971d-330473f41d6b)

**Comment by lilyvidenova** [comment]
Still subtle but less so - nice stuff, thanks @lyubomir-popov
