### ISSUE TITLE
Vanilla website should be always deployable

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#3001]
We should make sure webteam can update and deploy Vanilla website possibly at any time (for example when Docker images are updated).

Currently site can only be reliably deployed just when Vanilla package is released.

We need to find solution for that.

Possible options:

- separate feature branches
- release branches
- every merge to master gets released to npm automatically
- anything else?

**Comment by SirSamTumless** [comment]
The issue with the Vanilla project is that you can't just deploy master as a website as it is a library. What do we want to do? Is our process to divergent from the other sites.

**Comment by nottrobin** [comment]
I guess we need a brainstorming session 🙂

**Comment by bartaz** [comment]
Meeting notes: https://github.com/canonical-web-and-design/meeting-notes/issues/761
