### ISSUE TITLE
Consider speccing red text for failure, untinted text warning / success messages

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#3005]
@clagom Pointed out the use of icons here is excessive, and suggested keeping the jaas red for errors/ fail status messages, while leaving warngin/sucess messages untinted. Worth exploring this or other alternative ways to reduce the number of icons.

![image.png](https://images.zenhubusercontent.com/59d2496bb0222d5de479ea17/34cd6d05-913c-490a-bb8a-4b82b2742317)

**Comment by matthewpaulthomas** [comment]
It might help to decide whether the ꕕ icon represents an error, a status, or a model.

If it represents:
- An error, then it would belong together with the error message (left-aligned with the model name), and could therefore be removed from the “Status” column.
- A status, then it would belong together with the status text (in which case “Running” should have a less-prominent icon), and could therefore be removed from the “Model” column.
- A model, then it would belong together with the model name (in which case all non-blocked models should have less-prominent icons), and could therefore be removed from the “Status” column.

**Comment by lyubomir-popov** [comment]
We need to have a UX discussion to decide how we want this to work, and then document it.

**Comment by clagom** [comment]
The use case seems to be slim at the moment
