### ISSUE TITLE
Loading of embedded examples moves the page when loading specific section

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#3017]
Follow up to #3015

When navigating to specific section of the docs (for example https://vanillaframework.io/docs/patterns/navigation#side-navigation) on slower connection the CodePens loading later make page move and given section is no longer on top of the screen.

**Expected behavior**

When navigating to specific section it should be scrolled to regardless of CodePen loading.

We could make the wrapper div around CodePen reserve the space before the CodePen loads.

**Comment by lyubomir-popov** [comment]
@bartaz Is this still an issue?  Isee space reserved and nothing moves:

<img width="1680" alt="Screenshot 2020-10-15 at 13 52 00" src="https://user-images.githubusercontent.com/2741678/96128748-aac4e300-0eed-11eb-970f-2d93a193b029.png">

**Comment by bartaz** [comment]
We can try to scroll to correct position after frames are loaded.

**Comment by bartaz** [comment]
Scope:
- try to see if scrolling into position after loading examples will work
- or find another solution
