### ISSUE TITLE
More visibility of current version on vf.io homepage

### ISSUE THREAD

**Issue by barrymcgee** [canonical-web-and-design/vanilla-framework#3032]
On a semi-regular basis, I need to know what the latest version of Vanilla is... currently the quickest way for me to find this is to go directly to the npm homepage or alternatively, I can go to https://vanillaframework.io/docs, scroll to "Hotlink" and see what the last 3ish digits of the URL bar are...

Now that we have a unified codebase, could the latest version of the lib be displayed more prominently on the vf.io homepage?

E.g 

<img width="1978" alt="Screenshot 2020-04-30 at 08 50 45" src="https://user-images.githubusercontent.com/505570/80686100-1fcb6a00-8ac0-11ea-9c4b-212f6809d9fa.png">

**Comment by anthonydillon** [comment]
I think this is something the project sites such as multipass.run and juju.is would benefit from too.

**Comment by lyubomir-popov** [comment]
How about in the button, we already do that in the docs section:

![image](https://user-images.githubusercontent.com/2741678/80687727-a3865600-8ac2-11ea-95da-dc5abe77b09f.png)

**Comment by bartaz** [comment]
It's in the footer on all pages.

We can bring it back to the Download button. Now that site is together with docs it's a trivial change.

**Comment by anthonydillon** [comment]
Could do that but is probably not going to work for other sites?

**Comment by lyubomir-popov** [comment]
The footer sounds like the right place for something like this. But if we want it more prominent, maybe something like this?

![image](https://user-images.githubusercontent.com/2741678/80690598-f235ef00-8ac6-11ea-8201-180d9ba7c08d.png)

**Comment by matthewpaulthomas** [comment]
> I think this is something the project sites such as multipass.run and juju.is would benefit from too.

Yes, the multipass.run equivalent is [multipass.run#55](https://github.com/canonical-web-and-design/multipass.run/issues/55).

> Could [put it in the button] but is probably not going to work for other sites?

Is there any crossover between “sites that don’t, and shouldn’t, have a download/install button” and “sites where it’s relevant to know the version”? (netplan.io and mir-server.io don’t have a download/install button, but both feel like they should.)

**Comment by anthonydillon** [comment]
I believe we should have a consistent template for project sites such as these.

**Comment by bartaz** [comment]
For now we will just add it to the button.
