### ISSUE TITLE
Twitter share button page does not exist

### ISSUE THREAD

**Issue by solazio** [canonical-web-and-design/vanilla-framework#3035]
**Describe the bug**

Go to https://vanillaframework.io/docs/patterns/icons#social and click on the `Twitter` button in the "Share" section. The page does not exist.

We should replace the link to take you to https://developer.twitter.com/en/docs/twitter-for-websites/tweet-button/overview instead

**Comment by lyubomir-popov** [comment]
This now takes you to the correct page, closing.
