### ISSUE TITLE
Make new icons available

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#3039]
Now that there's a final set of icons, we need to make the icons that are not part of vanilla  available. Whether on npm as a separate package or some place else.

**Comment by bartaz** [comment]
I would split this into 2 tasks (maybe inside "New icons" epic).
One to update existing icons (maybe separate one for external link icon, because it requires transforming it to CSS mask and testing) and separate one to figure out the place for rest of the icons.

**Comment by lyubomir-popov** [comment]
I've taken the update vanilla icons out and created a separate [issue](https://github.com/canonical-web-and-design/vanilla-framework/issues/3040) for it.

**Comment by hatched** [comment]
Hey folks, any updates on this?

**Comment by bartaz** [comment]
@hatched Seems like no one needed it before, so it never got up in the queue. I will bump the priority, as I've seen the comments from Spencer on JAAS that you would like to have more icons.

Any particular ones that you need? May be quicker to add and release smaller set than the whole 100+ icons.
