### ISSUE TITLE
Links in dark/accent strips are not readable enough

### ISSUE THREAD

**Issue by MikkCZ** [canonical-web-and-design/vanilla-framework#3041]
**Describe the bug**

When a link is present anywhere inside `.p-strip--dark`, `.p-strip--accent` or `.p-strip--image.is-dark`, it is in blue color and not much readable on the dark background.

**To Reproduce**

1. Have some code like
```html
<section class="p-strip--image is-dark" style="background-image: ...;">
  <div class="row">
    <div class="col-6">
      <p>
        Paragraph <a href="/url/link">Link text</a>
      </p>
    </div>
  </div>
</section>
```
2. The paragraph text is white, however the link text is blue.

**Expected behavior**

Both the paragraph AND the link text should be white (or in light colours).

**Additional context**

I hit this issue with `https://assets.ubuntu.com/v1/vanilla-framework-version-2.10.1.min.css` when trying to use it on Ubuntu.cz. I used [the following CSS snippet as a workaround](https://github.com/UbuntuCZ/ubuntu-cz/blob/850dd60b4e81954a9806c3c2782e6fa7c17d673b/design/ubuntu-cz.css#L2).
```css
.p-strip--dark a,
.p-strip--accent a,
.p-strip--image.is-dark a {
  color: white !important;
}
```

**Comment by MikkCZ** [comment]
Note: if there is `.p-card--overlay` wrapping the link, the white colour is not actually desired, as the overlay provides light background for the text.

**Comment by bartaz** [comment]
Hi @MikkCZ, thanks for reaching out.

Link don't change color automatically in dark stips (like the text does), but we have a specific "inverted" link variant designed for dark backgrounds: https://vanillaframework.io/docs/patterns/links#inverted.

It does almost exactly what you did (changes link color to off-white).

**Comment by MikkCZ** [comment]
Thank you, I didn't know that and will use that as better workaround instead.
