### ISSUE TITLE
Better and more consistent documentation about color themes

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#3055]
As a follow up to #3051

We should improve documentation about color themes. There should be a dedicated separate page for theming details, or existing section on color settings page should be improved.

Documentation pages of components that implement themes should all contain consistent section describing how to use theme with given component.

**Comment by clagom** [comment]
Related to https://app.zenhub.com/workspaces/-vanilla-squad-59438c953747487777fbe484/issues/canonical-web-and-design/vanilla-framework/3301

**Comment by lyubomir-popov** [comment]
Duplicateof #3301
