### ISSUE TITLE
Old docs links not redirected

### ISSUE THREAD

**Issue by deadlight** [canonical-web-and-design/vanilla-framework#3056]
When visiting the URL `https://vanillaframework.io/docs/en/patterns/muted-heading` I get a 404 rather than a redirect to the new location of the page

**Comment by bartaz** [comment]
@deadlight This seems like a very old links (even pre docs.vanillaframework.io) - have they been ever redirected? I don't see any trace of that.

What was the structure of URLs back then? `/docs/en/[docs path]`?

**Comment by deadlight** [comment]
Yeah, I think it was basically the same paths but with the language string.
I came to this myself because it was indexed by Google.

**Comment by bartaz** [comment]
@nottrobin @tbille What's the best way to do it? In Flask app of the project? deployment configs? Do we have anything similar in other projects I can steal from?

**Comment by nottrobin** [comment]
@bartaz the site now uses flask-base right? In that case it should have native support for `redirects.yaml`. look at that file in the Ubuntu.com codebase, for example.

**Comment by bartaz** [comment]
@nottrobin Great, thanks - that should do it.

For my own record, this seems closest to what we need:
https://github.com/canonical-web-and-design/ubuntu.com/blob/c2b178dbb306736942c022b75a6c3bf5696a8b16/redirects.yaml#L828
