### ISSUE TITLE
Input borders do not meet 3:1 contrast ratio against white/light grey backgrounds

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#3057]
Input borders do not meet the minimum accessibility contrast ratio of 3:1 against white, #f7f7f7:

In addition, it should also meet the same ratio against the focus outline. Not sure if overlapping the border with the outline (as we do now) breaches that rule. TBD.

Reference article - https://uxdesign.cc/accessible-custom-focus-indicators-da4768d1fb7b

![image](https://user-images.githubusercontent.com/2741678/81566214-78d5b080-9392-11ea-94fb-a70e29dd55f1.png)

**Comment by lyubomir-popov** [comment]
(The closest accessible is #949494):

![image](https://user-images.githubusercontent.com/2741678/81566665-18933e80-9393-11ea-8780-40a227920052.png)

**Comment by matthewpaulthomas** [comment]
Darkening borders, of enabled controls, would also make them more distinct from disabled controls.
