### ISSUE TITLE
Inconsistent text colour

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#3062]
Most text in vanilla uses $color-dark, `#111`. There are a few outliers:

![image](https://user-images.githubusercontent.com/2741678/81828489-bd4b8280-9531-11ea-9288-9de582e8eecf.png)

@anthonydillon do know why? Should we make these consistent with the rest and use #111?

**Comment by anthonydillon** [comment]
Unsure why. Sure if they look ok.
