### ISSUE TITLE
Tabstrip black bar overlaps contextual menu

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#3068]
**Describe the bug**

The tab active bar overlaps the contextual menu:

 ![image](https://user-images.githubusercontent.com/2741678/81960850-792bb100-9609-11ea-8771-3747bb4861cb.png)

**To Reproduce**

Place a contextual menu and a tabstrip following it as in the screenshot.
Open contextual menu
Observe overlap

**Comment by bartaz** [comment]
This possibly should be fixed with #3079 and maybe provide an example to screenshot with Percy, as this issue was showing up as regression couple of times.
