### ISSUE TITLE
Nav bar and tabs are highlighted incorectly

### ISSUE THREAD

**Issue by solazio** [canonical-web-and-design/vanilla-framework#3073]
![image](https://user-images.githubusercontent.com/40214246/82218993-9c5da580-9914-11ea-806e-bd65fd084356.png)

![image](https://user-images.githubusercontent.com/40214246/82219022-a41d4a00-9914-11ea-87a6-97e6923d8da0.png)

We should avoid overlaps - however this might not be vanilla's fault. But we should make people aware of it.
![image](https://user-images.githubusercontent.com/40214246/82219533-4f2e0380-9915-11ea-8caa-e7fcba4062f1.png)

Some elements (middot list links) remain `focused` after you tab through them

![image](https://user-images.githubusercontent.com/40214246/82231817-a2a84d80-9925-11ea-9657-a36b0f657bb4.png)

**Comment by popey** [comment]
Sorry for the late reply, been on vacation. This still looks bad. 

![Screenshot from 2020-06-15 14-19-49](https://user-images.githubusercontent.com/1841272/84662173-572c9380-af13-11ea-87a2-55f48e955b8e.png)

**Comment by lyubomir-popov** [comment]
We've missed the tabstrip, sorry. Reopening.
