### ISSUE TITLE
Investigate publishing JavaScript as part of Vanilla npm package

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#3084]
As discussed with @bartaz @anthonydillon @lyubomir-popov 

To make sure projects have consistent implementation of JS required by Vanilla patterns we should experiment with providing JS code as part of vanilla-framework npm package.

Things to consider:
- it needs to work directly in the browser (without builds step)
- it needs to support importing into project JS
- ideally it should be possible to still inject JS into examples HTML (to make JS visible in CodePen embeds)
- importing SCSS from npm package should not be affected (should work as currently does)

**Comment by bartaz** [comment]
@anthonydillon Do you think its still something worth considering when we focus on React components?

It still would be useful for websites that don't use React, but it also means Vanilla would need to maintain 2 separate JS implementations: 'vanilla' JS, and React.

**Comment by anthonydillon** [comment]
Na I think its wise to leave the ES5 scripts as copy and paste so it's clear they are not supported by us. Just example solutions.
