### ISSUE TITLE
Receded interactive element text color

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#3085]
In scenarios where we avoid the use of blue to denote clickable, what would be an acceptable way to style a "receding" interactive element? At what point does a receding element risk bwing confused for a disabled element?

Is it ok to use grey `#666` and when?
- If part of a hierarchy like a side navigaiton / aside?
- If accompanied by a graphical element that hints at interactivity?

Some examples from material design:
![image](https://user-images.githubusercontent.com/2741678/82549496-ea60ec00-9b54-11ea-85ca-6cfa91854f70.png)

Material design also extensively uses grey links, and defines disabled state as an element with opacity 38%:
![image](https://user-images.githubusercontent.com/2741678/82549709-40ce2a80-9b55-11ea-8597-1864cecacda1.png)

Current difference between enabled/disabled in vanilla:
![image](https://user-images.githubusercontent.com/2741678/82552457-0d41cf00-9b5a-11ea-9990-ef4a7dab1e31.png)

**Comment by lyubomir-popov** [comment]
Another example of grey interactive element from gmail, accompanied with chevron: 
![image](https://user-images.githubusercontent.com/2741678/82552303-ba681780-9b59-11ea-8c13-7d312f752521.png)

**Comment by matthewpaulthomas** [comment]
Google Drive’s visual design is measurably awful: two similar typefaces, four different hover fill colours, at least five (!) different focus styles, and no (non-hover) distinction between clickable and unclickable column headings. So I don’t think we should treat, as a precedent, its mishmash of text colours: the directory heading is `#202124`, ‘New” is `#3c4043`, menu items are `rgb(95,99,104)` (= #5f6368), the “Name” column contents are `rgba(0,0,0,.72)` (≈ #484848 on white), and the other column contents are `rgba(0,0,0,0.54)` (≈ #767676 on white). And even if we did, I have no idea how we’d classify those five shades into “receded” and not. You couldn’t even draw a line between enabled and disabled: “Storage” is unclickable but exactly the same shade `rgb(95,99,104)` as the clickable labels above and below it!

Perhaps first we should collect use cases. The use case that prompted this was: “There aren’t any filters at the moment, but you could add some by clicking this button”. What others are there?

**Comment by lyubomir-popov** [comment]
We discussed that interactive elements can only be grey if the context makes it abundantly clear, as part of a navigation pattern for example. As such, the color is decided on pattern level, so this issue is not needed any more. Closing.
