### ISSUE TITLE
<b> inside <code> gets lost

### ISSUE THREAD

**Issue by Saviq** [canonical-web-and-design/vanilla-framework#3112]
In a handful of places in [the discourse post](https://discourse.ubuntu.com/t/using-virtualbox-in-multipass-on-macos/16591#bridging) I used `<b>` inside `<code>` to emphasize an item in the code listing.

It can be seen fine in Discourse:
![image](https://user-images.githubusercontent.com/231077/83736838-79402f00-a652-11ea-990d-5393f15f1d06.png)

But gets lost in the transition to [the doc page](https://multipass.run/docs/using-virtualbox-in-multipass-macos#bridging):
![image](https://user-images.githubusercontent.com/231077/83736891-89f0a500-a652-11ea-89d8-053105f11dca.png)

All `<code>` in the docs is `bolder`, so we'd need a `font-weight: 1000` or so for `code b`:
```css
code b {
  font-weight: 1000;
}
```

**Comment by bartaz** [comment]
Yes, seems like our default `bolder` value for font-weight is not enough with Ubuntu Mono.

We would need to bump it to 600 (or `bold`):
https://codepen.io/bartoszopka/pen/rNxavLv

<img width="369" alt="Screenshot 2020-06-05 at 07 52 55" src="https://user-images.githubusercontent.com/83575/83841756-c3ccb480-a701-11ea-85d9-7b66ac6f0c41.png">

**Comment by matthewpaulthomas** [comment]
As a bonus, changing `b`, `strong`, and `dt` to 600 or higher would also fix #2272.

**Comment by SirSamTumless** [comment]
Note; scope this to code, rather than font.
