### ISSUE TITLE
Field validation messages/errors are inconspicuous and easy to miss

### ISSUE THREAD

**Issue by Roadmaster** [canonical-web-and-design/vanilla-framework#3134]
**Describe the bug**

The vanilla style for errors is to highlight the field and describe/detail the error below the field:

https://vanillaframework.io/docs/base/forms#validation

However, since we vanillified Ubuntu SSO, we've received numerous complaints/requests for help from users who input invalid data in the form and then can't tell what's wrong with their input. This is  likely because the top "there are some errors in your form" message  attracts the eye while the entirely-unstyled per-field descriptions do not in any way (the type is small and there's no color difference).

We've had a [couple](https://bugs.launchpad.net/canonical-identity-provider/+bug/1864899) of [bugs](https://bugs.launchpad.net/canonical-identity-provider/+bug/1863645) filed on Ubuntu SSO describing this issue; 2 bugs with 4 affected people sounds like very few, but the error is most common when creating an SSO account at which point they can NOT file a bug, they can only email me for support); I can anecdotally tell you that the SSO support queue gets maybe 4 weekly requests for people for whom all I do is look at their screenshot and re-type what the error message says. People I've helped will not file a bug, which is why I thought it OK to quote the anecdata.

Form errors should NOT require an interpreter :)

Here is [an example](https://private-fileshare.canonical.com/~hasanammar/sso-errors.png), Hasan worked on styling the fields themselves a bit so they do show the red X if they have a problem, but on first glance the error descriptions just look like a chunk of extra text and are very easy to miss after a reload.

An example of error descriptions that use colors to highlight what needs fixing even if the font size is as small as Vanilla's:

https://getbootstrap.com/docs/4.5/components/forms/#server-side

**To Reproduce**

1. Foist this on an unsuspecting user. *You* already know what to expect :) but a regular user won't.
2. Go to 'https://login.ubuntu.com'
3. Ask them to create an account. Maybe suggest to them behaviors that will result in error, such as as noncompliant username (JohnIsGreat17 will work)
4. Watch in glee as they writhe while trying to figure out what the hell they typed wrong even though it's right there - sure enough if you ask them to pause and read very carefully they will figure it out, but something as critical as an error should just attract the attention/eye of the user.

**Expected behavior**

Users are able to quickly spot errors. At this point, if the problem description is unclear the onus is on me to fix it :) but the clearest description in the world is useless if users can't easily spot it.

To be clear, we can totally "hack" the styling of the message and make the errors in Ubuntu SSO very obvious (red/blinking/etc) but I would prefer to adhere to Vanilla recommendations as much as possible; that said, the issue I want to bring to attention is that the error styling which Vanilla recommends has the problems described above and it might be generally helpful if this were changed globally to something more visible.

**Screenshots**

( A few are provided above)

**Desktop (please complete the following information):**

 - (I think all platforms are affected)

**Smartphone (please complete the following information):**

 - (I think all platforms are affected)

**Comment by lyubomir-popov** [comment]
Hi, just trying to get to the core of the issue here, are we talking about this bit:
![image](https://user-images.githubusercontent.com/2741678/85316292-6cc23000-b4b4-11ea-96af-4fde426933ac.png)

If so, it is actually not the official validation styling used in Vanilla framework. The official one looks like this:
![image](https://user-images.githubusercontent.com/2741678/85316545-d8a49880-b4b4-11ea-9543-2271341455b1.png)

**Comment by lyubomir-popov** [comment]
And, if you're wondering why we don't colour text as bootstrap do, it's because it wouldn't satisfy the WCAG AA contrast ratio requirement  of 4.5:1. 

Bootstrap doesn't seem to aim for AA complience:
![image](https://user-images.githubusercontent.com/2741678/85316914-76986300-b4b5-11ea-9d57-e4df77f7e029.png)

Still, the combination of coloured border plus bold keyword "Error" in the validation message should suffice.

**Comment by Roadmaster** [comment]
Thanks for your reply!

Hasan did some work to align styling to what you showed (see screenshots linked above); indeed what was missing was changing the errored fields' border color and adding the red X. That does make the fields themselves stand out, which should help as you say. We'll go ahead and merge/deploy that ASAP.

I would still like to make the messages themselves stand out in some way. There is new text on the page which we need to call attention to. "Users don't read" applies here, though I'd nuance it as "users don't read anything they thing they've already read", so I would like to go the extra mile and highlight the text in other ways if possible.  Is there anything we can do that would satisfy that contrast ratio thing, like using a darker shade of green? If use of color is discouraged for accessibility reasons (which is fair), surely there are other patterns we can use?

We're open to any suggestions, and as mentioned we'll deploy the changes we've already made and we'll let you know if people are still encountering this issue.

**Comment by anthonydillon** [comment]
For a bit of background on this one. We would always like to use Vanilla's form validation. Forms should not use the notification pattern to indicate errors.

While working on SSO that would have required a rewrite of the form generator to wrap the fields in correct elements and classes. 

We planned to cover these updates in phase 2. Therefore, I believe this issue should involve converting all form validation to true form validation.

**Comment by Roadmaster** [comment]
Hello! Thanks for the extra clarification.

I filed this as a generic vanilla issue but if it's more of a "SSO is using vanilla wrong / in a strange way and wrangling it into using vanilla properly is going to be more work" and there are NO changes needed on vanilla, then I'm OK to close the issue - the SSO problems themselves are properly tracked on Launchpad.

We still need to do something regarding the non-obvious field errors, but per previous discussion we are OK with doing the errored field highlighting which I believe is needed anyway, and seeing whether that helps curb the constant flow of irate/sad users asking for help :)

**Comment by matthewpaulthomas** [comment]
I was helpfully distracted by these glitches from the screenshot:

![image](https://user-images.githubusercontent.com/19801137/85391724-76927480-b542-11ea-8778-a0e8cf12cb36.png) ![image](https://user-images.githubusercontent.com/19801137/85391774-8447fa00-b542-11ea-9b0f-ade87fecc21d.png)

These are, I think, Safari and Lastpass respectively offering to fill in the fields for you. 1Password, Dashlane, and probably other password managers, put UI in the same place. Why is this relevant? Because if we want to avoid colliding with them, the error icon should go somewhere else. So where could it go?…

> I would still like to make the messages themselves stand out in some way.

…It could go at the start of the error message instead. Solving two problems in one.

**Comment by Roadmaster** [comment]
Hi Matthew,

Hasan said he simply applied the appropriate vanilla style, he didn't decide on the position of the icon. Is this something then that should be fixed on vanilla itself so the icon appears on the left side of fields?

Let us know; if this will be tweaked in vanilla at some point it might make more sense to wait for that.

**Comment by bartaz** [comment]
@Roadmaster 

Matthew has a good suggestion, but it make take some time before it gets into Vanilla.

In the meantime we can have a look at https://bugs.launchpad.net/canonical-identity-provider/+bug/1864899 https://bugs.launchpad.net/canonical-identity-provider/+bug/1863645 and help with that.

**Comment by matthewpaulthomas** [comment]
@Roadmaster Since there was a separate SSO bug report, I posted SSO-specific suggestions there, Vanilla suggestion here.

**Comment by lyubomir-popov** [comment]
- require a validation message, and add the icon in front of the message. Left aligned with the input which is highlighted with an error/warning border

**Comment by bartaz** [comment]
Some UX consultation needed with [accessibility in mind](https://github.com/canonical-web-and-design/vanilla-framework/issues/3324):

- label of field with error should be marked
- we want icon outside of the input field (next to error message)

**Comment by bartaz** [comment]
This have been through WG before, but because it needs UX work we should pass it though our new process.

**Comment by clagom** [comment]
After reading all the comments, I think the proposed solution makes sense:

- label of field with error should be marked
- we want icon outside of the input field (next to error message)

Considering this accessibility requirement:
https://github.com/canonical-web-and-design/vanilla-framework/issues/3324

I think this is related (even if not directly) to the epic assigned to @wgx and @AnnSoMuller and would propose to merge this with the spec of that piece, including benchmarking and research around form labels, mandatory fields and error messages:
https://app.zenhub.com/workspaces/-vanilla-squad-59438c953747487777fbe484/issues/canonical-web-and-design/vanilla-framework/3766

Adding this issue to that epic.
CC @bartaz @lyubomir-popov @ziheliu214

**Comment by wgx** [comment]
Closing, resolved by work here: https://github.com/canonical-web-and-design/vanilla-framework/issues/3766
