### ISSUE TITLE
Add the required css to use Chip in react-components

### ISSUE THREAD

**Issue by solazio** [canonical-web-and-design/vanilla-framework#3143]
Currently the [Chip](https://github.com/canonical-web-and-design/react-components/tree/master/src/components/Chip) component in `react-components` is using some custom css.
Would be good to add the styling to vanilla so we can remove the custom styling in `react-components`.

**Comment by bartaz** [comment]
I guess work on the chip and search and filter is still in progress, so I'll leave that for @anthonydillon and @barrymcgee to propose CSS when it's completed (or just notify us when we can start looking into it).

**Comment by anthonydillon** [comment]
@solazio This work is planned soon.
