### ISSUE TITLE
Add the required css to use SearchAndFilter in react-components

### ISSUE THREAD

**Issue by solazio** [canonical-web-and-design/vanilla-framework#3144]
Currently the [SearchAndFilter](https://github.com/canonical-web-and-design/react-components/tree/master/src/components/SearchAndFilter) component in `react-components` is using some custom css.
Would be good to add the styling to vanilla so we can remove the custom styling in `react-components`.

**Comment by bartaz** [comment]
I guess work on the chip and search and filter is still in progress, so I'll leave that for @anthonydillon and @barrymcgee to propose CSS when it's completed (or just notify us when we can start looking into it).

**Comment by SirSamTumless** [comment]
@anthonydillon or @barrymcgee Are you guys planning on doing this?

**Comment by anthonydillon** [comment]
Sorry, I wasn't assigned and so, was not on my list. I will assign myself and try to get to it

**Comment by SirSamTumless** [comment]
Any progress on this?
