### ISSUE TITLE
In IE text in an icon is partially visible.

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/vanilla-framework#3162]
## Pattern to amend
`%vf-hide-text`

## Visual
<img alt="Screenshot 2020-07-09 at 10 13 57" width="185" src="https://user-images.githubusercontent.com/83575/87014864-03892f00-c1cd-11ea-9d07-0bfa4b9d04bb.png">

## Context
In IE text in an icon is partially visible. This is an issue with `%vf-hide-text`. IE does not support transitioning values set with `calc()`  therefore a solution could be to switch to using `2vw`. I will tackle that as a separate issue

**Comment by SirSamTumless** [comment]
Blocks the chip work.
