### ISSUE TITLE
🦛 Improve examples embedded in the docs  

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#3171]
**Team**:
{Project lead: Bartek}
{Requested by: Internal}
Initial size estimation:
Dev: {M 3 weeks}
Design: {S 1 week}
Deliverables:
Improved embedded examples for Vanilla docs

**Dependencies**:
- Code Snippet needs to be completed.
- Grid break-out may be a solution to the width problems.
Elevator pitch / short description
Improved embedded examples in the Vanilla docs using our own solution so we don't have to rely on CodePen.

MVP - having the code snippet showing the example, with the ability to switch between HTML and CSS, with the example rendered by it.
References
Here should contain a list of links to any reference documentation, designs, copy docs, master epic, etc.

GDrive; https://drive.google.com/drive/folders/1noOAsz_s4dqt0vH1Yh7W_knLcXKicQY1 
Existing; https://vanillaframework.io/docs/patterns/accordion

________________________________
This is a follow up of the discussion with @hatched on CodePen performance and UX of the embedded examples.

There are several issues we have with CodePen currently:

- it's slow to load - sometimes it may take 10-20 seconds to fully load all the examples on some docs pages (especially in areas with slower bandwidth)
- it sometimes breaks - during last 6 months there've been at least 3 times when CodePen embeds stopped rendering completely due to the issue on CodePen side, the issues were not noticed by them until we notified their support - but they usually solved them immediately (within hours)
- we can't control the layout of the embeds, so for example we can't show the code under the rendered example and because of that we hide code by default, and user needs to know where to click to show HTML markup (which is far from ideal UX)
- because code panels are built-in into CodePen embeds we can't make the embeds small, even if example is just a single button (because this will leave very little space for code panel), this results in unnecessarily big empty boxes (see: https://vanillaframework.io/docs/patterns/labels)

On the other hand there are several things that CodePen embeds gives us for "free":

- rendering encapsulated examples from the code that is maintained in Vanilla codebase
- out of the box support for showing HTML, CSS, JavaScript code of the examples, with possibilities for pre-processors such as SASS or potentially React
- out of the box code highlighting in the panels
- 'Edit in CodePen' functionality that allows easy access to editable examples on CodePen for testing, exploring, creating test cases

@hatched suggested that maybe instead of embedding examples via CodePen we could render them directly in HTML of the documentation. While it was difficult historically when Vanilla docs have been a static site, now when it's a full Flask webapp we could get back to explore the idea, as we could create examples as partial templates (that we already do for some more complicated ones) and include them where we need to:

- in docs to render example
- in docs to render the code of the example
- in the example pages for screenshots (with full Vanilla and standalone CSS)

This is not a trivial task and will require several things:

- exploring including examples via Flask - does it work, what does it involve, what is the impact on `.md` files in the documentation
- consider what to do with bigger 'full-page' examples (such as documentation layout) that require to be embedded in separate document
- design the example component - how does the example with code (HTML, CSS) look like, code highlighting etc
- consider future of example component with React examples
- build the example component - (panels for HTML/CSS, code highlighting, opening in CodePen, etc)
- and future maintenance of that

As this is a bigger task I think we should consider it as a roadmap proposal for next cycle.

**Comment by hatched** [comment]
This was a great issue, thanks @bartaz you beat me to it :)

I just wanted to add an example page from another framework that I thought worked quite well: 
- https://bulma.io/documentation/components/modal/
- https://bulma.io/documentation/components/card/
