### ISSUE TITLE
Enhancments to chip overflow

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#3192]
## Pattern to amend

The current chip proposal may result in the "dismiss" button overflowing and not being visible. Creating this issue so we can  merge the proposal, then consider the best approach to solve this. 

For some context - all elements inside the chip are display:inline, with the chip itself inline-block. This ensures wrapping happens as expected. However, It means a simple overflow on the parent hides the dismiss button. In itself, this can easily be acheived with a flex layout, but that would cause vertical align issues and wrapping issues.

![image](https://user-images.githubusercontent.com/2741678/88687576-5bda8f00-d0f0-11ea-8038-924cd59b1a93.png)

The simplest solution I can think of is to wrap the text in a div, whose width is equal to the parent minus the width of the buttton.

**Comment by anthonydillon** [comment]
Sorry, on second thoughts. I think this should be a critical issue (blocking release) because if this is likely to cause a markup change to the pattern. We should do it before it's released, to save early version bumps or supporting complicated deprecated legacy mark up.

**Comment by anthonydillon** [comment]
As its the end of the iteration it should be set to the next milestone and I'm not 100% sure the estimate.

**Comment by lyubomir-popov** [comment]
I can fix it in minutes if you're ok with the wrapper?

**Comment by lyubomir-popov** [comment]
@anthonydillon got it to work without a wrapper, as long as overflow is only expected on the value. The lead will break things:

![image](https://user-images.githubusercontent.com/2741678/88787045-2fc01c00-d18b-11ea-832c-f34b6e5ed7f5.png)

To get the leasd to also wrap, I need to limit its width with a max-width. Should I do it? What would be a sensible value - have you come across leads that are longer than the value?

![image](https://user-images.githubusercontent.com/2741678/88787161-5a11d980-d18b-11ea-89cd-959a669cf85b.png)
