### ISSUE TITLE
Docs has invisible gap between panes and footer

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/vanilla-framework#3197]
Vanilla docs pages appear to have two white panes followed by a grey footer.

What they actually have, however, is two white panes followed by a 64-pixel white strip, followed by a grey footer.

This white strip has a couple of unfortunate effects:

- There is nothing indicating the bottom of the sidebar, so the last item currently in view often looks like it’s being clipped accidentally.
  > ![image](https://user-images.githubusercontent.com/19801137/89167320-2bbd4100-d573-11ea-860a-374950383727.png)

- The start of the grey area looks like the end of the scrollbar trough, but it isn’t, misleading you about how far you can scroll. (Initially I thought my trackpad was being unresponsive.)
  > ![image](https://user-images.githubusercontent.com/19801137/89167884-e77e7080-d573-11ea-8584-68c423844654.png)

This is a regression: the previous layout did not have this gap.

> ![image](https://user-images.githubusercontent.com/19801137/89167552-78088100-d573-11ea-82cb-e5a766f380d9.png)

**Comment by bartaz** [comment]
Side navigation is not sticky or scrollable by default now, so this should not be an issue anymore.
