### ISSUE TITLE
No default for labels

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/vanilla-framework#3201]
There should be a default label pattern (I recommend a grey one). If you use `p-label` there is no styling.

**Comment by matthewpaulthomas** [comment]
Vanilla is currently consistent with most other toolkits here: labels use the same typeface, size, weight, and color as non-label text.

[In #2848](https://github.com/canonical-web-and-design/vanilla-framework/issues/2848#issuecomment-618985821) I suggested using grey to mean “this is a label for something that isn’t editable right now” — whether it’s the label for a disabled control (also common in other toolkits), or the label for data that is never editable.

**Comment by lyubomir-popov** [comment]
- Agreed to resolve independent of https://github.com/canonical-web-and-design/vanilla-framework/issues/3126

- Things to explore: roundedness of corners, tag shape, e.g. clothes tag, shapes suggested by @matthewpaulthomas in https://github.com/canonical-web-and-design/vanilla-framework/issues/3126, or plain gray shapes

**Comment by anthonydillon** [comment]
Has there been any movement on this issue?

**Comment by lyubomir-popov** [comment]
No, Not to my knowledge. 

@gomboli should this move through the new UX WG pipeline? 
@anthonydillon where would this be used? We have existing rules around making labels gray in MAAS for example (for uneditable fields), so we'd need to know what exactly this is intended for. Can you point me to a few cases where you might want to use it but have resorted to local solutions?

**Comment by anthonydillon** [comment]
This came up when looking at the new UA wireframes. Mostly this is to cover the missing default usage of this pattern which is unique to labels at the moment.

**Comment by lyubomir-popov** [comment]
Sounds like a small task, adding to this iteration and I'll ping you tomorrow with some quesitons.

**Comment by lyubomir-popov** [comment]
We had a meeting with @anthonydillon @ziheliu214 @bartaz, and agreed to:
- provide a default (grey) sufficiently distinct from the chip component, to avoid confusion
- create a followup [issue](https://github.com/canonical-web-and-design/vanilla-framework/issues/3800) to define when to use / when not to
