### ISSUE TITLE
Option to remove scrollbar in side-nav

### ISSUE THREAD

**Issue by carkod** [canonical-web-and-design/vanilla-framework#3206]
## Pattern to amend

Requested option to remove scrollbar on Side Navigation, when the content exceeds the height of the container

## Visual
![Screenshot from 2020-08-14 16-58-04](https://user-images.githubusercontent.com/14939793/90264605-9f076280-de51-11ea-8a94-73a3c572e025.png)

## Context

This request came from Anbox-cloud to remove scrollbar on the left side of the navigation. This could easily be done I suppose by adding a modifier to opt out of the sticky position

**Comment by lyubomir-popov** [comment]
- Agreed to add the alternative behaviour as an option with a modifier
- Once we do, either wait for complaints with the other opion, or do an AB test, or look for objective measurable analytics results (?)
- Flat version should be default, limiting height and scrolling within should be added with a modifier
