### ISSUE TITLE
🦍 Notifications

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/vanilla-framework#3210]
Spec

- [Spec](https://docs.google.com/document/d/1UoPy90NPc1atnGPs1drx5YA90vlPQQU5Pvb5Yt_bKkI/edit#heading=h.jnm96uld08h1)
- [Drive](https://drive.google.com/drive/folders/1nJTxqp2Cwflc9P84D51i4WVG35frKEyK)

**Comment by SirSamTumless** [comment]
@wgx I had made epics based on the phases with issues under them. When you pick them up next week, would you mind moving the epics into "Iteration epics" and the issues into "current iteration" as well as assigning them to the milestone "iteration 20-36"?

**Comment by SirSamTumless** [comment]
Do you think this is fine to be designed @wgx ?

**Comment by wgx** [comment]
@SirSamTumless I think if there's capacity, we should definitely do some visual design explorations of it. 👍🏽

**Comment by lyubomir-popov** [comment]
@wgx I'm due to start on this next iteration and we were wondering if the UX complete? Also according to the planning doc this is the final [spec](https://docs.google.com/document/d/1UoPy90NPc1atnGPs1drx5YA90vlPQQU5Pvb5Yt_bKkI/edit#heading=h.jnm96uld08h1) right?

**Comment by wgx** [comment]
@lyubomir-popov yes please! :)

**Comment by lyubomir-popov** [comment]
@wgx great, thanks!

**Comment by lyubomir-popov** [comment]
sorry didn't notice this was a master epic and closed by mistake
