### ISSUE TITLE
Notification action - should we replace the word "dismiss" with [x] icon?

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#3211]
The usual way to close something in many vanilla components is an [x] icon - e.g. modal, the upcoming panels, etc.

The notificaiton - action uses a "Dismiss" link. Is there a reason it is not using a close [x] icon?

**Comment by lyubomir-popov** [comment]
- Modify example to show both an action and a close, separately: e.g. Action settings at end of text, close button to the right.

**Comment by wgx** [comment]
@lyubomir-popov Some of the work I'm currently doing will affect this pattern, I should be able to deliver something useful in the next couple of weeks.

**Comment by lyubomir-popov** [comment]
That's great @wgx, we'll wait.

**Comment by bartaz** [comment]
We should just do it (similar to modal, etc).
Get UX review.

**Comment by wgx** [comment]
👍🏼  A close icon 'X' seems totally fine to me and is a widely-used pattern.
