### ISSUE TITLE
 UX: Benchmarking

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/vanilla-framework#3236]

**Comment by wgx** [comment]
Doc: https://docs.google.com/document/d/1vY0RZOSETXv5bn7kGX8b45SpJYfMc6MacRTHtdkx0K0/edit

**Comment by lyubomir-popov** [comment]
Looks great, added a couple of questions of things we have had / considered in the past, wonder if you've seen anything like that anywhere else.
