### ISSUE TITLE
 UX: User Stories

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/vanilla-framework#3241]

**Comment by wgx** [comment]
**User stories are part of this spec doc**: https://docs.google.com/document/d/1UoPy90NPc1atnGPs1drx5YA90vlPQQU5Pvb5Yt_bKkI/edit#

**Comment by wgx** [comment]
**Miro**: https://miro.com/app/board/o9J_kmE7rLM=/?moveToWidget=3074457349872343115&cot=12
