### ISSUE TITLE
https://vanillaframework.io/contribute needs to be updated

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#3259]
Bonus - include all contributors.

**Comment by barrymcgee** [comment]
Extra bonus - pull all contributors from the Github API every time the site is built - https://developer.github.com/v3/repos/#list-repository-contributors

**Comment by anthonydillon** [comment]
@barrymcgee Sounds like an interesting second task.

**Comment by tbille** [comment]
Not required on build. The site is a flask app, this can be done very simply on the backend.

```
 curl "https://api.github.com/repos/canonical-web-and-design/vanilla-framework/contributors" | jq
```

Order can be done by contributions (field from the API).

**Comment by bartaz** [comment]
Already done
