### ISSUE TITLE
Could we make native input validation more intuitive with CSS?

### ISSUE THREAD

**Issue by barrymcgee** [canonical-web-and-design/vanilla-framework#3262]
I came across this tweet; https://twitter.com/thearslankhalid/status/1302143505733750784

- Could we show invalid inputs with red keyline?

![EhIiET9WAAUfxk9](https://user-images.githubusercontent.com/505570/92386656-186e3a00-f10c-11ea-840b-55ceeaf2ce75.png)
![EhIjBIFXYAAdL1j](https://user-images.githubusercontent.com/505570/92386659-1906d080-f10c-11ea-9900-b15d69da6d8c.png)

**Comment by lyubomir-popov** [comment]
- Agreed to match existing styling from the validation pattern.

**Comment by bartaz** [comment]
Scope:

- try to apply Vanilla validation error styles (red border, followed by message in red color with error icon) applied when input is invalid (via `:invalid` selector, and possibly by `aria-invalid` as well).
- add it as separate example "Forms / Native validation" or something like that

**Comment by barrymcgee** [comment]
🤌🏻
