### ISSUE TITLE
Side navigation titles can be construed as links when they are not

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#3263]
## Pattern to amend

We've received comments that the side navigation titles (e.g. "Publisher suggests") in the screenshot below can be interpreted as items rather than titles:

![image](https://user-images.githubusercontent.com/2741678/92401910-917a8b00-f126-11ea-89bb-a96cac353dd7.png)

## Visual

No visual yet, but we maybe we should consider something more muted like the muted heading - to stress on them not being links.

**Comment by lyubomir-popov** [comment]
What a more muted title could look like:
![image](https://user-images.githubusercontent.com/2741678/92402788-1dd97d80-f128-11ea-90a2-504aaeb0813f.png)

**Comment by lyubomir-popov** [comment]
Another alternative if the goal is to really make it unmistakeable that the titles are not links...
![image](https://user-images.githubusercontent.com/2741678/92403532-90972880-f129-11ea-89ac-fefe00afa4e2.png)

**Comment by bartaz** [comment]
We recently made the titles darker, so I think this is not relevant anymore.
