### ISSUE TITLE
error while compiling using dart-sass 1.26.10

### ISSUE THREAD

**Issue by gidor** [canonical-web-and-design/vanilla-framework#3266]
It seems that dart sass fail compiling the framework while node-sass succeeded

**To Reproduce**
```
npm install vanilla-framework
npm install sass 
```
so that 
```
node_modules/.bin/sass --version
```
report 1.26.10 compiled with dart2js 2.8.4

now try to build 

```
node_modules/.bin/sass  node_modules/vanilla-framework/scss/build.scss 
Error: $lightness: Expected -5 to have unit "%".
   ╷
85 │   $button-hover-background-color: scale-color($color-x-light, $lightness: -$hover-background-opacity-amount * 100),
   │                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  node_modules/vanilla-framework/scss/_base_button.scss 85:35  vf-button-pattern()
  node_modules/vanilla-framework/scss/_base_button.scss 7:5    vf-b-button()
  node_modules/vanilla-framework/scss/_base.scss 29:3          vf-base()
  node_modules/vanilla-framework/scss/_vanilla.scss 78:3       vanilla()
  node_modules/vanilla-framework/scss/build.scss 3:1           root stylesheet

```
Using node-sass  everything  works but nodesas is still using an old version of libsass 3.5.5 while the last is 3.6.4 .

Is dart-sas not supported?

**Comment by bartaz** [comment]
Hi @gidor, thanks for trying out Vanilla and letting us know about the issue.

Indeed, as we are not using dard sass internally, we haven't noticed this error before.
I had a quick test and it seems that `scale-color` is the only one preventing the build with dart sass. I'll try to make a quick update and add the missing % to all our uses of scale-color function.
