### ISSUE TITLE
Side navigation: make titles #111

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#3269]
## Pattern to amend

Side navigation

## Visual

We received a request to make sidenav titles stand out more against links. After a [discussion](https://docs.google.com/document/d/1YuEQLWLKaf-Rxbn0g1St-FdsrCnTAKihVoBWZX_60M4/edit#bookmark=id.ouhsa0yjifir) in the design review meeting it was decided to darken titles like this:

![image](https://user-images.githubusercontent.com/2741678/92724995-5dd87480-f363-11ea-930a-ea95c63ed994.png)

**Comment by bartaz** [comment]
Just to be clear, technically titles can be links as well. How should they be styled in such case?

**Comment by lyubomir-popov** [comment]
My proposal would be to apply the standard hover to it in case it is a link.
