### ISSUE TITLE
`<small>` tries to align to baseline grid, but doesn't have display block so it doesn't work

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#3279]
We hould either apply display: block or remove the nudging, as it doesn't do much.

**Comment by hatched** [comment]
To expand on this a bit more, by default I was getting this result when trying to align the top of the text with the top of the visualization on the left. You can see it's a few pixels down, and this is after removing the aforementioned padding.

![Screen Shot 2020-09-15 at 10 28 11 AM](https://user-images.githubusercontent.com/532033/93243476-7a025a00-f745-11ea-9ddc-4c7c625f6276.png)

After some discussion, applying `display: block` resolved the issue and I was able to align it correctly.

Ultimately I ended up using:
```css
  line-height: 0.875rem;
  vertical-align: top;
```

Using this the `padding-top` gets pushed into the containers padding (so it should probably be removed to avoid issues where there is no padding to push into) and the line-height matched the actual text height to allow them to align right up.

![Screen Shot 2020-09-15 at 11 25 22 AM](https://user-images.githubusercontent.com/532033/93243940-2cd2b800-f746-11ea-872e-7f54e2df40b2.png)

**Comment by bartaz** [comment]
`<small>` is an inline element, we can't make it block. Possibly `inline-block` may work if we need the nudge.

**Comment by matthewpaulthomas** [comment]
Most of the places I’ve seen us use `<small>` _are_ blocks, like the one here. Another example is form element captions with `<p><small>Caption here.</small></p>`. This seems inelegant: it suggests that the element might someday also include some non-small text, when it never will.

I guess the solution here, and in the other examples, is to use `<p class="u-text--muted">` instead. If so, maybe not worth changing existing instances, but at least [the `<small>` reference](https://vanillaframework.io/docs/base/typography#small-text) should mention the existence of the muted class.

**Comment by bartaz** [comment]
We have a `p-text--small` to create a block level small text element.
