### ISSUE TITLE
Application layout responsiveness needs some improvement

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#3282]
A comment from @clagom that the juju team weren't able to use the vanilla panels because of responsiveness issues. Looking at the examples, there are a few things we can improve:

- ensure collapsed sidenav is wide enough to display icons centered in the column (or hide them)
- Beyond a certain width, the panel and main area become too narrow to be useful. At this point we should have an alternative mechanism like switching the panel to a slide from top/bottom. 

![image](https://user-images.githubusercontent.com/2741678/93439849-f3758600-f8c6-11ea-8681-2fdd9439d8ae.png)
![image](https://user-images.githubusercontent.com/2741678/93439906-0425fc00-f8c7-11ea-8d4f-673e5c19ba3c.png)

@clagom @barrymcgee please expand on this if the above doesn't go into enough detail.

JAAS issue [here](https://github.com/canonical-web-and-design/jaas-dashboard/issues/683)

**Comment by bartaz** [comment]
What's currently provided by Vanilla is solely the panels/layout part. None of the actual application components have been done in Vanilla CSS and [the example](https://vanillaframework.io/docs/examples/layouts/application) contains dummy components with custom copy/pasted styling just to give an idea how it can roughly look, it's not in any case a complete application screen with all the components.

At this point it's on the application project itself to build the components and put them in the layout.
This for example includes side navigation. Vanilla doesn't have side navigation that works with application layout collapsing.

Yes, the responsiveness of the panels is not ideal, and we will work on trying to improve that. Still, it's not Vanilla part to enforce widths of the content in these panels. Projects are free to set any max/min widths on the panels or position of them that suits their project the best.

So, as the scope of this issue (and current cycle) we can improve panel responsiveness (making sure that on small screens panels will utilize the screen width better).
We currently can't provide side navigation that works with application layout (JAAS dashboard has a custom side navigation that can probably be adapted to work with Vanilla layout).

**Comment by clagom** [comment]
I think we are on the same page @bartaz, and this doesn't need to be delivered now. What we would need to see from the application layout is that you can add other Vanilla patterns such as the side nav and the panels (and the toolbar in the future maybe?) and all of these parts can talk to each other predictably. For the panels component, would be enough to provide 2 or 3 standard sizes, optimised for responsive behaviour, that product can pick out of the box. Sure, there must then be work on the specific product content afterwards, if necessary. So probably at the moment we are missing a dedicated panel component?
Same for the side nav, evolving to a more modular pattern (which is already the plan, with or without icons, collapsible or not, and so on) can work predictably with other components in the application layout.
