### ISSUE TITLE
Code Snippet

### ISSUE THREAD

**Issue by wgx** [canonical-web-and-design/vanilla-framework#3284]
## Pattern to amend

Code snippet

## Visual

Visuals to be completed, UX / wireframes here: https://miro.com/app/board/o9J_kqQPDak=/?moveToWidget=3074457349016924433&cot=12

## Context

The proposed new code snippet pattern introduces these benefits:

- Version switching, for different languages, APIs, versions, etc
- Optional panels for input and output
- Title and optional description for code snippets
- Syntax highlighting and line numbering (optional, configurable)

**Comment by lyubomir-popov** [comment]
This is something to break down during planning. Taking the WG label off, we'll look at it at planning brainstorming.

**Comment by bartaz** [comment]
It has a master epic now, so closing this.

Epic: https://github.com/canonical-web-and-design/vanilla-squad/issues/921
