### ISSUE TITLE
Proposal: Global 'banner' notification

### ISSUE THREAD

**Issue by barrymcgee** [canonical-web-and-design/vanilla-framework#3298]
On JAAS dashboard, I recently experimented with alerting the user to when their internet connection had dropped; see https://github.com/canonical-web-and-design/jaas-dashboard/pull/686

![Screen Recording 2020-09-18 at 10 19 47 pm](https://user-images.githubusercontent.com/505570/93647727-08563480-fa01-11ea-9fe1-226536f12a4c.gif)

### What I think this is different to the current notification pattern

Holistically, I see this as a notification which applies site wide as opposed to the current Vanilla notification which feels to me to be more contextual to the view in which it sits? The current notification also needs to float or it needs external margin. Both of these options make it quite intrusive and not as subtle as I'd like a notification to be for this use case.

**Comment by bartaz** [comment]
@wgx Would there be a place for such notification in your explorations?

**Comment by wgx** [comment]
@bartaz Thanks - for sure this needs to be part of the Notifications spec.

**Comment by lyubomir-popov** [comment]
Validated, to be worked on as part of @wgx 's notification work.

**Comment by bartaz** [comment]
Will be done as part of notifications.

**Comment by bartaz** [comment]
Zeplin: https://zpl.io/VKOY7jR
