### ISSUE TITLE
P-navigation: Clicking "menu" (on small screens) jumps the page down

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#3302]
![Screen Shot 2020-09-22 at 3 49 35 PM](https://user-images.githubusercontent.com/532033/93941261-4d24e880-fceb-11ea-91d6-f65c6e8a57e1.png)
![Screen Shot 2020-09-22 at 3 49 42 PM](https://user-images.githubusercontent.com/532033/93941266-4e561580-fceb-11ea-9f35-75581969aeaf.png)

// Originally filed [here](https://github.com/canonical-web-and-design/charmhub.io/issues/362)

**Comment by bartaz** [comment]
To be more specific - happens only with global nav above main nav.

**Comment by bartaz** [comment]
That's an issue with global nav, and expected behaviour of the mobile navigation.
