### ISSUE TITLE
Add outline button

### ISSUE THREAD

**Issue by solazio** [canonical-web-and-design/vanilla-framework#3303]
Add a new pattern for outlined button with transparent background.

![image](https://user-images.githubusercontent.com/40214246/94004022-f4f5f100-fd93-11ea-9ca0-b2bf3f22714f.png)

Hover:
![image](https://user-images.githubusercontent.com/40214246/94004064-06d79400-fd94-11ea-82db-c58bb6f01bca.png)

```
  .p-button--outline {
    @extend %vf-button-base;

    border-color: $color-x-light;
    color: $color-x-light;

    &:visited {
      color: $color-x-light;
    }

    &:hover,
    &:active:hover {
      background-color: rgba($color-mid-x-light, 0.2);
    }
  }
```

**Comment by bartaz** [comment]
We will need to have both light and dark versions of this when adding to Vanilla.

**Comment by bartaz** [comment]
For Working Group:
- how does this button fit in current range of buttons?
- is this a new type of button, or modified version of existing one?

**Comment by lyubomir-popov** [comment]
In my mind thisis the dark theme version of the normal button.

**Comment by lyubomir-popov** [comment]
Agreed to just implement themeing for buttons, which would provide this.

**Comment by cristinadresch** [comment]
Theming has now been added to buttons https://vanillaframework.io/docs/patterns/buttons#theming
