### ISSUE TITLE
Add privacy icon to `password` text fields

### ISSUE THREAD

**Issue by squidsoup** [canonical-web-and-design/vanilla-framework#3304]
## Pattern to amend

Single-line text field

## Visual

![image](https://user-images.githubusercontent.com/130286/94083871-54b5d000-fe58-11ea-8024-ce6981c7e61f.png)

## Context

Add privacy icon to `password` text fields

**Comment by squidsoup** [comment]
@amylily1011 as per your [IPMI settings](https://app.zeplin.io/project/5f623e8f646531bc74bd9b43/screen/5f623edb236a59b861fe6067) design.

**Comment by squidsoup** [comment]
@bartaz I think the intention is also to have some behaviour, which we could implement in react-components, where toggling the privacy icon would show the text in the clear.

**Comment by bartaz** [comment]
For working group:
- should this affect all password fields or be an option
- do we have the icons in new set for both states?
- how should it work with validation (that shows icon inside the input)

**Comment by amylily1011** [comment]
Hi @bartaz,

- I hope to change MAAS's password fields to this pattern
- there will be icons for both states (the icons already exist) 
Link to asset: 
hide:  https://assets.ubuntu.com/v1/5590f22c-hide.svg
show: https://assets.ubuntu.com/v1/34b8a02c-show.svg

- can you clarify what you meant by validation in this case? 
This is what I had in mind.
![image](https://user-images.githubusercontent.com/18423198/94123702-07cbfc80-fe4c-11ea-920d-a4f7c56cb52f.png)

**Comment by bartaz** [comment]
Thanks for clarifications @amylily1011!

While I have you here, can you verify if that's intended behaviour:

- By default password field should work normally (hide password) and show the "Show" (eye) icon
- When eye is clicked password is shown in plain text in the same field, icon changes to "hide" (crossed eye)
- When the crossed eye is clicked password is hidden again (brings input to initial state)

**Comment by lyubomir-popov** [comment]
One thing to keep in mind: some plugins add an icon there, we've have an open [issue](https://github.com/canonical-web-and-design/vanilla-framework/issues/3134) to fix that. The problem would occur here as well:
![image](https://user-images.githubusercontent.com/2741678/94130724-f0ddd800-fe54-11ea-96c7-53138ddb9f62.png)

**Comment by amylily1011** [comment]
> Thanks for clarifications @amylily1011!
> 
> While I have you here, can you verify if that's intended behaviour:
> 
> * By default password field should work normally (hide password) and show the "Show" (eye) icon
> * When eye is clicked password is shown in plain text in the same field, icon changes to "hide" (crossed eye)
> * When the crossed eye is clicked password is hidden again (brings input to initial state)

Yes, that sounds about right 😃

**Comment by lyubomir-popov** [comment]
@amylily1011 @clagom should this be an option or an inbuilt behaviour?

- are there cases where it makes snes, and cases where it doesn't  -in this case it would need to be optional
- or should every site get it as soon as they update vanilla (this will require a js change, but that shouldn't drive the decision)

**Comment by amylily1011** [comment]
@lyubomir-popov I haven't done enough research to patternize this. So I'm not sure if there are cases that it might not make sense. Although I've proposed this based on how MAAS handles the IPMI fields, where they need to view the password content (maybe change, maybe to copy), but also would need this to remain a secret for the majority of the time. So it makes sense in that scenario.  

(In my opinion) I would not impose this to all sites just yet as I don't know enough about other use cases. But I hope to patternize this for MAAS on all password cases.

**Comment by bartaz** [comment]
I just learnt that Edge has it native by default on all password fields. I wonder how we can detect that not to duplicate functionality ...

<img width="290" alt="Screenshot 2020-10-05 at 16 39 16" src="https://user-images.githubusercontent.com/83575/95093783-6d13cd80-0729-11eb-9ef2-4d594c36f4f2.png">
<img width="307" alt="Screenshot 2020-10-05 at 16 39 07" src="https://user-images.githubusercontent.com/83575/95093788-6e44fa80-0729-11eb-977f-1e6ec5e60389.png">

**Comment by davegoddard42** [comment]
Here's @rayito and mine's proposed solution

https://docs.google.com/document/d/1Q5i2DI801rKA4XO8MZv0dldUUGGbB6zPSWsRVLf8mk0/edit?usp=sharing

Here's our thought process and workings:

https://miro.com/app/board/o9J_lC9sbTk=/

**Comment by clagom** [comment]
Very well-structured proposal @davegoddard42 @rayito

**Comment by clagom** [comment]
@rayito and @davegoddard42 to create issues inside of this epic
