### ISSUE TITLE
Code copyable reveals a strange orange focus state on Chrome

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical-web-and-design/vanilla-framework#3328]
Clicking on the copy button (or tabbing to it) reveals a strange orange focus state:

![image](https://user-images.githubusercontent.com/2741678/94438389-f578f800-0196-11eb-97e7-a104a1b434b7.png)

_Originally posted by @lyubomir-popov in https://github.com/canonical-web-and-design/MAAS-squad/issues/2079#issuecomment-700007084_

**Comment by fitojb** [comment]
It depends on the Chrome version; newer versions have a default black focus outline instead.
