### ISSUE TITLE
Show/Hide utilities don't work well with table columns

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#3337]
**Describe the bug**

`u-hide` and `u-show` utilities that Vanilla provides work on `display` property.
While it successfully hides/shows table cells if applied it messes up the `colspan` functionality, because cells with `display: none` are not counted.

To hide columns (but still count them in `colspan`) we should hide them using `width: 0` instead.

**To Reproduce**

See codepen:
https://codepen.io/bartoszopka/pen/qBNWvqX

**Comment by Caleb-Ellis** [comment]
Applying `width: 0` on expanding table cells does not work because they use a flex layout. e.g. applying `u-hide` to a table header still displays the header, pushing the remaining table headers out of alignment:

![2020-10-15_18-25](https://user-images.githubusercontent.com/25733845/96097100-ea9ec100-0f13-11eb-9b1b-0c074b721292.png)

**Comment by bartaz** [comment]
A workaround for that issue caused a breaking change in react-components repo.
We should work on fixing it as soon as possible.

Some important areas to be aware of:

- scoping existing `u-hide` utils to do something different in tables is probably a bad idea, it's safer to introduce new utility specifically to hide table cells/columns - this may require updates in products that use u-hide to hide columns (like snapcraft builds with new modular table)
- expanding table is using u-hide as integral part of the pattern. This should be avoided, patterns should not depend on usage of utilities in their required markup
- alongside updates on Vanilla side we should update relevant react components as well
