### ISSUE TITLE
Importing individual components instructions are out of date

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/vanilla-framework#3342]
The [base placeholders have been wrapped in a mixin](https://github.com/canonical-web-and-design/vanilla-framework/blob/f4c7d28e00e78405d3fb595f5e0e3d47bb2da973/scss/_base_placeholders.scss#L6):
```scss
@mixin vf-b-placeholders {
  ...
}
```

When reading the https://vanillaframework.io/docs/customising-vanilla#importing-individual-components it does mention you now need to include `@include vf-b-placeholders;` otherwise, components using placeholders fail.

**Comment by bartaz** [comment]
Sorry, which instructions are out of date then?

There is `vf-b-placeholders` mixin, and we do mention it's required on  https://vanillaframework.io/docs/customising-vanilla#importing-individual-components page. So what is missing?

**Comment by anthonydillon** [comment]
I am referring to the code example:
![image](https://user-images.githubusercontent.com/1413534/95337051-5b593400-08a9-11eb-9997-bd7fe2011e15.png)

**Comment by bartaz** [comment]
This example includes whole `vf-base` (which is recommended), this includes `vf-b-placeholders` in it.

Including `vf-b-placeholders` alone (without `vf-base` is minimal requirement if someone doesn't want whole base).
Maybe it's not clear from the text description.

**Comment by anthonydillon** [comment]
Ah, your right. Sorry. Double checked.
