### ISSUE TITLE
Next on docs search gives a 404

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/vanilla-framework#3356]
**Describe the bug**

When searching on vanillaframework.io there is a "Next" button at the bottom, but clicking it takes you to a 404 page.

**To Reproduce**

1. Go to https://vanillaframework.io/docs/search?q=tabs&submit=
2. Click on 'Next >'
3. See that it shows a 404 page.

**Expected behavior**

It should either not show the next link or show the next page of results.

**Comment by bartaz** [comment]
Fixed by #3359
