### ISSUE TITLE
Explore different variations of the nav highlight

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#3364]
The white highlight we switched to succeeds in increasing prominence, but causes some issues in other areas:

- The white block becomes visually grouped with the orange block on sites like microk8s, charmhub (as white is closer to orange than to dark grey)
![image](https://user-images.githubusercontent.com/2741678/96845215-5cad6380-1448-11eb-993e-4c449b9e6d8c.png)

- it causes unintended blending when the background underneath is white
![image](https://user-images.githubusercontent.com/2741678/96846803-4902fc80-144a-11eb-87a8-cf62e35b70ad.png)

- it causes a strange near-blend when the color underneath is light grey, and
- It can make narrow strips look like a menu stuck open:
![image](https://user-images.githubusercontent.com/2741678/96847003-8e272e80-144a-11eb-899a-f895e99af174.png)

- it is easily the highest point of contrast on the page, overpowering primary buttons:
![image](https://user-images.githubusercontent.com/2741678/96846946-7e0f4f00-144a-11eb-8197-32317a1b4d2a.png)

- we have a [complaint](https://github.com/canonical-web-and-design/snapcraft.io/issues/3120) about the change

We need to explore alternatives and propose something that satisfies the need for strong contrast while avoiding the points above.

**Comment by SirSamTumless** [comment]
@lyubomir-popov What's happening with this?

**Comment by lyubomir-popov** [comment]
On hold for now. Will be picked up again later in the cycle.

**Comment by lyubomir-popov** [comment]
Ready for review:

https://zpl.io/aBQrkEL

**Comment by lyubomir-popov** [comment]
The design has been updated, ready for another look.

https://zpl.io/aBQrkEL
