### ISSUE TITLE
$font-monospace returns a non-functional quoted value

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/vanilla-framework#3369]
When using `font-family: $font-monospace;` as outlined here https://vanillaframework.io/docs/settings/font-settings the resulting CSS is `font-family: '"Ubuntu Mono", Consolas, Monaco, Courier, monospace'` which is incorrect formatting. To fix this I had to use `font-family: unquote($font-monospace);` which isn't documented.

I'd have expected `font-family: $font-monospace` to work out of the box.

**Comment by bartaz** [comment]
Won't fix ATM, as discussed in https://github.com/canonical-web-and-design/vanilla-framework/pull/3370
