### ISSUE TITLE
Application layout is not keyboard accessible

### ISSUE THREAD

**Issue by barrymcgee** [canonical-web-and-design/vanilla-framework#3377]
**Describe the bug**

The application layout sidebar does not open if a user navigates links within with a keyboard

**To Reproduce**

1. Go to https://codepen.io/barrymcgee/full/RwRpMpj
2. Tab into application layout example
3. See that links are traversed but sidebar does not expand

**Expected behavior**

When I traverse links, I would expect sidebar to open

**Comment by bartaz** [comment]
That's a good call - we haven't really looked into application layout sidebar contents yet, but definitely we should take that into account.
I guess `:focus-within` should do the trick here.
