### ISSUE TITLE
`l-status` in application layout sticks to the content, not to the window

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/vanilla-framework#3378]
## Pattern to amend

Application layout

## Context

I believe that it was intended that the `l-status` aside was intended to act as a footer to the application and not to the content on a specific page.

This become apparent when looking for an element to render the new Juju Web CLI into in the Juju Dashboard.

**Comment by bartaz** [comment]
@hatched Can you give an example what do you mean that it sticks to the content and not to the window?

When there is little content in 'main' status is on the bottom:
https://vanillaframework.io/docs/examples/layouts/application-structure

Same when there is more content in 'main' and its scrollable:
https://vanillaframework.io/docs/examples/layouts/application

The height of the `l-status` is determined by it's content (as intended) and when it grows bigger it makes `l-main` smaller (doesn't overlap it) to make sure all content in main is available (can be scrolled to).
We don't have an example for it, but technically `l-status` can be resized (when height is set on it via javascript), so can work as resizable container for terminal.

Does JAAS layout need something that is not covered here?

**Comment by hatched** [comment]
Interesting, those examples work how I expected it to work. In the dashboard and in the example on this page https://vanillaframework.io/docs/layouts/application the `l-status` sticks to the content, not the window, you can see this by the scroll bar making the status appear or not.

**Comment by anthonydillon** [comment]
I looked into this and the `l-status` positioned correctly when a direct child of `l-application`. I believe the current wCLI panel is inside the `l-main` panel.

This screenshot is a mock-up of the `l-status` at the bottom of the page:
![image](https://user-images.githubusercontent.com/1413534/97232563-43544080-17d5-11eb-8d91-179e7bad7e8b.png)

**Comment by anthonydillon** [comment]
The layout make-up needs to be:
```html
<div class="l-application" role="presentation">
  <header class="l-navigation is-collapsed">...</header> <!-- left side navigation -->
  <main class="l-main">...</main> <!-- main content -->
  <aside class="l-aside is-pinned u-hide">...</aside> <!-- info right side panel -->
  <aside class="l-status">...</aside> <!-- Web CLI -->
</div> 
```

**Comment by bartaz** [comment]
> The layout make-up needs to be..

Correct. Application layout uses CSS grid. `l-application` is root element and all other `l-regions` need to be direct children of it.

**Comment by bartaz** [comment]
Seems that this has been sorted out for now @hatched?

If it's still an issue feel free to comment and reopen.
