### ISSUE TITLE
.is-ticked is too specific

### ISSUE THREAD

**Issue by bethcollins92** [canonical-web-and-design/vanilla-framework#3403]
## Pattern to amend

`.is-ticked`

## Visual

![image](https://user-images.githubusercontent.com/58959073/98938992-a980d900-24e0-11eb-9f45-30fdcf179195.png)

## Context

the `.is-ticked` class contains generic styles not specific to the ticked icon. I was trying to add a list item with a cross but the class name implies the icon has to be a tick. Could a more generic name be used such as `.has-icon`?

**Comment by bartaz** [comment]
This seems quite closely related to #3405. Once we allow having different icons it will completely make sense to use different name than `is-ticked`. We'll discuss this on next WG meeting.

**Comment by lyubomir-popov** [comment]
Closing as duplicate of #3405
