### ISSUE TITLE
Jumping checkboxes

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/vanilla-framework#3411]
**Describe the bug**
When you use a list with the new `p-checkbox` component in it. The input is absolutely positioned at the bottom of the nearest relative element (which is most likely the `strip`). This causes the screen to jump down if the content is long enough.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://codepen.io/anthonydillon/pen/vYKMELv
2. Click on "Jumping one" check box
3. See that it scrolls down the page
4. Scroll back up and click the "Fixed one" (see that the `p-checkbox` has `position: relative` applied)

**Expected behaviour**
Act as the Fixed one does.

**Additional context**
This is for https://charmhub.io

**Comment by bartaz** [comment]
Oh, wow. I was sure they have position relative, but indeed they don't.
Seems like our examples worked because there was no parent with position relative.
