### ISSUE TITLE
Application layout - allow collapsing side navigation programatically

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#3412]
Currently the width of the screen defines when side navigation is fully expanded and when it's collapsable.

JAAS team would like to have more control over it, to collapse side navigation on some screens, while keeping it expanded on the others.

**Comment by bartaz** [comment]
@hatched @barrymcgee 

I wonder how much do we need a separate class to do that, I think it is (kinda?) possible currently with a bit of customization.

As far as I understand your requirements, at certain screen size you'd like to control programatically when side navigation is expanded or collapsed.

I would propose doing it like that:

Since Vanilla 2.20 you can [customize application layout](https://vanillaframework.io/docs/layouts/application#customizing-the-application-layout), including breakpoints at which app layout collapses/expands the navigation.
By default the breakpoint at which side nav is always expanded `$application-layout--breakpoint-side-nav-expanded` is `$breakpoint-large` which is not very big to current screen standards. I would suggest bumping it up to some large value (2000px?) - I guess there is a certain breakpoint like this when it makes sense to keep side nav always expanded, because screen is large enough.

With that adjusted you should have quite a wide window of screen sizes when side navigation will be collapsed by default. But When it is collapsed, you can always pin it (force it to expanded width) by adding `is-pinned` class to `l-navigation`.
So, instead of having separate class to force expanded navigation to be collapsed, I suggest letting the side nav to be collapsed by default, but expand it for the views that have enough space for it.

Would that work for you?

**Comment by barrymcgee** [comment]
I have a strong preference for not trying to second guess when the side panel should be collapsed and giving that control back to the user via a well designed button toggle.

**Comment by hatched** [comment]
While I agree with @barrymcgee, we should also provide sane defaults and I think that allowing us to tweak when the sidebar collapses will remedy the issue. We can then add the pin functionality so that if the user chooses to pin open we can persist that.

Thanks @bartaz

**Comment by barrymcgee** [comment]
@hatched Why did you close this issue? Has the work been completed?

**Comment by cristinadresch** [comment]
@barrymcgee I think it was closed because the plan is to it on jaas and not vanilla? Makes sense?

**Comment by hatched** [comment]
Yep that's exactly it :) If we determine that the suggested approach doesn't work for us then we can re-open with additional requirements.
