### ISSUE TITLE
Look at reducing the focus state on click

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/vanilla-framework#3418]
In a review, it was requested we look at reducing the focus state when you click a button or link. It is thought that the think blue border is garish.

**Comment by bartaz** [comment]
We have a separate report to look into using :focus-visible - which makes focus visible when navigating with keyboard (when you expect it) but not visible when you click on things.
I guess it would help us keep prominent focus when needed, and avoid showing it when things are clicked. 

https://github.com/canonical-web-and-design/vanilla-framework/issues/3352

**Comment by bartaz** [comment]
Closing as duplicate of #3352
