### ISSUE TITLE
Side panel as Level.2 element on page

### ISSUE THREAD

**Issue by long-chung** [canonical-web-and-design/vanilla-framework#3435]
## Pattern to amend

Application layout

## Visual

![JAAS-Panel.png](https://images.zenhubusercontent.com/5f1ec667037c164bb1ed32d9/43cf1129-8693-4570-b3da-6d8b42d760e3)

## Context

Currently the application panel is intended to sit at the highest level on the page.
We'd like to propose the ability to allow the application layout to sit as a level 2 component on the page. 
With more features and actions in the backlog of JAAS; the top navigational element could/will be a primary area to navigate around the page.

**Comment by lyubomir-popov** [comment]
- Add separate grid area for a horizontal header
- Decide on whether that's a default or an optional header later on once the application layout is adopted in more apps

**Comment by lyubomir-popov** [comment]
Closing as @long-chung indicated it is not relevant any more.
