### ISSUE TITLE
Proposing `p-separator` for spaced <hr>

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/vanilla-framework#3437]
In [many sites](https://github.com/search?q=org%3Acanonical-web-and-design+p-separator&type=code), we use an in row border to separate content in the same strip. The way we do that currently is by having a local pattern called `p-separator` which when attached to an `hr` creates a horizontal divider with a few rem padding top and bottom.

## Visual
![image](https://user-images.githubusercontent.com/1413534/100770829-9bdeb500-33f5-11eb-9153-41786676c8ff.png)

## Context
This is used mainly on marketing sites. The style has been copied or worse inlined on the `hr` element which means it is not resonsive.

## State
None that I can think of.

## Progressive enhancement
The padding should scale with the viewport.

**Comment by bartaz** [comment]
How does it differ from base `<hr>` styles?

**Comment by anthonydillon** [comment]
They require padding top and bottom.

**Comment by lyubomir-popov** [comment]
This sounds better than what I've been doing, which is to remove the margin fro mthe hr and wrap the content on either of it in a strip. One question though - the spacing you need depends on the kind of content you have, so I can see the same need as with strips - should there be p-separator--deep, p-separator-shallow?

**Comment by anthonydillon** [comment]
Currently, we only have use one amount of padding (I believe its `2rem`). So let's build that and extend as the requirements arise.
