### ISSUE TITLE
Remove l-docs from mass-docs example

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/vanilla-framework#3452]
We either need to remove the maas-docs example now that we have supported docs layout examples. Or refactor the template to use the docs layout [instead of `l-docs`](https://github.com/canonical-web-and-design/vanilla-framework/blob/master/templates/docs/examples/templates/maas-docs.html#L10).

**Comment by bartaz** [comment]
Yes, this example was created when working on docs layout to make sure our changes in Vanilla don't break existing (old) docs layouts.
Now that all docs have migrated we should be able to remove this example without worrying about breaking changes.
