### ISSUE TITLE
Add right aligned text link into input

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/vanilla-framework#3466]
## Pattern to amend

Form

## Visual

![Screen Shot 2021-01-04 at 10 50 56 AM](https://user-images.githubusercontent.com/532033/103558844-e29f4f00-4e7a-11eb-9951-1867edf65751.png)

## Context

Like the search box "x" to clear we'd like to add a custom "reset" text to individual values in a form field.

**Comment by matthewpaulthomas** [comment]
Can you be more specific about how you’re using this? Perhaps there are more familiar solutions. For example, a menubutton alongside the field could open a menu of recent values, where the last-used value is just one of them.

If a reset button is appropriate, it would be both less obtrusive and less geeky if labelled just “Reset”.

**Comment by hatched** [comment]
This is used in the application configuration list in the Juju Dashboard. When a value differs from the default configuration value this link will appear that'll reset it back to its default. We're going to update the text to read "use default" to make it clearer as to what's happening.

**Comment by lyubomir-popov** [comment]
- Safari, FF password manager, lastpass (among ohters?) make use of this space, so putting anything there risks being overlapped. This also has implications for our validation pattern, or which we have an open issue [link to be added].

The UX opinion on the subject is we should avoid placing anything there.

@long-chung has also mentioned that the jaas designs have changed, so this is not currently needed, so closing.
