### ISSUE TITLE
Create markup structure

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#3467]

**Comment by bartaz** [comment]
CodePen prototype: https://codepen.io/bartoszopka/pen/XWjqVxL

**Comment by lyubomir-popov** [comment]
That was quick, it's almost there :) 

A couple of small comments - in terms of markup, the titles should be h5 not h4. 
I also made some spacing alterations in a fork, to get it a little closer to the designs - feel free to ignore for now - https://codepen.io/lyubomir-popov/pen/MWjGVLO
