### ISSUE TITLE
/docs/patterns/icons - LinkedIn link isn't working

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/vanilla-framework#3475]
**Describe the bug**

**To Reproduce**

1. Go to https://vanillaframework.io/docs/patterns/icons
2. Scroll down to 'Share'
2. Click on 'LinkedIn'

**Screenshots**
<img width="1137" alt="Screenshot 2021-01-06 at 11 05 03" src="https://user-images.githubusercontent.com/36884067/103761735-0bf0e400-500f-11eb-8b05-0c83fa820d5e.png">

**Comment by sowasred2012** [comment]
After an initial search, it looks like this is the replacement for the old link: https://docs.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/plugins/share-plugin
