### ISSUE TITLE
Add a new option for small text to have more line height when text wraps more than 2 lines

### ISSUE THREAD

**Issue by danielmutis** [canonical-web-and-design/vanilla-framework#3482]
Currently we are using a style <small> for the parragraph on the cards of Charmhub, that looks as if the text is too tight vertically.

 ![Screenshot 2021-01-07 at 14.43.33.png](https://images.zenhubusercontent.com/5e1c5367f4dbe2bfe4c77ad8/37bbf505-79be-46c0-b038-b5e9bb41aef3)

I would suggest adding a new option for when the text wraps to more than one (or two) lines to have a line height of 1.25 rem so the text feels less tight visually.

**Comment by bartaz** [comment]
Maybe some other styles affect line height there?

Small text by itself seem to wrap nicely:

<img width="216" alt="Screenshot 2021-01-07 at 16 02 38" src="https://user-images.githubusercontent.com/83575/103907666-dbd63d80-5101-11eb-950e-bc80c486f255.png">
https://vanillaframework.io/docs/examples/base/small

**Comment by lyubomir-popov** [comment]
@bartaz strange, `<small>` looks like it has a much bigger line-height than 1rem. Even stranger, the supposed equivalent `p-text--small` (which is to be used on block level elements, as <small> is inline) looks as expected at 1rem line-height.

![Uploading image.png…]()


Either way, we have two needs:

- dense small text when you have just a line and a half, or just one line as in a table header
- sparse small text, when we hae an entire paragraph

**Comment by lyubomir-popov** [comment]
There are valid needs for both a 1rem line-jheight, and a 1.25rem line-height. To be decided:
- should the 1.25rem be default? 
- naming for the class that alters the agreed default to achieve the other line-height

**Comment by lyubomir-popov** [comment]
- Switch default to 1.25rem
- Revisit unitless - is it still causing the rounding bug?
- Hold off on the utility for now, revisit if denser tex is needed
