### ISSUE TITLE
Sortable table jumps when sorting

### ISSUE THREAD

**Issue by spencerbygraves** [canonical-web-and-design/vanilla-framework#3488]
When you use the sorting arrows, the [table jumps a little bit](https://vanillaframework.io/docs/examples/patterns/tables/table-sortable). This can also be seen on the [Jaas tables](https://jaas.ai/models).

**Comment by lyubomir-popov** [comment]
Duplicate of [this](https://github.com/canonical-web-and-design/vanilla-framework/issues/3120) right @bartaz?

**Comment by bartaz** [comment]
Fixed via #3120.

Thanks @spencerbygraves, we happened to fix this last week, so it will be released with next version of Vanilla.
