### ISSUE TITLE
Improve card box-shadow appearance

### ISSUE THREAD

**Issue by elioqoshi** [canonical-web-and-design/vanilla-framework#3492]
Currently cards in Vanilla have one single shadow appearance, one example of vanilla cards used is in the Charmhub directory. This is how it currently looks like: ![Current Shadow.png](https://images.zenhubusercontent.com/5a5649f54b5806bc2bc23b6d/79f389f6-73c7-4e2d-802e-60feb3468991)

This box-shadow styling could feel unnatural, as shadows are more nuanced in reality. A good example covering this topic is following: 
https://tobiasahlin.com/blog/layered-smooth-box-shadows/

Currently, the box shadow values are expressed in one layer in the CSS, Using 2 ore more layers we could provide a more natural looking shadow effect for cards. One problem with the current shadows is that they are rendered as if light hits the cards right from the front, while most websites design shadows with a slightly higher light source (so shadow bounces off to the bottom of the card, making it taller than at the top of the card, similar to Material Design: https://material.io/design/environment/light-shadows.html#light)

While I am not saying that Material Design is right about everything, I'd say they got it right when it comes to key and ambient lights. Using this philosophy it would make sense we design box-shadow with 2 layers, one using a key light and one using an ambient light.

I have prototyped 3 different proposals in Sketch on how that could look like:

Option 1:
![New Shadow 1.png](https://images.zenhubusercontent.com/5a5649f54b5806bc2bc23b6d/e95f5359-4383-4d1a-a0f7-00e0363394ca)

Option 2:
![New Shadow 2.png](https://images.zenhubusercontent.com/5a5649f54b5806bc2bc23b6d/0763738c-7a83-43b4-aebb-8a680576dc04)

Option 3:
![New Shadow 3.png](https://images.zenhubusercontent.com/5a5649f54b5806bc2bc23b6d/a22b5a28-6cb5-4dbd-bcb3-73b3cdc16088)

What do you think?

**Comment by elioqoshi** [comment]
Here is a quick GIF to compare it in real-time
![GIF Shadows](https://user-images.githubusercontent.com/5436686/104733151-9091df80-573e-11eb-9d66-c9597a46d513.gif)

**Comment by lyubomir-popov** [comment]
Good exploration. Would be nice to see a bit of benchmarking - e.g. ours vs material vs apple vs a few others - to judge whether we're leaning towards more subtle or more pronounced shadows than the average.

A further step could be to compare apple's minimalistic approach to interaction (no hovers) to material's multitude of states and propose where on this scale we want to be.

**Comment by spencerbygraves** [comment]
Thanks @elioqoshi, it would be good to look at updating this.

**Comment by elioqoshi** [comment]
@lyubomir-popov That sounds good. Happy to do a little further explorations comparing it with other design languages.

> loosing the contours of the cards - option 2 & 3 loose definition at the top

True. Though I don't think that's a major issue. Te card shape differentiates itself from the background by the lower shadow already.

> relationship between shadow depth and comfortable margin. Increasing the depth would require more space around the card to compensate.

Indeed. The shadow length can't be too large in these cases the margins between the cards was only 16px.

**Comment by lyubomir-popov** [comment]
Validated that this could be an improvement to the current drop-shadow in `.p-card--highlighted`.
Next steps: proceed with benchmarking and dial in exact shadow values.

**Comment by lyubomir-popov** [comment]
Did some benchmarking: the [material design card shadows](https://material.io/components/cards) are a lot more subtle and help get content closer together:
 
![image](https://user-images.githubusercontent.com/2741678/106463384-41aeae80-648f-11eb-9be7-d1e31fbcbe74.png)

Trying the same css on our cards:
![image](https://user-images.githubusercontent.com/2741678/106463185-01e7c700-648f-11eb-9ecc-3cdc138e9020.png)

**Comment by lyubomir-popov** [comment]
Would be interesting to see where apple currently stand on this, I can't find any shadows outside of he OS. Although their guide does mention it is allowed acording to this discussion https://ux.stackexchange.com/questions/113951/is-subtle-shadow-effect-an-anti-pattern-in-ios

**Comment by elioqoshi** [comment]
Thanks for going ahead with this already @lyubomir-popov , I think your middle-ground solution is an improvement. Do we want to consider multiple shadow styles in Vanilla or is that part of another discussion?

**Comment by lyubomir-popov** [comment]
@elioqoshi Well, one of the issues linked to this one shows that there are problems when a sticky element's shadow matches that of a card or panel, so I think we need a number of "depths" to avoid this kind of issue. I also think an alternative like apple's, where there are no shadows at all, might be even better. 

I think what's needed is more benchmarking, the above is just one data point, which, among other things, highlights the fact that even google's spec contradicts their usage of shadows within the same page.

**Comment by lyubomir-popov** [comment]
Offshoot from the notifications work:

![image](https://user-images.githubusercontent.com/2741678/109160057-39375400-776d-11eb-9eba-7baf567557a4.png)

**Comment by lyubomir-popov** [comment]
I think this is ready for comments. @spencerbygraves what do you think?

- change #cdcdcd to #d9d9d9 (20% -> 15% darkness) globally for all items using that colour (that's mostly borders)
- slightly strengthen shadow derived above so it doesn't look less prominent than the border:

![image](https://user-images.githubusercontent.com/2741678/109190877-7ad7f700-778d-11eb-98b7-dcfdbef6dd62.png)

**Comment by spencerbygraves** [comment]
Thanks @lyubomir-popov. I like the shadow as it feels more considered than our current version.

One question; is there a case for having a card with a border next to a card with a shadow? I'm wondering if there's a need to change the border colour if it's not a real world comparison.

(This perhaps raises the question of shadows on hover...)

I'm not a fan of the increased border radius, and it would have a knock on effect to buttons etc.

**Comment by lyubomir-popov** [comment]
> is there a case for having a card with a border next to a card with a shadow?

None that I can think of, but I think it should be clear that one is a more emphasized treatment than the other. 

For example, if you want to make something more prominent, and the bordered version is turned down as too inconspicuous (e.g. for the charmhub cards), then the shadowed version should visually look stronger. 

Separately, there's a strong tendency for borders in different design system to become as subtle as possible, for example compare the borders here on github. So unless there's an accessibility requirement as in input fields, I think lightening borders Is a good thing.

Finally for the border radius, I overdid it here, but I think there should be some element of proportionality - the bigger the element, the less noticeable the border radius is, and it feels especially tiny on panels / modals. But that is a separate thing so not necessarily something that should be part of the shadow proposal, I'll revert it.
