### ISSUE TITLE
Design the improved embedded examples

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/vanilla-framework#3518]

**Comment by lyubomir-popov** [comment]
Mockup on [zeplin](https://zpl.io/bzPgAlA)

**Comment by spencerbygraves** [comment]
@lyubomir-popov I'd be happy with either version 2 or 3. Do you have a preference?

**Comment by lyubomir-popov** [comment]
@spencerbygraves I was leaning towards the darker gray, to avoid light strips blending with the background.

**Comment by spencerbygraves** [comment]
@lyubomir-popov ok, sounds good 👍
