### ISSUE TITLE
Using focus-within on the app layout navigation drawer prevents some actions

### ISSUE THREAD

**Issue by steverydz** [canonical-web-and-design/vanilla-framework#3530]
In the application layout navigation drawer, if you include a button to close the drawer, it won't work until you click then unfocus the button because `:focus-within` sets the `transition` property to `none`.

**Comment by bartaz** [comment]
Yes, if any elements gets focused in collapsed sidenav `:focus-within` styling will make side nav expand (for accessibility reasons), this unfortunately includes the 'close' button (if located within the sidenav).

The only workaround for that seems to be in JavaScript of the close button. It needs to remove the focus from itself when clicked, to allow CSS transition to hide the navigation. We have that in our example:

https://github.com/canonical-web-and-design/vanilla-framework/blob/98621694cf9ff81f034ce7b032edaebac61b194d/templates/docs/examples/layouts/application/_script.js#L8-L11

**Comment by steverydz** [comment]
Fair enough. I'll update the code on snapcraft with this change. Thanks.
