### ISSUE TITLE
Support buttons in Tabs component

### ISSUE THREAD

**Issue by squidsoup** [canonical-web-and-design/vanilla-framework#3532]
## Pattern to amend

Tabs

## Visual

n/a

## Context

The `Tabs` component assumes that you want to manage state via URL changes, but when used in the context of a React app, you may want to manage state within the component (e.g. binding an `onClick` event to each Tab with a call to `setState`. Ideally Tabs should support using a Button as the Tab component, rather than an anchor. While you *can* currently set a Button as the `component` in the react-components `Tabs` component, the stying is a bit off:

![image](https://user-images.githubusercontent.com/130286/106539108-3d9f9100-6562-11eb-868d-18243e46e0e7.png)

**Comment by lyubomir-popov** [comment]
the wai-aria tabs example is implemented with buttons https://www.w3.org/TR/wai-aria-practices/examples/tabs/tabs-1/tabs.html

**Comment by clagom** [comment]
Implemented in the current Vanilla:
https://vanillaframework.io/docs/examples/patterns/tabs/content
