### ISSUE TITLE
Code snippet dark theme

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/vanilla-framework#3534]
## Pattern to amend

Code Snippet

## Visual

N/A

## Context

The current code snippet presents code in a container with a grey background and dark text, which wouldn't look good against a dark background. We should create a dark theme to avoid this problem.

**Comment by SirSamTumless** [comment]
Is there a need for this - discuss in the working group.

**Comment by cristinadresch** [comment]
@lyubomir-popov to leave a comment here

**Comment by lyubomir-popov** [comment]
@sowasred2012 Do we use this outide of the application layout example? If not, then maybe best to focus on translating the levels of grey for dark theme so they are discernable, but hold off on a code snippet dark theme until we have an actual need for it in production?

**Comment by sowasred2012** [comment]
@lyubomir-popov not currently, no. We added `is-dark` support for code elements, which solved the problem we were having there, so at the moment there isn't yet a need for the code snippet to have a dark theme.

**Comment by cristinadresch** [comment]
@sowasred2012 thanks for the info, we'll close it for now then
