### ISSUE TITLE
Button space incorrect when using an anchor tag instead of button

### ISSUE THREAD

**Issue by carkod** [canonical-web-and-design/vanilla-framework#3542]
**Describe the bug**

When using `p-button--neutral` or `p-button--negative` for `<a class="p-button--neutral">` tags, the space shrinks

**To Reproduce**

Here is an [example code pen](https://codepen.io/carkod/pen/qBqqgYe)

**Expected behavior**

Default spacing as if using `<button class="p-button--neutral">`.

**Comment by bartaz** [comment]
This is something we've been struggling to properly fix in Vanilla.

We are using margin-right on buttons (to make sure that when button wraps into new line it doesn't have offset on the left). So when buttons are next to each other (`<button A> <button B>`) the first one (button A) will have margin right, and the second one will have the unnecessary margin removed via `:last-of-type` selector. The issue with `:last-of-type` selector is, that it only works on same type of the element (`button` or `a`), so when links and buttons are mixed together both are treated as last of type and have their margin removed.

There is no `:last-of-class` selector that we could use (but arguabely even that won't fix the issue completely as you could mix `p-button--positive` `p-button--negative` that don't share the same class).

I don't know what would be the best way to fix this.

The only solution that comes to my mind now is to remove `:last-of-type` selector from buttons (so they always have right margin), but add `is-last` state, so manually the margin can be removed. This would be a breaking change though.

Or the other way around, we could add a class that would add the margin back, `is-followed-by-a-button` (or however we can call that).

**Comment by anthonydillon** [comment]
The more I looked into this the simpler the solution became which worries me that I'm missing an edge case:
https://codepen.io/anthonydillon/pen/xxRqBqN
