### ISSUE TITLE
Clearer expanding table with support for multiple expanding cells

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#3563]
## Pattern to amend

Proposed update to the expanding table. The goals:

- Clearly separate the expanded panel's contents
- Provide sufficient padding all around, and sufficient white space within
- Make it obvious which table cell initiated the panel, as @cassiocassio (rightly) commented the borders we used on UA were too subtle

[ WIP, will add more variations later, just wanted to capture the idea somewhere]

## Visual

Single dropdown:

![image](https://user-images.githubusercontent.com/2741678/108077632-a60f6780-7064-11eb-889b-02fd514bffdc.png)

Multiple dropdowns as @anasereijo had on UA:
![image](https://user-images.githubusercontent.com/2741678/108077949-03a3b400-7065-11eb-88d0-0c824783cd4e.png)

**Comment by bartaz** [comment]
How does this relate to the modular table spec and design?

I'm not sure if we should update existing "expandable table" pattern, which has a lot of limitations. If we want to rebuild it expanding table it should be done with modular table in mind.

**Comment by anthonydillon** [comment]
We need to separate the styling from the proposal of having individual cell expanding rows. 

Where is the demand for cell expending table coming from?

**Comment by cassiocassio** [comment]
Aside from the UA table, where in the wild have we implemented the expanding cell?

I don't think it's necessarily a bad idea if done well, I just don't think we've used it as much as we thought we might, and the current version is a bit unloved.

@lyubomir-popov do you consider this  proposal a visual layout enhancement,  to make the UA table better this year, because a more considered version is  beyond the current scope?

**Comment by lyubomir-popov** [comment]
Just a note - we had an initial discussion in the design review meeting to discuss these questions in more detail, to quickly summarise - 

1) The expanding table is part of a number of designs that are aobutto go into production - so not really a deprecated thing we can schedule for phasing out.
2) We need to collect the most complicated examples of usage - e.g. a row that is itself clickable, selectable, with text in cells that acts as links to other pages, and multiple chevrons for expanding - @danielmutis and anyone else (@ziheliu214 ?) to provide the most involved cases the've come across
3) Once we have those, we can iterate on the design proposal
4) Since in certain contexts wwe use application panels to display detailed information about the date that corresponds to a given table row, we need a clear destinction - when do you use this expanding table vs when do you use a panel

**Comment by bartaz** [comment]
Previous discussions on the subject: canonical-web-and-design/vanilla-framework#2958

**Comment by clagom** [comment]
WG: moved to the next cycle as it requires product audit and UX specs afterwards.

**Comment by clagom** [comment]
We might solve this issue with the work scheduled for the release UI on Snapcraft: https://zpl.io/25l0pWr
