### ISSUE TITLE
Segmented control / Button group 

### ISSUE THREAD

**Issue by solazio** [canonical-web-and-design/vanilla-framework#3571]
## Visual
Snapcraft admin dashboard:
![image](https://user-images.githubusercontent.com/40214246/108327939-e9341c80-71c3-11eb-846e-a28f1d735eeb.png)

Charmhub library page:
![image](https://user-images.githubusercontent.com/40214246/108328259-4af48680-71c4-11eb-87c5-651fcbddaa7c.png)

Jaas dashboard:
![image](https://user-images.githubusercontent.com/40214246/108328386-724b5380-71c4-11eb-9d3c-2d13d4a8e107.png)

## Context

So far this pattern is used on 3 projects that I am aware of.

**Comment by cristinadresch** [comment]
@danielmutis to work on the rationale of why we need this component, in order to decide if we should build this or not

**Comment by anthonydillon** [comment]
I just applied the new styling to JAAS here: https://github.com/canonical-web-and-design/jaas-dashboard/pull/894

**Comment by clagom** [comment]
CC @amylily1011

**Comment by amylily1011** [comment]
- Define 3 different sizes (based on context)
- 2 stylings (with icon and without icon) (based on context)
- usage: as a secondary tab or region(local) switcher (not meant global switcher like Tabs)
- URL changes based on context.

**Comment by clagom** [comment]
- UX specs, when do we need this component
- Visual
- Implementation in Vanilla

**Comment by clagom** [comment]
@SirSamTumless this is ready for planning

**Comment by danielmutis** [comment]
@ziheliu214 here is the [spec for this component. ](https://docs.google.com/document/d/1__Ee_7s1jLJdNBEyrA-fUKNHx5Jbxz158IZuWtb6zEA/edit?usp=sharing)

**Comment by ziheliu214** [comment]
> @ziheliu214 here is the [spec for this component. ](https://docs.google.com/document/d/1__Ee_7s1jLJdNBEyrA-fUKNHx5Jbxz158IZuWtb6zEA/edit?usp=sharing)

Looks great! Do you have examples to include on when to use the 3 variants?

**Comment by danielmutis** [comment]
@ziheliu214 thanks for the feedback. I have added some comments on the use of the sizes and some examples of this component being used in other products.

**Comment by danielmutis** [comment]
I have amended the spec removing the small size, and keeping regular and dense sizes.
