### ISSUE TITLE
Updating ubuntu.com to 2.24.0 is blocked

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/vanilla-framework#3574]
By [increasing the specificity of cols block value](https://github.com/canonical-web-and-design/vanilla-framework/pull/3504#pullrequestreview-582516441), it has broken a few (strange) local patterns on ubuntu.com.

For example the header logo:
![image](https://user-images.githubusercontent.com/1413534/108407517-ba499500-721b-11eb-9a4e-9fd334b5c742.png)

The cards when purchasing a subscription:
![image](https://user-images.githubusercontent.com/1413534/108407579-d1888280-721b-11eb-9b71-2ef4841cff96.png)

The update has been rolled back in this PR: https://github.com/canonical-web-and-design/ubuntu.com/pull/9258

I think we should talk about the fix as it could be that the local patterns are incorrect.

**Comment by lyubomir-popov** [comment]
The documentation explicitly mentions col classes need to be children of row classes, the fact they worked outside was a bug.

![image](https://user-images.githubusercontent.com/2741678/108481020-8dcf6080-728f-11eb-8387-8ddeeee48389.png)
![image](https://user-images.githubusercontent.com/2741678/108481079-a0e23080-728f-11eb-9d38-5437a40fcd50.png)

**Comment by bartaz** [comment]
As discussed in stand up.

I think on the side of Vanilla we can (temprorarly) revert this change, and bring the column selector to just being the `.col-X` class, so it won't be breaking existing stuff.

Still, on ubuntu.com side, it should be fixed in longer term, because we will be introducing this later (maybe 3.0 or earlier).

**Comment by bartaz** [comment]
Fixed via #3577 and 2.24.1 release
