### ISSUE TITLE
Remove demo specific styling for the application layout

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/vanilla-framework#3575]
**Describe the bug**
While debugging an issue in an app's layout. I was trying to compare the differences between the [Vanilla example](https://vanillaframework.io/docs/examples/layouts/application/structure) and the use in the application. This is made difficult with demo specific styling being applied.

**To Reproduce**

1. Go to https://vanillaframework.io/docs/examples/layouts/application/structure
2. Check the inspector for `app-demo` class
3. This class applies to style making the elements differ in the wild

**Expected behavior**
I would expect the examples to have no local styling in the demos. Presentational styles are sometimes required but not within the layout itself.

**Additional context**
I am trying to debug the anbox-app layout where the navigation scrolls:
![image](https://user-images.githubusercontent.com/1413534/108481891-a55b1900-7290-11eb-957d-8067bedf3f49.png)

**Comment by bartaz** [comment]
The example styling is purely visual, only some backgrounds and borders are applied to make the layout visible. Without it, it would be just white boxes without any borders. It would make it really hard to see anything.

When looking for 'real world use' example the better one is the 'default': https://vanillaframework.io/docs/examples/layouts/application/default

This one uses built-in panel styles (just as real app should do), and it should not contain any custom styling.

**Comment by bartaz** [comment]
As mentioned in the stand up, maybe we made this 'structure' example look to much like a real thing.

It's supposed to be a wireframe type of example (similar to grid examples with redish boxes). Maybe we can update app layout strucutre example to reuse similar color to give it more 'debug' look.

**Comment by anthonydillon** [comment]
Yeah, I think we should show examples of real-world uses and the wireframe version might be better as a visual image of the structure maybe?

**Comment by bartaz** [comment]
> Yeah, I think we should show examples of real-world uses and the wireframe version might be better as a visual image of the structure maybe?

@anthonydillon  Problem with an image is that it's static. And in such layout it's quite important to be able to demonstrate how it behaves in different screens. 

But we can definitely look into making the 'structure' example look more like a wireframe to reduce the demo custom styling.
