### ISSUE TITLE
Horizontal/vertical tabs with nested content

### ISSUE THREAD

**Issue by elioqoshi** [canonical-web-and-design/vanilla-framework#3582]
A pattern in Vanilla needs to be flexible enough that it can be used across a wide range of scenarios and shouldn't be constrained to a specific number of applications.

## Visual

![Frame 2.png](https://images.zenhubusercontent.com/5a5649f54b5806bc2bc23b6d/79719e00-dde4-4cba-8c03-3542b77bd622)
![Frame 3.png](https://images.zenhubusercontent.com/5a5649f54b5806bc2bc23b6d/a62f3f86-02f2-4eaf-a4b4-52306dad5416)
![Frame 4.png](https://images.zenhubusercontent.com/5a5649f54b5806bc2bc23b6d/6a0e54bf-dc13-4853-b7fb-453d5085b058)

(mockups are not pixel-perfect, mostly wireframes)

## Context

We use a lot of vertically stacked content sections on Ubuntu.com which make content harder to scan and hard to digest (especially many of the Enterprise section pages). With tabs we could nest related content with each other, reducing page length and improving scannability of the content. In the above examples we have 2 scenarios which illustrates how this could look like:

1A Horizontal Tabs for Raspberry Pi https://ubuntu.com/download/raspberry-pi
1B Vertical Tabs for Raspberry Pi https://ubuntu.com/download/raspberry-pi
2 Vertical Tabs for Trainings https://ubuntu.com/training

## State

Only one content block would be shown during a time. Cycling through the tab items would cycle through the content blocks.

## Progressive enhancement

All tabs could be shown as scrollable horizontal tabs or as a collection of items as we do with the ubuntu.com menu where items would wrap on a new line:
![image.png](https://images.zenhubusercontent.com/5a5649f54b5806bc2bc23b6d/8f1ad855-c4a8-4f9f-9dae-a4226916fc74)

Content blocks would basically be existing components, just nested by the tab menu.

**Comment by cristinadresch** [comment]
These are existing components in vanilla e.g. left navigation that could be used within a section of the page. Also, Mark has a tendency to want to expose all content on the page and not hide it underneath tabs etc.
