### ISSUE TITLE
Searching code snippet returns 404

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/vanilla-framework#3599]
When [searching for code snippet](https://vanillaframework.io/docs/search?q=code+snippet&submit=) one of the [top result is a 404](https://vanillaframework.io/docs/examples/patterns/code-snippet/code-snippet-dropdown).

**Comment by bartaz** [comment]
It seems that some of the examples have been renamed since initial release, so `/docs/examples/patterns/code-snippet/code-snippet-dropdown` became `/docs/examples/patterns/code-snippet/dropdown`

**Comment by anthonydillon** [comment]
I believe we can trigger google to reindex our pages. @nottrobin is that true?

**Comment by nottrobin** [comment]
Yes, through webmaster tools.

They don't make any promises or guarantees, but they should get to your request at some point.

Let @pmahnke know, I think, if you need to be given access to manage the domain.

**Comment by nottrobin** [comment]
From [Ask Google to recrawl your URLs](https://support.google.com/webmasters/answer/6065812?hl=en):

> Use the URL Inspection tool to request a crawl of individual URLs. Note that if you have large numbers of URLs, you should submit a sitemap instead.
> 
> To submit a URL to the index:
> 
>     Read the general guidelines above.
>     Inspect the URL using the URL Inspection tool.
>     Select Request indexing. The tool will run a live test on the URL to see whether it has any obvious indexing issues, and if not, the page will be queued for indexing. If the tool finds issues with the page you should try to fix them.
> 
> Note: Requesting a crawl does not guarantee that inclusion will happen instantly or even at all. Our systems prioritize the fast inclusion of high quality, useful content.

I believe @pmahnke gave @bartaz access to these tools, so maybe @bartaz you could give it a go?

We are making a recent push to try to show people how to solve problems themselves to reduce the amount of maintenance falling on certain people, hope that's ok. :)

**Comment by bartaz** [comment]
Yes, thanks, I have access now. I think I found and triggered indexing on relevant pages.

**Comment by bartaz** [comment]
Reindexed example pages, and also requested removal of 404 results. So hopefully this will be fixed soon.
