### ISSUE TITLE
Modular Table rows' interaction exploration

### ISSUE THREAD

**Issue by ziheliu214** [canonical-web-and-design/vanilla-framework#3604]
## Pattern to amend

Modular Table rows

## Visual

I created a JAAS local issue here:
https://github.com/canonical-web-and-design/juju-squad/issues/1679

## Context
We had a design Sync meeting between JAAS and MAAS,
current interactive elements on table rows need consistency.
https://github.com/canonical-web-and-design/juju-squad/issues/1649

**Comment by clagom** [comment]
@ziheliu214 @lyubomir-popov can you have a sync and discuss the detail, please.

**Comment by cristinadresch** [comment]
Link to meeting notes jaas/maas sync https://github.com/canonical-web-and-design/meeting-notes/issues/754

**Comment by ziheliu214** [comment]
updates on 17th March:

We are still changing table contents on JAAS right now (because of the managing CMR feature). Once it's finished, we can summarise the number of links on a row, and their different use cases on JAAS and MAAS to see if the modular table needs adaption. 

the previous proposal and benchmarking:
https://zpl.io/aNNnEA9

CC: @lyubomir-popov @amylily1011 @long-chung

**Comment by clagom** [comment]
@ziheliu214 to have a look at this issue and update it
