### ISSUE TITLE
Modular table header - Sortable column and segmentation 

### ISSUE THREAD

**Issue by ziheliu214** [canonical-web-and-design/vanilla-framework#3605]
Proposed design update for modular table header which includes:

- All column headings to be left aligned
- Column heading to have a vertical line to segment each column
- Propose a new icon for sort

![Table](https://user-images.githubusercontent.com/68847062/109822636-0c80b200-7c2f-11eb-8f54-f82f26567acd.png)

JAAS local issue:

https://github.com/canonical-web-and-design/juju-squad/issues/1678

**Comment by clagom** [comment]
Duplication, already in WG
