### ISSUE TITLE
Running tests checks all vendor files

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/vanilla-framework#3611]
Locally if you run `./run test` it fails as some vendor files do not lint. The test should only run on Vanilla code.

**Comment by bartaz** [comment]
@anthonydillon What exactly fails for you? Running `dotrun test` seems to work fine for me (no unexpected errors). Also, we run it as PR check, so if it fails locally it would fail on CI as well.

**Comment by anthonydillon** [comment]
Still fails for me on the latest master. It fails with errors like:
```
[warn] vendor/bundle/ruby/2.5.0/gems/kramdown-1.17.0/test/testcases/block/09_html/html_to_native/table_simple.html
vendor/bundle/ruby/2.5.0/gems/kramdown-1.17.0/test/testcases/block/09_html/markdown_attr.html[error] vendor/bundle/ruby/2.5.0/gems/kramdown-1.17.0/test/testcases/block/09_html/markdown_attr.html: SyntaxError: Unexpected closin
g tag "p". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (19:1)
[error]   17 | <p>                                                                                               
[error]   18 |   <p><em>para</em></p>                                                                            
[error] > 19 | </p>                                                                                              
[error]      | ^^^^                                                                                              
[error]   20 |                                                                                                   
[error]   21 | <p>                                                                                               
[error]   22 | <em>para</em> 
```

**Comment by bartaz** [comment]
@anthonydillon we don't use ruby for a long time now in Vanilla I think. `vendor` folder is in gitignore and you don't need it. You can safely remove it.

**Comment by anthonydillon** [comment]
After clearing out my local directory and re-cloning I got the tests to pass. One gotcha is that you need to run `dotrun build` before you can test. Maybe tests should do that for us?

**Comment by bartaz** [comment]
Fair point. But this will mean slowing down the test runs (as they will always need to build, even if you have built locally already). Not sure how other projects approach that. Should `dotrun test` work on clean unbuilt project, or can we assume you build first...

We can have a look into that.

**Comment by anthonydillon** [comment]
I guess its fine as I assume CI runs build && test.
