### ISSUE TITLE
Muted heading for whitepaper/case-study/webinar content strip

### ISSUE THREAD

**Issue by bethcollins92** [canonical-web-and-design/vanilla-framework#3618]
## Visual

![image](https://user-images.githubusercontent.com/58959073/110308675-533c2680-7ff8-11eb-95f1-a33398612614.png)

![image](https://user-images.githubusercontent.com/58959073/110309246-03aa2a80-7ff9-11eb-8c73-eddab5abd20c.png)

## Context

Currently there is a hack being used for the muted-heading when including a whitepaper/case-study/webinar content strip, which is being used in a few places. see [here](https://github.com/canonical-web-and-design/ubuntu.com/pull/9365/files) and [here](https://ubuntu.com/0_docs/content_strips). Could this be a pattern?

**Comment by clagom** [comment]
Thanks @bethcollins92, @lyubomir-popov is going to work on it.

**Comment by lyubomir-popov** [comment]
Somewhat similar situations on Maas.io:

![image](https://user-images.githubusercontent.com/2741678/113126083-310c8180-920f-11eb-8292-0a7efee0b6c1.png)

**Comment by lyubomir-popov** [comment]
Also worth comparing with the spacing / positioning within the matrix component:
![Uploading image.png…]()

**Comment by anasereijo** [comment]
another example:

<img width="1334" alt="Screenshot 2021-04-07 at 14 28 08" src="https://user-images.githubusercontent.com/36884067/113874266-86b3d180-97ad-11eb-8c93-b370ae6ab209.png">
