### ISSUE TITLE
Linebreaks occur incorrectly for monospace text on published web page

### ISSUE THREAD

**Issue by pmatulis** [canonical-web-and-design/vanilla-framework#3636]
Linebreaks occur incorrectly on rendered HTML for monospaced text.

[Published page](https://microstack.run/docs/multi-node):
![image](https://user-images.githubusercontent.com/6303808/111722287-f3375280-8837-11eb-800f-80b0df41bc71.png)

[Discourse page](https://discourse.ubuntu.com/t/multi-node/18259):
![image](https://user-images.githubusercontent.com/6303808/111722353-14983e80-8838-11eb-8f6d-5787980b6334.png)

**Comment by anthonydillon** [comment]
@pmatulis thank you. Your right the inline code element should not wrap.

**Comment by sowasred2012** [comment]
This is fixed, it is an issue that had been fixed in Vanilla a little while ago, but the site hadn't been deployed to production recently. I have since deployed it.
