### ISSUE TITLE
Modal close button truncates title on mobile

### ISSUE THREAD

**Issue by wgx** [canonical-web-and-design/vanilla-framework#3639]
![image](https://user-images.githubusercontent.com/930099/111951207-3fee8800-8adb-11eb-9350-af21183321af.png)

When viewed on mobile, a long title is truncated by the close button on a modal. 

Safari 14, iOS 14.4.

**Comment by anthonydillon** [comment]
Thanks @wgx, looks like we should add some right padding to that component.
