### ISSUE TITLE
Side-navigation: add example with counts

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#3658]
Counts are cropping up in a number of places, e.g.:
![image.png](https://images.zenhubusercontent.com/59d2496bb0222d5de479ea17/5c23897a-5e86-4e7d-a0c5-d0ec2cbf1294)

The design above has a couple of drawbacks:

- counts are visually grouped as a column
- the distance doesn't help the eye follow from label to count

This problem has been solved nicely in table of contents a long time ago, here's an example from Robert Bringhirst's "The Elements of Typographic Style"
 
![IMG_0500.jpg](https://images.zenhubusercontent.com/59d2496bb0222d5de479ea17/aef7c240-3357-4230-ab77-5d2e625d5428)

Proposal: 

1) inline counts with a 1rem gap between menu item and count
2) test same alignment logic with lables

TBD: add a screenshot of the above proposal

**Comment by anasereijo** [comment]
Hi Lyubo, thanks for suggesting this - I really like the idea. See below how it looks on my design proposal

![search results](https://user-images.githubusercontent.com/36884067/112501507-35551c80-8d81-11eb-872c-12b0d3b50b51.jpg)

**Comment by sowasred2012** [comment]
Closing: after discussion with @lyubomir-popov, decided this was easily achievable with what's currently available in Vanilla, e.g.

```html
<label class="p-checkbox">
  <input type="checkbox" aria-labelledby="Core 20" class="p-checkbox__input" id="release-filter" name="release" value="Core 20">
  <div class="p-checkbox__label" id="Core 20">
    <span>Core 20 coimcom co comcomco c ocommc
      <!-- insert count with the below markup -->
      <span class="u-text--muted">&emsp;30</span>
    </span>
  </div>
</label>
```
