### ISSUE TITLE
Update table spec with alignment rules for icons, icons accompanied with words, etc.

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#3659]
Related to https://app.zenhub.com/workspaces/vanilla-working-group-613738fb1be3b40010b8c5a0/issues/canonical-web-and-design/vanilla-framework/3710

**Comment by clagom** [comment]
Issue generated from a meeting between @lyubomir-popov @long-chung @amylily1011 @ziheliu214 about iterating the modular table.
- Collect a list of issues to inform the UX solutions (e.g. Ana's UA table, Juju Dashboard/MAAS with in-line CTAs)
- UX specs

@SirSamTumless making this an Epic, needs UX and Visual to amend UX specs.

**Comment by clagom** [comment]
Consider: https://app.zeplin.io/project/601d6513b99f24a8412ecfa5/screen/6023f659c384ee06240c02b4

**Comment by clagom** [comment]
WG: postponed to next cycle
