### ISSUE TITLE
linkchecker fails when installed via pip3

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#3682]
Recently linkchecker started to fail running when it was installed via pip3:
https://github.com/canonical-web-and-design/vanilla-framework/pull/3679/checks?check_run_id=2251926958

We reverted it back to be installed via apt (#3681), but this forces us to run the CI on ubuntu@18.04.

We should investigate why the linkchecker fails to run in GitHub action and try to fix it.
It's hard to say if it's a problem of linkchecker, GitHub Actions environment, or python envirionment?

**Comment by anthonydillon** [comment]
I recently rolling out a bunch of actions which might help: https://github.com/canonical-web-and-design/maas.io/blob/master/.github/workflows/docs-links.yaml

**Comment by bartaz** [comment]
> I recently rolling out a bunch of actions which might help: https://github.com/canonical-web-and-design/maas.io/blob/master/.github/workflows/docs-links.yaml

Thanks @anthonydillon

Thats weird. We used to have `sudo pip3 install linkchecker` and it worked for a while, and yesterday it stopped.
Seems that what you suggest `sudo pip install LinkChecker` works fine (https://github.com/canonical-web-and-design/vanilla-framework/pull/3683/checks?check_run_id=2252883684) at this point.

I don't know python or GH actions enough to understand the difference...

**Comment by anthonydillon** [comment]
I'm surprised it worked before. I believe pip3 uses python 3 but linkchecker only works with python 2. I can only assume something changed in Ubuntu as it's the variable part.

**Comment by bartaz** [comment]
> I'm surprised it worked before. I believe pip3 uses python 3 but linkchecker only works with python 2. I can only assume something changed in Ubuntu as it's the variable part.

Latest linkchecker (available via pip) uses (and requires) python 3: https://pypi.org/project/LinkChecker/
"Requires: Python >= 3.6"

It was the older version of linkchecker available via apt that was using python 2 (and that's why it's not available in new ubuntu).
