### ISSUE TITLE
Tabs and sidebar links don't show active states when focused

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/vanilla-framework#3686]
**Describe the bug**

When an active tab or active sidebar link is focused then the active bar is hidden. This is an issue with JavaScript apps as there is no page refresh once the link is clicked, so the active state is invisible until the user clicks elsewhere on the page.

**To Reproduce**

1. Go to https://vanillaframework.io/docs/patterns/tabs
2. Scroll down to the first example.
3. Click on the active tab (Machine summary) and the underline will disappear.
4. Go to https://vanillaframework.io/docs/patterns/navigation
5. Scroll down to the side navigation example.
6. Click on the active link (Commissioning and hardware testing scripts) and the border on the left will disappear.

**Expected behavior**

The active state should be visible.

**Additional context**

It seems that these borders are being hidden so that a focus state can be shown (which doesn't seem to exist anymore on mouse click):
https://github.com/canonical-web-and-design/vanilla-framework/blob/master/scss/_patterns_tabs.scss#L79
https://github.com/canonical-web-and-design/vanilla-framework/blob/5d3821024bd80c355c12cfed33a1e2662461f976/scss/_patterns_side-navigation.scss#L203

**Comment by huwshimi** [comment]
We also had to add `:focus` and `:active` states as well in MAAS. Our fixes for these two issues can be seen here: https://github.com/canonical-web-and-design/maas-ui/pull/2462/files#diff-e781fe83665a0b7baa36c2c6606251a56596a4c0ce538dccc4e61dd0749972deR85.

**Comment by anthonydillon** [comment]
This looks like a real issue in Vanilla. MAAS is now explicitly adding back something Vanilla is removing.

**Comment by anthonydillon** [comment]
I don't think this is a Low
