### ISSUE TITLE
Provide a pattern that can explain why an element is disabled

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/vanilla-framework#3690]
The sequel to https://github.com/canonical-web-and-design/vanilla-framework/issues/2180

## Visual
https://codepen.io/sowasred2012/pen/PoWJpay

![Screenshot from 2021-04-07 14-34-35](https://user-images.githubusercontent.com/2376968/113875195-6afcfb00-97ae-11eb-9392-7b4ba89c123c.png)

## Context
We previously suggested tooltips could be used on disabled elements, such as buttons, but [it was agreed](https://github.com/canonical-web-and-design/vanilla-framework/issues/2180#issuecomment-814218162) that it should be clear to the user why the element is disabled without them first needing to interact with the element to acquire the information.

In a follow up conversation, it was suggested that Vanilla should have a pattern to cover these scenarios.

**Comment by clagom** [comment]
This would result in a too broad guidelines and it's something that each UXer should take into consideration when working on the user experience of a project/flow/product.
The example here is one of the multiple possible solutions, too general to adopt broadly on different use cases.
To be defined case by case by UXers.
