### ISSUE TITLE
Consider combining new logo section with inline images

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/vanilla-framework#3700]
Would it be possible to use the inline-images classes for the new logo section? If we could, this would:
- simplify learning for devs
- instant adoption
- no deprecations

**Comment by lyubomir-popov** [comment]
I don't think this is a good idea foer 3 reasons:

- It is not a 1 to 1 translation - there's an additional wrapper, so you'd have to add that to all current inline-images instances
-  The name inline images is very misleading - there's nothing inline about them. They are block level elements that behave as such
- I'll describe this in the blog post I'm writing, but I think the transition needs to be a concious thing - not just a dependancy update. To truly get the benefit of the new pattern the team needs to understand that logos should first go through the logo template, where each logo's size is considered in relation to the sizes of the other logos within that strip. So I think it should be a planned piece of work where each designer revises the logos on the site they work on, resizes them via the template, and hands them over to dev

**Comment by anthonydillon** [comment]
> It is not a 1 to 1 translation - there's an additional wrapper, so you'd have to add that to all current inline-images instances

It would have to be a drop-in replacement which is the main question.

> The name inline images is very misleading - there's nothing inline about them. They are block level elements that behave as such

I am not disputing the name is a better description of the pattern but name changes come with a lot of work. Such as depreciation and re-education. If we commonly found this was an issue when it would be worth it. Also, at no point should we be naming things but the attributes of the styling. Only its function.

> 'll describe this in the blog post I'm writing, but I think the transition needs to be a conscious effort - not just a dependancy update. To truly get the benefit of the new pattern the team needs to understand that logos should first go through the logo template, where each logo's size is considered in relation to the sizes of the other logos within that strip. So I think it should be a planned piece of work where each designer revises the logos on the site they work on, resizes them via the template, and hands them over to dev

This is concerning. We are a small team (4 designers). Why would you need to force hours of work on the rest of the team to make this transition happen?

Due to the fact its not a drop in replacement (or could it?) would lead this issue to be invalid.

**Comment by lyubomir-popov** [comment]
> This is concerning. We are a small team (4 designers). Why would you need to force hours of work on the rest of the team to make this transition happen?

No one is forcing anyone to do it - but concerns have been raised in the past about the unsightliness of the inline images, and I think the act of deprecating the inline images, and giving people at least 6 months before the deprecation requires action,  creates a good opportunity to plan and update the existing strips. 

To reiterate - if you do not do this nothing bad will happen. Simply changing the markup will lead to significant improvement and ease of maintenace.

**Comment by anthonydillon** [comment]
If it can not a drop-in replacement then this is not possible.
