### ISSUE TITLE
Write blog post on logo section component

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#3701]
80% draft: https://docs.google.com/document/d/15FTvDI-NHfuWnJVVGnNUeJk9BoHA3ybsPtRr1iaALWk/edit#

**Comment by lyubomir-popov** [comment]
@spencerbygraves could you review this blog post when you get a chance?

https://docs.google.com/document/d/15FTvDI-NHfuWnJVVGnNUeJk9BoHA3ybsPtRr1iaALWk/edit?pli=1#

**Comment by anthonydillon** [comment]
Good article @lyubomir-popov, really feels like it's a good technique as you get towards the end. I only have view rights so will leave some comments and suggestions here: 

Could you add links everywhere you can. For example, the old inline images pattern, canonical.com at the end, etc.

---

> This is not only inconsistent but also time consuming as developers had to try to adjust logo sizes by adding inline width and height attributes of individual logos.

This is still true with the new pattern as a need the logos to lazy load and to reduce CLS.

---

> Most logos roughly fir into 3 categories

I believe you mean "fall".

**Comment by lyubomir-popov** [comment]
Thanks for the comments @anthonydillon, and sorry about the permissions. I've changed them.

**Comment by lyubomir-popov** [comment]
Link on wp-admin https://admin.insights.ubuntu.com/wp-admin/post.php?post=102611&action=edit

**Comment by lyubomir-popov** [comment]
Addressed the comments @anthonydillon it's ready for a fina llook at the link above in the wordpress admin.

**Comment by anthonydillon** [comment]
LGTM @lyubomir-popov :+1:

**Comment by spencerbygraves** [comment]
Thanks @lyubomir-popov looks good.

**Comment by lyubomir-popov** [comment]
Thanks, I've published it https://admin.insights.ubuntu.com/2021/04/30/taming-unruly-logo-sections/
