### ISSUE TITLE
Add vertical dividers between header elements in table

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/vanilla-framework#3710]
## Pattern to amend

Table

## Visual

![III  Action logs - Default view](https://user-images.githubusercontent.com/532033/115294431-d2536d00-a115-11eb-9db1-a0147f387e5a.png)

## Context

This design calls for small vertical dividers between the header elements in the table. It would be great if we could apply this pattern (or have it available) in vanilla.

**Comment by clagom** [comment]
WG: implement this in the current tables, then update the modular table specs after these investigations here: https://app.zenhub.com/workspaces/vanilla-squad-59438c953747487777fbe484/issues/canonical-web-and-design/vanilla-framework/3659

**Comment by clagom** [comment]
@SirSamTumless this is ready for planning

**Comment by clagom** [comment]
@long-chung the icon for sorting should be this one:
![Screenshot 2021-07-28 at 10.42.45.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/4321521a-d76e-4376-8324-74ddfa65b485)

The needs for separators is still valid

**Comment by clagom** [comment]
Blocking this issue because we currently don't have this design implemented. Should probably be revisited on the modular table, too.
