### ISSUE TITLE
Chevrons are not aligned with the text

### ISSUE THREAD

**Issue by solazio** [canonical-web-and-design/vanilla-framework#3711]
## Pattern to amend

p-subnav

## Visual

![image](https://user-images.githubusercontent.com/40214246/115563769-c9969e80-a2af-11eb-8d6c-1ec8dbaaea5e.png)

## Context

If the navigation height is different than 48px, the chevrons will not be aligned with the text.

**Comment by lyubomir-popov** [comment]
@sowasred2012 this seems fixed - can we close?
![image](https://user-images.githubusercontent.com/2741678/126966556-7fba09b6-a496-45f2-b6cd-2b352dfac70d.png)

**Comment by sowasred2012** [comment]
@lyubomir-popov ah yes - this was raised on juju.is, I'll add an issue there to clean up the [local fix Ovi introduced](https://github.com/canonical-web-and-design/juju.is/blob/master/static/sass/_patterns_p-subnav.scss#L6-L10) while waiting for this.
