### ISSUE TITLE
Fluid breakout layout: toolbar should align to fixed-width

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#3732]
The platform select would look better if aligned ot the fixed width:

![image](https://user-images.githubusercontent.com/2741678/117314503-bcb4a600-ae7e-11eb-9bd2-00df7f432bed.png)

As seen on juju.is

**Comment by barrymcgee** [comment]
Also on https://charmhub.io/?q=ceph+osd

<img width="2043" alt="Screenshot 2021-05-06 at 15 09 48" src="https://user-images.githubusercontent.com/505570/117314808-07362280-ae7f-11eb-9a13-b4e7f82a7449.png">

**Comment by sowasred2012** [comment]
@lyubomir-popov I've marked this with a question label, was hoping to get your thoughts on this.

At large breakpoints, it looks like the toolbar is left aligned with a typical fixed width element e.g. the nav mentioned in the issue, but at smaller breakpoints it quickly falls out of line. The toolbar is clearly meant to left align to the main section of the fluid layout below, so I'm not sure what the best way to proceed here is:

![toolbar](https://user-images.githubusercontent.com/2376968/119524971-0570c800-bd76-11eb-859c-cbbc9c44f250.gif)

I considered a couple of routes, but they're very different approaches, so need your wisdom:
- Keep the toolbar left aligned as it is, and somehow right align with fixed width elements like the nav.
  - If we go with the above, should it be optional, with a utility class? Maybe it's not always necessary to make it right align with another element.
- Just take the toolbar out of the fluid layout pattern and make it a standalone 12 column pattern.

**Comment by lyubomir-popov** [comment]
Asigning to myself as I have to do some thinking, I'll get back to you tomorrow.

**Comment by lyubomir-popov** [comment]
Thinking some more on this, @danielmutis does the platform dropdown have to be on the right? It might be easier to solve this if the dropdown is left-aligned. Would that be acceptable from the charmhub store point of view?

**Comment by lyubomir-popov** [comment]
@danielmutis For example, would something like this work?

![image](https://user-images.githubusercontent.com/2741678/119656822-09a6ef00-be23-11eb-842c-96f22f3a07a0.png)

**Comment by danielmutis** [comment]
@lyubomir-popov yes, it would definitively work. The only reason platform is on the other side is because it used to be grouped with a search bar and a sort button, which felt easier to scan visually by being on that side. I don't have a strong opinion on this.

**Comment by lyubomir-popov** [comment]
In that case I will close this. Solving the problem this way is far eaiser.
