### ISSUE TITLE
Vanilla-framework package homepage links goes nowhere

### ISSUE THREAD

**Issue by carkod** [canonical-web-and-design/vanilla-framework#3734]
**Describe the bug**

This link goes to http://canonical-web-and-design.github.io/vanilla-framework/ which doesn't exist
<img width="980" alt="Screenshot 2021-05-06 at 16 30 00" src="https://user-images.githubusercontent.com/14939793/117325430-9e53a800-ae88-11eb-960f-1b54fb468d01.png">

**To Reproduce**
 You can find this in any renovate update where there is a vanilla update.

**Expected behavior**

I believe changing [this line](https://github.com/canonical-web-and-design/vanilla-framework/blob/master/package.json#L11) might fix it

**Comment by sowasred2012** [comment]
Thanks for reporting @carkod - the "this line" link doesn't work, could you share it with us?

**Comment by carkod** [comment]
> Thanks for reporting @carkod - the "this line" link doesn't work, could you share it with us?

Fixed. I think it's just the homepage link in `package.json`

**Comment by anthonydillon** [comment]
I believe it's the homepage field in package.json.
