### ISSUE TITLE
p-stepped-list numbers look broken when used with a paragraph instead of a title

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#3748]
## Pattern to amend

Details visible [here](https://github.com/canonical-web-and-design/juju.is/issues/239)
## Visual
![image](https://user-images.githubusercontent.com/2741678/118782074-a0a10380-b885-11eb-89e8-55e315623738.png)

Provide a screenshot or link to a prototype of your pattern amendment.

**Comment by bartaz** [comment]
Hmm... I thought I fixed it with https://github.com/canonical-web-and-design/vanilla-framework/pull/3731 but it doesn't seem to work... Not sure why.

**Comment by bartaz** [comment]
Oh, I think it's fixed, but not released. We haven't released last week because of the sprint.

So marking as fixed. It will work with next release.
