### ISSUE TITLE
Whitepaper/case study heading pattern

### ISSUE THREAD

**Issue by bethcollins92** [canonical-web-and-design/vanilla-framework#3753]
## Visual

![image](https://user-images.githubusercontent.com/58959073/119123932-04633200-ba28-11eb-82f6-c7ff0e18ba8d.png)

![image](https://user-images.githubusercontent.com/58959073/119123956-0c22d680-ba28-11eb-85ea-70d8b8f4f742.png)

## Context

This pattern is being used in multiple places to showcase whitepapers/case studies/blogs. e.g. https://anbox-cloud.io/ and (soon to be) https://ubuntu.com/financial-services. Currently this is created with custom styles.

**Comment by bartaz** [comment]
Hey @bethcollins92, thanks for reporting this.

Could you give a bit more context and examples of custom styles needed for this?

By having a quick look those seem to be built with combination of existing patters (matrix, heading icon, etc).

**Comment by bethcollins92** [comment]
Sure - we add these styles to the p tag

```<p class="p-heading-icon__title p-heading--4" style=" color: #FFF; line-height: 1.5rem;">Case study</p>```

and also in ubuntu.com repo in `static/sass/_pattern_heading-icon.scss` the following to ensure the icons aren't streched 
```
  .p-heading-icon__img--small {
    align-self: center;
    height: auto;
    margin-bottom: 0;
    margin-top: 0.25rem;
    max-width: 2rem;
  }
```

**Comment by bartaz** [comment]
That's helpful, thanks @bethcollins92.

It feels that part of this is adding dark theme to the patterns (like heading icon), so it can be used on dark backgrounds with white text.

And the other one is figuring out how heading icon should work with icons/images that are not square.

So I feel like it's more amendment/fixes to heading icon pattern than new pattern, but we will look into that.

**Comment by bethcollins92** [comment]
@bartaz That sounds exactly right - thank you!
