### ISSUE TITLE
New mobile table card width broken 

### ISSUE THREAD

**Issue by bethcollins92** [canonical-web-and-design/vanilla-framework#3754]
**Describe the bug**

the width of each `<td>` in the responsive table pattern is still being applied on the cards.

![image](https://user-images.githubusercontent.com/58959073/119167146-67b88880-ba57-11eb-9849-ed83b13b5027.png)

if I override the width and set it to 100% it fixes it (apart from the text being cut off at the end?):

![image](https://user-images.githubusercontent.com/58959073/119167253-90d91900-ba57-11eb-83eb-c2999532640a.png)

**To Reproduce**

1. Go to https://ubuntu.com/cube/microcerts
2. View the page in mobile view and see the card is broken

**Expected behavior**

The `<td>` widths should be overridden to 100% as soon as the card is visible

**Desktop (please complete the following information):**

- OS: Mac 
- Browser: Chrome

**Comment by sowasred2012** [comment]
The widths of each column are being overridden by https://github.com/canonical-web-and-design/ubuntu.com/blob/master/static/sass/_pattern_cube-table.scss and the `.p-table--cube` class; I don't think this is a Vanilla issue, and could be fixed using media queries, i.e.

```
@media (min-width: $breakpoint-medium) {
  width: 4%;
}
```

That said, we should look at the text overflow/lack of ellipsis, it seems like it doesn't apply to child elements for some reason.

**Comment by bethcollins92** [comment]
Thanks Scott - I've fixed it using media queries but me and Ant thought there could be other places where people have set the widths on a table without using media queries so is there a way to make sure it's overridden with 100% on small screens?

**Comment by anthonydillon** [comment]
Your right Scott its not a Vanilla issue which is what I originally thought then I thought, damn we now have to go and add media queries to all widths on a mobile-card table. That lead me to think, Vanilla takes over control of the presentation of the data table at the small breakpoint with the mobile card and so the "true" fix would be for Vanilla to set the widths to 100% which is what it needs to display the card view.

**Comment by sowasred2012** [comment]
@anthonydillon @bethcollins92 yeah, this is a fair point - after a bit of tinkering, there's a simple fix we can do, and we'll get it released today. Give me a couple mins!
