### ISSUE TITLE
Search box in navigation is misaligned

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#3764]
After the navigation height update the searchbox in the navigation is misaligned a bit (has less space from the top than from the bottom):

![Screenshot 2021-05-26 at 15.29.14.png](https://images.zenhubusercontent.com/593a660851aa2c30578102bb/89be584d-246b-4a5f-97a5-34005990e695)

**Comment by lyubomir-popov** [comment]
I have a fix for that in the states pr, will be merged soon
