### ISSUE TITLE
Form labels, mandatory field and error messages

### ISSUE THREAD

**Issue by long-chung** [canonical-web-and-design/vanilla-framework#3766]
WG decided to investigate the pattern altogether, considering whether this is the right indication for a mandatory fields, confusing it with annotations. This epic includes working on labels, mandatory field and error messaging.
https://www.nngroup.com/articles/required-fields/
This needs to consider accessibility: https://www.deque.com/blog/anatomy-of-accessible-forms-required-form-fields/

---------------

Original issue about red asterisk:
Red asterisk on required field labels

See checkbox as example
https://vanillaframework.io/docs/base/forms

![Screenshot 2021-05-26 at 17.22.53.png](https://images.zenhubusercontent.com/5f1ec667037c164bb1ed32d9/282171e6-07e3-42c7-8daf-a4c6f4e3b909)

Context

We currently use a red asterisk to denote that a type of form field is a required input. 
Red is associated with danger or something has gone bad which isn't the message we want to convey for required fields.

In JAAS we use the standard text colour for labels and would like to propose we change the red to black.

JAAS example [here](https://zpl.io/V4NlA94)

**Link to designs**

Link to [Zeplin](https://zpl.io/anBA4Lr)

Link to [Figma](https://www.figma.com/file/3JbdJmkcWRyCrRQvOuTVoP/21.10-Vanilla-Mandatory-fields-and-Error-labels?node-id=201%3A65)

**Comment by clagom** [comment]
Work to be considered for this epic: https://app.zenhub.com/workspaces/-vanilla-squad-59438c953747487777fbe484/issues/canonical-web-and-design/vanilla-framework/3304

**Comment by AnnSoMuller** [comment]
@wgx,
Having done some research and reading N&N group and Deque, I would suggest that with go with the following direction:

- keep the asterisk (*) as a marker: well known pattern
- Keep it in the same colour than the text (not red): no accessibility issue, no 'danger' association
- show " * indicates a required field" at the beginning of the form (before all required patterns): no more confusion with annotation
- keep the asterisk before the label (on the left hand side): easier to scan

 here is an example:
![Screenshot 2021-06-22 at 10.05.15.png](https://images.zenhubusercontent.com/606c1e6c5aab87d8cd196107/cc49b072-ad21-4cd4-a42b-24889cb0b607)

**Comment by wgx** [comment]
@AnnSoMuller When we work on this today, let's think about the submitted-but-failed state - which could address [3324](https://github.com/canonical-web-and-design/vanilla-framework/issues/3324)

**Comment by wgx** [comment]
We should add to this with:

>Using client-side validation, the omission is detected and an alert dialog appears informing the user that mandatory fields have not been completed. The labels of the fields with this problem are changed to identify the problem field, and links(1) to the problem fields are inserted in the document after the submit button so the user can move to them after dismissing the alert.

(1) can be hidden from screens and only shown to screen-readers. 

https://www.w3.org/WAI/WCAG21/Techniques/general/G83.html#examples

If feel that including this in the pattern will resolve [3324](https://github.com/canonical-web-and-design/vanilla-framework/issues/3324) also.

**Comment by wgx** [comment]
Myself and @AnnSoMuller have put together a mini-spec which we believe resolves all the issues within this epic.

The doc is here:

[Form labels & Mandatory fields](https://docs.google.com/document/d/1gXvmudhPYvW2-mRxjXDjG4VVIrEfeYl2fMFo7_I41A0/edit#heading=h.xv8ipqxdub9l)

Feel free to review, and bear in mind the images are wireframes and will need visual design review.

**Comment by ziheliu214** [comment]
@wgx @AnnSoMuller Thanks for the work! Could you please walk us through the final design in tomorrow's design assembly, if everyone is ok with it we will close the issue. 😊

**Comment by ziheliu214** [comment]
@wgx @AnnSoMuller 
Thanks for the demo! 
So now the team agrees on this change, we can get ready to close the issue, tasks remaining is:
- to add the new visual updates, behaviours specs and accessibility checks to the existing component documentation

If you require visual updates work please create an issue.

**Comment by wgx** [comment]
Added to [Discourse](https://discourse.ubuntu.com/t/mandatory-form-fields-specification/23360/1). (cc @AnnSoMuller @ziheliu214 @clagom @long-chung)

**Comment by clagom** [comment]
Did we work on this visual wise?

**Comment by wgx** [comment]
The visuals on discourse are from @long-chung 's updated versions. I believe they're the latest, but we can update if things change.

**Comment by clagom** [comment]
👍 cool, thanks
