### ISSUE TITLE
Expandable search pattern

### ISSUE THREAD

**Issue by ziheliu214** [canonical-web-and-design/vanilla-framework#3774]
https://vanillaframework.io/

landing page:
![Screenshot 2021-06-03 at 11 25 24](https://user-images.githubusercontent.com/61144986/120630105-65dec400-c45e-11eb-9afe-57d39086b211.png)

but when im on the 'docs' page, the 'showcase' tab on top nav is hidden.
![Screenshot 2021-06-03 at 11 24 52](https://user-images.githubusercontent.com/61144986/120630037-52cbf400-c45e-11eb-991a-f1a4912a524e.png)

**Comment by cristinadresch** [comment]
@ziheliu214 could you amend the description for this issue please

**Comment by clagom** [comment]
Vanilla has an issue: #2291 to implement this component in the documentation. Vanilla website is going to be redesigned.
