### ISSUE TITLE
Base button is white on grey background

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#3779]
**Describe the bug**

In 2.31.0 the background of base button was changed from transparent to white. It makes the button visible on lightgrey backgrounds (like MAAS) when it was not visible before.

<img width="1435" alt="Screenshot 2021-06-08 at 08 51 20" src="https://user-images.githubusercontent.com/83575/121137588-1837d200-c837-11eb-9a43-d76d0831df99.png">

**Expected behavior**

<img width="1446" alt="Screenshot 2021-06-08 at 08 55 01" src="https://user-images.githubusercontent.com/83575/121137714-3b628180-c837-11eb-8b99-bcee9e1b81a4.png">

**Context**

This blocks MAAS update to 2.31.0: https://github.com/canonical-web-and-design/maas-ui/pull/2736

**Comment by lyubomir-popov** [comment]
The base button used to be invisible on dark background, e.g. here:
![image](https://user-images.githubusercontent.com/2741678/121146908-4964d200-c838-11eb-86e4-34932b9db7f3.png)

Seems we need 2 things:
- transparent button that works on white and gray
- a button that works within dark elements, posibly not whie as that inverts the perception of primary-ness compared to the green

**Comment by bartaz** [comment]
@lyubomir-popov it may still be 1 thing, if the "transparent" base button works on dark backgrounds as well (with appropriate text and hover colors)
