### ISSUE TITLE
Nav exploration with new logos

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/vanilla-framework#3790]
Mockups ready for review on [figma](https://www.figma.com/proto/Apn4jJPYgjP7aGZNnfWqW7/logo-consistency-tag?node-id=57%3A226&scaling=min-zoom&page-id=0%3A266)

**Comment by lyubomir-popov** [comment]
https://www.figma.com/proto/Apn4jJPYgjP7aGZNnfWqW7/logo-consistency-tag?node-id=14%3A125&scaling=min-zoom&page-id=0%3A266

**Comment by waynecrosby** [comment]
@lyubomir-popov Feedback was good, we need to do some more explorations and also try solve a couple of issues that came up, I'll take you through them next week and we can create new issues.
