### ISSUE TITLE
Specification Documentation

### ISSUE THREAD

**Issue by AnnSoMuller** [canonical-web-and-design/vanilla-framework#3794]
- Complete the specifications/description of the different options in the [google doc](https://docs.google.com/document/d/1GSq8z6rkYZ_4rmJIAGZkRRiQpJwvqBrx2AMaUdb7w3k/edit#)
- Validate with the team
- Write the discourse document for the new pattern

**Comment by AnnSoMuller** [comment]
[Here](https://docs.google.com/document/d/1GSq8z6rkYZ_4rmJIAGZkRRiQpJwvqBrx2AMaUdb7w3k/edit) is the link to the google doc for key/value pair pattern.

**Comment by ziheliu214** [comment]
Will leave this to review until the decision is finalised and documentation is up-to-date.

**Comment by AnnSoMuller** [comment]
@ziheliu214 this is ready for review :)

**Comment by clagom** [comment]
Is this still blocked?

**Comment by lyubomir-popov** [comment]
@clagom don't think so, we had a productive catchup with @AnnSoMuller and I think we're good to proceed.

**Comment by ziheliu214** [comment]
Left some comments in the documentation @AnnSoMuller, good format thanks!

**Comment by AnnSoMuller** [comment]
posted on [Discourse](https://discourse.ubuntu.com/c/design/key-value-pair/91)!
So I close it :)
