### ISSUE TITLE
Address nav feedback for Brand presentation on Wednesday

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#3797]
[Current state](https://www.figma.com/file/Apn4jJPYgjP7aGZNnfWqW7/logo-consistency-tag?node-id=0%3A266):

![image.png](https://images.zenhubusercontent.com/59d2496bb0222d5de479ea17/659ea344-c840-4429-b9eb-ccaa89bb9adb)

Remaining concerns: 

- [ ] "Where do I click to go to canonical.com"?
- [ ] Is Signing / Search prominent enough wth just the icons?
- [ ] Responsiveness: What happens on smaller screens?

**Comment by lyubomir-popov** [comment]
@waynecrosby latest design attached above, with the remaining issues noted in the description. Please add any further feedback / concerns here so I can work through them on Wednesday.
cc @spencerbygraves @marcushas

**Comment by spencerbygraves** [comment]
@lyubomir-popov @waynecrosby has it been agreed to go with the stacked version? Also, it looks like the spacing within the logo is different. Perhaps we should have a catch up meeting tomorrow.
