### ISSUE TITLE
UX v2 wireframe - Design system site Components/patterns page

### ISSUE THREAD

**Issue by ziheliu214** [canonical-web-and-design/vanilla-framework#3803]
Working with Lyubo on the wireframe / Visual of the page on Figma

https://www.figma.com/file/7kb43f063vsMkfv3nGMC2r/Component-Pattern-page?node-id=0%3A1

Zeplin:
https://zpl.io/a3rJnAl

**Comment by cristinadresch** [comment]
@clagom @lyubomir-popov @bartaz could you have a look at this

**Comment by clagom** [comment]
Good job @ziheliu214, the structure seems to be working well with the presentation of this pattern. Later today in planning let's consider what we just discussed in the call, but going well so far 👍
