### ISSUE TITLE
Showcase page is very outdated - Remove page

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/vanilla-framework#3805]
Whilst prepping the masterclass, I noticed that the [showcase](https://vanillaframework.io/showcase) page is very outdated - a lot of the screenshots feature old designs or suru strips, conjure-up now redirects to juju.is, and one of them (Notes on development) doesn't use Vanilla anymore. 

If we're making Vanilla more of an internal tool, maybe the page is redundant?

![FireShot Capture 032 - Showcase - Vanilla documentation - 0 0 0 0](https://user-images.githubusercontent.com/2376968/123235777-17a86800-d4d4-11eb-81c7-71241aafd459.png)

**Comment by bartaz** [comment]
I agree, we haven't been really updating it (other than removing stuff that was not using Vanilla anymore from time to time), and apart from some exceptions it barely lists anything outside of Canonical sites.

**Comment by cristinadresch** [comment]
Agreed to remove page during standup
