### ISSUE TITLE
Update React component to match new notification pattern

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/vanilla-framework#3818]
The scope of this is to update the react `Notification` component to use the updated HTML structure and new style features.

It seems that current props of the React component shouldn't cause any bigger compatibility issues, but we may want to rename/alias some of them:

![Screenshot 2021-07-12 at 14.56.15.png](https://images.zenhubusercontent.com/593a660851aa2c30578102bb/3a5291a1-5a16-42db-835e-8198128edc7d)

I guess `children` can still be used in the same way to provide the body of the notification. `className` obviously stays the same. `close` can be a way to provide dismiss handler (I don't know if we need to rename it to `dismiss` or `onClose` - I'm not sure if we have any consistent practices for naming event handlers in components at this point). `status` is what we call title now, so it may stay as legacy way to set this, but would be good to have `title` prop as a new way of doing it. In Vanilla we don't have `timeout` functionality defined, so this can remain as is (I don't know where it is used currently). `type` can stay, although renaming it to `severity` would be good.

On top of that we need another prop to define `appearance` (default, borderless, raised, modal), and `inline`.

About renaming the props - I don't know what are the possibilities in React to deprecate some props and define new ones in place of them? Would be nice to keep backwards compatibility for some time, but provide new props as well.

**Comment by bartaz** [comment]
@Caleb-Ellis @huwshimi 

Your notifications work is now merged in Vanilla and released to npm as `2.33.0-rc1`, so you can use that in react components.
