### ISSUE TITLE
Add icon support to contextual menu items

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/vanilla-framework#3820]

**Comment by sowasred2012** [comment]
@waynecrosby could we please get a "snooze" icon? We have need for one as part of the new notification pattern:

https://app.zeplin.io/project/5fac06865cfff51271b72cc6/screen/60353ac1f130133007d40217

![Screenshot from 2021-06-28 15-43-48.png](https://images.zenhubusercontent.com/5cd93aaf2406d87914830598/38472bf0-6803-4722-bde8-00de41c1d1ab)

**Comment by waynecrosby** [comment]
@sowasred2012 Sure thing, I'll get it scheduled in for you.

**Comment by lyubomir-popov** [comment]
@waynecrosby we also need a bell icon (clicking it leads to a notification center).

**Comment by waynecrosby** [comment]
@lyubomir-popov We do already have a notification bell, can this be used?
![image](https://user-images.githubusercontent.com/42238722/123776020-cda1f680-d8c6-11eb-8788-1e164909dcac.png)

**Comment by lyubomir-popov** [comment]
@waynecrosby didn't know, thanks. We'll use it.
