### ISSUE TITLE
Build default notification pattern

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/vanilla-framework#3823]
It seems that the current HTML structure would not be enough to cover all the functionality and styling for new notifications:

```html
<div class="p-notification" id="notification">
  <p class="p-notification__response">
    <span class="p-notification__status">Warning:</span>We use cookies to improve your experience. By your continued use of this site you accept such use.
  </p>
  <button class="p-icon--close" aria-label="Close notification" aria-controls="notification">Close</button>
</div>
```

so we want to deprecate the HTML of current notifications and propose a new one.

We want to keep the `p-notification` root class name for consistency (and not to invent a new name), but child elements should have different strucuture and different class names.

Things we need to support:

  - title, that can be "inline" with body or stacked
  - notification icon - we probably don't want it directly in HTML but added with CSS based on `--caution` etc modifier
  - close button
  - additional elements below body: time, actions

The scope of this PR is just to provide a basic default variant, but when thinking about HTML we need to look ahead and know what we will need to add later.

<img width="691" alt="Screenshot 2021-07-01 at 13 16 00" src="https://user-images.githubusercontent.com/83575/124115800-835b7980-da6e-11eb-9038-004199a1b49d.png">

Possible HTML structure may look like this (this is just a proposal, details of HTML or class names to be worked out in development):

```html
<div class="p-notification">
   <div class="p-notification__title">Title</div>
   <div class="p-notification__content">Lorem ipsum...</div>
   <div class="p-notification__meta">
       <span class="p-notification__time">1h ago</span>
       <div class="p-notification__actions"><button>Action</button></div>
   </div>
   <button class="p-notification__close">Close</button>
</div>
```

**Comment by Caleb-Ellis** [comment]
Closed in #3847
