### ISSUE TITLE
Visual - form labels, mandatory field and error messages

### ISSUE THREAD

**Issue by cristinadresch** [canonical-web-and-design/vanilla-framework#3834]
Link to [Zeplin](https://zpl.io/anBA4Lr)

Link to [Figma](https://www.figma.com/file/3JbdJmkcWRyCrRQvOuTVoP/21.10-Vanilla-Mandatory-fields-and-Error-labels?node-id=201%3A65)

**Comment by long-chung** [comment]
@wgx @AnnSoMuller @lyubomir-popov @ziheliu214 Hi guys i've done some exploration and several options around this pattern. 
Would be grateful if you could take a look and help whittle them down.

Thanks

**Comment by lyubomir-popov** [comment]
Looking good @long-chung, I've left a couple of comments.
