### ISSUE TITLE
$color-accent couples nav and is-ticked patterns together

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/vanilla-framework#3836]
On [this Snapcraft PR](https://github.com/canonical-web-and-design/snapcraft.io/pull/3592#discussion_r661488178) there was a need for the nav `is-selected` highlight bar to be Ubuntu orange. 

The color of the bar is set by the `$color-accent` variable, which also determines the color of the tick icons in `is-ticked` lists: https://vanillaframework.io/docs/examples/patterns/lists/lists-ticked. It feels like it should be possible to set the color of one without affecting the other, since they're not obviously related otherwise.

**Comment by anthonydillon** [comment]
This is by design. We wanted a simple method to just accent across a project. It was deemed by Vanilla that color of the navigation highlight and the ticks should match.

**Comment by clagom** [comment]
WG validated the proposal to decouple the accent colour with "is-ticked".

**Comment by sowasred2012** [comment]
Making a note: it was suggested in [a related issue](https://github.com/canonical-web-and-design/vanilla-framework/issues/3405) that `$color-accent` be deprecated altogether (see @lyubomir-popov's [comment](https://github.com/canonical-web-and-design/vanilla-framework/issues/3405#issuecomment-888187444)).
