### ISSUE TITLE
Consider removing the fixed header convention that is becoming more common on our sites

### ISSUE THREAD

**Issue by steverydz** [canonical-web-and-design/vanilla-framework#3850]
In dev catchup on 6th July 2021 we discussed a problem where fixed headers cause problems with in-page links.

By default when you click an in-page link, e.g. https://example.com#page-section, that section will go straight to the top of the viewport. When there is a fixed header, the top of that section is hidden underneath the header.

There are things we can do to avoid this, such as using [scroll-padding](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-padding), but even then the behaviour is unreliable.

You can see an example using `scroll-padding` here: https://juju.is/cloud-native-kubernetes-usage-report-2021

If you click around enough you can probably break it.

Ultimately the problem would go away if we banned fixed headers.

Whilst this isn't a vanilla issue per se, could we consider making a rule/guideline against fixed headers? Or if there are valid reasons for keeping the fixed header, could they be made public?

**Comment by clagom** [comment]
FYI this might be more difficult to drop than anticipated because there are some parallel discussions with brand and Mark about navigation that changes on scroll. Maybe we don't need this in every page especially complex ones such as docs, but wouldn't be great to drop it completely. CC @anthonydillon

**Comment by lyubomir-popov** [comment]
I'd like to look into this. How can I replicate scroll-padding failing? Any special circumstances?

**Comment by steverydz** [comment]
@lyubomir-popov it happens often when loading the page with a section in the URL, e.g. 

https://juju.is/cloud-native-kubernetes-usage-report-2021#size-is-important-how-many-machines-and-clusters-are-people-running

but if you click around enough in the side nav you'll probably be able to break it

**Comment by anthonydillon** [comment]
It's not technically difficult until it hasn't been addressed which leads to common errors in our sites. It has consequences with other patterns such as sticky table headings. It is a trade-off better the UX of have navigation always available and regular issues on our sites.

**Comment by lyubomir-popov** [comment]
I was wondering whether it can be done sitewide, e.g. using the `:target` selector so it isn't a manual process.

**Comment by clagom** [comment]
@bartaz is going to talk about this issue during Dev catchup

**Comment by bartaz** [comment]
We discussed this on WG and it seems that there are sites that will continue to use sticky header nav, so we can't drop it completely.

If there are any implementation issues, we need to find a way to address them on implementation side.
