### ISSUE TITLE
Document changing icon colors

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/vanilla-framework#3858]
It turns out that the icons are mixins that can be called with a color to change the color of the icon. It would be great to document that you can do this in the [icons page](https://vanillaframework.io/docs/patterns/icons).

```scss
@import "vanilla-framework/scss/vanilla";
@import "vanilla-framework/scss/base_placeholders";
@import "vanilla-framework/scss/patterns_icons";
@include vf-p-icons;
@include vf-b-placeholders;

.p-icon--share {
  @include vf-icon-share($color-dark);
}
```

https://github.com/canonical-web-and-design/vanilla-framework/search?q=vf-icon-share

**Comment by bartaz** [comment]
We don't have much documentation on Vanilla internals currently, but we could start documenting things like that.
