### ISSUE TITLE
Pagination - visual updates

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#3870]
Visual design work related to #3208

- strip borders from pagination buttons
- review stylign in the wireframe and see if any changes are needed

**Comment by long-chung** [comment]
Had a chat with @davegoddard42 and he's happy with the design proposal. Putting this in for review anyway to give people an opportunity to feedback.

**Comment by lyubomir-popov** [comment]
Just one comment, we agreed to strip the pagination buttons' borders.

**Comment by lyubomir-popov** [comment]
@long-chung can you please link to the final version here for future reference?

**Comment by long-chung** [comment]
@lyubomir-popov can you link to the conversation or document what you had discussed?

- Does the active state have a border?
- Is there a border on hover or just an underline or colour change?
- Do we strip out borders from the chevrons?
- If there are no borders do we increase the count?

**Comment by long-chung** [comment]
@lyubomir-popov

**Comment by long-chung** [comment]
Link to [Zeplin project](https://zpl.io/VY0evEn)

Link to [Figma](https://www.figma.com/file/qdYdqPWOiaJRy9ynBioCdW/21.10-Vanilla-Segmented-Controller)

**Comment by ziheliu214** [comment]
Thanks @long-chung visual looks good! no UX issues from my eyes 👀

cc: @davegoddard42

**Comment by long-chung** [comment]
@davegoddard42 I've updated the documentation to reflect what we discussed for the mobile behaviour and also replaced the example images with updated visuals.

Closing off this issue as redesigning the pagination wasn't in scope when I initially picked up this issue. 

@lyubomir-popov if you still feel strongly about redesigning the pagination, please create a new issue for this and we can relook at this another time.
