### ISSUE TITLE
Search field icon padding update

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#3884]
Implement decision arrived at in https://github.com/canonical-web-and-design/vanilla-framework/issues/3626

**Comment by sowasred2012** [comment]
The decision arrived at (from [Eden's research doc](https://docs.google.com/document/d/1J7TXFeG1Yaszd17S509yzgqomV4n7seFS3avP9glcn8/edit#)):

> In a perfect world, a component would give users exactly what they need. We see a clear button might not be necessary for static search fields. That would not necessarily compromise the system's consistency: if something is not useful, it shouldn’t be there just for consistency reasons. However, even in those cases, a clear button could be useful for mobile users (selecting several words and removing them is not an amazing experience).
>
> Keeping it simple, unless we find strong arguments against it, **we can make the clear button a mandatory item in search/filter components**. It will save time for future designs, avoid new discussions (is it necessary in this particular case?) and keep it consistent across our products.
