### ISSUE TITLE
Add ability to reduce left padding to accordion panel

### ISSUE THREAD

**Issue by bethcollins92** [canonical-web-and-design/vanilla-framework#3885]
## Pattern to amend

Accordion

## Visual

Using accordion with no styles:
![Screenshot 2021-07-23 at 11 45 53](https://user-images.githubusercontent.com/58959073/126777913-01d66b61-2fc4-438b-a84b-77cf9c0a60bd.png)

with amendment 
![Screenshot 2021-07-23 at 11 45 45](https://user-images.githubusercontent.com/58959073/126777847-57b67492-a514-45cb-893a-dca51c8b0cd9.png)

## Context

I'm using the pattern for a list of filters, and I needed to reduce the left padding of the panels to 1rem to line align the panels with the tab titles. Could this be a modifier class to the accordion pattern?

**Comment by sowasred2012** [comment]
@lyubomir-popov what do you think? This padding override is being used on a number of (though not all) accordions on u.c, I wonder if we could introduce an `is-dense` modifier for that pattern.

**Comment by lyubomir-popov** [comment]
Can't we use `u-no-padding--left`? Do you need modifications on multiple elements?

**Comment by sowasred2012** [comment]
> Can't we use `u-no-padding--left`? Do you need modifications on multiple elements?

No, what @bethcollins92 has done in the example is reduce it to `1rem`, rather than eliminate the padding entirely - and it's just applied to the `.p-accordion__panel` element.
