### ISSUE TITLE
Figma library - contextual menu

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#3888]
This is ready for review @long-chung @elioqoshi 

![image](https://user-images.githubusercontent.com/2741678/127132770-c857adbf-3641-4026-a8d7-de38e553518d.png)

**Comment by long-chung** [comment]
Looks good and works like a charm

**Comment by lyubomir-popov** [comment]
I'm getting the hang of it :) Cool, I'll move it to the official library.

**Comment by elioqoshi** [comment]
@lyubomir-popov Looks good to me too!

Just a few things I am curios with: 

- How would we handle if someone needs that component with more items? Or would that not be the case? It's easy to remove items from an instance but it's not possible to add new items unless a new component/variant is created.

- How would one control where dividers would be positioned in the instance? Could that be a variant property of the item variants maybe?

**Comment by lyubomir-popov** [comment]
> * How would we handle if someone needs that component with more items? Or would that not be the case? It's easy to remove items from an instance but it's not possible to add new items unless a new component/variant is created.

we can always increase the number in the library file if someone needs more - or the person can detach etc. 

> * How would one control where dividers would be positioned in the instance? Could that be a variant property of the item variants maybe?
try it - the border is already a property

**Comment by elioqoshi** [comment]
> or the person can detach etc.

We should avoid that, but yeah we could offer variants with more items.

> try it - the border is already a property, you toggle it on/off

Perfect, I missed that somehow. Thanks!

**Comment by lyubomir-popov** [comment]
This is done and published, closing.
