### ISSUE TITLE
Design system library: add tick elements

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#3890]
I've ported the tick element component to the figma library, ready for QA:
https://www.figma.com/file/H6MSsN3taoXXOJCPUbIImQ/Design-system-library?node-id=0%3A1
![image](https://user-images.githubusercontent.com/2741678/127170936-5ce9451d-a80b-49a7-81d9-16af5836fe65.png)

**Comment by long-chung** [comment]
Maybe we could set the state as a true/false so it can also be a toggle switch rather than a dropdown?

**Comment by lyubomir-popov** [comment]
good point!

**Comment by lyubomir-popov** [comment]
FIxed the text colour and I see you turned them to switches. Can we close this?
