### ISSUE TITLE
Figma design library: Input and search component

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#3892]
https://www.figma.com/file/H6MSsN3taoXXOJCPUbIImQ/Design-system-library?node-id=31%3A4153

**Comment by lyubomir-popov** [comment]
@long-chung can you please review (and use thew qa labels not the design labels as the design hasn't changed)

**Comment by long-chung** [comment]
Thanks Lyubo. Left some feedback.
