### ISSUE TITLE
Drop support for node-sass

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#3900]
This involves:
- make building with dart sass default
- find a way to pass version to SASS from dart sass (or ignore this feature) - it is related to functions.js
- update the documentation (remove node sass from the docs)
- update the code to fix warnings (division in dart sass)

**Comment by sowasred2012** [comment]
This seems like a duplicate of https://github.com/canonical-web-and-design/vanilla-framework/issues/3848
