### ISSUE TITLE
Side navigation with icons / chevrons - visual design

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#3908]
Create visual design mockups to resolve the remaining alignment / indentation issues arund the newly proposed icons+chevrons side navigation.

Related UX issue: https://github.com/canonical-web-and-design/vanilla-framework/issues/3817

**Comment by danielmutis** [comment]
@lyubomir-popov by the way, we also need to consider what happens visually when this nav is collapsed (see image). At the moment we have the chevrons ahead of the icons, so maybe something needs to be done to make that transition obvious. When you are in a child page of an expand-collapse parent, we need to probably show the parent on the nav as selected when the nav is collapsed. 

![Screenshot 2021-08-05 at 16.05.38.png](https://images.zenhubusercontent.com/5e1c5367f4dbe2bfe4c77ad8/6bedf486-c1c1-458f-80d4-05d6f7791e85)

**Comment by lyubomir-popov** [comment]
Yes, I agree - I'll include that in the visual examples.

**Comment by lyubomir-popov** [comment]
Link to visual: 
https://zpl.io/2v8K3B7
