### ISSUE TITLE
Filter vs Search & filter

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#3911]
Simple filter cases like the charmhub filter are being used as a basis for much more complex filtering. This means wrapping collecitons of check boxes inside accordions, adding counters to collapsed accordion items to reveal how many checkboxes inside are ticked, etc. This wades into the territory of the Search and FIlter pattern IMO, and raises a few questions:

When should you:

- put the filters behind a click in the search field (as the current search and filter does, in a panel that pops up)
- put them directly on the page (this one is easy, when there's not sa lot of them and they aren't caegorized?)
- put them in an accordion (which potentially also hides them depending on choice of default)

Ubuntu case in point:
For context - see end of this pr discussion
https://github.com/canonical-web-and-design/ubuntu.com/pull/10125

https://app.zeplin.io/project/60c1ca887b99f18a380e57e9/screen/60f18615cd1dde1328810d46

charmhub example 
https://charmhub.io/?base=all&filter=big-data,ai-ml,networking,security

**Comment by ziheliu214** [comment]
I distinguished usages of these 2 variants of search and filter in this [documentation](https://docs.google.com/document/d/1zmqt3aAyiEs0j8LxWzLnQoAY67mzYcwE1YfBJKss3EM/edit#)

Please review @clagom @lyubomir-popov

**Comment by clagom** [comment]
Thanks @ziheliu214 had a few comments

**Comment by ziheliu214** [comment]
Updated usage section for split search and filter.

- Added general usage guideline
- Amended when to use
- Added a section 'when to use a batch filter'
