### ISSUE TITLE
Help text looks misaligned on checkbox/radio inputs

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/vanilla-framework#3972]
On Snapcraft we want to add checkboxes with descriptive help text, like so:
![Screenshot from 2021-09-06 14-44-07.png](https://images.zenhubusercontent.com/5cd93aaf2406d87914830598/07267655-4bef-4914-be29-4c9603f45a32)

At the moment, adding help text below a `p-radio/p-checkbox` looks like:

![Screenshot from 2021-09-06 14-45-21.png](https://images.zenhubusercontent.com/5cd93aaf2406d87914830598/3a29f54c-1b7e-4d63-ae3c-f73eef01e677)

It would be good if that text could align with the input label.

**Comment by bartaz** [comment]
One week in snapcraft and you already don't know what's happening in Vanilla ;)

Duplicate of #3402

**Comment by sowasred2012** [comment]
@bartaz haha - I miss you guys!
