### ISSUE TITLE
Figma library: Add side navigation component

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#3977]

**Comment by lyubomir-popov** [comment]
@long-chung @elioqoshi the side navigation is ready for review:

https://www.figma.com/file/H6MSsN3taoXXOJCPUbIImQ/Design-System-Library?node-id=187%3A2591

**Comment by long-chung** [comment]
@lyubomir-popov Wow really nice work! this was a super complex one. (I feel you).

Couple of minor things
Setting layers "BG" and the main component to "Hugs content" in the resizing parameters would help the component resize when changing its label.
The components don't accommodate multiline. It losses its top and bottom padding as well as the icons being centred to the text.
