### ISSUE TITLE
Add Segmented controller components to Figma library

### ISSUE THREAD

**Issue by elioqoshi** [canonical-web-and-design/vanilla-framework#3978]
I reconstructed the segmented controller components in a (hopefully) more lightweight way based on the WIP @long-chung did.

You can find it in the Design System Library file under Components in review:
https://www.figma.com/file/H6MSsN3taoXXOJCPUbIImQ/Design-System-Library?node-id=203%3A1887

Link to UX specification:
https://docs.google.com/document/d/1__Ee_7s1jLJdNBEyrA-fUKNHx5Jbxz158IZuWtb6zEA/edit#heading=h.tjkrn1nfg877

![image.png](https://images.zenhubusercontent.com/5a5649f54b5806bc2bc23b6d/d2e48b5d-248a-4108-88f4-425b4721a4be)

## Anatomy

I got rid of the first,middle and last properties for the items, so we can have fewer variants within the component. There is also an additional divider component existing on its own which can be used between 2 items. The outer border of the segmented controlls is specified by another component nesting the controller items instead. In this way we should require only 12 component variants for the items (3 states x 2 icon types x 2 dense or default height types) as well as 2 component variants for the whole controls (default+dense).

## Notes
There are a few things to keep in mind with this setup
- I added a version with 7 items for the segmented controls components. That means that someone who needs a control with 3 items, needs to delete items and dividers in their instances until they have as much as they need. If someone needs controls with more than 7 items, we would have to add that to the library. I think this approach is less ergonomical but allows the library to be more lightweight. The alternative is to have a variant for each number of items a segmented control should have (so 2,3,4,5,6,7 and so on) which makes it easier to use out of the box but adds to the number of components in the library. 
- I am unsure on what the height of these should be. I sticked to 32px for the default height and 24px for the dense type. The WIP specs were respectively 36 and 30px high.
- I don't think we actually need a segmented control dense version type. One could choose dense instances right inside the instance instead of changing the variant of the whole segmented control instance. But I do think it's a bit more usable this way.
- Please stress test it out in different scenarios and see whether the auto layout behaviour is correct.

**Comment by lyubomir-popov** [comment]
Is this something we can consult the forums for? It feels like we're creating a very bespoke workflow, and it might be the best so nothing wrong with that. But surely people have come across these issues before and there's a best practice. I'd rather get confirmation this is the one before we start doing this everywhere, as it does add an additional step to set the properties of the inner component.

**Comment by elioqoshi** [comment]
I mean it's not set in stone, rather than a design philosophy decision. These vary vastly across design systems. GitLab is still not using instances for example:
https://www.figma.com/file/E6vGCBRPAN7ZctiuBB4VLP/GitLab-Component-Library-Community?node-id=425%3A138

That's also exactly how TailwindUI does it with their own Figma library:
![image.png](https://images.zenhubusercontent.com/5a5649f54b5806bc2bc23b6d/5fe1486c-fd4c-412f-910a-dd1995e8f12b)

I do think Tailwind's Figma library is one of the best constructed libraries out there and think it's worth to adapt that approach. Most other libraries use older Figma features which do not include variant capabilities.

I copied the tab group example for you here @lyubomir-popov :
https://www.figma.com/file/H6MSsN3taoXXOJCPUbIImQ/Design-System-Library?node-id=212%3A2798

**Comment by lyubomir-popov** [comment]
@elioqoshi Let's catchup tomorrow to look at these together.

**Comment by long-chung** [comment]
@elioqoshi Thanks for transferring this over to the main fig file.
There are a few things that need updating before this is ready to go live.

- Tab buttons should be 36px tall as per the spec to align with button heights.
- In the spec under "Questions to ask yourself" it is recommended that we should use no more than 5 segments
- I'm not sure grouping the dense and normal size together as you have done works to well, as it requires you to select each segment and select its type individually, whereas keeping them separate would allow you to apply the sizing to the whole component.

**Comment by cristinadresch** [comment]
@elioqoshi can you have a look please ^

**Comment by elioqoshi** [comment]
@long-chung Thanks!

- I updated the height to 36px
- Good point. I changed the default component of segmented controls to 5. If someone needs less, they need to remove item and dividers in their instance.

> I'm not sure grouping the dense and normal size together as you have done works to well, as it requires you to select each segment and select its type individually, whereas keeping them separate would allow you to apply the sizing to the whole component.
I am not sure what the problem is. The tab item instance is not supposed to be consumed in designs, the item group is meant to be consumed and comes with 2 variants. The final segmented control can be switched from default to dense right away without going into every item. Could you elaborate your concerns further?

**Comment by elioqoshi** [comment]
Going into the specs again, it says:

> Are there too many segments in this button? (try to keep it under 5, optimally 2 or 3)

Maybe the max amount of items should be 4 then. @danielmutis do you agree?

Also, I didn't plan for icon support yet, so I will do that before we go ahead with this.

**Comment by long-chung** [comment]
@elioqoshi Ah sorry my bad. I didn't notice that you could select default/dense from the component level.
Its when I selected a segment(link) it gave a dropdown for default/dense and only changed that particular segment.

**Comment by elioqoshi** [comment]
@long-chung All good! What you said made me think though: Do we even need a dense and default item component? We could have a generic item component and a group component where dense and default is controlled from. There might be no need for 2 flavours within the item component.

**Comment by elioqoshi** [comment]
@long-chung I removed the dense item variants now. Density is now controlled within the group component. Also added icon variants to the group for better ergonomics so you don't need to go within the items of an instance to toggle icons on one by one.

I saved the previous version to the Figma version history, just in case, but I think this is better designed now. If you could have another look before closing.

**Comment by danielmutis** [comment]
@elioqoshi the spec is giving only a recommendation, these decisions should stay up to the UX designer who is working on the project. I think maybe we can reduce the maximum to 5, because really a 7 item one would be overkill, but I don't agree with making decisions for the designer through the specs.

**Comment by elioqoshi** [comment]
@danielmutis Well, we need to make decisions for the designer in the design system unfortunately. We can keep it at 5 then.

**Comment by long-chung** [comment]
@elioqoshi LGTM. Thanks for sorting.

I removed "type=default" fro each of the components in the "Segmented Control Elements" Variant as it left a dropdown with only 1 value (default).

**Comment by elioqoshi** [comment]
> I removed "type=default" fro each of the components in the "Segmented Control Elements" Variant as it left a dropdown with only 1 value (default).

Thanks, yeah I missed that!
