### ISSUE TITLE
New badge component

### ISSUE THREAD

**Issue by cristinadresch** [canonical-web-and-design/vanilla-framework#3980]

**Comment by lyubomir-popov** [comment]
@rayito do you think we need more variations than these? 
[Uploading... image.png]

**Comment by lyubomir-popov** [comment]
@rayito could you please take a look and let me know whether the above seems ok to you / covers all scenarios we discussed ^

**Comment by rayito** [comment]
Sorry, I didn't get (or see) any notification from the mentions. 

The question that comes to me is if we ever want to allow a large and important number to be in a badge. If it's something like notifications, more than 999 is already so wild that nobody cares about the real number; but what about important stuff? 

Let's say machines / processes / models / whatever. Having 1.000 or 50.000 might be quite different and in a badge, they would look like 999+. So I wonder if we should aim for a "smarter" badge with things like "1k" and "50k" or if that is overkilling and that kind of information should never be inside a badge.

This is a bit me talking to myself out loud, I'll give it a quick thought.

**Comment by lyubomir-popov** [comment]
50k still fits within th4 4 allotted characters :) Good suggestion though, we should have it in the documentation. I'll put this in the workign group so someone can be assigned to write the documentation. CC @clagom

**Comment by lyubomir-popov** [comment]
Adding the WG:validated label as this is now ready for final spec / documentation, the visuals are done.

**Comment by lyubomir-popov** [comment]
Closing, the design is on zeplin at the link above. I've illustrated @rayito's suggestions in the mockups.
