### ISSUE TITLE
Checkbox is positioned incorrectly after upgrading to 2.36

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/vanilla-framework#3981]
**Describe the bug**

The checkbox is positioned incorrectly after upgrading to 2.36

**Expected behavior**

The checkboxes should be visible.

**Screenshots**

After upgrading to Vanilla 2.36:
<img width="232" alt="Screen Shot 2021-09-13 at 10 40 13 AM" src="https://user-images.githubusercontent.com/532033/133124052-88e56b4a-847e-43bf-ad3a-414466192e4b.png">

Unchecking this position relative mostly moves it back:
<img width="498" alt="Screen Shot 2021-09-13 at 10 44 56 AM" src="https://user-images.githubusercontent.com/532033/133124055-de9e93dd-ba8e-470e-b970-136435af22fa.png">

<img width="199" alt="Screen Shot 2021-09-13 at 10 46 59 AM" src="https://user-images.githubusercontent.com/532033/133124302-a21f3ce9-e301-4c6f-81a0-d66569f1fdbc.png">

With Vanilla 2.35:
<img width="222" alt="Screen Shot 2021-09-13 at 10 48 06 AM" src="https://user-images.githubusercontent.com/532033/133124441-0fec9f96-28de-401a-bfca-d80fa84b2209.png">

Markup:
<img width="1013" alt="Screen Shot 2021-09-13 at 10 49 12 AM" src="https://user-images.githubusercontent.com/532033/133124585-bbcb0853-eb6d-4e2b-8968-930249bce1ae.png">

**Desktop (please complete the following information):**

- OS: MacOs
- Browser Firefox 
- Version 92

**Comment by bartaz** [comment]
@hatched Not sure exactly what's the difference, but in Vanilla itself we have checkboxes in the tables and they work as expected:

https://vanillaframework.io/docs/examples/patterns/forms/tick-comparison

Could you try updating it to `p-checkbox--inline` (which is supposed to be used in contexts like this)? Hopefully that will help with alignment. Or maybe there are some other local styles that affect checkboxes?

**Comment by hatched** [comment]
Thanks @bartaz that was the trick, it needed the `--inline` added. Looks like I missed that when implementing this.
