### ISSUE TITLE
Notification center

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/vanilla-framework#3997]
Snapcraft is now using notifications in a notification center, as part of the work @steverydz is doing with React on the admin view, so we should talk about whether we want to add it to Vanilla.

**Comment by cristinadresch** [comment]
Check in WG if this notification designs were based on Will's notification designs, and decide if we should implement this in Vanilla.

**Comment by clagom** [comment]
@sowasred2012 we don't recall having notification center in the admin view pages, just notification toasts. @wgx wrote the specs for a notification center but it's not implemented in Vanilla yet.

**Comment by clagom** [comment]
@AnnSoMuller @steverydz could you clarify what "notification centre" we are talking about? WG recalls having just notification toasts in the admin view pages, not a notification centre.

**Comment by clagom** [comment]
Closing this as we didn't get more information, please open a new issue if still relevant.
