### ISSUE TITLE
Focus on modal close button seems broken in Firefox

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#4007]
Focus outline around close button in modal is also around the title:

![Screenshot 2021-09-30 at 16.50.46.png](https://images.zenhubusercontent.com/593a660851aa2c30578102bb/d9864860-8022-48ad-8a1e-93627fcf6aa2)

It seems fine in Chrome.

**Comment by bethcollins92** [comment]
<img width="827" alt="Screenshot 2022-01-27 at 14 15 22" src="https://user-images.githubusercontent.com/58959073/151376314-bc45cf08-5a0a-4b00-a9be-1b961c27e2a6.png">
@ilayda21 and I have both checked this, it seems to be fine now. Must have been a bug in Firefox
