### ISSUE TITLE
Add tabstrip figma component

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#4012]
https://www.figma.com/file/H6MSsN3taoXXOJCPUbIImQ/Design-System-Library?node-id=415%3A5232

@long pleaser review when you get a chance.

**Comment by long-chung** [comment]
@lyubomir-popov found a couple of things in the component that needs fixing.

- Second item in the tab strip component has an underline whereas the others don't.
- Only item 1 and 2 are components, the others are just smart layout layers

**Comment by lyubomir-popov** [comment]
@long-chung thanks, fixed - ready for another look

**Comment by long-chung** [comment]
@lyubomir-popov Hey sorry, one last thing. I'd take the grey bar out of the tabs themselves and have it as its own element that spans the full width, as you may only need say 3 tabs but the grey bar won't fill the page width.

**Comment by long-chung** [comment]
@lyubomir-popov sure that makes sense

**Comment by long-chung** [comment]
@steverydz could you increase the margins between the top and bottom of the diagram, then its good to go. Thanks
