### ISSUE TITLE
Chip - enhance to support coloured chips - build

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#4013]
## Pattern to amend

Chip

## Context
As part of https://github.com/canonical-web-and-design/vanilla-framework/issues/3126 we agreed to deprecate labels and expand chips to cover the functionality currently supported by lables. We agreed to do this as there's no clear distinction between labels and chips, so rather than having two components that overlap, we can have one component. Just opening an issue so we can track this piece of work.

**Comment by bartaz** [comment]
UX/Visual issue: https://app.zenhub.com/workspaces/-vanilla-squad-59438c953747487777fbe484/issues/canonical-web-and-design/vanilla-framework/4090

**Comment by lyubomir-popov** [comment]
Proposed shades for the different states. These are fiddly to recreate with formulas as they have different initial darkness (the warning colour has to be 2% darker than the rest to appear visually similar), so probably easier to just hardcode them than trying to account for those differences with code calculations. What do you think @bartaz ?

![image](https://user-images.githubusercontent.com/2741678/141828200-cc3322ce-2f14-46ec-8b20-652fb14bca5c.png)

@spencerbygraves can you take a look and let me know if those look agreeable to you? Once they are in the system, we'll reuse them for things like notification background, etc. The shades are derived to match the blue selected colour states I did when I was researching and benchmarking the new blue colour and state increments in other systems.

**Comment by bartaz** [comment]
@lyubomir-popov As for now they only need to work on this limited set of colors, so I don't mind hardcoding the values if needed. 

For the chips states themselves - what do these 3 lines show? normal, hover, active (from top to bottom?). The changes are very subtle, I don't think I see the difference between line 1 and 2 at all, and 3 only seems slightly darker. But maybe when it's interactive and changes with mouse movement it will be more noticable...

One other question - are chips focusable? Do we need focused state for them?

**Comment by lyubomir-popov** [comment]
@bartaz let's see how it is when you niteract and  I can adjust. We're daerkening by 2 % no hover, and another 4% on top of that on active, I think it will look subtle but noticeable. This is based on benchmarking I did when I did the new blue exploration. 

I think they should be focusable - currently only the dismiss inside is. @sowasred2012 any accessibility considerations arund that?

**Comment by spencerbygraves** [comment]
@lyubomir-popov the difference is quite subtle, but happy to look when built as mentioned above.
