### ISSUE TITLE
Chip - enhance to support coloured chips - spec 

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#4019]
Vanilla 3.0 introduced coloured chips and we need to add that to the spec. Spec should also include a message about chips being clickable and labels not.

**Comment by elioqoshi** [comment]
@rayito to work with @lyubomir-popov for the specs. Let us know if you need anything WG-wise!

**Comment by rayito** [comment]
[First version of the spec](https://docs.google.com/document/d/1gAq0oliQ5XEPuwJs8IUrdZNBKFuEWjSyLDuGeC4oSNw/edit?usp=sharing)

Please have a look, there are things I am not completely sure about (like the possibility of using new colours and not only the predefined ones).

**Comment by cristinadresch** [comment]
@rayito just checking you managed to review lyubo's comments in the doc?

**Comment by rayito** [comment]
Yes, I did, changed some lines and will check with him about the last one.

**Comment by lyubomir-popov** [comment]
@eden finally had a look at this, much better thanks. I've +1'd it and I resolved the comment.
