### ISSUE TITLE
update slider specs in line with new toggle switch specs

### ISSUE THREAD

**Issue by elioqoshi** [canonical-web-and-design/vanilla-framework#4020]
![image.png](https://images.zenhubusercontent.com/5a5649f54b5806bc2bc23b6d/5d069508-f605-435d-be61-706ce86dc65e)

The slider component is using the same visual style as the current toggle switch. Once we update the toggle switch component, we should also update the slider accordingly (#4001)

**Comment by wgx** [comment]
Sliders in Ubuntu desktop (light mode) look like this:

![image.png](https://images.zenhubusercontent.com/5ecce60f6f3d7a74562f9dfe/42aa89ce-889d-48f1-ad17-36521625332b)

**Comment by clagom** [comment]
Build issue here: https://app.zenhub.com/workspace/o/canonical-web-and-design/vanilla-framework/issues/4080
