### ISSUE TITLE
Radio panel pattern UX

### ISSUE THREAD

**Issue by steverydz** [canonical-web-and-design/vanilla-framework#4029]
## Visual

<img width="1439" alt="Screenshot 2021-10-12 at 10 58 40" src="https://user-images.githubusercontent.com/501889/136935319-c1e279bd-b29f-4858-a8db-2a5930be33cb.png">

<img width="1429" alt="Screenshot 2021-10-12 at 10 58 47" src="https://user-images.githubusercontent.com/501889/136935332-dee698d1-8eb7-4e31-83f9-35920fdc4084.png">

<img width="1393" alt="Screenshot 2021-10-12 at 10 58 54" src="https://user-images.githubusercontent.com/501889/136935360-d1761754-ab7e-460f-9306-33dca9130700.png">

## Context

The is a panel button pattern that is current used in https://ubuntu.com/advantage/subscribe and https://juju.is/brew, and soon on the new blender support section. Behind the scenes this pattern uses radio inputs. As it's a pattern we clearly want to repeat it would be good to make it a standard Vanilla pattern.

There are a few variants, e.g. logos, just text and now media object style. Maybe the content area itself should be completely up to the implementation but the button itself should be a pattern IMO.

## State

It should have a selected state.

## Progressive enhancement

The width of the button is defined by it's container so on small screens it will likely span the whole screen.

**Comment by anthonydillon** [comment]
Another state would be disabled.

**Comment by marinacastejon** [comment]
Sorry for the late comment. 
As we expected, the radio panel benchmark I did showed that indeed radio panels should be read by screen readers exactly like radio buttons. 
@bartaz

**Comment by wgx** [comment]
Working on the spec in this Doc: https://docs.google.com/document/d/1lNspyxiffzV1lO_cbsoXYtbaevulijxVXRiGVoXVCEI/edit#heading=h.2tbz0zuxor01

**Comment by wgx** [comment]
Ok, finished my draft. Needs a review by another Vanillian. 🍦

**Comment by davegoddard42** [comment]
LGTM @wgx.

The only possible issue with these is making sure the user knows they are clickable options and not just images etc. Have you explored including a radio button within the card? Roughly, maybe something like below?

![image](https://user-images.githubusercontent.com/25453620/151001689-bfe55ac4-0e89-403a-8144-3ae8019cc470.png)

Maybe these patterns are standard enough now it's not an issue.

As by default, nothing is selected (in contrast to standard radio buttons), is it worth expliclity stating that it's not possible to go back to that nothing selected state? I.e. if I choose option 1, I can't unselect option 1 and have nothing selected - only choose a different option.

**Comment by elioqoshi** [comment]
Looking good @wgx!

Just +1 on what Dave said. This overflows into visual design quite a bit but some benchmarking might be useful here what others are doing with radio panels. Something which is quite clear might be an example like this: https://stackoverflow.com/questions/54723738/how-to-custom-style-images-and-radio-buttons

![grafik](https://user-images.githubusercontent.com/5436686/151041140-d8dcfb75-2895-46b3-9d7a-7dd0bd709099.png)

Not sure if it needs to be a checkbox or not. That would be another can of worms we don't want to open (is it confusing compared to checkboxes?).

There is definitely a lot of visual design considerations required I think (such as what are the margins of the icon and where is the radio indicator placed?)

**Comment by marinacastejon** [comment]
Good points. From an accessibility perspective (screen readers apart) the general rule is that colour should not be used alone to convey meaning. In the case of showing the difference between selected and non-selected states, I agree it would make sense to use something other than colour to show what has been selected.

**Comment by lyubomir-popov** [comment]
> Have you explored including a radio button within the card? Roughly, maybe something like below?
IMO this should be made clear by the context. Adding a radio in it feels insecure... like a "click here" label. Here's how apple do it:
![image](https://user-images.githubusercontent.com/2741678/151148640-d31cb81e-9eec-4ffd-95ba-4fd1c6edb504.png)

**Comment by wgx** [comment]
1. Updated google Doc with 'no selection' state fix from @davegoddard42 
2. Agree with @lyubomir-popov that the radio visual isn't needed - I feel there's enough visual affordance there already
3. Agree with @marinacastejon about some non-colour affordance on the selected state

The only remaining questions are visual, so happy to leave it to visual design to take it forward. 👍🏽

**Comment by wgx** [comment]
@elioqoshi I'm not dead against the radio icon being present, just not sure it's needed - from the user point of view they're "buttons that behave like radios".

**Comment by lyubomir-popov** [comment]
> from the user point of view they're "buttons that behave like radios".

not entirely like radios - as you'd need a confirm button if using radios... to me, they seem like multiple choice toggles...

**Comment by cristinadresch** [comment]
Visual issue here https://app.zenhub.com/workspaces/-design-system-tribe-59438c953747487777fbe484/issues/canonical-web-and-design/vanilla-squad/1192
