### ISSUE TITLE
Switch and slider - visual update

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#4036]
Link to WIP: https://zpl.io/VDQvOlO 

cc @elioqoshi 

![image](https://user-images.githubusercontent.com/2741678/137157591-a01540b7-105d-4063-a54e-95fefc02ddfd.png)

**Comment by spencerbygraves** [comment]
@lyubomir-popov the design on Zeplin looks good, thanks 👍
