### ISSUE TITLE
[Accessibility Docs] Buttons

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/vanilla-framework#4039]
Using [this template](https://docs.google.com/document/d/1IwFMfJrTfJPXDcVJfLWXYkw-pjgWhBWo4GX8X098Q64/edit#), create accessibility docs for [Buttons](https://vanillframework.io/docs/patterns/buttons)

**Comment by bethcollins92** [comment]
First draft of [accessibility doc](https://docs.google.com/document/d/11H6xPtBRxB1a8KCmK7XFH1FeZDduQhSJXxq-wNJ_CZ8/edit#) for buttons

Feedback VERY welcome (especially UX/UI considerations I may have missed @elioqoshi)
also @bartaz

**Comment by davegoddard42** [comment]
@bethcollins92 nice work. LGTM.

**Comment by bethcollins92** [comment]
Notes are up here: https://vanillaframework.io/docs/patterns/buttons#accessibility
