### ISSUE TITLE
[Accessibility Docs] Cards

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/vanilla-framework#4040]
Using [this template](https://docs.google.com/document/d/1IwFMfJrTfJPXDcVJfLWXYkw-pjgWhBWo4GX8X098Q64/edit#), create accessibility docs for [Cards](https://vanillframework.io/docs/patterns/card)

**Comment by bethcollins92** [comment]
First draft [accessibility doc](https://docs.google.com/document/d/1f_dJS0MquxNm9D6e1OaHohyqXBNG1GwnPfFdxFci60k/edit#) for cards.

@bartaz @sowasred2012 @elioqoshi

**Comment by davegoddard42** [comment]
@bethcollins92 nice work - I added one suggestion about headings. LGTM

**Comment by bethcollins92** [comment]
Notes are up here: https://vanillaframework.io/docs/patterns/card#accessibility
