### ISSUE TITLE
[Accessibility Docs] Grid

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/vanilla-framework#4043]
Using [this template](https://docs.google.com/document/d/1IwFMfJrTfJPXDcVJfLWXYkw-pjgWhBWo4GX8X098Q64/edit#), create accessibility docs for [Grid](https://vanillframework.io/docs/patterns/grid)

**Comment by bethcollins92** [comment]
[Accessibility doc](https://docs.google.com/document/d/1cPgsBMHdS0_3fhaLReiN830Ni8uJSNIM-frqvpZTB8E/edit#) for Grid

**Comment by AnnSoMuller** [comment]
Good for me!

**Comment by steverydz** [comment]
LGTM 👍
