### ISSUE TITLE
[Accessibility Docs] Heading icon

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/vanilla-framework#4044]
Using [this template](https://docs.google.com/document/d/1IwFMfJrTfJPXDcVJfLWXYkw-pjgWhBWo4GX8X098Q64/edit#), create accessibility docs for [Heading icon](https://vanillaframework.io/docs/patterns/heading-icon)

**Comment by bethcollins92** [comment]
Accessibility doc for [heading icon](https://docs.google.com/document/d/1-pph5kexTYURof_M1WgYbouPUxElhPbubgQq5hbuiXs/edit#heading=h.53fyn87a5ihd)

**Comment by mrgnr** [comment]
@bethcollins92 Reviewed -- I added some punctuation but otherwise looks great!

**Comment by wgx** [comment]
@bethcollins92 added 1 new bullet, looks good to me 👍🏽
