### ISSUE TITLE
[Accessibility Docs] Labels

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/vanilla-framework#4048]
Using [this template](https://docs.google.com/document/d/1IwFMfJrTfJPXDcVJfLWXYkw-pjgWhBWo4GX8X098Q64/edit#), create accessibility docs for [Labels](https://vanillaframework.io/docs/patterns/labels)

**Comment by bethcollins92** [comment]
[Accessibility doc](https://docs.google.com/document/d/1xRFBOGBN0m8kW94TSrcfSTWJ1ftjHm-_CXEe9IgbRuw/edit#) for Labels. Not much here so open to any suggestions of what I could include

**Comment by wgx** [comment]
@bethcollins92 reviewed - not much to add but made a few tweaks. 👍🏽

**Comment by mrgnr** [comment]
@bethcollins92 Looks great! I made a few small suggestions (added a comma and split a sentence), but do what you think sounds best :+1:

**Comment by bethcollins92** [comment]
Notes are up here: https://vanillaframework.io/docs/patterns/labels#accessibility
