### ISSUE TITLE
[Accessibility Docs] Links

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/vanilla-framework#4049]
Using [this template](https://docs.google.com/document/d/1IwFMfJrTfJPXDcVJfLWXYkw-pjgWhBWo4GX8X098Q64/edit#), create accessibility docs for [Links](https://vanillframework.io/docs/patterns/links)

**Comment by bethcollins92** [comment]
First draft of [accessibility doc](https://docs.google.com/document/d/1DcYBpmuLKZGLIWR6jgjYfZc1X64d8HtDt9uKMoB0POE/edit#) for links.

Looking for any feedback - especially on the how it works? Can't think what else to write here 😬

@elioqoshi @bartaz

**Comment by elioqoshi** [comment]
@bethcollins92 I added some copy-related principles which are somewhere inbetween UX and Code. Though it also depends where we will store a11y docs (on their own or part of UX/Code?)

**Comment by sowasred2012** [comment]
@elioqoshi for the new design system site, the docs are intended to live under their own tab alongside (if I'm recalling correctly) design and implementation.

**Comment by elioqoshi** [comment]
That was the original assumption but we discussed it and are not sure if it's still the ideal approach, as information would be spread around further (there are a11y considerations fitting in code or ux )

**Comment by bethcollins92** [comment]
Notes are up here: https://vanillaframework.io/docs/patterns/links#accessibility
