### ISSUE TITLE
[Accessibility Docs] Lists

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/vanilla-framework#4051]
Using [this template](https://docs.google.com/document/d/1IwFMfJrTfJPXDcVJfLWXYkw-pjgWhBWo4GX8X098Q64/edit#), create accessibility docs for [Lists](https://vanillframework.io/docs/patterns/lists)

**Comment by bethcollins92** [comment]
First draft of [accessibility doc](https://docs.google.com/document/d/1pK4kmbo83pyfQ92DuRLCqVAJaY9HdRTWbaAI3yCg59I/edit#) for lists. 

Feedback VERY welcome (especially UX/UI considerations I may have missed @elioqoshi)
also @bartaz

**Comment by elioqoshi** [comment]
@bethcollins92 I don't have much to add here, but maybe mentioning ARIA `list` and `listitem` would be appropriate? 
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/list_role

Not my forte though!

**Comment by sowasred2012** [comment]
@bethcollins92 @elioqoshi I'd be wary of using/mentioning ARIA roles here - using `ul`/`ol`/`dl`, we get the benefits those roles brings automatically, so it might encourage people to apply them to other HTML elements (and possibly conflict with other Vanilla components).

That said! I looked at the lists docs, and there is a component in there whose example _isn't_ a list: https://vanillaframework.io/docs/patterns/lists#responsive-divider

**Comment by bethcollins92** [comment]
Thanks @sowasred2012 and @elioqoshi. I agree that we shouldn't be encouraging the use of ARIA roles where native HTML elements can be used instead. 

About the example, it seems strange not to use `<ul>` and `<li>` here. I edited the code on codepen and using the divider classes on list elements seem to work fine. I'll file a bug on vanilla to look into this.

**Comment by bethcollins92** [comment]
Notes are up here: Notes are up here: https://vanillaframework.io/docs/patterns/lists#accessibility
