### ISSUE TITLE
[Accessibility Docs] Logo section

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/vanilla-framework#4052]
Using [this template](https://docs.google.com/document/d/1IwFMfJrTfJPXDcVJfLWXYkw-pjgWhBWo4GX8X098Q64/edit#), create accessibility docs for [Logo section](https://vanillaframework.io/docs/patterns/logo-section)

**Comment by bethcollins92** [comment]
First draft of [accessibility doc](https://docs.google.com/document/d/1oVPfBXrkm6YsKRoL4MlAXO7SMKmewv7zYWHEQH9uHSI/edit#) for logo section.

Looking for review from UX and Devs

**Comment by bethcollins92** [comment]
This has Dev +1 just waiting on design

**Comment by AnnSoMuller** [comment]
+1 for me!

**Comment by bethcollins92** [comment]
Notes are here: https://vanillaframework.io/docs/patterns/logo-section#accessibility
