### ISSUE TITLE
[Accessibility Docs] Navigation

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/vanilla-framework#4057]
Using [this template](https://docs.google.com/document/d/1IwFMfJrTfJPXDcVJfLWXYkw-pjgWhBWo4GX8X098Q64/edit#), create accessibility docs for [Navigation](https://vanillframework.io/docs/patterns/navigation)

**Comment by ilayda21** [comment]
[Accessibility doc](https://docs.google.com/document/d/1WAmoXaiy6bSBXitwglNAg5PFls-Zi5R8K4jIlzFR1Sw/edit) for navigation

**Comment by wgx** [comment]
@bethcollins92 done :)
