### ISSUE TITLE
[Accessibility Docs] Notifications

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/vanilla-framework#4058]
Using [this template](https://docs.google.com/document/d/1IwFMfJrTfJPXDcVJfLWXYkw-pjgWhBWo4GX8X098Q64/edit#), create accessibility docs for [Notifications](https://vanillaframework.io/docs/patterns/notification)

**Comment by mtruj013** [comment]
[Accessibility doc](https://docs.google.com/document/d/1iw5ZMMzDjnnz3oG1P4wwjj9JYsGOsTPfl6Kzp_H6NoU/edit#) for notifications is ready for review

**Comment by marinacastejon** [comment]
Updated the doc with 2 new things: focus management and timing

**Comment by bethcollins92** [comment]
Great work @mtruj013 - super grateful for your help with this. Just a couple of comments in the doc but feels like you've covered everything
