### ISSUE TITLE
[Accessibility Docs] Pagination

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/vanilla-framework#4059]
Using [this template](https://docs.google.com/document/d/1IwFMfJrTfJPXDcVJfLWXYkw-pjgWhBWo4GX8X098Q64/edit#), create accessibility docs for [Pagination](https://vanillaframework.io/docs/patterns/pagination)

**Comment by bethcollins92** [comment]
First draft [accessibility doc ](https://docs.google.com/document/d/1S1Wv8XjYL-q_yLzkmjebjRS1Pqvd4NDLOAyHI7x2Tzk/edit#) for pagination. There have been some amendments to the pattern in writing these docs. The PR with the changes is [here](https://github.com/canonical-web-and-design/vanilla-framework/pull/4258)

**Comment by mtruj013** [comment]
> First draft [accessibility doc ](https://docs.google.com/document/d/1S1Wv8XjYL-q_yLzkmjebjRS1Pqvd4NDLOAyHI7x2Tzk/edit#) for pagination. There have been some amendments to the pattern in writing these docs. The PR with the changes is [here](https://github.com/canonical-web-and-design/vanilla-framework/pull/4258)

Doc has been reviewed and +1'd. Great job @bethcollins92! 🎉

**Comment by marinacastejon** [comment]
@bethcollins92 I added a couple things that need reviewing from DEV

**Comment by bethcollins92** [comment]
Notes are up here: https://vanillaframework.io/docs/patterns/pagination#accessibility
