### ISSUE TITLE
[Accessibility Docs] Search box

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/vanilla-framework#4062]
Using [this template](https://docs.google.com/document/d/1IwFMfJrTfJPXDcVJfLWXYkw-pjgWhBWo4GX8X098Q64/edit#), create accessibility docs for [Search box](https://vanillframework.io/docs/patterns/search-box)

**Comment by bethcollins92** [comment]
First draft [accessibility doc](https://docs.google.com/document/d/1YH05QhjuXLl93pdh_9ETYhalY7lU7tfNQ5EKD4ZRfw0/edit#) for search box. 

Feels like this could do with padding out but can't find much more information.

**Comment by AnnSoMuller** [comment]
added a comment in the doc and +1

**Comment by bethcollins92** [comment]
Notes are up here: https://vanillaframework.io/docs/patterns/search-box#accessibility
