### ISSUE TITLE
[Accessibility Docs] Strip

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/vanilla-framework#4064]
Using [this template](https://docs.google.com/document/d/1IwFMfJrTfJPXDcVJfLWXYkw-pjgWhBWo4GX8X098Q64/edit#), create accessibility docs for [Strip](https://vanillframework.io/docs/patterns/strip)

**Comment by wgx** [comment]
Needs a review @bethcollins92 but the doc is here: https://docs.google.com/document/d/1cEkDcilw5irLRLEqkJcozx_-WORdm3Ihu4dPtg8mO2o/edit#

**Comment by bethcollins92** [comment]
Thanks @wgx - you are the winner! First one to the finish line. I'll take a look (probably will be next week now)

**Comment by bethcollins92** [comment]
Dev +1 from me. Wondering if @marinacastejon could take a look and review UX - thanks!

**Comment by marinacastejon** [comment]
@bethcollins92 @wgx Done! I just fixed a typo (_the_ for _they_)
