### ISSUE TITLE
[Accessibility Docs] Switch

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/vanilla-framework#4065]
Using [this template](https://docs.google.com/document/d/1IwFMfJrTfJPXDcVJfLWXYkw-pjgWhBWo4GX8X098Q64/edit#), create accessibility docs for [Switch](https://vanillaframework.io/docs/patterns/switch)

**Comment by bethcollins92** [comment]
[Accessibility doc ](https://docs.google.com/document/d/1mvRvpEwtxUQAVRrfMiEgS-QgsWCm4-QsmWFfg6y5NZ0/edit#heading=h.53fyn87a5ihd) for switch

**Comment by mtruj013** [comment]
+1 👍🏻

**Comment by marinacastejon** [comment]
@bethcollins92 I updated the doc with some comments, they need a DEV review

**Comment by bethcollins92** [comment]
Notes are up here https://vanillaframework.io/docs/patterns/switch#accessibility
