### ISSUE TITLE
[Accessibility Docs] Tabs

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/vanilla-framework#4067]
Using [this template](https://docs.google.com/document/d/1IwFMfJrTfJPXDcVJfLWXYkw-pjgWhBWo4GX8X098Q64/edit#), create accessibility docs for [Tabs](https://vanillframework.io/docs/patterns/tabs)

**Comment by mtruj013** [comment]
> Accessibility doc for tabs is [here](https://docs.google.com/document/d/1NYZ7l_f2K3hhi8euPyJncSHpG2_RBiequyraakQuDq0/edit#heading=h.tityw67q1sgi) (thanks to @sowasred2012!)


+1 👍🏻

**Comment by bethcollins92** [comment]
@elioqoshi could you take a look at [this](https://github.com/canonical-web-and-design/vanilla-framework/issues/4067#issuecomment-1016549551) please?

**Comment by elioqoshi** [comment]
@bethcollins92 looking good! Added a few suggestions and tweaks.
