### ISSUE TITLE
Nested ordered list where the primary section is always visible, x.1, x.2...

### ISSUE THREAD

**Issue by petesfrench** [canonical-web-and-design/vanilla-framework#4074]
Currently an ordered list will appear as follows:
![image](https://user-images.githubusercontent.com/58276363/137718703-c1765fcd-dbd1-4a84-915c-944b8b71e401.png)

There is a use case, mostly within /legal, to allow lists with the 'section' and 'item' number on each item, for example:
1. Section 1
  1.1. item 1
  1.2. item 2
2. Section 2
  2.1. item 1
  2.2. item 2

## Context

Any nested list where you want very clear numbering, especially within the /legal part of our sites. There already exists a class on ubuntu.com that does this [here](https://github.com/canonical-web-and-design/ubuntu.com/blob/7687afcdf34a537c757e060d9b7578eec55fafe2/static/sass/_pattern_lists.scss#L187)

**Comment by clagom** [comment]
WG: issue validated, can go to build directly
