### ISSUE TITLE
Introduce coloured versions of chips

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#4090]
To be able to remove "p-label" component from 3.0 we need to update chip component to support the coloured versions.

This issue requires visual design (proposed colors of the chips) and building it as amendment of the chip pattern.

**Comment by lyubomir-popov** [comment]
Design ready for review: 

https://www.figma.com/file/H6MSsN3taoXXOJCPUbIImQ/Design-System-Library?node-id=487%3A5089

![image](https://user-images.githubusercontent.com/2741678/139717285-f0e8e94a-9416-47ce-b818-7b1994b8e656.png)

**Comment by bartaz** [comment]
@lyubomir-popov Are grey chips affected by the change? Can you also show coloured ones with dismiss? Can chip have both a badge and dismiss button?

**Comment by lyubomir-popov** [comment]
good questions, will add these to the examples.

**Comment by spencerbygraves** [comment]
@lyubomir-popov I think this is fine with the update to the red badge in an orange chip, as discussed earlier. Thanks.
