### ISSUE TITLE
Accordion UX specs

### ISSUE THREAD

**Issue by elioqoshi** [canonical-web-and-design/vanilla-framework#4123]
Based on outcome from https://github.com/canonical-web-and-design/vanilla-squad/issues/968 and #3989

**Comment by danielmutis** [comment]
Left some comments on the doc with some suggestions.

**Comment by elioqoshi** [comment]
@danielmutis ready for re-review

@cristinadresch @clagom should the next step be visuals or should I draft this into Discourse?

**Comment by clagom** [comment]
> @danielmutis ready for re-review
> 
> @cristinadresch @clagom should the next step be visuals or should I draft this into Discourse?

We can publish to Discourse (web and design one) and then update with visuals later, or wait for the visuals and publish all together.

**Comment by clagom** [comment]
Thanks @elioqoshi, I just moved it from "discussion" to "web and design" naming it [Pattern] as the other specs. https://discourse.ubuntu.com/t/pattern-accordion/27604

**Comment by clagom** [comment]
Also, one thing, do we want to keep the "considerations and references" bits public? I assumed it was just for WIP

**Comment by lyubomir-popov** [comment]
LGTM @elioqoshi
