### ISSUE TITLE
Breadcrumb component - Figma library

### ISSUE THREAD

**Issue by long-chung** [canonical-web-and-design/vanilla-framework#4144]

**Comment by long-chung** [comment]
Ready for review please.

Link to Figma component
https://www.figma.com/file/H6MSsN3taoXXOJCPUbIImQ/Design-System-Library?node-id=667%3A7578

**Comment by elioqoshi** [comment]
@long-chung looks good to me, thanks! Might have been a bit easier to use if the arrows and text are in separate layers so people can update the text easily without deselecting the arrow ascii character.

![image.png](https://images.zenhubusercontent.com/5a5649f54b5806bc2bc23b6d/63802acf-3488-4760-89ea-5282674430f3)

Is there a deliberate choice for this?

**Comment by long-chung** [comment]
Thanks @elioqoshi. I've changed the component so now the arrow is in a separate layer.

**Comment by elioqoshi** [comment]
@long-chung Thanks. I went the extra mile and locked the arrows so anyone using this doesn't need to delete the arrows as they are in separate layers now. I put them under another auto layout and locked the arrows, so when deleting a link, it deletes both link and arrow while not allowing the user to select the arrow which is redundant. 

<img width="301" alt="image" src="https://user-images.githubusercontent.com/5436686/143224859-8a53b46b-da6e-4c85-9518-6c7062ef4f35.png">

You can have a look at my Breadcrumb version in there. If that's fine with you we can publish it after adding a description.

**Comment by long-chung** [comment]
@elioqoshi LGTM

**Comment by elioqoshi** [comment]
Published!
