### ISSUE TITLE
Pagination component - Figma library

### ISSUE THREAD

**Issue by long-chung** [canonical-web-and-design/vanilla-framework#4146]

**Comment by long-chung** [comment]
Ready for review.

Link to Figma component
https://www.figma.com/file/H6MSsN3taoXXOJCPUbIImQ/Design-System-Library?node-id=673%3A7714

**Comment by elioqoshi** [comment]
@long-chung thanks. Changed the pagination group property to `Is truncated` for consistency with other components. I will try to add also some description to the variants as well.

Not very familiar with this component but when truncated, the active page number will always be the middle one, so tweaked that in the component variant.

@lyubomir-popov maybe a design review to be sure?

**Comment by elioqoshi** [comment]
I added descriptions and removed duplicate truncation elements (no need for truncation states for hover or active). Published as well.
