### ISSUE TITLE
Matrix component - Figma library

### ISSUE THREAD

**Issue by long-chung** [canonical-web-and-design/vanilla-framework#4148]

**Comment by long-chung** [comment]
Ready for review

**Comment by elioqoshi** [comment]
@long-chung Works great! The descriptions were missing so I added them. Is there any scenario when there can be more than 9 items displayed? @bartaz maybe knows? Do we need to cater for that? I only see 9 items in the examples on Vanilla.

**Comment by long-chung** [comment]
Thanks for reviewing and adding the descriptions @elioqoshi

**Comment by elioqoshi** [comment]
@long-chung as @lyubomir-popov pointed out, there are instances where we use more than 9 instances (e.g 12 on MAAS.io)

Should we eventually allow for 15 items as part of the component and allow people to delete rows and items they do noit need?

Also, is it currently possible to use the component with 3 items only? I had some trouble with a redundant divider in that case.

**Comment by bartaz** [comment]
It seems from code point of view it works well with multiplications of 3 items, so 3, 6, 9, 12, etc would work well.

**Comment by long-chung** [comment]
@elioqoshi Having 15 items will create a really long module on mobile. Is this something we want?
The stray divider line can be hidden if not needed.

**Comment by long-chung** [comment]
@elioqoshi I've added 15 items. Let me know if this os ok or if it feels too heavy on mobile. Thanks

**Comment by elioqoshi** [comment]
@long-chung Thanks! Oh definitely it's too heavy and I'd discourage anyone to use more than 9, though we had this discussion in Design Assembly one day that we should let designers do these decisions themselves and be flexible in the Figma library.

This is good to go now I think.
