### ISSUE TITLE
Heading icon component - Figma library

### ISSUE THREAD

**Issue by long-chung** [canonical-web-and-design/vanilla-framework#4150]

**Comment by long-chung** [comment]
Ready or review.

Link to Figma component:
https://www.figma.com/file/H6MSsN3taoXXOJCPUbIImQ/Design-System-Library?node-id=680%3A16683

**Comment by elioqoshi** [comment]
@long-chung looks good to me! Just added a description to each variant. We can publish this and close this issue.
