### ISSUE TITLE
Modal component - Figma library

### ISSUE THREAD

**Issue by long-chung** [canonical-web-and-design/vanilla-framework#4152]

**Comment by long-chung** [comment]
Ready for review

Link to Figma component:
https://www.figma.com/file/H6MSsN3taoXXOJCPUbIImQ/Design-System-Library?node-id=692%3A9482

**Comment by elioqoshi** [comment]
@long-chung Thanks!

I don't see a reason for having an item component for this. The modal building blocks could be already included in the final component, no?

What about content? We should either offer a content section paragraph or a content placeholder instance (maybe both as variants?)

Might need some more tweaks I think (of course @lyubomir-popov and me should take this on from here on)

**Comment by elioqoshi** [comment]
@lyubomir-popov I redesigned the modal with content placeholder options as well as making them scrollable in prototyping mode: Could you stress test them? https://www.figma.com/file/H6MSsN3taoXXOJCPUbIImQ/Design-System-Library?node-id=734%3A11299

**Comment by lyubomir-popov** [comment]
Wrapping needs work:
![Uploading image.png…]()

**Comment by elioqoshi** [comment]
@lyubomir-popov should have addressed these, can you re-review?

**Comment by elioqoshi** [comment]
This was published,  so closing this.
