### ISSUE TITLE
Dark theme for chips

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#4158]
Some minimal adjustments  are needed for chips on dark backgrounds (borders only, so they meet contrast ratio requirements against `#333` and similar backgrounds like the jaas one)

![image](https://user-images.githubusercontent.com/2741678/143604837-a759d785-a952-4222-98de-9bfc86a9a61b.png)

**Comment by bethcollins92** [comment]
@lyubo Should I add a new `$colors-dark-theme--tinted-borders:` or change the existing borders to the ones suggested above?

**Comment by lyubomir-popov** [comment]
@bethcollins92 
add a new one

**Comment by lyubomir-popov** [comment]
@bethcollins92 Update on the colours:

fill-positive: rgba(14, 134, 32, .5)
fill-caution: rgba(199, 89, 0, .5)
fill-negative: rgba(199, 22, 43, .5)
fill-information: rgba(9, 89, 170, .5)
fill-neutral: rgba(255, 255, 255, .15)


border-positive: #33CC4A
border-caution: #F9A11F
border-caution: #F87E8D
border-neutral: #999
border-information: #3896F5

We'll need to be careful when we create states for the interactive version of chips, as according to this: 
![image](https://user-images.githubusercontent.com/2741678/144045877-5a208ee2-964c-4529-a61c-96ffcaa66e38.png)

the state changes need to also pass the contrast requirements. The colours above have been selected to still pass contrast 3:1 when lightened by up to 8%. In the image below, the second row is the lightened version for active (8% lighter).

![image](https://user-images.githubusercontent.com/2741678/144046110-a8aa1923-d89c-43e2-905a-6aaf4a41e92d.png)


border-information: #3896F5 can also be added as $color-dark-theme--link as we'll use the same for blue links in the dark theme. This is really tricky as it needs to have contrast of 4.5:1 against the background, and 3:1 against the default text that surrounds it. To achieve this, the background of the dark theme cannot be lighter than `#2b2b2b`
![image](https://user-images.githubusercontent.com/2741678/144045383-2b77aff5-edf5-4c25-8968-af516b65abeb.png)
Here's an interpretation of the wcag reqs that require this: https://webaim.org/articles/contrast/
![image](https://user-images.githubusercontent.com/2741678/144045689-7adb93e1-0336-455b-af22-7c4126256ddf.png)
