### ISSUE TITLE
Expose $text-max-width as a class 

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#4159]
Somethign we used to have but under a confusing high-brow name (.measure--p). It would be very useful, for example to make a list that contains text only as wide as a paragraph. (Lists don't have a max-width as anything could be implemented as a list, there's no way of knowing if it is going to contain text only at framework level). My proposal: `.u-text-max-width`.

**Comment by anthonydillon** [comment]
What is the use case for this?

**Comment by bartaz** [comment]
I'm also not sure what it is solving - if we want lists (`<ul>`, `<ol>`) to have max width same as paragraphs shouldn't they have it by default? To make sure they are consistent and work whenever they are used (for example in docs from discourse, where class can't be added).

Sure, we use lists a lot in components (for navigation, etc), but in component we can easily remove the max-width, because we control the styling via class name.

**Comment by lyubomir-popov** [comment]
The use case is to be able to make anything match the size of text. e.g. Images, code snippets, lists. 

@bartaz If we did that navs and all sorts of other things that use the ul markup would get max-width. This was how I originally did it, but we had to revert.

**Comment by lyubomir-popov** [comment]
Thinking some more about it, the framework is in a much better state now than it was at v 1.6 - so maybe we can try setting it as default to `ul`s and `ol`s again? 

Regardless I think it is still very usefull to be able to apply a max-width to other elements like code snippets or images - not by default, but when those elements are single instances and appear to depart from the overall layout for no good reason. We currently use the grid for that, e.g. wrapping everything in a `.col-8`, but that causes unnecessary reflow when resizing, or too narrow a width when on a smaller resolution that is still above the desktop threshold.

**Comment by bartaz** [comment]
Yes, it would be good if we could try adding it by default and remove in components that use lists.

As for the usefulness of the utility - sure, it seems we can find use cases for it, but it seems that it would be most useful in places where we can't add class name - discourse docs.

For example: https://snapcraft.io/docs - should the tables have limited max-width here? Should the notification on the bottom?
Code blocks here? https://snapcraft.io/docs/channels - they are not code snippets, just `<pre>` blocks - should we limit those by default?

I'm worried about making these decisions now, when we want to release 3.0 really soon, and these seem like quite significant  breaking changes that we will have to QA extensively.

**Comment by lyubomir-popov** [comment]
Well we did have it before under a different name - `.measure--p`. So technically it's just giving it a more user friendly name.
