### ISSUE TITLE
Mobile card labels have negative margin when $multi is 1

### ISSUE THREAD

**Issue by petermakowski** [canonical-web-and-design/vanilla-framework#4162]
## Describe the bug

`v2.37.1`
When `$multi` is `1`, the bottom margin of the `::before` element in responsive table pattern on mobile has a negative value of `-0.25rem` (selector: `.p-table--mobile-card td[aria-label]::before`) 

### Actual
![image](https://user-images.githubusercontent.com/7452681/144077543-5500fd75-d1b1-4ed6-b3f1-dcb2d4144f9a.png)

### Expected:
I'd expect the `bottom-margin` value to be no smaller than 0.25rem:

![image](https://user-images.githubusercontent.com/7452681/144077766-9a0be926-f92e-49c7-a7ab-8a02962e2a40.png)

**Comment by lyubomir-popov** [comment]
Hi, thanks for reporting this. We're actually deprecating and removing the $multi in 3.0, which is imminent. So any release fro mcurrent master will completely remove $multi and treat everything as if $multi is set to 2. @bartaz what is the policy on this - should we issue a patch or should this be fixed locally until the whole site is migrated to 3.0?

**Comment by bartaz** [comment]
I'd say wait for 3.0. I don't think this issue was introduced recently, so quite likely this bugs exists for a while. It's probably not worth fixing it if we release 3.0 in a week or two.

But on our side I guess it's worth verifying how it looks in 3.0.

**Comment by bartaz** [comment]
Just verified that in 3.0 `multi` is removed and this problem doesn't happen anymore.
