### ISSUE TITLE
Using responsive and expanding table variant overwrites margins on mobile

### ISSUE THREAD

**Issue by petermakowski** [canonical-web-and-design/vanilla-framework#4163]
## Describe the bug

If you use `.p-table--expanding` in combination with `.p-table--mobile-card` the margin values on mobile are overwritten by `.p-table--expanding` values.

## To Reproduce

1. Go to responsive table codepen example: https://vanillaframework.io/docs/base/tables#responsive
2. Check that margins are correct on mobile
2. Add `p-table--expanding` class next to `p-table--mobile-card`
3. See that margins are no longer correct

## Expected behavior

Values from `.p-table--mobile-card` should take precedence for mobile breakpoint.

### Actual
![image](https://user-images.githubusercontent.com/7452681/144079342-ce928273-481c-452a-a25e-771129c210e6.png)
### Expected
![image](https://user-images.githubusercontent.com/7452681/144080029-6d900e0b-fd32-4112-a0c5-cefee1676a78.png)

**Comment by bartaz** [comment]
First of all I don't think these 2 variants were designed to be mixed. They are two separate top level variants `--modifiers` and usually you should not put multiple of those on same element.

I do understand the possible need for that though. We did create a spec for modular table with various of features, but it was not heavily developed for now.

This particular issue seems to be fairly easy to check. If it's just about a margin we can verify if this can be easily fixed (or maybe already is in 3.0 which had some spacing refactored).

**Comment by bartaz** [comment]
It seems to be caused by these lines, but they don't seem to be needed at all for expanding table (margin is 0 anyway), so it should be safe to just remove it and it will fix the conflict there.

https://github.com/canonical-web-and-design/vanilla-framework/blob/2c051aa4c656f66059a4931f555ced1f1a7bb01c/scss/_patterns_table-expanding.scss#L24-L26
