### ISSUE TITLE
Dismiss icon should be in css

### ISSUE THREAD

**Issue by bethcollins92** [canonical-web-and-design/vanilla-framework#4166]
## Pattern to amend

Chip pattern. Currently the `p-icon--close` icon is included in the HTML for chips with a dismiss button. We don't want users to use any other icon other than close here so it should be added with CSS instead. 

For the dark variant we currently need to add the `is-light` class to the icon which is confusing. Having it in CSS will enable us to include it in theming

## Visual

https://vanillaframework.io/docs/examples/patterns/chip/with-dismiss

**Comment by bartaz** [comment]
Added this to existing PR #4169
