### ISSUE TITLE
u.com navigation updates

### ISSUE THREAD

**Issue by cristinadresch** [canonical-web-and-design/vanilla-framework#4174]
- Grey variations
-

**Comment by anthonydillon** [comment]
Is this issue complete? Seems to be missing information.

**Comment by cristinadresch** [comment]
We have planning together with marcus  and wayne on Monday to go through the details for this

**Comment by anthonydillon** [comment]
I am going to assume this is for this iteration

**Comment by lyubomir-popov** [comment]
@anthonydillon yes, it is for this iteration.

**Comment by lyubomir-popov** [comment]
This work is tracked on the brand board, closing.

 https://github.com/canonical-web-and-design/vanilla-framework/issues/4128
