### ISSUE TITLE
Remove non-interactive chips

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#4187]
As part of chips work we decided not to use chips for non-interactive elements and keep label component for this purpose. We need to make sure we remove any examples and documentation around non-interactive chips.

The only chips should be interactive `<button>` or a chip with dismiss button in it.

**Comment by lyubomir-popov** [comment]
Can the dismiss chip extend our button with icon? Seems strange to have some in a span and some in a button.

**Comment by bartaz** [comment]
@lyubomir-popov I know, but how would dismiss work in such case - clicking on whole chip would dismiss it? This feels weird, seems like we need some UX input on this.

**Comment by cristinadresch** [comment]
@elioqoshi to add a comment
