### ISSUE TITLE
Round dismiss buttons in chips

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#4189]
As @elioqoshi suggested in comment to #4188:

> Not sure how Lyubo prepared it in the design specs, though it would be best if the hover state of the dismiss icon would be round, and not a square. Similar to how Material does it: https://m3.material.io/components/chips/specs

<img width="147" alt="grafik" src="https://user-images.githubusercontent.com/5436686/145365452-b585c0e9-e4a6-4666-b1b3-609ccbe4e85d.png">

**Comment by bartaz** [comment]
@lyubomir-popov Any thoughts? Are we fine with doing it like this? If we want such style should we apply it to some other things outside chips?

**Comment by lyubomir-popov** [comment]
I'm ok with this. We don't have naything similar to apply it to, but if in the future we have other round narrow containers, that's a good solution.

**Comment by bartaz** [comment]
@lyubomir-popov quick adjustment of border radius can give us this:

<img width="147" alt="Screenshot 2021-12-09 at 11 46 12" src="https://user-images.githubusercontent.com/83575/145382511-aab10d55-9d2f-44db-a3d9-68830b1530e0.png">

if we want to tweak padding or something it may require readjusting spacing in chips, so I'd like to avoid this before 3.0
