### ISSUE TITLE
How should validation message look with checkbox/radio inputs?

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#4193]
Vanilla provides examples of how to use [validation with standard text input fields](https://vanillaframework.io/docs/examples/patterns/forms/form-validation), but not with radios/checkboxes. Using existing validation message placement doesn't seem to work well with single or groups or checkboxes.

<img width="402" alt="Screenshot 2021-12-10 at 10 49 51" src="https://user-images.githubusercontent.com/83575/145553927-a723e80d-c9c6-4b1c-abc2-591a407ae23c.png">

https://codepen.io/bartoszopka/pen/ExwgPoJ

Do we have any guidelines on how validation should look for:
- single checkbox (for example required terms agreement) when there is error (for example required field not selected)?
- group of checkboxes/radios, possibly having a label above the group of them when selection is invalid and error is shown?

We should provide such guidelines (UX/visual) and create examples for them in Vanilla.

**Comment by clagom** [comment]
WG: validated, @wgx can you look at this next iteration? Sync with @cristinadresch in case please

**Comment by wgx** [comment]
**Visual thoughts**

Agree the warning seems mis-aligned, but not by much. Nudging it a few pixels down and 1px right seems to space it better - but will defer to a visual expert.

![image](https://user-images.githubusercontent.com/930099/156555739-d0451da4-8cc2-44a1-a91d-91590a059d16.png)

**UX thoughts**

The main goals should be:

1. Make users instantly aware there is an error
2. Allow users to locate the place that needs correction
3. Explain clearly how the user can rectify the error

For these reasons, I think (like we do with a single checkbox) the error for a group of checkboxes or radio input should *also* be immediately after the items. I think if we move it *before* the clickable elements we risk creating confusion. 

So, for example - Wireframe: 

![image](https://user-images.githubusercontent.com/930099/156556821-470c64a5-9384-455a-9e31-0071fe700b18.png)

**Comment by danielmutis** [comment]
I agree with the UX recommendations. Visually, I am not sure whether the error on a single-line checkbox should be aligned with the text rather than with the box. Maybe @lyubomir-popov can take a look.

**Comment by lyubomir-popov** [comment]
@danielmutis I would propose something like this: 
![image](https://user-images.githubusercontent.com/2741678/157008731-0dac378e-0743-4121-84a4-7c77c6a1713b.png)

**Comment by danielmutis** [comment]
I think this is a good approach when the error is related to only one checkbox, but not when it relates to the whole list (in this case I would align it as per Will's example).

**Comment by lyubomir-popov** [comment]
@danielmutis good point, I'll add a design for that too. Can you think of a plausible example for groups of checkboxes? I'm finding it difficult to come up with a scenario where the message applies to more than one.

**Comment by lyubomir-popov** [comment]
"You can't register unless you also subscribe to the newsletter" isn't very plausible, but in terms of design, when the message applies to more than one checkbox, maybe something like this:

![image](https://user-images.githubusercontent.com/2741678/157022434-0dc878a5-4f1c-4b54-bb6b-10eb48bb6414.png)

**Comment by spencerbygraves** [comment]
Thanks @lyubomir-popov, I think this looks good.

**Comment by clagom** [comment]
WG: @wgx to write UX spec to specify how we handle errors, including visually.

**Comment by AnnSoMuller** [comment]
Seems ok for me for the 2 changes mentioned :)

However, for the wording (I know that wasn't the subject here), I would advice also recommendations
e.g: Consistency, condensed sentences, use affirmative etc.
"_You can't register without agreeing to the terms of service_" might become 
"_You must agree to the terms of service to register_" in line with "_you must choose a delivery method_"

**Comment by AnnSoMuller** [comment]
so review +1 👍

**Comment by wgx** [comment]
Thanks @AnnSoMuller  - I'll go ahead and write up the spec over the coming week.

**Comment by wgx** [comment]
@cristinadresch @clagom  I've re-approached this with a spec:

https://docs.google.com/document/d/1JO4sW0POd7oN86pUm5GEz_cIUEj46sSH5d5ljXOam20/edit#

This isn't the normal spec format because this is a sub-behaviour of checkboxes and radios, so not sure if we do really want to handle it as a separate component, or if we want to bring these behaviours into the specs for checkboxes and radios?

**Comment by danielmutis** [comment]
@wgx I think this is good, but it should probably be a section of the forms spec. I will add this to that epic and maybe we can revisit it when we work on those.
