### ISSUE TITLE
[Sphinx] Permalink anchors should only be displayed on hover

### ISSUE THREAD

**Issue by bethcollins92** [canonical-web-and-design/vanilla-framework#4195]
The heading links shouldn't be visible unless you over over the title. They also need some styling.

**Comment by bethcollins92** [comment]
@bartaz you should be able to review this now irrespective of the other one as I've removed the changes that were from the other PR

**Comment by bartaz** [comment]
@bethcollins92 Could you link to the PR? I don't see it here anywhere.

**Comment by bethcollins92** [comment]
@bartaz wups - sorry https://github.com/evildmp/vanilla-sphinx-test/pull/41
