### ISSUE TITLE
Dart sass "/" depreciation warnings

### ISSUE THREAD

**Issue by carkod** [canonical-web-and-design/vanilla-framework#4227]
**Describe the bug**

After updating dart sass to higher versions such as `1.45.2`, it's warning us that in files like 
```
  node_modules/vanilla-framework/scss/_settings_spacing.scss 8:12  @import
  node_modules/vanilla-framework/scss/_settings.scss 10:9          @import
  node_modules/vanilla-framework/scss/_vanilla.scss 1:9  
```
We have variables that are using a division format that is going to be deprecated e.g.

```
$ms-ratio: 16 / 14 !default;
$value: $value / $number;
```

Instead they recommend:

```
math.div(16 / 14 ) or calc(16 / 14 )
math.div($value, $number) or calc($value / $number)
```

Apparently, this is a sass thing, and there is an [automatic migrator](https://sass-lang.com/d/slash-div)

**To Reproduce**

I believe running any project with `sass: 1.45.1` renovate update will show the errors clearly.

**Screenshots**

![sass-division-deprecation](https://user-images.githubusercontent.com/14939793/148243685-0823db9f-eb60-4488-9807-9c324683242a.png)

**Comment by cristinadresch** [comment]
This will be fixed in 3.0
