### ISSUE TITLE
Write blog post about writing accessibility docs

### ISSUE THREAD

**Issue by bethcollins92** [canonical-web-and-design/vanilla-framework#4229]

**Comment by bethcollins92** [comment]
First draft is here. I don't want to publish it until I've added some of the ones currently in review to our website and can link from the issue so people can read and give feedback. 

https://docs.google.com/document/d/16Jn-mJp8942BOWFalNdqhGQU_rQao9nwdpqb7BHxqNQ/edit

**Comment by wgx** [comment]
Reviewed! 👍🏽
