### ISSUE TITLE
Search issue on firefox

### ISSUE THREAD

**Issue by tbille** [canonical-web-and-design/vanilla-framework#4232]
it seems the search is not displaying correctly on Firefox.

![image](https://user-images.githubusercontent.com/2707508/148819927-2f83fa99-271e-4bea-94e6-7ba5ee778358.png)

**Comment by bartaz** [comment]
Thanks @tbille - search seems fine on my side - could this be a cache issue? Maybe the site loaded with old stylesheet?

**Comment by tbille** [comment]
yeah it seems it's all good now.
It's weird when I tried to do some cache-busting I still had the issue.
Anyway closing the issue now.
