### ISSUE TITLE
UX Spec - Enable UA subscription attach in Subiquity

### ISSUE THREAD

**Issue by cristinadresch** [canonical-web-and-design/vanilla-framework#4245]

**Comment by elioqoshi** [comment]
Draft specs here (in progress): https://docs.google.com/document/d/1oji-YLGafmL15EbZE5Iq42s8Xfzhff-Pgu5eOHi7UNk/edit#

**Comment by elioqoshi** [comment]
Initial specs ready! 
https://docs.google.com/document/d/1oji-YLGafmL15EbZE5Iq42s8Xfzhff-Pgu5eOHi7UNk/edit?usp=sharing

UX Review from @wgx would be appreciated. Needs sign off from @lechsandecki and Daniel Bungert as well which I am doing separately. Additionally checking with the ua-client team to ensure coherency.

**Comment by wgx** [comment]
+1 from me.

**Comment by elioqoshi** [comment]
Thanks @wgx .

Will await a review from Lech on the document before closing this.

**Comment by elioqoshi** [comment]
Did a few changes on this based on my discussion with Lech and others. We will not be supporting attaching tokens offline as we don't see much value in it. Updated specs and mockups accordingly and awaiting final review from Lech and the Foundations team
