### ISSUE TITLE
Command links - Visual

### ISSUE THREAD

**Issue by cristinadresch** [canonical-web-and-design/vanilla-framework#4282]
For reference - the spec issue: https://github.com/canonical-web-and-design/vanilla-framework/issues/3923#issuecomment-1033582360

**Comment by cristinadresch** [comment]
@amylily1011 can you review the visuals that Lyubo put together pls

**Comment by lyubomir-popov** [comment]
@amylily1011 final visuals for the images that need replacing are in https://www.figma.com/file/Gay7v9kkqNwmGCNxK0RU0e/Command-link-example-mockups?node-id=0%3A1
