### ISSUE TITLE
UX Wireframes - Enable UA subscription attach in Subiquity

### ISSUE THREAD

**Issue by cristinadresch** [canonical-web-and-design/vanilla-framework#4283]

**Comment by elioqoshi** [comment]
Included wireframe related changes in the user journey as well: https://miro.com/app/board/uXjVOSU66Is=/?invite_link_id=566158019602

**Comment by elioqoshi** [comment]
This is ready for review! https://miro.com/app/board/uXjVOSU66Is=/?invite_link_id=715758985020

@wgx if you could have a look, with a focus on the offline installer especially as that might be a bit more fidgety. The last screen in the offline installer might need a copy review.

**Comment by wgx** [comment]
Couple of optional suggestions @elioqoshi but 👍🏽

**Comment by elioqoshi** [comment]
Thanks @wgx !

Closing this
