### ISSUE TITLE
Collapse/expand side navigation for docs

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#4294]
After clarifying some side navigation requirements with docs team, here is what they would like to have in terms of expanding side navigation:

- Each item in the menu should be a link to a resource.
- Each item that contains other items should be collapsed by default.
- When an item that contains other items is selected, or we land on a page, then as well as navigating to the page, its child items should be shown.
- In order to see child items without navigating, the disclosure should a) indicate that child items exist and b) function as a toggle to hide/show them.
- keeping max. nesting level to current 3 is fine
- both 1st level and 2nd level should be collapsible if it has children

Example documentation sites that feature side navigation like that:
https://docs.divio.com/en/latest/
https://linuxcontainers.org/lxd/docs/master/

The expandable side navigation that we initially designed in #3817 is different (expandable items are not documents themselves), so we should discuss if we can change the design to better fit into needs of docs team.

![docs-side-nav](https://user-images.githubusercontent.com/83575/152327697-339acf70-00ef-4ca7-bce7-b022130b4edf.gif)

Previous UX issue: #3817

**Comment by clagom** [comment]
@danielmutis is going to meet the documentation team next week

**Comment by bethcollins92** [comment]
This [PR](https://github.com/canonical-web-and-design/vanilla-framework/pull/4296) was a first draft of an expandable collapsable side nav. I imagine a lot will change so it won't be much use but leaving it here just incase someone can use it in the future.
