### ISSUE TITLE
Empty states for data visualisation

### ISSUE THREAD

**Issue by marinacastejon** [canonical-web-and-design/vanilla-framework#4295]
## Pattern to amend

[Empty state for data visualisation proposal doc
](https://docs.google.com/document/d/1x4KQJBZU1Rw91zKR7XUeZ0HtqueO3ijNQ5MKGLcStOo/edit#)[Link to the empty state pattern in Discourse](https://discourse.ubuntu.com/c/design/pattern-empty-state/95). 

## Visual

This is  wireframe of the Hiring Dashboards UI. 
![image.png](https://images.zenhubusercontent.com/61309e789df65d8124887eac/a0d3a12a-921c-4d7b-b78f-88d077c4729e)

## Context

The pattern does not currently cover the case of empty states for charts. 
In data visualisation UIs, it makes sense in certain use cases to show the outline of the chart, as in the data value is zero on this chart.

**Comment by clagom** [comment]
WG: @marinacastejon could you add more information on this issue, explaining what is the current problem we need to solve and the different use-cases?

I think this can be part of the data visualisation pattern, and integrate the empty state from that perspective.

**Comment by marinacastejon** [comment]
Sure. The current pattern does not take into account use cases where there is a chart. As defined in my previous work ([empty states definition](https://miro.com/app/board/uXjVOTPrM_A=/), there are cases where it makes more sense to hide an entire section (ie. chart outline is hidden) and cases where it makes sense to show the graph outline with values as zero.

**Comment by clagom** [comment]
@marinacastejon I think this can be included in the spec of the data visualisation pattern, to inform how an empty state would be.

**Comment by marinacastejon** [comment]
Hi @amylily1011 @AnnSoMuller @wgx , please take a look at my proposal [here](https://docs.google.com/document/d/1x4KQJBZU1Rw91zKR7XUeZ0HtqueO3ijNQ5MKGLcStOo/edit#).

**Comment by AnnSoMuller** [comment]
Good for me :)

**Comment by amylily1011** [comment]
LGTM

**Comment by marinacastejon** [comment]
@danielmutis , it was reviewed and +1'ed by AnnSo and Amy. Could you please look at it to ensure documentation consistency?

**Comment by danielmutis** [comment]
I think we could include this as part of "Behaviour" in the overall spec for Data Vis. The content looks good to me, I just think maybe we don't need a full page just for this.
