### ISSUE TITLE
Should button styles work in pagination?

### ISSUE THREAD

**Issue by carkod** [canonical-web-and-design/vanilla-framework#4298]
**Describe the bug**

In "interactive forms" the `p-button--positive` is applied together with `p-pagination__link--next`, it seems that the pagination styles override the button styles.

It works in the previous Vanilla version, see below screenshot

**To Reproduce**

[Here is a codepen](https://codepen.io/carkod/pen/bGYwood) to see this clearly based on pagination pattern.

I tried 3 ways of adding it, of which 2 of them don't work at all.

**Expected behavior**

The next button should be green. Current https://ubuntu.com/aws still uses Vanilla <v3 so you can see it works:

![current-ubuntu-buttons](https://user-images.githubusercontent.com/14939793/152546154-3ff3b6d4-6ca9-406f-9cde-2e264365c442.png)

**Comment by bartaz** [comment]
@carkod 

It seems that button styles never worked with pagination and they were not expected to.

Your CodePen example changed to Vanilla 2.37.1 has the same issues: https://codepen.io/bartoszopka/pen/eYeBaqE

It seems that on ubuntu.com/aws the "pagination" that is used is not really Vanilla `p-pagination` but some other `pagination` style that doesn't affect button styling (or has no styling at all, not sure what these class names do there).

So it doesn't seem to be a bug here or any regression in 3.0. Buttons in pagination should work the same as before.

The question of whether pagination should allow styling buttons or not is still relevant. I'll bring it to working group to discuss if we consider having Next/Prev navigation in a modal good example of pagination that should have positive button.

**Comment by carkod** [comment]
> @carkod
> 
> It seems that button styles never worked with pagination and they were not expected to.
> 
> Your CodePen example changed to Vanilla 2.37.1 has the same issues: https://codepen.io/bartoszopka/pen/eYeBaqE
> 
> It seems that on ubuntu.com/aws the "pagination" that is used is not really Vanilla `p-pagination` but some other `pagination` style that doesn't affect button styling (or has no styling at all, not sure what these class names do there).
> 
> So it doesn't seem to be a bug here or any regression in 3.0. Buttons in pagination should work the same as before.
> 
> The question of whether pagination should allow styling buttons or not is still relevant. I'll bring it to working group to discuss if we consider having Next/Prev navigation in a modal good example of pagination that should have positive button.

Updated the title

**Comment by clagom** [comment]
WG: we recommend using the primary buttons for these use-cases, the pagination button shouldn't be used in these case (depends on the UX work done during the definition phase)
