### ISSUE TITLE
Copying the contents of a code snippet copies also the dollar sign at the beginning

### ISSUE THREAD

**Issue by danielmutis** [canonical-web-and-design/vanilla-framework#4338]
An issue has been reported to me by Rajan Patel (PM of Landscape) about people complaining that when they copy the contents of a code snippet, they also copy the dollar sign at the beginning of the snippet; which is unnecessary.

**Comment by bartaz** [comment]
@danielmutis Do you have more context on where this problem occurs? Current code snippet component has $ as an icon that can't be selected or copied:

<img width="850" alt="Screenshot 2022-02-22 at 18 57 31" src="https://user-images.githubusercontent.com/83575/155191373-b71f84aa-3ae7-419f-844b-a7ab22b37115.png">

**Comment by rajannpatel** [comment]
This may be a symptom of us not using Vanilla features correctly, when publishing content.

2 examples of a $ sign being selectable:
1. https://ubuntu.com/tutorials/multipass-and-libvirt-vms-on-ubuntu-managed-via-landscape#1-overview
2. https://ubuntu.com/blog/get-started-with-linux-game-development-on-ubuntu

1 example of the $ sign not being used at all:
https://ubuntu.com/blog/replacing-docker-desktop-on-windows-and-mac-with-multipass

**Comment by bartaz** [comment]
Thanks for the links @rajannpatel. Yes, these seem to errors in usage of code block. Both of the examples with $ have dollar sign as part of code block text, so obviously it's selectable. It would probably be better for users if $ was just removed from those.

But I guess it shows where the problem originates - in places where content is created (discourse or wordpress). They only provide standard code block (not any features of Vanilla one), so a natural way to add CLI prompt is to just type it in the text, which makes it selectable. To fix it they would need to edit HTML markup directly to use Vanilla component CSS class names. I guess this should be possible in wordpress, but discourse strips any styling from HTML.

Overall I see it not directly as issue with Vanilla, but how to make Vanilla patterns easier to use when we don't control HTML markup.

**Comment by anthonydillon** [comment]
Due to the source of the content being external we can't convert that to the Vanilla pattern for code snippets. Therefore this content needs to remain basic. I have removed the `$` from the beginning of the commands to make the easier to copy.
