### ISSUE TITLE
Dark themed side navigation visited links show as black text on dark grey

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/vanilla-framework#4341]
**Describe the bug**

Looked for an existing issue but couldn't find one - if a link in the dark themed side navigation has been visited, the text becomes very difficult to read.

**To Reproduce**

- Visit [the dark side nav example](https://vanillaframework.io/docs/examples/patterns/side-navigation/dark)
- Click any of the links
- Every link in the example (because they're all set to `href="#"`) will turn black

**Expected behavior**

The links should remain the same colour, or change to a colour that allows them still to be readable

**Screenshots**

![Screenshot from 2022-02-24 22-27-04](https://user-images.githubusercontent.com/2376968/155618127-2fa453ae-66fc-48fa-9edd-035bda280c47.png)

**Comment by bartaz** [comment]
Oh, good catch, how did we miss that?
