### ISSUE TITLE
Support aria-pressed on chips with dismiss

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/vanilla-framework#4366]
## Pattern to amend

Chip

## Change

Support the `aria-pressed` attribute and hover state on chips that include a dismiss button.

## Context

This is required for chips that need to have both a dismiss button and an active state.

Specifically this is to support the following UI in MAAS:

https://www.figma.com/file/AFw4WN623gie2Fi34btFlZ/%5B22.04%5D-Tag-management?node-id=834%3A20476

## Usage

The current implementation uses a span for dismissible chips as you can't have nested buttons.

```
<span class="p-chip">
  <span class="p-chip__lead">Owner</span>
  <span class="p-chip__value">Bob</span>
  <button class="p-chip__dismiss">Dismiss</button>
</span>
```

I would like to turn the span into an interactive element e.g.

```
<span class="p-chip" aria-pressed="true" role="button" tabindex="0">
  ...
</span>
```

However when using span the chip is not marked as [interactive](https://github.com/canonical-web-and-design/vanilla-framework/blob/main/scss/_patterns_chip.scss#L255) so it does not have selected or hover states.

To support this we'd need to include these states for `[role="button"].p-chip...` (or add a new class e.g. "p-chip--interactive") in addition to the current selector: `button.p-chip...`.

**Comment by huwshimi** [comment]
This was my initial attempt: https://github.com/canonical-web-and-design/vanilla-framework/compare/main...huwshimi:clickable-dismissible-chip but I couldn't figure out a way to prevent the hover/click states from propagating from the dismiss button to the span.

**Comment by bartaz** [comment]
@huwshimi Why do you want chip to be interactive itself? From UX and accessibility point of view interactive elements should not be nested, that's why chip with dismiss is implemented as a span not a button.

**Comment by huwshimi** [comment]
> https://www.figma.com/file/AFw4WN623gie2Fi34btFlZ/%5B22.04%5D-Tag-management?node-id=834%3A20476

It's for this UI: https://www.figma.com/file/AFw4WN623gie2Fi34btFlZ/%5B22.04%5D-Tag-management?node-id=834%3A20476

When you click one of the chips the details of the tag appears on the right hand side.

**Comment by huwshimi** [comment]
@bartaz Also, if you think we shouldn't be doing this it's probably worth having a chat with @lyubomir-popov and @rayito so they can redesign that screen.

**Comment by lyubomir-popov** [comment]
@bartaz we agreed to redesign the ui, no need for changing the chjip behaviour.
