### ISSUE TITLE
Better name for Vanilla "labels"

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/vanilla-framework#4367]
In browsers the "label" element is used in forms to describe a form field.

We introduced another "label" component into Vanilla that has completely different purpose.

![Screenshot 2022-03-22 at 08.28.33.png](https://images.zenhubusercontent.com/593a660851aa2c30578102bb/9a2a7c2a-87b2-445e-8c5d-57fe455df5f6)

The name "label" is not only confusing (because it conflicts with a form label), but is also now causing problems when implementing in React, because in React we have `Label` component for form labels and now need another name for this label component.

MAAS implemented it as `StatusLabel` for now, but it would be good to find a good name for it, rename it in Vanilla and use a proper non-conflicting name in other places.

Related proposal in React components repo: canonical-web-and-design/react-components#724

**Comment by fitojb** [comment]
What about “badges”?

**Comment by bartaz** [comment]
Some suggestions to discuss on WG:

- badge (https://getbootstrap.com/docs/5.1/components/badge/)
  - we are currently have plans for another "badge" component (a counter badge)
  - bootstrap uses "badge" for both - text and counters
- status
- status label
  - this probably is not always a "status"
- tag (https://www.carbondesignsystem.com/components/tag/usage) (https://design-system.service.gov.uk/components/tag/)
- annotation

**Comment by lyubomir-popov** [comment]
My proposal is to just use `em` with an optional dot:

![image](https://user-images.githubusercontent.com/2741678/161544741-a9780e51-9cac-4e43-b09b-bc2396cc7eea.png)

**Comment by clagom** [comment]
WG: use "status label" as the new name for the component.
We probably need to amend our UX spec.

**Comment by bartaz** [comment]
To follow up:

UX spec: vanilla-squad#1323
Rename it in Vanilla: vanilla-framework#4395
