### ISSUE TITLE
Websites latest version is ahead of the releases

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/vanilla-framework#4393]
**Describe the bug**

The website has been released with the next version number bumped in the package.json but the package has not been released so is incorrect and the hotlink in docs is 404'ing.

**To Reproduce**

Steps to reproduce the behaviour:

1. Go to https://vanillaframework.io and see the last version is v3.1.2
2. Go to https://github.com/canonical-web-and-design/vanilla-framework/releases and see that the latest version is v3.1.1 with a draft release for v3.1.2
3. Check https://assets.ubuntu.com/v1/vanilla-framework-version-3.1.2.min.css is 404'ing

**Comment by bartaz** [comment]
Ups, sorry, must have happened after reverting from April Fools.
Reverted to correct image in prod now.
