### ISSUE TITLE
Middots appear to wrap to the next line before their item does

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/vanilla-framework#4429]
**Describe the bug**

@minkyngkm just spotted this on https://github.com/canonical-web-and-design/canonical.com/pull/521#discussion_r854006532

When middot lists wrap, at certain points the middot will wrap before the text of the item it's related to does.

**To Reproduce**

- Visit https://vanillaframework.io/docs/examples/patterns/lists/lists-mid-dot-dark
- Reduce browser width to ~280px
- See that the dot belonging to "Data privacy" has wrapped to the line below and is overlapping "Report a bug on this site"

**Expected behavior**

The dot should wrap with the item text

**Screenshots**

![Peek 2022-04-20 12-12](https://user-images.githubusercontent.com/2376968/164218561-c659279e-ce7a-4036-92d7-2b23b9487156.gif)

**Comment by bartaz** [comment]
Bumping priority to High as it is quite a visible bug on specs.canonical.com
