### ISSUE TITLE
Links for code standards don't work

### ISSUE THREAD

**Issue by andesol** [canonical-web-and-design/vanilla-framework#4449]
The two links for code standards in `/contribute` are not working. (Because the practices website doesn't exist anymore)

**To Reproduce**

1. Go to https://vanillaframework.io/contribute
3. Scroll down till you see the guidelines card 
4. Click in the links

**Comment by bartaz** [comment]
I think those were moves to discourse somewhere?

**Comment by bethcollins92** [comment]
@bartaz do you know where on discourse? I wouldn't even know where to start...

**Comment by bartaz** [comment]
It seems practices was moved into webteam portal: https://webteam.canonical.com/practices

Relevant pages: https://webteam.canonical.com/practices/html-code-standards https://webteam.canonical.com/practices/css
