### ISSUE TITLE
Beak the dependency between `l-fluid-breakout` and the variable `$grid-max-width`

### ISSUE THREAD

**Issue by goulinkh** [canonical-web-and-design/vanilla-framework#4459]
## Pattern to amend

`l-fluid-breakout`

## Context

I'm using the layout `fluid-breakout` for the main section of my application and I would like to align the other sections of my app with the main section, in the other sections I use components like `p-navigation` and `row`, so by doing the following, I expect the `max-width` of `grid/row` based components to have the same width:
```scss
$grid-max-width: 100rem;
```

The problem is that changing the variable `$grid-max-width` changes the `max-width` of a part of the `fluid-breakout` layout as well!
You can see more details for our issue in this [PR discussion](https://github.com/canonical-web-and-design/specs.canonical.com/pull/59#discussion_r869271746).

**Comment by bartaz** [comment]
@goulinkh Can you show some screens of what do you are trying to achieve?

I don't know exactly from top of my head, but as far as I remember fluid breakout layout needs to align with the grid and therefore the use of grid-max-width there is intentional. If the main grid width changes it should affect how fluid breakout works (at least to my understanding).

I think being able to see what do you want to achieve and which parts you want configurable would help.

Thanks!

**Comment by goulinkh** [comment]
@bartaz What I want to achieve is aligning the `row` section with the `fluid-breakout` section, here is an illustration:
![Screenshot from 2022-05-11 10-33-27](https://user-images.githubusercontent.com/36013798/167807697-e3a2157e-2cef-4b01-9860-3d375e3b6296.png)

Whereas the current behavior aligns different elements:
![Screenshot from 2022-05-11 10-33-27](https://user-images.githubusercontent.com/36013798/167808727-c95bf1fd-345a-445b-b3b5-fa2f4d8df2a4.png)

**Comment by bartaz** [comment]
Thanks @goulinkh.

Currently the layout behaves as expected - that's what it was designed to do - to "break out" of the grid width and allow showing the left hand side bar outside of the main "grid max width". 

If you want to stay in side the grid I think you possibly don't need the fluid breakout layout? Just make the `grid-max-width` wider, and use standard grid class names for the content? Or does fluid breakout layout have some features that you would like to keep (while having it within grid width)?

**Comment by goulinkh** [comment]
I think I can achieve what I want by doing:
```scss
.l-fluid-breakout {
  max-width: $grid-max-width;
}
```

So basically my question is should this be the default behavior or something specific to my project @bartaz?

**Comment by lyubomir-popov** [comment]
I second what @bartaz said, this is not what the fluid layout was intended for. Why not just use the regular grid?

**Comment by lyubomir-popov** [comment]
> Yes, We are using the fluid breakout to be able to make the elements fit in mobile by making the elements align vertically:

this can be achieved very easily with the grid.

**Comment by anthonydillon** [comment]
The [current uses of the fluid grid](https://charmhub.io/) does have the navigation aligned as you had it before? Who is asking for the navigation alignment?

**Comment by goulinkh** [comment]
Closing this issue as I think that I miss understood the expected behavior of the fluid breakout. charmhub.io is making it clear of how it should look like.

Sorry for the disturbance and thanks for answering :+1:
