### ISSUE TITLE
New logo mark larger than the word mark

### ISSUE THREAD

**Issue by petermakowski** [canonical-web-and-design/vanilla-framework#4460]
#### logo mark is taller than the accompanying word mark
<img width="236" alt="image" src="https://user-images.githubusercontent.com/2741678/168072877-f313109b-b538-463a-a915-37a8a13e69db.png">

#### original logo for reference
<img width="1044" alt="image" src="https://user-images.githubusercontent.com/2741678/168073076-2cf30d7b-9547-4523-93de-5ab6b2458158.png">

---

This affects all instances where the new Navigation component is used.

The Canonical text is also not aligned with the logo mark in the example on vanilla

https://vanillaframework.io/docs/patterns/navigation

<img width="430" alt="image" src="https://user-images.githubusercontent.com/7452681/168075814-f3e05fec-5123-4ede-a581-221a420fa758.png">

_Originally posted by @lyubomir-popov in https://github.com/canonical-web-and-design/maas-ui/issues/3933_

**Comment by bartaz** [comment]
Seems that because the text is a heading it's affected by responsive font size:

![logo-size](https://user-images.githubusercontent.com/83575/168080015-67f8b9c2-ead4-4bc7-b10c-7aed193b882a.gif)

So the size of the font will depend on size of the screen. This may also affect line height and baseline alignment.

**Comment by bartaz** [comment]
@lyubomir-popov Could you have a look and confirm what is the desired font size (I guess it's not meant to change in same way like standard headings do), and what the alignment against the logo should it have?

**Comment by lyubomir-popov** [comment]
could you try with this maas logo? I think the old one may have been exported at 18px instead of 16:

https://assets.ubuntu.com/v1/4efc86a8-MAAS-icon_wht.svg
