### ISSUE TITLE
[Inline list] Extra space between list items

### ISSUE THREAD

**Issue by andesol** [canonical-web-and-design/vanilla-framework#4471]
**Describe the bug**

Since list items are inline elements (in the inline list), the following html renders an extra space at the end of each item. 

```html
<ul class="p-inline-list">
  <li class="p-inline-list__item">Community</li>
  <li class="p-inline-list__item">Careers</li>
  <li class="p-inline-list__item">Press centre</li>
</ul>
```

More context [in this PR](https://github.com/canonical-web-and-design/specs.canonical.com/pull/74)

**To Reproduce**

Check [this example](https://codepen.io/andesol/pen/MWQOazB).

**Screenshots**

![image](https://user-images.githubusercontent.com/20623084/170222601-9fcd5df9-0a16-4505-8c9e-4e7ce4038281.png)

**Comment by andesol** [comment]
@bartaz Both, because it's a [HTML thing](https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Whitespace#spaces_in_between_inline_and_inline-block_elements) that the space between inline elements matters.

I thought that maybe we could use flex instead of `display: inline`

**Comment by bartaz** [comment]
I will close this one for now.

The inline lists are "inline" for a reason - we expect them to be inline elements, so the whitespace between them is expected.

Middot pattern takes this into account, so whitespace there is **required** to make sure the dot appears in correct place.
