### ISSUE TITLE
Upstream u.c cards with top bar

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#4495]
U.c and other sites are using a custom implementation of the card component. Since it breaks in certain scenarios, we should upstream it and make it more robust. For reference:

https://github.com/canonical-web-and-design/ubuntu.com/issues/11734
https://github.com/canonical-web-and-design/ubuntu.com/issues/11589

**Comment by lyubomir-popov** [comment]
@anthonydillon Proposal to address your 's commenta on this pr:
https://github.com/canonical-web-and-design/vanilla-framework/pull/4496

<img width="1033" alt="image" src="https://user-images.githubusercontent.com/2741678/180167917-f5dab244-40a4-49c9-9ad1-348029963f9a.png">

**Comment by anthonydillon** [comment]
Thanks @lyubomir-popov. Much closer. Shame to have to redesign the pattern to accommodate information I am not unsure is even useful.

**Comment by lyubomir-popov** [comment]
@anthonydillon so can we close this and move it to ready for development?

**Comment by anthonydillon** [comment]
Yeah, thanks.
