### ISSUE TITLE
Web 22.10 - "All Canonical" intermediate solution visual design

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#4518]
Provide visual design for these wireframes by @davegoddard42 
https://miro.com/app/board/uXjVOm_3tiY=/

**Comment by lyubomir-popov** [comment]
@davegoddard42 @marcushas can we close this? 
Final version: https://www.figma.com/file/BSP7FqnRMcMvO7kCozJKUa/Ubuntu.com-navigation-update-Iteration-9?node-id=4534%3A25846

**Comment by davegoddard42** [comment]
Thanks @lyubomir-popov. LGTM.
