### ISSUE TITLE
C.com candidate page

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/vanilla-framework#4519]
Visual design for the wireframe located [here](https://miro.com/app/board/uXjVO9E_QFA=/)

Ready for review:
https://www.figma.com/file/KQSCmTqOjY4gfKvJPyvzj2/Canonical.com-latest-only?node-id=4905%3A12117

**Comment by lyubomir-popov** [comment]
Thanks @marinacastejon [this](https://www.figma.com/file/KQSCmTqOjY4gfKvJPyvzj2/Canonical.com-latest-only?node-id=4943%3A10006) new mockup addresses them, let me know if you have any further comments.

**Comment by lyubomir-popov** [comment]
Closing this as I have received n further feedback after addressing the above. @marinacastejon if you need any other changes please let me know and I'll create a new issue for it.

**Comment by marinacastejon** [comment]
Hi Lyubo, sorry for the delay. I do have some relevant comments but it's difficult to explain in figma. I'll schedule a meeting tomorrow, but we'll need a new issue for sure.
