### ISSUE TITLE
Add template pages with different types of cases

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/vanilla-framework#695]
As far as I know, there is no longer anywhere that I can find an example full HTML page example of the top-level vanilla-framework structure, including wrapper and all. Something to copy when making my base templates for a site based on pure vanilla-framework 1.0. Something like:

``` html
<html>
<body>
  <section class="p-wrapper">
    <header class="p-header">...</header>
  </section>
</body>
</html>
```

Does this exist somewhere I'm missing? If not, could it be added to documentation?

**Comment by yaili** [comment]
I don't think we should add back the demo page, but template pages with different types of cases, like a form, a marketing page, etc.

**Comment by yaili** [comment]
@barrymcgee @anthonydillon @nottrobin Do we still need this issue open open?

**Comment by barrymcgee** [comment]
@yaili Yes - the new Jekyll example site contains examples of patterns but not any templates showing how patterns can be combined to construct a page.

**Comment by yaili** [comment]
OK, I don't think it's ready to be worked on though, needs design work, no?

**Comment by anthonydillon** [comment]
I think we should decide on some templates and create cards for these.

**Comment by yaili** [comment]
OK, let's make a list here.

**Comment by barrymcgee** [comment]
https://twitter.com/jongold/status/694591217523363840


![screen shot 2017-02-07 at 09 09 57](https://pbs.twimg.com/media/CaOvCDjWQAQgjW7.png)

**Comment by yaili** [comment]
Here's a start:

- Started template
- Hero + rows with image/text block
- Forms of some kind
- Newsletter subscription

Bootstrap v4 has an examples page: https://v4-alpha.getbootstrap.com/examples/

**Comment by anthonydillon** [comment]
I think we should use this as the brochure template: https://github.com/ubuntudesign/www.ubuntu.com-design/issues/2

**Comment by yaili** [comment]
@anthonydillon yes, that might work, that design isn't signed off though, just seeing it now.

**Comment by anthonydillon** [comment]
Investigate creating some codepen examples and adding links to them in vanillaframework.io.

**Comment by kwm14** [comment]
Nice example from @anthonydillon https://akveo.github.io/nebular/docs/components/layout/overview#nblayoutcomponent

**Comment by nottrobin** [comment]
Lol, This issue has lived since October 2016. This has to be one of the longest.
