### ISSUE TITLE
Create KPI metrics dashboard

### ISSUE THREAD

**Issue by barrymcgee** [canonical-web-and-design/vanilla-framework#760]
Notes from sprint meeting:

Metrics:
- Downloads
- Issues
- Issues closed
- PRs
- Development
- Hits to the site
- GitHub repos
- How many times the repo has been forked
- Developers, external developers, active external developers (see snappy)
- Number of non-Canonical mailing list subscribers
- You derive KPIs from metrics to give you something useful: eg issues divided by issues closed
- Most dashboards are set up through Kibana
- You can link through GitHub and Analytics
- Need to see how to get npm download count
kpi.canonical.com 
- This would be internal, behind SSO
- But could be public

**Comment by anthonydillon** [comment]
I think we have a good list of metrics here. I believe this issue should now be to create the KPI dashboard.

**Comment by kwm14** [comment]
We have a [Master epic](https://github.com/canonical-web-and-design/vanilla-squad/issues/603) ready to be worked on containing metrics we want to track, you've highlighted some we hadn't thought about so I will add. 👍
